### ISSUE TITLE
Setting version options to number disable it's output

### ISSUE THREAD

**Issue by sukrosono** [yargs/yargs#1000]
#### Affirmation
disable output is when i call `cliProgram -v` it show nothing, doesn't show version number.

**yargs version** `9.0.1`
yargs work as expected before i want to change the options type to number.

> options | desc | type
> --- | --- | ---
> -v, --version | Show version number | [boolean]

expected 

> options | desc | type
> --- | --- | ---
> -v, --version | Show version number | [number]

It's disabling when i wrote this
```
yargs.option('v', {
	desc: 'Print installed version',
	type: 'number'
});
```
same effect with either: 
```
// yargs.number('v');
yargs.number('version');
```
#### Maybe related

  1.  option version with option object aliasing to v, resulting -v, --version disappear from usage 
information

```
yargs.option('version', {
	alias: 'v',
	desc: 'desc',
	type: 'number'
});
// later (redundant code)
yargs.alias('v', 'version');
```
  2.  option v with option object aliasing to version, resulting --version appear twice on usage information

```
yargs.option('v', {
	alias: 'version',
	desc: 'desc',
	type: 'number'
});
// later (redundant code)
yargs.alias('v', 'version');
```
**result**
> options | desc | type
> --- | --- | ---
> -v, --version,--version | Show version number | [boolean]

It's low priority, thanks for this awesome module guys :smile:

**Comment by shadowspawn** [comment]
The "type" shown after an option is how it is used on the command-line. `--version` is used on its own so it is a "boolean". For this reason it does not make sense to change it to a "number".

When you add options that clash with `-v, --version` they automatically shadow the built-in flags. So here I end up with my own option for `-v` which expects a number.

```js
const yargs = require('yargs/yargs');

const argv = yargs(process.argv.slice(2))
   .option('v', {
      desc: 'Print installed version',
      type: 'number'
   })
   .parse();

console.log(argv);
```

```console
% node index.js --help
Options:
      --help     Show help                                             [boolean]
      --version  Show version number                                   [boolean]
  -v             Print installed version                                [number]
% node index.js -v 123
{ _: [], v: 123, '$0': 'index.js' }
% node index.js --version
1.0.0
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
