### ISSUE TITLE
requiresArg don't work with number type

### ISSUE THREAD

**Issue by edmBernard** [yargs/yargs#1007]
```node
var argv = require('yargs')
    .option("port", {type: "number", requiresArg: true, default: 6379})
    .option("address", {type: "string", requiresArg: true, default: "localhost"})
    .alias("h", "help")
    .version("0.0.1")
    .argv;
console.log(argv)
```

work with `string`
```node
./app.js --address
Options:
  --port                                                 [nombre] [défaut: 6379]
  --address                          [chaine de caractère] [défaut: "localhost"]
  --version   Affiche le numéro de version                             [booléen]
  -h, --help  Affiche de l aide                                        [booléen]

Argument manquant: address
```

don't work with `number`
```node
./app.js --port
{ _: [],
  help: false,
  h: false,
  version: false,
  port: undefined,
  address: 'localhost',
  '$0': 'app.js' }
```

**Comment by bcoe** [comment]
great catch 👍

If you're interested in making a contribution to this project, I would love help digging into this bug; otherwise, hopefully we'll get through some of our issue backlog soon.

**Comment by edmBernard** [comment]
I will try to dig on this bug.
Unfortunately, I'm not a javascript expert.

**Comment by edmBernard** [comment]
In this function https://github.com/yargs/yargs/blob/master/lib/validation.js#L59
default value is compare with parsed argument.
Default value for number is `undefined` so it didn't match any of ` [true, false, '']` and so never push missing argument status : https://github.com/yargs/yargs/blob/master/lib/validation.js#L74

**Comment by edmBernard** [comment]
@bcoe I'm not sure that adding `undefined` in default value array will be a good thing.  [validation.js#L60](https://github.com/yargs/yargs/blob/master/lib/validation.js#L60)
I don't see if there will be border effect
The change https://github.com/edmBernard/yargs

**Comment by bcoe** [comment]
@edmBernard I would try adding `undefined` to the list, and running the existing test suite; our tests are pretty thorough, so we should know immediately if it's an issue. I think you could probably crib this code for adding a test:

https://github.com/yargs/yargs/blob/20bb99b25630594542577133d51e38a4c6712d31/test/validation.js#L362

I find a good start for debugging things (and learning a new language while at it) is to add a failing test first.

**Comment by edmBernard** [comment]
I add test for number, string, array and boolean. I create pull request : https://github.com/yargs/yargs/pull/1015

**Comment by edmBernard** [comment]
https://github.com/yargs/yargs/pull/1015 have been merge
