### ISSUE TITLE
Question: Filename appearing next to command in help menu

### ISSUE THREAD

**Issue by aa7955** [yargs/yargs#1010]
Just a quick question. I am not sure if this is a NodeJS issue or what, but when I run the example yargs code, I get the following in my terminal:

```
example.js <cmd> [args]

Commands:
  example.js hello [name]  welcome ter yargs!

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
```

In the example, the filename is not next to the command `hello` under the `Commands` section. Just wondering how to get the filename out of that section so that it looks like the one from the example:

```
  Commands:
    hello [name]  welcome ter yargs!

```

**Comment by Morishiri** [comment]
It was changed in https://github.com/yargs/yargs/pull/983. It is replacing every `$0` to filename. I guess it cannot be configured not to.

**Comment by ajalger** [comment]
Thanks @Morishiri. This is definitely a fugly change, especially if you print out commands that need more than one input ... arg

**Comment by Morishiri** [comment]
We could actually do something about it, @bcoe can you please drop your opinion on this as I think it should work as it worked before.

**Comment by bcoe** [comment]
We opted to start placing the filename in the command output, because it helps better clarify what's happening when you have top-level positional arguments configured, which in the past would have looked like:

```
Commands:

[foo] <bar>
```

☝️ where you have positional arguments with nothing bound to them. I think that by placing the actual bin being executed as part of the command description we provide clearer help output for applications that have top-level commands configured.

**Comment by ajalger** [comment]
I understand that @bcoe. Just wondering if there is a way to expand the help table then because I am getting arguments on multiple lines like:
```
apiUsersTeamsRoles.js add-user            Add user to an account
  <accountid> <name> <email> [phone]
```

**Comment by bcoe** [comment]
@ajalger that's a pretty long application name and it takes a lot of arguments, even if we exposed an API for increasing the left-hand column width, I think you'd be making the right-hand column look pretty ugly, because you'd end up with something that looks like this:

```
Add 
user to
an account
```

What if you had an alternate bin name that's shorter, like `autr`; and we exposed an API for changing `$0` if we don't already (you might just be able to overwrite `$0`on the yargs object0>

**Comment by ajalger** [comment]
@bcoe yeah this was just an example command-line app. Indeed the filename is longer than expected because it was just used to differentiate one file from another. I wouldn't do that for something that is meant for production.

I'll experiment a little and come up with something that works. Thanks a lot.

**Comment by bcoe** [comment]
@ajalger 👍 maybe a slightly clearer API for changing `$0`? I could also imagine making the left column a little bit wider?

**Comment by ajalger** [comment]
If the left column is a little wider, I'd be cool with that. @bcoe

**Comment by richburdon** [comment]
I have another reason to remove it.

I'm using `yargs` in a CLI that processes `realine` I.e., you invoke the CLI then each line is a statement that gets executed. So at that point the executable isn't part of the command syntax.

Would really appreciate making this optional.

**Comment by bcoe** [comment]
@richburdon @ajalger @Morishiri open to suggestions if we can figure out something better than the filename, that still provides appropriate contextual information when default (root level) commands are run.

**Comment by richburdon** [comment]
Makes sense as a default @bcoe, but why not a boolean configurable option?

**Comment by bcoe** [comment]
@richburdon my immediate reaction to another boolean configuration option is; oh my goodness, yargs has so many config options already! I'm sure we can figure out a layout that better suits folks if we think on it a bit 😄

**Comment by saurabh-deep** [comment]
Hey guys! Is there a workaround so that the command name is printed in the output instead of the command file name?

```
testcommand <cmd> [args]

Commands:
testcommand hello [name]  welcome ter yargs!

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
```

**Comment by richburdon** [comment]
@bcoe, here's my output; do you see what I mean?

~~~~
[wrl]> help
main.js <command>

Commands:
  main.js quit        Quit                                       [aliases: exit]
  main.js build       Build deployment bundle.
  main.js deployment  Deploy API.                                 [aliases: dep]
  main.js domain      Organization domains.                       [aliases: dom]
  main.js service     Registry API.                            [aliases: svc, s]
  main.js status      Service status.                            [aliases: stat]

Options:
  --version            Show version number                             [boolean]
  --verbose, -v                                                 [default: false]
  --endpoint                             [default: "https://api.wireline.ninja"]
  --api_key, --apiKey                                            [default: null]
  --help               Show help                                       [boolean]
~~~~

**Comment by WeeJeWel** [comment]
Why not simply print the command as defined in package.json#bin ?

**Comment by Booom3** [comment]
I just ran into this issue too. My use case is that I am writing a Discord bot and using yargs to provide a very authentic and rich command line-line like experience for bot configuration through the chat. It's working wonderfully but this shows the name of the .js file the bot is running on instead of what you actually use to invoke the bot commands. If nothing else I would like to be able to change what the name of the "file" is.

**Comment by ChristianJacobsen** [comment]
I'd love this feature. Currently working on CLI using readline (same as people above). Adding an option to skip printing it would be a godsend.

**Comment by richburdon** [comment]
@ChristianJacobsen my workaround is the string replace the command when I'm running in interactive mode. It's hacky but it works well:

~~~~
      this._parser.parse(input, context, (err, argv, output) => {

        // Strip command name if in CLI mode.
        // TODO(burdon): https://github.com/yargs/yargs/issues/1010
        if (interactive) {
          let command = argv.$0.split('/').pop();
          output = output.replace(new RegExp(command + ' ', 'gi'), '');
        }

        console.log(output);
      });
~~~~

**Comment by Smolations** [comment]
Wow, third issue on this topic. Wish I would have seen this one before looking at #1048 and #1065. I am working on a chat bot as well. I was able to workaround this particular issue using the callback provided in the `.parse()` method. I've included an example in #1065.

**Comment by kerfallak** [comment]
while defining your command you can just call parse like this and replace the filename to your desired command name. to be safe you can use argv.$0 to refer to the filename and use regex to replace the string in your output.
``` javascript
.help("h")
.alias("h", "help")
.parse("", (err, argv, output) => {
    if (output) {
      const newOutput = output.replace("filename.js", "commandname");
      console.log(newOutput);
    }
  })
.argv;
```

**Comment by wyqydsyq** [comment]
@bcoe why was this issue closed?

I am still not aware of any way to override the command name?

For example I get this output:
```
index.ts [command]

Commands:
  index.ts build [project]  Build a project or the entire stack

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

I want to be able to replace the `index.ts` with `projects` as this script is exposed as a yarn script and ran as `yarn projects build MyProject`

**Comment by bcoe** [comment]
@wyqydsyq `scriptName` can now be used to modify the bin name as you see fit:

https://github.com/yargs/yargs/pull/1143

At this time, we have no plan to remove command name from the command listing, as it helps distinguish between top-level and nested commands.

For a chat bot, you should be able to set  `scriptName` to "", for `projects` you should be able to run `scriptName('projects')`.

Let me know if this does the trick for you 👍

**Comment by wyqydsyq** [comment]
@bcoe why was this closed? As far as I can see the issue is unresolved -- a hacky workaround is not a good solution.

**Comment by wyqydsyq** [comment]
Yeah the change in that PR is exactly what I was after, thanks!

**Comment by saivan** [comment]
Sorry to beat a dead horse. But I think it would also be useful to simply omit the command name in the help message, but still keep it in the usage string. Setting `scriptName` seems to change both, which is not desirable behaviour.

For example, git's help shows the shortened name in the main help menu:

![image](https://user-images.githubusercontent.com/8543370/65877987-4ad9c800-e3d0-11e9-8356-6629e5087f77.png)

But then in the usage string, it shows the full usage information

![image](https://user-images.githubusercontent.com/8543370/65878031-6d6be100-e3d0-11e9-8200-3f51e710a795.png)

This seems like sensible behaviour to me, but at the moment I can't see a way to change one without affecting the other (unless I'm missing something)

**Comment by Dunky13** [comment]
I'm facing this issue now as well, is there a workaround for this?

**Comment by bcoe** [comment]
@Dunky13 could you set `scriptName` as suggested? If this doesn't work, could I bother you to open a new issue (since this has been closed).
