### ISSUE TITLE
Allow us to call the default completion function from a custom one

### ISSUE THREAD

**Issue by tkarls** [yargs/yargs#1013]
So, I have a app with a few commands and a couple of arguments to each command.

For some of these arguments I want to provide a custom completion function to be able to provide completion for the argument values.

The problem is that I still want to leverage the automatic completion functionality for the commands and argument names.

Is there a way to call the automatically generated function from the custom one if I conclude that the current parameter is not something I want/can complete?

**Comment by bcoe** [comment]
@tkarls I don't believe there's currently a way to pull this off. If you have any thoughts about how to implement this feature, I'd be grateful for your contribution.

**Comment by tkarls** [comment]
Well, perhaps one way would be to add a new argument to the completion function that passes in the generated one. That way, instead of calling done one can call the generated one if one so chooses?

**Comment by tkarls** [comment]
@bcoe So, I tested the waters some...
https://github.com/yargs/yargs/compare/master...tkarls:enable-fallback-to-standard-completion?expand=1

Can't say that I'm 100% satisfied with the solution. To make it backwards compatible I had to add the yargs completion function as the last argument. I.e. after the done callback. I would have preferred to have the done callback last.

I didn't open a pull request as I'm not sure that this is something to build on. But wanted to share.

**Comment by bcoe** [comment]
@tkarls this is looking great 💯 one thought comes to mind -- you're right, it's definitely a bit ugly that `done` comes before the default completion.

Here's an idea, what if you look at the [number of arguments that the function expects](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/length) before you invoke it; then invoke the closure with accordingly (always passing done in as the last argument).

Seems like you're making good progress, so please feel free to open the pull request whenever you're comfortable.

_note, I'm sometimes somewhat terrible with git issues; as I get 100s a month; feel free to prod me in [this slack channel](http://devtoolscommunity.herokuapp.com/) if I'm ever moving slow._

**Comment by tkarls** [comment]
Thanks,

I'll take another look at it hopefully later this week and see if I can make the interface better by looking at the number of arguments as you suggest!

**Comment by gardenappl** [comment]
Any progress on this? I'm working on a project where this would be extremely helpful.

**Comment by gturi** [comment]
I tested it out and it works fine for my use case, you can even decide to merge your custom completion with yargs default one.

Recently a well explained example has been added to completion documentation https://yargs.js.org/docs/#api-reference-completioncmd-description-fn

**Comment by shadowspawn** [comment]
Thanks @gturi
