### ISSUE TITLE
Scientific notation with arguments without flag

### ISSUE THREAD

**Issue by florianleroux** [yargs/yargs#1017]
How to prevent arguments without a corresponding flag (argv._) to be interpreted as number?

example:

test.js:
```
console.log(require('yargs').argv._)
```
terminal:
```
$ node test.js 4317e500900
[ Infinity ]
```
I would like to have: `[ '4317e500900' ]`

**Comment by bcoe** [comment]
@florianleroux 👋 sorry for the slow reply -- have been fairly slammed with work.

we recently introduced the concept of `positional` arguments to address this issue:

```javascript
console.log(require('yargs')
  .usage('$0 <value>', 'do something with scientific notation value', (yargs) => {
    yargs.positional('value', {
      type: 'string',
      describe: 'provide a scientific notation value.
    })
  }))
```

I can confirm that this approach works for giant integers that would break numeric types, e.g., `test.js 4317999999999999999999999999999999999999` ... however, oddly, `4317e500900` still parses as `Infinity`.

I will leave this issue open as a bug; once it's addressed, the snippet of code above would be how you indicate that a positional argument should not be parsed as a number.

**Comment by florianleroux** [comment]
it work
thank you @bcoe
