### ISSUE TITLE
Use 'system-locale' instead of 'os-locale'

### ISSUE THREAD

**Issue by cktang88** [yargs/yargs#1026]
Would a PR to use [system-locale](https://www.npmjs.com/package/system-locale) instead of [os-locale](https://www.npmjs.com/package/os-locale) be welcome? It seems to be basically a drop-in replacement, and is much more lightweight.

**Comment by bcoe** [comment]
@cktang88 at this time I'd rather stick with `os-locale`, mainly because it has a larger user-base (which I find helps keep things bug free).

Thanks for the suggestion though, new library suggestions are always something I'm willing to consider.
