### ISSUE TITLE
Positional argument, build, and argument separator behavior

### ISSUE THREAD

**Issue by fvilers** [yargs/yargs#1030]
Hi!

I'm using yargs to build a CLI. The CLI is made up of commands. The application is initialized like this:
```
import yargs from 'yargs';

yargs
  .commandDir('cmds')
  .demandCommand()
  .help()
  .argv;
```

The cmds directory contains various commands and one of them has a positional argument that should be treated as string as it is sometimes composed only by numbers, it must remains a string.

Here's how the command is written:
```
export const command = 'setup <client_id> <api_key>';
export const builder = yargs => yargs.string('client_id');
export const handler = setup;
```

Here's the odd behavior, client_id is coerced as string or as number depending on how the application is executed:
```
$ npx babel-node ./src setup 012 test
client_id 12
$ npx babel-node ./src -- setup 012 test
client_id 012
```

Using babel-node doesn't change anything, after being transpiled to ES5, the issue remains. I don't want my user to have to use the argument separator. What can I do better? Is it a bug in yargs?

Thanks in advance,
Fabian

**Comment by bcoe** [comment]
@fvilers I feel this is a bug with the parser, if we see leading 0s, I don't think we should try to parse the number.

**Comment by fvilers** [comment]
Looks good to me. Does it mean I should open an issue in https://github.com/yargs/yargs-parser ?

**Comment by bcoe** [comment]
@fvilers 👍 yeah, I would appreciate that.

**Comment by fvilers** [comment]
Done! https://github.com/yargs/yargs-parser/issues/112
