### ISSUE TITLE
Failed on guessversion()

### ISSUE THREAD

**Issue by soimy** [yargs/yargs#1031]
Correct me if I was wrong. It's my first attempt switching from `commander`.
Following the API I wrote my cli setup but end up with fs.accessSync exception `path/to/cli.js/package.json` not found
So I digged a little deeper and find out this line in `yargs.js`
```javascript
const pkgJsonPath = findUp.sync('package.json', {
        cwd: path || require('require-main-filename')(parentRequire || require),
        normalize: false
```
which will pass filename `path/to/cli.js` instead of `path/to/` to `find-up`.
After adding `require('path').dirname(require('require-main-filename')(parentRequire || require))` the error is gone.

Am I the only one having this error?

**Comment by bcoe** [comment]
@soimy I haven't personally bumped into this issue, but feels like using `dirname` would be a worthwhile sanity check.

Would you mind submitting a patch?
