### ISSUE TITLE
"extends" should also trigger for files without extension that end in "rc"

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#1035]
It's a common convention for a configuration file to end with the suffix `rc`., e.g., `.nycrc`; it seems like a good extension to the `extends` functionality would be to also support filenames of the form `.*rc`.

Currently `extends` only supports the `.json` extension. fixes https://github.com/istanbuljs/nyc/issues/732

CC: @genepaul

**Comment by arunasank** [comment]
I'm interested in working on this✋

**Comment by arunasank** [comment]
I was taking a look at some files that have the extension `rc`, and the contents seem different in different files. For example:

## .npmrc
```
package-lock=false
```

## .babelrc
```
{
  "presets": ["env"]
}
```

And the nycrc file seems to be a json file. So, do we intend to only support files with a json format?

**Comment by bcoe** [comment]
@arunasank 👋 I've been dealing with some family health issues, so have been working on open-source sporadically; I would _love_ to have your help on this issue. Please don't hesitate to ask me questions in Slack...

> And the nycrc file seems to be a json file. So, do we intend to only support files with a json format?

I'm on the fence; if we could support INI format with minimal work, it could be interesting (but I think we should open a separate ticket for discussion.

**Comment by genepaul** [comment]
@arunasank, have you had a chance to work on this? Otherwise, I can take a crack at it now that I actually have time to get back to this.

**Comment by arunasank** [comment]
:wave: @genepaul I'd still like to work on this if you can help me.

**Comment by arunasank** [comment]
Oh, saw that you PR-ed already. 👍 Thanks for the fix!

**Comment by genepaul** [comment]
@arunasank, sorry to pull it out from under you, but when I made the change it was a lot easier than I expected it to be, so I just submitted the PR.

**Comment by arunasank** [comment]
Don't worry about it - maybe we can work together on another issue. : ) Thanks again for the fix!

**Comment by bcoe** [comment]
@arunasank @genepaul good news, I intend to start having a monthly meetup (both in person, and online, for triaging issues on yargs, Istanbul, conventional-commits, etc., and distributing work to the community). I'll try to pick a time that works well across timezones -- unfortunately it might be a bit early in the morning in Bangalore ...

**Comment by arunasank** [comment]
@bcoe yes! I can do anytime between 6 and 8 am except on Wednesdays when
I've an office call at 7.30. I'm a morning person. : )
