### ISSUE TITLE
Remove pinkie-promise in the dependencies chain

### ISSUE THREAD

**Issue by thangngoc89** [yargs/yargs#1040]
The original author of pinkie-promise: @floatdrop has unpublished all of his packages from npm (leftpad anyone? ) . And someone is taking control of the package in npm. pinkie-promise is used in `find-up` of yargs. 

You can follow the thread here https://github.com/floatdrop/pinkie-promise/issues/4

**Comment by zenflow** [comment]
Check out this similar issue: https://github.com/lerna/lerna/issues/1182

**Comment by thangngoc89** [comment]
Hi. I posted this in the very early minutes of the incident (way before npm even reported an incident). So this can be close now.

**Comment by bcoe** [comment]
missed this issue because I was ironically helping out (to a small degree) with the npm ops around the incident -- a more thorough post from my peers at npm will be going up soon.
