### ISSUE TITLE
requiresArg is enforced when option is not passed

### ISSUE THREAD

**Issue by jddxf** [yargs/yargs#1041]
index.js
```
const yargs = require('yargs');

yargs.options({
  a: {
    type: "string",
    requiresArg: true
  },
});
console.log(yargs.argv);
```
`node index.js` now fails, but it worked in versions prior 10.0.3.

I ran into the problem when using webpack-dev-server, but I think it probably is not the only thing being affected.

I have spent some time on this, and found the behavior was introduced in https://github.com/yargs/yargs/pull/1015.

**Comment by ljharb** [comment]
i'm confused, shouldn't this fail?

**Comment by jddxf** [comment]
@ljharb I suppose `node index.js --a` should fail while `node index.js` should not. Option `a` itself is not required. 

Here's a real life example: https://github.com/webpack/webpack-dev-server/blob/3e220fe1c9dcdc7b688090f0f4661e06a1e87c91/bin/webpack-dev-server.js#L112. Should `webpack-dev-server` fail when option `open-page` requires an argument and the option itself not passed? I suppose not.

That said, I'm not familiar with `yargs` and might misunderstand something about it.

**Comment by gombosg** [comment]
I experienced the same issue after an update.
```
.option('q', {
    alias: "queuesize",
    describe: "Maximum queue size",
    requiresArg: true,
    type: "number"
})
```
used to work, now it's not working after the update. Setting a default value is a temporary workaround.
