### ISSUE TITLE
Help dialog without script prefix

### ISSUE THREAD

**Issue by alex-phillips** [yargs/yargs#1045]
I just updated a project to the latest version of args, and I noticed that the generated help output now prefixes all of the commands with the script run (i.e., `index.js my_command` instead of previously just `my_command`). Is there a way to suppress this? It seems extremely redundant depending on the project.

Sorry if I missed it in the docs.

**Comment by emolr** [comment]
+1

**Comment by emolr** [comment]
Please let me know if any suggestions comes around :)

**Comment by emolr** [comment]
@alex-phillips take a look at https://github.com/yargs/yargs/issues/1010

**Comment by arthurattwell** [comment]
Update: #1143 resolves this issue: you can now [set the script name with `.scriptName($0)`](https://yargs.js.org/docs/#api-reference-scriptname0).

**Comment by bcoe** [comment]
hooray, another issue we can close, thank you @arthurattwell.
