### ISSUE TITLE
Function to modify argv

### ISSUE THREAD

**Issue by rrwen** [yargs/yargs#1052]
Hi,

I would like to request for way to add a function that modifies `argv` in between `yargs` methods:

```javascript
var yargs = require('yargs');
var argv = yargs
  .usage(...)
  .help(...)
  .transform(argv => {
    // modify argv before command
    return argv;
  })
  .command(...)
  .transform(argv => {
    // modify argv after command
    return argv;
  })
  .argv;
```

It may bring some flexibility to transforming `argv` in a simple way without the restrictions of .`coerce()` or in the case of .`command()`, where `argv` only gets returned if the command is called.

Thanks for the great package!

**Comment by bcoe** [comment]
I believe the functionality you asked for has since been added with [middleware](https://github.com/yargs/yargs/blob/master/docs/advanced.md#middleware) 🥳
