### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by LandonSchropp** [yargs/yargs#1055]
I used `yargs` for the first time yesterday, I have to say I'm extremely impressed with this library. Everything worked exactly how I expected it to, the documentation was fantastic, and the amount of functionality `yargs` added for such little configuration was amazing. I just wanted to say thanks for all the hard work. Creating a library that works this seamlessly isn't an easy thing to do, and I appreciate all the hard work you guys did on it.

Thank you!

**Comment by bcoe** [comment]
@LandonSchropp @dennisreimann thank you very much for the kind words 😄 makes working on OSS fun.
