### ISSUE TITLE
NODE JS 

### ISSUE THREAD

**Issue by akashdignitas** [yargs/yargs#1059]
how to add a sentence in cli in node js using yargs

this is what i do 

node app.js add --title:'Akash Secrets'

the whole 'Akash Secrets' is not coming under title key

**Comment by Morishiri** [comment]
Don't use `:` sign. It should be `=`.

So this:
`node app.js add --title:'Akash Secrets'`

becomes this:
`node app.js add --title='Akash Secrets'`

**Comment by akashdignitas** [comment]
Thanks for Help its blooming ....
