### ISSUE TITLE
way to remove an option from a subcommand

### ISSUE THREAD

**Issue by itai-codefresh** [yargs/yargs#1062]
is there a way to remove an option that was defined in a parent command form a subcommand?

**Comment by shadowspawn** [comment]
Does this mean so options are positional with respect to the commands? So these are handled differently?

```
$ program --debug sub
$ program sub --debug
```

**Comment by shadowspawn** [comment]
This issue has not had any activity in over four months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
