### ISSUE TITLE
Ability to alter the command name in the output of the help command

### ISSUE THREAD

**Issue by adrianth** [yargs/yargs#1065]
From what I can tell, the command name that is being used in the output of the help command is the name of the JavaScript file that yargs was set up from. I would like to alter the command name, or at least exclude the ".js" extension and use just the base name of the file. For example, instead of:

```
Commands:
  dosomenthing.js talk       Say somenting
  dosomenthing.js walk       Start walking
```

We should have:

```
Commands:
  dosomenthing talk       Say somenting
  dosomenthing walk       Start walking
```

Is there a way to accomplish this that I've missed in the documentation? If this feature doesn't exist yet, can you please consider adding it?

**Comment by Smolations** [comment]
I am actually having the same trouble. I am using args to work with a slack bot's slash commands, but `$0` always represents `index.js` so when I show the help, the js file shows up. I'd love to be able to replace it with the slash command if possible. I'll let you know if I find a workaround, but I'd love to see some feedback on this...

**Comment by kerfallak** [comment]
while defining your command you can just call parse like this and replace the filename to your desired command name. to be safe you can use argv.$0 to refer to the filename and use regex to replace the string in your output.
``` javascript
.help("h")
.alias("h", "help")
.parse("", (err, argv, output) => {
    if (output) {
      const newOutput = output.replace("filename.js", "commandname");
      console.log(newOutput);
    }
  })
.argv;
```

**Comment by adrianth** [comment]
Just tested the code and it does what I need. Thank you, @kerfallak. I only have one more question: do you still need to do the `.argv` at the end if you're calling `parse()`? I thought they do the same thing. I tested and everything seems to work fine without it.

**Comment by adrianth** [comment]
Perfect, thanks @kerfallak

**Comment by talon** [comment]
more recently [`.scriptName("pirate-parser")`](https://github.com/yargs/yargs/pull/1143) is how you set this
