### ISSUE TITLE
Improve performance during validation.

### ISSUE THREAD

**Issue by istvandomokos** [yargs/yargs#1066]
Hi,
Just an idea, but I recognized during to work on my project (using yargs) that the "validation.customChecks(argv, aliases)" is run before the remaining checks (like "validation.limitedChoices", "validation.implications" and "validation.conflicting" at yargs.js:1120). I made some memory and cpu intensive checks in my custom .check(...) function, and if the options where wrongly set (there were conflicts, or implications not met) than the parser fails (which is ok) and I made my custom checks unnecessarily.
If it looks a good idea (and there was no special reason why the checks are in this order) there should be a performance improvement to change the order of the checks and make the validation.customChecks the last.
Thanks, and all the best
i

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
