### ISSUE TITLE
Make `setPlaceholderKeys` optional

### ISSUE THREAD

**Issue by pvdlg** [yargs/yargs#1071]
The `setPlaceholderKeys` function has been added in #116. It sets all the options not set by the user in the CLI to `undefined`. This problematic the options object returned by `yargs` get merged with another one.
For example if you have an options object coming from a config file or somewhere else, and you want to merge it with `Object.assign` to the `yargs` options in a way that `yargs` options take precedence over the other object values.

Typically that would be a situation in which a CLI allows users to override config parameter via CLI arguments. It seems to a very common pattern.

In such situation all the flags not passed by the user (so the user does not want to override the config file) end up being set to `undefined` and override the config file value.

The workaround is to filter out the `yargs` options properties with a value equal to`undefined`.

I'm not really sure what was the need behind the implementation of `setPlaceholderKeys`, but as a result it forces to post-process `yargs` options (removing `undefined` values) to implement the very common pattern of "setting CLI arg to override config options".
 
Maybe the call to `setPlaceholderKeys` could be enable/disable with a `yargs` option?

Even better if this option, disable it by default, unless there is a good use case for setting placeholder to `undefined` that I don't see.

Would you be open to PR ?

See also yargs/yargs-parser#116 which is also related to implementation of the pattern "setting CLI arg to override config options"

Not that it matters much but this is the way `optimist` works, it doesn't create `undefined` placeholders.
```js
optimist.option('foo', {type: 'string'}).parse([])
{ _: [], '$0': '...' } // => no foo property

yargs.option('foo', {type: 'string'}).parse([])
{ _: [], '$0': '...', foo: undefined } // => foo set to undefined
```

**Comment by evocateur** [comment]
This definitely smells like a yargs-parser option to me (although that begs the question, should (can?) setPlaceholderKeys be a yargs-parser method?)...

**Comment by evocateur** [comment]
> In any case that would be helpful to understand what was the purpose of implementing this function.

I have often wondered myself, it does feel a bit out of place.

**Comment by pvdlg** [comment]
@evocateur should I open a PR that remove `setPlaceholderKeys` to at least see the impact on the tests?
@bcoe do you know what was the purpose of implementing `setPlaceholderKeys`?

**Comment by evocateur** [comment]
Yes, let’s see what breaks. I have personally yearned for its absence, chiefly for the Object.assign() use case.

**Comment by pvdlg** [comment]
See #1105.

It changes 2 tests:
- one that was explicitly testing the `undefined` "placeholder" behavior
- one that seems to be unintentionnal

**Comment by bcoe** [comment]
@pvdlg thanks for taking this on; I agree with your assertion that this is the better behavior.

I think (as @evocateur indicates) it would be good however to make this configurable (I think we should switch the default behavior to not setting placeholder keys however).

Let's add the configuration option described in these tickets: https://github.com/yargs/yargs/issues/1103, https://github.com/yargs/yargs/pull/1053, and make `set-placeholder-key` configurable behavior.

**Comment by pvdlg** [comment]
@bcoe I looked at the code but not sure where options are currently retrieved.
It seems #1103 and #1053 are about adding a function to programmatically change options. Am I right assuming the ability to set options already exist? If this is the case I could check the value of the `set-placeholder-key` option and apply the function when this option is `true`.

Could you help me to figure out where options are read? Should it be done in `yarg-parser` by adding an option to the one described in [customizing-yargs-parser](https://github.com/yargs/yargs/blob/master/docs/advanced.md#customizing-yargs-parser)?
If it's the case then the PR #1105 which remove `setPlaceholderKeys` from `yargs` is still valid. And I would need to open a new PR for `yarg-parser` that adds the `set-placeholder-key` option (default `false`) and set the missing options to `undefined` if the option is set to `true`.

**Comment by bcoe** [comment]
@pvdlg could I convince you to join our community slack:

http://devtoolscommunity.herokuapp.com/

and we can move towards finishing up this work.

**Comment by pvdlg** [comment]
Absolutely!

**Comment by pvdlg** [comment]
See https://github.com/yargs/yargs-parser/pull/123 that adds the `set-placeholder-key` configuration (default to `false`).
