### ISSUE TITLE
Calling .parse() with no arguments is equivalent to calling yargs.argv ? 

### ISSUE THREAD

**Issue by liangzeng** [yargs/yargs#1072]
https://github.com/yargs/yargs/blame/master/docs/api.md#L23

```
const yargs = require("yargs");
console.log(yargs.parse());
```

![image](https://user-images.githubusercontent.com/8503065/36336709-3377a042-13c5-11e8-9359-6991aa620788.png)

**Comment by tiboun** [comment]
yargs l.18 => processArgs = processArgs || [] // handle calling yargs().
yargs l.989 => get: () => self._parseArgs(processArgs),
yargs l.528 => if (typeof args === 'undefined') args = processArgs

In 11.1.0, your code doesn't fail. Maybe you should upgrade your version.
