### ISSUE TITLE
question dose it support es6 module？

### ISSUE THREAD

**Issue by xiayuxiaoyan** [yargs/yargs#1087]
if i do not use babel, can i use yargs like follow
import yargs from 'yargs'

**Comment by aduh95** [comment]
Have you tried it before asking your question?

I tried to save a file `test.mjs` with the following content:

```js
import yargs from "yargs";

yargs.help("h").alias("h", "help").argv;
```

Then I run it with the following command:

```sh
$ node --experimental-modules test.mjs --help
(node:5925) ExperimentalWarning: The ESM module loader is experimental.
Options:
  --version   Show version number                                      [boolean]
  -h, --help  Show help                                                [boolean]
```


> The flag `--experimental-modules` is available only for Node v8.5+, and the [API](https://nodejs.org/docs/latest-v9.x/api/esm.html) is not stable yet.
