### ISSUE TITLE
Documentation incorrectly says .help() prints help message. Should reference .showHelp()

### ISSUE THREAD

**Issue by dshepsis** [yargs/yargs#1088]
Currently, the documentation [here](https://github.com/yargs/yargs/blob/master/docs/api.md#help) and [here](http://yargs.js.org/docs/#api-help) claims that:

> If invoked without parameters, .help() will use --help as the option and help as the implicit command to trigger help output.

This is incorrect in the current version of yargs, as far as I can tell. The documentation should reference [`yargs.showHelp()`](https://github.com/yargs/yargs/blob/master/docs/api.md#showhelpconsolelevelerror) instead.

**Comment by nic-hartley** [comment]
I think you've misread the documentation. It's not saying "calling `.help()` prints the help message", it says "calling `.help()` adds a `--help` option and a `help` subcommand which, when used, displays the relevant help message."

**Comment by shadowspawn** [comment]
An answer was provided (thanks @nic-hartley), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
