### ISSUE TITLE
Is there any way to add a new line before the help contents ?

### ISSUE THREAD

**Issue by faressoft** [yargs/yargs#1089]
I noticed that there is always a blank line after the help contents, but there are no blank line at the beginning. I am looking for consistency, so is there any way to print a blank line at the beginning ?

<img width="583" alt="screen shot 2018-03-18 at 5 55 57 pm" src="https://user-images.githubusercontent.com/1908658/37567872-e128147a-2ad5-11e8-9fde-3d8fe6595425.png">

**Comment by bcoe** [comment]
@faressoft looking at a few of the common bins on my computer, it seems  as though most bins don't have a `\n` at the start or the end of the help output:

---

```bash
Benjamins-MBP-2:tmp benjamincoe$ heroku --help
Usage: heroku COMMAND

Help topics, type heroku help TOPIC for more details:
```

```bash
Benjamins-MBP-2:tmp benjamincoe$ git --help
usage: git [--version] [--help] [-C <path>] [-c name=value]
           [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p | --paginate | --no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           <command> [<args>]

These are common Git commands used in various situations:
```

```bash
Benjamins-MBP-2:tmp benjamincoe$ kubectl --help
kubectl controls the Kubernetes cluster manager. 

Find more information at https://github.com/kubernetes/kubernetes.

Basic Commands (Beginner):
```
---

to add a newline before the help output you can do something like this:

```js
require('yargs')
  .usage('\ncool')
  .argv
```

☝️ but, I think a better solution might be for us to nix the blank newline at the end of help output (this would better match tools like git, and kubectl).

**Comment by faressoft** [comment]
@bcoe Yes indeed, removing the \n at the end will be better.
