### ISSUE TITLE
Process exits when chaining config methods in v.11.0.0

### ISSUE THREAD

**Issue by sharonswli** [yargs/yargs#1092]
Hello,

I'm having trouble using the yargs API [here](https://github.com/yargs/yargs/blob/master/docs/api.md) to add some configurations to my script. It seems like while `const argv = require('yargs').argv` works great, as soon as I add custom configurations to my `yargs` object, the script terminates early and prints out `1.7.0` on my console...No warning and no errors, just `1.7.0`. 

```
$ node script.js
>1.7.0
```

This works fine:
```
const argv = require('yargs').argv;
console.log(argv);
// Running rest of the code now...
```
But this doesn't.
```
const argv = require('yargs')
  .array('flag') // any method
  .argv;
// Process exits!
```
I've been staring at the docs and wondering if I'm missing something...but from the documentation looks like my code is right. I'm using yargs `v.11.0.0` and node `v.8.9.4 (LTS)`.

Cheers!

**Comment by shadowspawn** [comment]
I cannot reproduce this problem.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
