### ISSUE TITLE
Is this how check(fn, [global=false]) is supposed to behave?

### ISSUE THREAD

**Issue by keithbentrup** [yargs/yargs#1094]
Am I misunderstanding how global should behave? If I set it to `false`, I expect my check function to only apply to the current command. However, `false` seems to disable it completely.

Here's a simplified version of a CLI I'm working on. The 1st commands expect no additional args. The 2nd may have several.

```
#!/usr/bin/env node

const yargs = require('yargs')

yargs
  .usage('$0 <cmd> [args]')
  .strict()
  .alias('h', 'help')

const verifyOnly1Arg = function(a, b) {
  if (a._.length > 1) {
    throw `The "${a._[0]}" command expects no additional args.`
  }
  return true
}

yargs.command(['command1', 'c1'], 
  'Run command 1', 
  () => {}, 
  argv => console.log(1)
)
.check(verifyOnly1Arg, false)

yargs.command(['command2', 'c2'], 
  'Run command 2', 
  () => {}, 
  argv => console.log(2)
)

yargs.argv
```
When `check(verifyOnly1Arg, false)`, the check isn't run on either. When `check(verifyOnly1Arg, true)`, the check is run on both.

when false
```
$ ./file c1 dummy-arg
1
$ ./file c2 dummy-arg
2
```

when true
```
$ ./file c1 dummy-arg
The "c1" command expects no additional args.
$ ./file c2 dummy-arg
The "c2" command expects no additional args.
```

**Comment by roccomuso** [comment]
Same. Following.

**Comment by jramsley** [comment]
I was running into this today, so poked around the repo and it looks like this is expected.  When doing the `.check` at the top level, this is not running it on any of the sub-commands unless global is true even if it looks like you are adding it to the command in the builder.  Instead, you need to add the check to the command's builder instead.

ex.
```
yargs.command(['command1', 'c1'], 
  'Run command 1', 
  yargs => { yargs.check(verifyOnly1Arg) },
  argv => console.log(1)
)
```

vs.

```
yargs.command(['command1', 'c1'], 
  'Run command 1', 
  () => {}, 
  argv => console.log(1)
)
.check(verifyOnly1Arg)
```

**Comment by bcoe** [comment]
@jramsley thanks for fielding this question 👍.

Closing this issue since it's been open for several years, and you've outlined a good approach.
