### ISSUE TITLE
Parent Command Global Handler

### ISSUE THREAD

**Issue by mmacfadden** [yargs/yargs#1097]
We have several nested commands like this:

```
cli server --url <url> get users
cli server --url <url> get groups
cli server --url <url> get roles
cli server --url <url> create user
...
```
We are using command modules and the commandDir method of yargs, such that each of these commands is in a separate file. The issue is that for every command we want to take some common actions.  For example, when the code executes we would like to always print the server url:

```
$ cli server --url http://localhost/ get users
Using server: http://localhost/
{
  users: []
}

$ cli server --url http://localhost/ get users
Using server: http://localhost/
{
  users: []
}
```

There are other common actions. Presently, we have created some common functions that are simply called by each child command handler. I would love to be able to execute some code at the higher level, in this case within the "server" command module. The `server.js` file that implements the server command looks like this:

```
exports.command = 'server <command>';
exports.desc = 'Executes a remote command against a server';
exports.builder = function (yargs) {
  return yargs
    .option("url", {
      alias: "u",
      describe: "The URL of the server"
    })
    .commandDir('server_cmd')
};
exports.handler = function (argv) {
  // Would love to execute a common function here that would be executed 
  // before the handler of the child commands.
  console.log("Using server: " + argv.url);
};
```
This way, this code would always be executed and i would not need to do it in each child command.  Is something like this possible?

**Comment by vonagam** [comment]
Hi, had same problem recently.

The answer is `visit` function in `opts` of [`commandDir`](https://github.com/yargs/yargs/blob/master/docs/advanced.md#commanddirdirectory-opts). It receives command object and can modify it before returning. 

You can add middleware or replace handler with wrapped version to implement common functionality.

**Comment by shadowspawn** [comment]
Thanks for the detailed description. An answer was provided (thanks @vonagam), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
