### ISSUE TITLE
optional positional argument followed by required ones, results in odd behaviour

### ISSUE THREAD

**Issue by ahmadnassri** [yargs/yargs#1100]
~seems like positional argument order is not respected, or at least processed in reverse ...~

I think I stumbled into this oddity by mistake, but nevertheless, perhaps some user warning is needed when positional arguments start with optional followed by requried.

```js
#!/usr/bin/env node

const yargs = require('yargs')

function command (yargs) {
  yargs
    .positional('first', {
      describe: 'first pos'
    })
    .positional('second', {
      describe: 'second pos'
    })
    .positional('third', {
      describe: 'third pos'
    })
}

function builder (argv) {
  console.log('should be first:', argv.first)
  console.log('should be second:', argv.second)
  console.log('should be third:', argv.third)
}

yargs.command('$0 [first] <second> <third>', '', command, builder).argv
```

```bash
$ ./lib/cli.js first second third
should be first: third
should be second: first
should be third: second
```

**Comment by bcoe** [comment]
@ahmadnassri in your definition, you have an optional argument `[first]` before two required arguments `<second>` and `<third>`; this behavior would be undefined, and we should probably make raise an exception.

Try instead:

`yargs.command('$0 <first> <second> <third>', '', command, builder).argv`

or:

`yargs.command('$0 <first> <second> [third]', '', command, builder).argv`

depending on what you were going for.

**Comment by ahmadnassri** [comment]
ah, indeed, that seems odd that I ended up with an optional argument as the first one ... I certainly see this no longer as an error, but rather an edge case worthy perhaps (as you suggested) of raising a warning. I'm going to update the issue title accordingly! :+1:
