### ISSUE TITLE
command error propagation is not predictable

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#1102]
see #953, #955 for examples of folks bumping into issues around error propagation in commands.

@evocateur ran into this issue in Lerna, and has some potential thoughts about a better implementation.

let's start a discussion here, regarding API improvements.

**Comment by rehangit** [comment]
This seems an old open issue. Is there any news about it? What is the workaround if any?

**Comment by bcoe** [comment]
@rehangit I think it would be best to close this, and if folks are bumping into problems with commands, we should open a new  issue with a more specific error.
