### ISSUE TITLE
make yargs advanced configuration available through API (not just implicitly)

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#1103]
yargs' parser settings can currently be configured using the `yargs` stanza in your package.json. This works for some use-cases, but it can be difficult for (as an example) writing unit tests.

Let's introduce the a `yargsConfiguration` API method that allows you to programmatically configure these advanced settings, and takes precedence over finding a package.json.

This is a prerequisite for implementing #1053.

**Comment by shadowspawn** [comment]
Was this implemented as `.parserConfiguration()`? First iteration in #1262.

**Comment by shadowspawn** [comment]
I _think_ this has been done. Closing as resolved. 😅
