### ISSUE TITLE
Move Code of Conduct section to CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by aorinevo** [yargs/yargs#1114]
Complete the [Community Profile Checklist](https://github.com/yargs/yargs/community)
  - Move Code of Conduct section from [here](https://github.com/yargs/yargs/blob/master/contributing.md) to [CODE_OF_CONDUCT.md](https://github.com/yargs/yargs/community/code-of-conduct/new?template=contributor-covenant)
  - Add an issue or pull request template

<img width="1019" alt="screen shot 2018-05-01 at 12 25 52 am" src="https://user-images.githubusercontent.com/3240137/39461092-8aff3f7e-4cd6-11e8-9ca1-997b932f8f97.png">

**Comment by bcoe** [comment]
\o/ done, thanks @aorinevo
