### ISSUE TITLE
Boolean negated --no-xxx variant isn't discoverable in the command line help

### ISSUE THREAD

**Issue by papandreou** [yargs/yargs#1116]
A tool I help develop takes a boolean `--recursive` option that defaults to true. This has caused some confusion, because it isn't really obvious from the help how to turn it off: https://github.com/Munter/subfont/issues/20

I don't have a specific suggestion, but would you entertain the idea of having the help explicitly list the `--no-...` variant of the switch?

**Comment by aorinevo** [comment]
@papandreou It is possible to set the default value to false, if that is what you're expecting when a user passes the recursive flag:
```js
exports.builder = {
  recursive: {
    default: false
  }
};
```

**Comment by papandreou** [comment]
I want `true` to be the default, and it all works fine. The problem (as you can see in the linked thread) is that it is non-obvious from the help text that it's possible to turn it off by providing `--no-recursive`:

```
  --recursive, -r  Crawl all HTML-pages linked with relative and root
                   relative links. This stays inside your domain
                                               [boolean] [default: true]
```

So what I'm suggesting is to somehow explicitly list `--no-recursive` also.

**Comment by aorinevo** [comment]
I think one thing to consider, if you explicitly list `--no-` for all boolean flags, is that the size of the help menu could, at worse, double.

An alternative might be to add to the description of the tool a reminder that `--no-` can be used to invert the default values.  

For example,
```bash
▶ ./node_modules/.bin/subfont --help
Create optimal font subsets from your actual font usage.  Prepend --no- to boolean flags to invert default values.
subfont [options] <htmlFile(s) | url(s)>
```

**Comment by papandreou** [comment]
@aorinevo, A general reminder at the top or bottom would be an improvement. However, I think it'd be more in-your-face obvious if it accompanied the (probably rare) boolean switches that have `true` as the default.

Something like:

```
  --inline-fonts   Inline fonts as data-URIs inside the @font-face
                   declaration                [boolean] [default: false]
  --[no-]recursive, -r  Crawl all HTML-pages linked with relative and root
                   relative links. This stays inside your domain
                                               [boolean] [default: true]
```

Or:

```
  --inline-fonts   Inline fonts as data-URIs inside the @font-face
                   declaration                [boolean] [default: false]
  --recursive, -r  Crawl all HTML-pages linked with relative and root
                   relative links. This stays inside your domain
                  [boolean] [default: true] [to disable: --no-recursive]
```

**Comment by bcoe** [comment]
I hear where you're coming from, but I think that the docs get a little bit verbose if we document this much of the parser's behavior by default ... if your customers need the hint I recommend putting it in the description of the argument, and perhaps your README.md file.

It's worth noting that you can also specify `--recursive false` 👈 which is equivalent to `--no-recursive`.

**Comment by bcoe** [comment]
to expand a bit, just so I don't look like a jerk running around closing issues; there are a bunch of parsing rules like this:

* how we automatically parse floating point numbers and integers.
* how we parse arrays; based on passing flags multiple times.

It feels like a bit of a slippery slope documenting all of this in yargs' help output.

**Comment by patarapolw** [comment]
It looks like I have to resort to this for the time being...

```javascript
const { argv } = yargs
.option('no-recursive', {
  type: 'boolean',
  describe: 'Disable recursive mode'
})

...
argv.noRecursive
```
