### ISSUE TITLE
PR-AN-06: Split yargs.js

### ISSUE THREAD

**Issue by aorinevo** [yargs/yargs#1117]
## Feature Request

Separate yargs.js into separate files by api method.  Under lib directory, create an api directory.  For each api method, create a file - use the method name for the filename.  Port the code over to the file, and require it into yargs.js.

**Comment by aorinevo** [comment]
PR reduced yargs.js by 63 lines.

**Comment by bcoe** [comment]
@aorinevo 👍 made a few comments on the pull request. I'm on the fence about this refactor, but open to kicking around some alternatives.

**Comment by aorinevo** [comment]
Discussed refactoring state management instead (see #1150)
