### ISSUE TITLE
Add support for ES6 using Webpack/Rollup

### ISSUE THREAD

**Issue by aorinevo** [yargs/yargs#1120]
Use webpack (v4.x.x) and babel to precompile and bundle yargs' files.

This would let developers use ES6 while maintaining support for node 4, 5, and 6.

**Comment by aorinevo** [comment]
See PR #1153

**Comment by evocateur** [comment]
I'd rather use Rollup, tbh. Much cleaner generated output, for one thing

**Comment by aorinevo** [comment]
Ok, I'll take a look.

**Comment by aorinevo** [comment]
@evocateur, I added a build script - `npm run build` - to transpile down to ES2015 using Rollup. See PR https://github.com/yargs/yargs/pull/1164.

I wasn't able to get the spec runner to work work with the new ES6 syntax (i.e. imports/exports).

Any ideas on how to do this?

**Comment by aorinevo** [comment]
Adding a transpiler makes sense for apps targeting multiple browsers but since yargs is able to target specific versions of Node.js, we can simply drop Node versions over time.  We would also end up adding too much complexity for small gains.

Closed PRs #1164 and #1153
