### ISSUE TITLE
README.md on NPM page no longer links to github docs correctly

### ISSUE THREAD

**Issue by speakerwiggin** [yargs/yargs#1122]
## Intended result:
1. Click `Yargs API` under `Table of Contents` on https://www.npmjs.com/package/yargs
2. Redirected (or new tab opens to) https://github.com/yargs/yargs/blob/master/docs/api.md

## Actual result:
1. Click `Yargs API` under `Table of Contents` on https://www.npmjs.com/package/yargs
2. Redirected (or new tab opens to) https://www.npmjs.com/docs/api.md

**Comment by bcoe** [comment]
I believe this is corrected now, it was a bug on npm's side of things.
