### ISSUE TITLE
npm has 11.0.0 (not 11.1.0) tagged as latest

### ISSUE THREAD

**Issue by jimhigson** [yargs/yargs#1128]
See the [versions on npm](https://www.npmjs.com/package/yargs?activeTab=versions)

Npm thinks 11.0.0 is the latest version, but it looks like 11.1.0 should be.

**Comment by styfle** [comment]
Ping @evocateur

**Comment by evocateur** [comment]
I’m not authorized to make changes to yargs on the registry.

**Comment by bcoe** [comment]
`11.1.0` is a candidate release on the `next` branch, we do this from time to time during the QA process.
