### ISSUE TITLE
Using other input, instead of process.argv

### ISSUE THREAD

**Issue by allnulled** [yargs/yargs#1141]
As I have noticed, the API is thought to work only with process.argv.

But there are libraries out there that can transform a string into an array, just like the array found at process.argv.

We could maybe, as the JS let us add properties even to a function, do something like:

require("yargs").args("node my-command as string")...

And so, we can respect the whole API as it is right now.

I have seen in your source code that you have, in your index.js file, a special function for this purpose: Argv.

I think it would be worthy to open this functionality, as all the programs would turn reusable in any point of a program, but not in a os-process level, just as a functional level, which is quite interesting.

**Comment by haykam821** [comment]
Please, stop with all, of the commas, that you use unnecessarily.

Anyways, there is already `yargs.parse` for this functionality:

```js
const yargs = require("yargs");
yargs.parse([
    "node",
    "my-command",
    "-x",
    "1",
    "--why",
    "2",
]);
```

**Comment by allnulled** [comment]
Nothing to do with what I am saying, as the APi you are using does not provide the whole functionality that the `yargs` library gives.

Sorry if the way I express annoys you, but it is not my business, as the commas I use are needed to express what I want to express.

**Comment by haykam821** [comment]
What do you mean? It’s functionally the same as `yargs.argv`.

**Comment by allnulled** [comment]
Thank you bro. That was exactly what I was looking for, I can combine this with `string-argv` and get the desired behaviour. Thank you.

**Comment by allnulled** [comment]
Shame on me.
