### ISSUE TITLE
banner() or header() that works like epilogue()

### ISSUE THREAD

**Issue by ZaDarkSide** [yargs/yargs#1142]
I would like a function to display a banner or header before the actual command list help, it should work like epilogue().

**Comment by 4matic** [comment]
Yes! I also needed this feature.
In my case I wanted to use ascii banner for cli header like [this](http://patorjk.com/software/taag/#p=display&f=ANSI%20Shadow&t=CLI%20BANNER).

Any ideas when it could be done?)

**Comment by Linard11** [comment]
usage() will be printed above the command list when typing given the `help` command or `--help`

**Comment by ZaDarkSide** [comment]
Thanks.
