### ISSUE TITLE
default command not work in commandDir

### ISSUE THREAD

**Issue by binarymist** [yargs/yargs#1147]
Default command in `screen.js`

```
const pkg = require(`${process.cwd()}/package.json`);

exports.command = '*';
exports.desc = 'Default command (shows the interactive screen).';
exports.builder = {};
exports.handler = (parsedArgv) => {
  debugger;
  parsedArgv._handled = true;      
  if (parsedArgv.a) {
    const { name: projectName, version, description, author: { name, email } } = pkg;
    console.log(`${projectName} ${version}`);
    console.log(description);
    console.log(`Created by ${name}<${email}>`);
  } else {
    // Add commands so they show up in help.
    yargs.command(screen).command(test).command(testPlan);
    yargs.showHelp();
    console.log(`Unknown argument: ${parsedArgv._[0]}`);
  }
};
```
produces:

(node:10145) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: yargs is not defined
(node:10145) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Add in `const yargs = require('yargs');`

and now produces:

(node:10360) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): ReferenceError: screen is not defined
(node:10360) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by binarymist** [comment]
I missunderstood how this is supposed to work, due to the docs being a bit lacking. Is working now.

**Comment by JimTheMan** [comment]
@binarymist what did you change?

**Comment by bcoe** [comment]
@binarymist bother you to open a PR with a docs update, or an issue outlining what was confusing?

**Comment by lewebsimple** [comment]
This works for setting a command as default:
```
export const command = "$0 <url>";
```

**Comment by binarymist** [comment]
Sorry, only just saw this. My code is here: https://github.com/purpleteam-labs/purpleteam
This maybe the same file, can't remember now: https://github.com/purpleteam-labs/purpleteam/blob/main/src/cli.js
