### ISSUE TITLE
zsh completion hints

### ISSUE THREAD

**Issue by oncletom** [yargs/yargs#1156]
Hello,

I was inspecting zsh completion and discovered it was not working.
Too bad!

By screening into https://github.com/mklabs/tabtab/blob/master/scripts/zsh.sh, I found out there was not much to change to port the existing template.

From this bash handlebar template

```
###-begin-{{app_name}}-completions-###
#
# yargs command completion script
#
# Installation: {{app_path}} {{completion_command}} >> ~/.bashrc
#    or {{app_path}} {{completion_command}} >> ~/.bash_profile on OSX.
#
_yargs_completions()
{
    local cur_word args type_list

    cur_word="${COMP_WORDS[COMP_CWORD]}"
    args=("${COMP_WORDS[@]}")

    # ask yargs to generate completions.
    type_list=$({{app_path}} --get-yargs-completions "${args[@]}")

    COMPREPLY=( $(compgen -W "${type_list}" -- ${cur_word}) )

    # if no match was found, fall back to filename completion
    if [ ${#COMPREPLY[@]} -eq 0 ]; then
      COMPREPLY=( $(compgen -f -- "${cur_word}" ) )
    fi

    return 0
}
complete -F _yargs_completions {{app_name}}
###-end-{{app_name}}-completions-###
```

To this zsh completion template

```
###-begin-{{app_name}}-completions-###
#
# yargs command completion script
#
# Installation: {{app_path}} {{completion_command}} >> ~/.bashrc
#    or {{app_path}} {{completion_command}} >> ~/.bash_profile on OSX.
#
_yargs_completions()
{
  local reply
  local si=$IFS

  # ask yargs to generate completions.
  IFS=$'\n' reply=($(COMP_CWORD="$((CURRENT-1))" COMP_LINE="$BUFFER" COMP_POINT="$CURSOR" {{app_path}} --get-yargs-completions "${words[@]}"))
  IFS=$si

  _describe 'values' reply
}
compdef _yargs_completions {{app_name}}
###-end-{{app_name}}-completions-###
```

I have no idea what's going on but it works — although it seems to recommend everything and not much what's only matching the typed words.

It's a start.

**Comment by oncletom** [comment]
There are plenty of beautiful stuff happening in https://github.com/f/omelette/blob/master/coffee/omelette.coffee too.

**Comment by oncletom** [comment]
The last element being `bashcompinit`, to enable bash completion for zsh.

```
autoload -U +X bashcompinit && bashcompinit
eval "$(yargs-enabled-program completion)"
```

**Comment by Loilo** [comment]
For anybody interested: Until there's official support for zsh completion, I made [this little tool](https://github.com/Loilo/completarr) (with the aforementioned [omelette](https://github.com/f/omelette)).

**Comment by tylerssn** [comment]
@trevorlinton - would love to see what you came up with.

**Comment by john-osullivan** [comment]
@loilo Hey, `competarr` seems to provide exactly the experience I was hoping `yargs` autocomplete would!  I see how the scripts get generated, but having to update bash myself seemed like a waste.  Thanks for writing this up!  That simple setup through scripts is perfect.

**Comment by loilo** [comment]
@john-osullivan Thanks! But to be honest, the point of `completarr` is pretty much void now that yargs has [built-in auto completion](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#features-3) for zsh (which was my major pain point before). Using it also is a performance hit as it executes and parses the `--help` output, which is quite some overhead.

The easy installation step however is a thing I consider very important — maybe I should provide an installation script for yargs-based CLIs as an extra package. 🙂
