### ISSUE TITLE
yargs unable to handle option on command levels

### ISSUE THREAD

**Issue by abuzarhamza** [yargs/yargs#1157]
I am using the node js yargs module to the options passed to the terminal. My script has multiple commands with each command having different input for other commands.

When I am running the command `myscriptname cp -i 12345 `it gives the following message on the terminal  

> Not enough non-option arguments: got 0, need at least 2

here is my yargs code to handle terminal option in command

```
const yargs = require('yargs');    
let argv = yargs
    .usage('$0 <command> [option]')
    .command(
        'cd , compare_dollar',
        'compare exchange rate of dollar',
        (yargs) => {
            return yargs
                .usage('$0 compare_dollar -file <fileName> -stage [options] -country [option]')
                .example('$0 compare_dollar -file fpp.xls -stage dev', 'calculate the exchange')
                .example('$0 cd -f fpp.xls -s dev', 'calculate the exchange')
                .alias('f', 'file')
                .nargs('f', 1)
                .describe('f', 'file path')
                .default('f', './foo.xls')
                .alias('s', 'stage')
                .describe('s', 'stage i.e [dev|qa|uat|prod]')
                .default('s', 'dev')
                .alias('c', 'country')
                .describe('c', '[IN|BA]')
                .default('c', 'IN')
                .help('h')
                .alias('h', 'help')
                .wrap(null);

        }
    )
    .command(
        'cp , compare_price',
        'compare price for an item on various sites',
        function (yargs) {

            return yargs
                .usage('$0 cp -i <item_id> -s [option] -c [option]')
                .example('$0 cp -item_id <item_id> -s dev -c US', 'foooo')
                .example('$0 cp -i <item_id>', 'foooo')
                .alias('i', 'item_id')
                .demand(1)
                .alias('s', 'stage')
                .describe('s', 'stage i.e [dev|qa|uat|prod]')
                .default('s', 'dev')
                .alias('c', 'country')
                .describe('c', '[IN|BA]')
                .default('c', 'IN')
                .help('h')
                .alias('h', 'help');
        }
    )
    .help('h')
    .alias('h', 'help')
    .demand(1)
    .wrap(null)
    .argv;

```

**Comment by Linard11** [comment]
`cd , compare_dollar`
will be interpreted as
command: `cd`
positionals: `<,>` `<compare_dollar>`

to give an alias for your command you need to put it in an array like this:
`['cd', 'compare_dollar']`
The string at index 0 will be the 'real' name of the command with every other string in the array as an alias. Positionals can be defined only at the string at index 0, and will be ignored if defined in an alias string, but will ofc work for all alias the same as when using the real name

**Comment by shadowspawn** [comment]
Thanks for the detailed description. An answer was provided (thanks @Linard11), and no further activity. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
