### ISSUE TITLE
.defaults() will be removed in farther version?

### ISSUE THREAD

**Issue by zzzgit** [yargs/yargs#1185]
![image](https://user-images.githubusercontent.com/1060733/43067515-25e1aee6-8e9a-11e8-828a-2bb385cd4760.png)

sorry for my poor english.
what will be removed? `.defaults()` itself or `.defaults()`'s alias?

**Comment by juergba** [comment]
Only the alias will be removed.
`.default(key, value, [description])` => remains valid
`.defaults(key, value, [description])` => only this alias will be removed.

Please close this issue, thanks.
