### ISSUE TITLE
Yargs vulnerable to Denial of Service

### ISSUE THREAD

**Issue by marcincubernews** [yargs/yargs#1209]
Any plans to fix the following:

MEDIUM SEVERITY
Denial of Service (DoS)
Vulnerable module: mem
Introduced through: yargs@12.0.1
Detailed paths
Introduced through: aws-cfm-utils@marcincuber/aws-cfm-utils#79f71e6219feee28029f424ae5fc08153f270384 › yargs@12.0.1 › os-locale@2.1.0 › mem@1.1.0
Overview
mem is an optimization technique used to speed up consecutive function calls by caching the result of calls with identical input.

Affected versions of this package are vulnerable to Denial of Service (DoS) attacks. Old results are not deleted from the cache and could cause a memory leak.

**Comment by spencern** [comment]
`os-locale` was updated today: https://github.com/sindresorhus/os-locale/pull/31

**Comment by Delagen** [comment]
#1211

**Comment by dominykas** [comment]
#1195 has been merged and `master` does not have this problem anymore, so all this needs is a new `npm publish`.

**Comment by rhuddleston** [comment]
Don't we need version 3.0.1?

**Comment by dominykas** [comment]
@rhuddleston it will update itself as it matches semver

**Comment by bcoe** [comment]
@marcincubernews I believe this should be corrected in yargs>=12.0.2.
