### ISSUE TITLE
Medium severity vulnerability in mem (sub-dependency included with yargs v12.0.1)

### ISSUE THREAD

**Issue by dominykas** [yargs/yargs#1211]
Running `snyk test` on yargs `v12.0.1` (latest release on npm) results in:

```
✗ Medium severity vulnerability found in mem
  Description: Denial of Service (DoS)
  Info: https://snyk.io/vuln/npm:mem:20180117
  Introduced through: os-locale@2.1.0
  From: os-locale@2.1.0 > mem@1.1.0
```

`os-locale` has [already been upgraded](https://github.com/yargs/yargs/pull/1195) and `master` does not have this problem anymore, so all this needs is a new `npm publish`.

Thanks!

**Comment by Delagen** [comment]
#1195

**Comment by dominykas** [comment]
Duplicate of #1209, sorry.
