### ISSUE TITLE
Overriding --version flag

### ISSUE THREAD

**Issue by mzedeler** [yargs/yargs#1213]
I haven't used yargs before and just needed to write a small utility taking one parameter named `version`.

It turns out that yargs mangles this parameter, not making it available as expected.

To reproduce:

Run this:

    node -e 'const { argv } = require("yargs").option("my-value").option("version"); console.log(argv)' -- --version=42 --my-value=test

Expected:

The `argv` parameter that is being output contains `version: 42`.

Actual:

The `argv` does not contain `version: 42`.

Alternatively, yargs should complain loudly about declaring the `version` field, because it is being used for something else.

**Comment by ohjimijimijimi** [comment]
+1

**Comment by cschuff** [comment]
This should do:
```
yargs.version(false)
  .option('version', {
    alias: 'v',
    default: 'something',
    describe: 'Description of my usage of the version parameter',
    type: 'string',
  })
```

**Comment by bcoe** [comment]
@cschuff thank you for providing this (correct) solution. @mzedeler, I apologize for letting this issue become so stale.
