### ISSUE TITLE
Middleware does not accept a single function

### ISSUE THREAD

**Issue by JamesMessinger** [yargs/yargs#1214]
According to [the docs for the `.middleware()` method](http://yargs.js.org/docs/#api-middlewarecallbacks):

> The `callbacks` parameter can be a function or a list of functions

However, it currently (as of v12.0.2) only works with an array of functions.  Passing a single function does nothing.  

```javascript
yargs
  .command('myCommand', 'some command', {}, function(argv){
    console.log('Running myCommand!');
  })
  .middleware(() => console.log('Running middleware 1'))   // <--- this never runs
  .middleware(() => console.log('Running middleware 2'))   // <--- neither does this
  .parse(['myCommand']);
```

[Here is a reproduction of the issue on RunKit.](https://runkit.com/bigstickcarpet/yargs-middleware-bug)

The problem is caused by this block of code:
https://github.com/yargs/yargs/blob/6c6c27d8c87c25e052df23abcf5875253b6b20cd/lib/middleware.js#L3-L7

I believe that `if (typeof callback === 'object')` should be `if (typeof callback === 'function')`.

I will submit a PR for this momentarily

**Comment by JimiC** [comment]
Confirmed. Currently, if you need to pass a single function, it's mandatory to add it to an `Array` and pass that.

What I don't get either, is why and when a `callback`  is an `object` (See also https://github.com/yargs/yargs/blob/v12.0.2/test/middleware.js#L24).
From what I know a `callback` is **always** a `function`.

**Comment by BigstickCarpet** [comment]
@JimiC - Agreed.  I think the `'object'` in the type check was just a typo or misunderstanding.  It probably should have always been `'function'` instead

**Comment by BigstickCarpet** [comment]
@aorinevo - Here's the PR: https://github.com/yargs/yargs/pull/1215

**Comment by JimiC** [comment]
And the related test is also adjusted.

**Comment by bcoe** [comment]
@JamesMessinger @JimiC please try `npm i yargs@next`, which should have a patch that fixes this; if the release is looking good, I'll promote it next week.

**Comment by JimiC** [comment]
LGTM :+1:

**Comment by arkon** [comment]
Seems like this should be closed?

**Comment by bcoe** [comment]
@arkon thanks for helping us groom some of our old issues 👍
