### ISSUE TITLE
Can a positional arg be mandatory

### ISSUE THREAD

**Issue by cmoulliard** [yargs/yargs#1216]
This syntax works `jira get SB-456` using this code

```
exports.command = 'get [id]';
exports.desc = 'Fetch a Jira issue';
exports.builder = (yargs) => yargs
    .positional('id', {
        desc: 'Pass the Issue Key such as SB-567',
        alias: 'i',
        type: 'string'
    });

exports.handler = (argv) => {
    console.log("args : " + argv.id)
```

but yargs doesn't complain that `id` is missing when we execute this command `jira get`

Is there an option to tell to args that positional is mandatory ?

**Comment by DennyGD** [comment]
It should work if you just change the type of brackets:
`get [id]` to `get <id>`

**Comment by shadowspawn** [comment]
Thanks for a clear description. An answer was provided (thanks @DennyGD), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
