### ISSUE TITLE
coerce not called if option not given

### ISSUE THREAD

**Issue by Nautigsam** [yargs/yargs#1219]
I have this command definition:
```javascript
module.exports = {
    command: 'ls [options]',
    describe: 'List tags',
    builder(yargs) {
        yargs
            .option('task', {
                alias: 't',
                describe: 'a task number',
                type: 'string',
                requiresArg: true
            })
            .coerce('task', arg => {
                console.log('AAA: ', arg)
                return arg
            })
            .showHelpOnFail(true)
    },
    async handler(argv) {
        ...
    }
}
```

But when option `--task` is not provided, the `coerce` function is not called. Is it really the expected behaviour? Shouldn't the function be called with `undefined` nonetheless?

**Comment by brewster1134** [comment]
if no value is passed, your default should be all the coercion you would  need.  do you have a use case that would need it called?

**Comment by Nautigsam** [comment]
I can not remember the initial use case that made me open this issue. I guess will just close it.
