### ISSUE TITLE
Upgrade os-locale in yargs 11 to support webpack 3

### ISSUE THREAD

**Issue by corymcdonald** [yargs/yargs#1223]
Issue #1209 details that yargs is vulnerable to a DOS attack through the `os-locale` node package. This is resolved in version 12, because the os-locale version is `^3.0.0`.

I opened a pull request in webpack to resolve this https://github.com/webpack/webpack/pull/8130 by upgrading to yargs 12.0.  But support for node 4 was removed in 12.x which is a breaking change for webpack 3. 

So I was hoping that we could branch off of the v11 tag and create a minor release under that so we can resolve that vulnerability in webpack - [which I went ahead in did in my fork of yargs](https://github.com/corymcdonald/yargs/tree/os-local-upgrade) but I can't submit a PR because there's not a v11 branch. 

I suppose the next steps are
- [ ] Create a 11.x branch in yargs repo
- [ ] Create a PR for the `os-locale` version bump to `^3.0.1`
- [ ] Merge the PR 
- [ ] Cut a 11.2.0 release

**Comment by bcoe** [comment]
@corymcdonald well I have no objection to this, the problem is that os-locale `^3.0.0` drops support for Node 4:

https://github.com/sindresorhus/os-locale/commit/3edb63cd5e9269f46b45cc47444e990c2b81aaf2

which is part of why yargs was bumped from 11 to 12; any thoughts as to how we could solve this issue while still keeping webpack on Node 4? CC: @sokra.

**Comment by corymcdonald** [comment]
Well it looks like `mem@1` is the real issue here - @sindresorhus do you think we can release a previous version of os-locale to update the `mem` library so we resolve this vulnerability?

**Comment by bcoe** [comment]
@corymcdonald I like this solution, let's work with @sindresorhus to back port a security fix if possible.

**Comment by mbrookes** [comment]
Doesn't seem possible: https://github.com/sindresorhus/os-locale/issues/32#issuecomment-422108321

**Comment by bcoe** [comment]
@mbrookes @corymcdonald it's a pain, but perhaps see how hard it would be for `mem` to back port the fix?

**Comment by simlu** [comment]
This is now a security vulnerability that npm alerts on. Would love to see this resolved!

**Comment by bcoe** [comment]
I've back-ported the fix to a tag called `latest-11`, simply run `npm i yargs@latest-11`.

Let me know if anything else needs to be back ported, thanks for putting this on our radar.
