### ISSUE TITLE
Unexpected token ... When Using require('yargs').argv;

### ISSUE THREAD

**Issue by mitchshaw** [yargs/yargs#1229]
Hello! I'm relatively new to github so please bear with me if I cross into the taboo by mistake.

My issue involves v12.0.2 and v12.0.3-candidate.0 of yargs. I'm only using yargs for 4 lines:

```javascript
const args = require('yargs').argv;
const ip = args.ip;
const user = args.user;
const pass = args.pass;
```

...And the way I'm running it just to cover my bases:

```
nodejs localserver.js --ip={IP} --user={USERNAME} --pass={PASSWORD}
```

An extremely simple use case. However, when running this on my Ubuntu AWS VM I get the following error:

```bash
 /[my folders]/node_modules/yargs/lib/command.js:22
    globalMiddleware.push(...middlewares)
                          ^^^

SyntaxError: Unexpected token ...
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:374:25)
    at Object.Module._extensions..js (module.js:417:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/opt/lcci/node_modules/yargs/lib/argsert.js:2:17)
    at Module._compile (module.js:410:26) 
```

I looked through the forums here and most answers say that `npm i yargs@next` would work for most cases, but when I do that, this is what happens:

```bash
 @0.0.1 /opt/lcci
└─┬ yargs@12.0.3-candidate.0  invalid
  ├── decamelize@1.2.0
  └─┬ yargs-parser@11.0.0
    └── camelcase@5.0.0

npm WARN @0.0.1 No repository field.
npm WARN @0.0.1 No license field. 
```

I tried then looking up the versions here on github and tried to install 12.0.2, which did fine until I got the same error as before.

I'm a bit lost as to where to look otherwise so I came here. Any ideas?

**Comment by mitchshaw** [comment]
Quick Update:

On a hunch from reading more posts I downgraded from 12.0.2/12.0.3-candidate.0 to 12.0.0 and that resolved my issue for the time being. I'm still curious as to why this is a problem on the more recent versions.

I'll leave this open for the sake of investigation but my current problem is solved.

**Comment by bcoe** [comment]
@mitchshaw there have been several major releases since you were bumping into this issue (I'm guessing the problem has probably been addressed).

Let me know if you're continuing to bump into issues.
