### ISSUE TITLE
chained middleware argv references are not updated

### ISSUE THREAD

**Issue by perissology** [yargs/yargs#1232]
When multiple middleware are ran, it appears that the `argv` param is not updated until after all middleware are completed. If would be useful to be able to chain middleware & access the updated `argv`

ex:

```
function middleware1(argv) {
    return { prop1: true }
}

function middleware2(argv) {
    // do something w/ argv.prop1
}

require('yargs')
  .command('test')
  .middleware([middleware1, middleware2])
  .argv
```

**Comment by ajgamble-milner** [comment]
Each middleware function is passed a reference to `argv`, so you can mutate the object directly:

```javascript
function middleware1(argv) {
    argv.prop1 = true;
}

function middleware2(argv) {
    console.log(argv.prop1)
    // => true
}

require('yargs')
  .command('test')
  .middleware([middleware1, middleware2])
  .argv
```

**Comment by perissology** [comment]
yes, that's what I ended up doing, but it seems like a bit of a workaround

**Comment by aorinevo** [comment]
Hi @perissology,

I wanted to share another option in the case that middleware1:
  - is not just updating argv, and
  - middleware2 needs to do something with the return value of middleware1

In this case, combine the two middleware functions into one (see example):

```
function middleware1(argv) {
   argv.prop1 = true;
    return { someData: 'only middleware2 needs this };
}

function middleware2(argv, someData) {
    console.log(someData);
}

function middleware3(argv){
    const retVal = middleware1(argv);
    argv.prop1 = true;
    middleware2(argv, someData);
}

require('yargs')
  .command('test')
  .middleware([middleware3])
  .argv
```

**Comment by aorinevo** [comment]
One more note:
By definition, yargs middleware functions accept only one parameter, a reference to arv, and return undefined.  So, in my example, it's incorrect to call middleware2 a middleware function.
