### ISSUE TITLE
.strict() not validating (global) options properly

### ISSUE THREAD

**Issue by billybarnum** [yargs/yargs#1236]
I have an option called logging-level, with no alias, that isn't getting validated properly.

        .option('logging-level', {
            description: 'Logging severity level.',
            global: true,
            type: 'string',
            choices: ['error', 'warn', 'info', 'verbose', 'debug', 'silly'],
            default: 'info'
        })

I read [.strict() does not work as expected](https://github.com/yargs/yargs/issues/518), and added .strict() to all command builders.

However, `--log-level` or `--logging-xxx` still pass validation. Yet if I pass a completely bogus option, say `--abc` or `--xxx`, validation works as expected. 

I'm confused. Am I doing anything wrong?

**UPDATE:**

It seems the problem has something to do with the single dash in the middle of the option name. If I enter any option with a single dash it will pass validation, even if strict is turned on globally and within all command builders: `--foo-bar` as well as `--xxx-yyy` will erroneously pass validation, but `--foobar` and `--xxxyyy` are properly flagged as problems.

I don't see anything in the docs about this, and option names with single dashes are everywhere. Seems like a bug to me.

**Comment by juergba** [comment]
If you set `camel-case-expansion` in `yargs-parser` to `false`, no alias is created for your dashed option and your flag will be recognized as problem.

see https://github.com/yargs/yargs/issues/1325#issuecomment-477487511

**Comment by bcoe** [comment]
this should have (_finally_) been addressed in `yargs@14.2.0`, thanks to the hard fork of @andrewdotn.
