### ISSUE TITLE
is there a default command?

### ISSUE THREAD

**Issue by zzzgit** [yargs/yargs#1240]
``` shellscript
mytool get --object sth
// that is  implemented by defining a command named "get"
mytool --set --object sth
// that is  implemented by defining a command named "set"
mytool 
// with no command specified, it will print the operation log, how to implement this?

```

Can I define a default command, which will be executed if I supply nothing after the script-name.

**Comment by acro5piano** [comment]
yargs.command('*', // ...) does.

https://github.com/yargs/yargs/issues/855

**Comment by bcoe** [comment]
Linking docs here:

https://github.com/yargs/yargs/blob/master/docs/advanced.md#default-commands

Hopefully you got things working eventually @zzzgit, sorry we missed answering your question.
