### ISSUE TITLE
Micmic `.options()` paradigm for `.command()`

### ISSUE THREAD

**Issue by mster** [yargs/yargs#1245]
Hello 👋 

I haven't seen an issue on this, but apologize if I missed it.

I was wondering if it would be possible to mimic the `yargs.options(OPTIONS)` paradigm for the `yargs.command()` feature. 

I found the options feature to be extremely helpful for both writing and reading code using `yargs`. I personally implemented a bit of a work-around to achieve my goal, storing command parameters in a series of respective vectors, then passing them to the command function via a spread operator

Like this:
```
// otherFile.js
const commands = {
    test: [
        'test',
        'This is a test command using yargs!',
        (yargs) => somefunction
    ],
    ...
}

export = commands

// main.js
var yargs = require('yargs')
const commands = require('./commands')

yargs
.command(...commands.test)
.command(...commands.foo)
...
```

Thanks all! 🙌

**Comment by bcoe** [comment]
@mster I think describing `positional` commands might be what you're looking for, I very much had this use-case in mind:

https://github.com/yargs/yargs/blob/master/docs/api.md#positionalkey-opt

**Comment by mster** [comment]
> @mster I think describing `positional` commands might be what you're looking for, I very much had this use-case in mind:
> 
> https://github.com/yargs/yargs/blob/master/docs/api.md#positionalkey-opt

Should work for my use-case! Thank you :)
