### ISSUE TITLE
middleware may need to run before required check

### ISSUE THREAD

**Issue by trevorlinton** [yargs/yargs#1254]
One use case that's valuable to use a middleware is to lookup a value that's optional or required on an argument if there's a separate mechanism for finding it. (Think about the heroku cli and how they default the app argument by looking at the .git repo you're currently in).  This could be implemented with middleware, however the middleware runs after required checks are done.  In this circumstance if a required field could be derived using the middleware it never gets a chance to resolve those values. 

A suggested fix would be to complete parsing then execute the middleware then do a required/sanity check on the arguments passed in. 

Simple code:

```
let yargs = require('yargs')
yargs.command('foobar', 'foo then bar', {"an-option":{"demand":true, "string":true, (args) => console.log('done', args)}}
yargs.middleware([(args) => { 
  args['an-option'] = 'this option'
  console.log('middleware ran',args) 
});
yargs.argv
```

If you ran `node example.js foobar` it will simply return with the option `an-option` is required. Where what I'm proposing it would execute the command with `an-option` set to `this option`.

Thoughts? Willing to submit a pull request if one would be accepted.

**Comment by aorinevo** [comment]
Hi @trevorlinton, 

I can see the value of having middleware called before required/sanity checks and would be happy to review a PR for this.  One thought is maybe to differentiate the middleware functions called before required/sanity checks from the ones that run after the checks are complete.  Maybe call them preChecksMiddleware.

**Comment by trevorlinton** [comment]
I created a PR here: https://github.com/yargs/yargs/pull/1255/files I just named it `preChecksMiddleware`, at the moment only globally available, as I'm not sure the utility of having it on a per-command basis (and overloading `command` didn't seem ideal).

**Comment by trevorlinton** [comment]
I should mention, the `preChecksMiddleware` gets passed two objects, the first is the parsed argv as the middleware, but the second is an object containing the array of commands as the property `commands` that could be executed, and a map of the available options and their aliases as `availableOptions`.  This is important for most of the purposes the `preChecksMiddleware` would be performing.

**Comment by boneskull** [comment]
this can be closed?
