### ISSUE TITLE
pre-command hooks

### ISSUE THREAD

**Issue by brewster1134** [yargs/yargs#1258]
I want to run some code before each command callback, and need the name of the command for it

each of my commands creates its own cache in a `.tmp` folder, and want to delete each commands cache each time it runs.  for example the command foo, creates a cache in ./.tmp/foo. i want to delete only that cache before each time it runs. i can delete it from each command callback, but curious if there is a more programmatic way to do it.

**Comment by aorinevo** [comment]
Hi @bewster1134, sounds like yargs global middleware of command middleware might work.  Have you tried that?

**Comment by brewster1134** [comment]
that is exactly what i needed! ... never thought to search for middleware. ty!
