### ISSUE TITLE
Specify yargs-parser options via `yargs` JS API

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#1259]
Use-case: I want to write a command-line tool that uses yargs to parse command-line options.  I have a `--foo` boolean flag.  I do *not* want yargs to allow `--no-foo`.  So I want to pass `{'boolean-negation': false}` to yargs-parser.  (although you can certainly think of situations where other people might want to write CLI tools and pass other flags to yargs-parser; I'm just using this as an example)

It is important that users of my CLI tool do not need to be aware of nor think about yargs.  I will configure yargs to behave predictably and I'll write documentation for my tool that matches the configured behavior.  It's important that my CLI tool behaves exactly as I intend, without being accidentally influenced by external factors such as a consumer's package.json or other yargs-based CLI tools.

I'm imagining that the API looks something like this:

```
yargs.setParserConfiguration({'boolean-negation': false}).option(//... and so on
```

EDIT per [Slack conversation](https://node-tooling.slack.com/archives/C6GD3ELSJ/p1545076446048800), the preferred name for this method is either `parserConfiguration` or `yargsConfiguration`

**Comment by cspotcode** [comment]
Might be related to #1248

**Comment by boneskull** [comment]
While I think such a thing would be useful, and considering the paucity of information in #1248, yargs is careful to load its config from the `package.json` of your CLI app.  It won't look elsewhere unless `require.package.main` *isn't* your app.

Untested, but that's what I can deduce from reading the code.

**Comment by boneskull** [comment]
this is important to mention:

`boolean-negation: true` means `--no-foo` will *expand* that to `foo: false`.  It *does not mean* `--no-foo` is not allowed.  You need to enable "strict" mode via `yargs.strict()` if you want this behavior.

**Comment by bcoe** [comment]
@cspotcode please take this for a spin:

`npm i yargs@next`

There's now a method `parserConfiguration`.

**Comment by bcoe** [comment]
@jean-emmanuel mind trying `npm i yargs@next` and letting me know if I've shipped your work appropriately?

**Comment by shadowspawn** [comment]
#1262 has shipped, so closing this.
