### ISSUE TITLE
Please do not load script from http:// on /docs 

### ISSUE THREAD

**Issue by buckle2000** [yargs/yargs#1264]
[This page](https://yargs.js.org/docs/) cannot load jQuery because mixed content is blocked in my browser.
`http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js` is prevented from loading.

Please change all script tags from `<script src="http://url>"` to `<script src="//url">`.

**Comment by Haroenv** [comment]
I'd like to help out with this issue, but I can't seem to find where the source of the documentation site is, I only see .md files here.

EDIT: https://github.com/yargs/yargs.github.io

**Comment by buckle2000** [comment]
Confirmed, closing.
