### ISSUE TITLE
I can't install yargs

### ISSUE THREAD

**Issue by chnejohnson** [yargs/yargs#1274]
I can't install yargs from npm, why?
it presents
npm ERR! code E404
npm ERR! 404 Not Found: yargs@latest

**Comment by dhill2522** [comment]
Works fine for me. Are you sure that your network connection is good? It looks like you may not have internet. 

It could also be due to using the wrong npm registry. Try setting the npm registry and then installing
```bash
npm set registry https://registry.npmjs.org/ 
npm install yargs
```

**Comment by chnejohnson** [comment]
oh, you're right. I used wrong npm registry. Thanks!
