### ISSUE TITLE
Any string is matched when alias used

### ISSUE THREAD

**Issue by subnetsRU** [yargs/yargs#1276]
Config without using alias:
```
args = require('yargs')
    .usage(__dirname + '/$0 [args]')
    .options({
        'socket': {
            alias: 's',
            describe: 'unix socket path',
            demandOption: true,
            type: 'string',
        },
    })
    .fail(function (msg, err, yargs) {
        if (err) throw err // preserve stack
        console.error(msg + '\n');
        console.error('Usage:', yargs.help());
        process.exit(1);
    })
    .help('help')
    .argv;
```

Now run app:
```
# node test.js --socketqwerty=aaa
```
As expected we see error: Missing required argument: socket

Now add alias to the config:
```
args = require('yargs')
    .usage(__dirname + '/$0 [args]')
    .options({
        'socket': {
            alias: 's',
            describe: 'unix socket path',
            demandOption: true,
            type: 'string',
        },
    })
    .fail(function (msg, err, yargs) {
        if (err) throw err // preserve stack
        console.error(msg + '\n');
        console.error('Usage:', yargs.help());
        process.exit(1);
    })
    .help('help')
    .argv;
```
Now run app and just add 's' anywhere in string:
```
# node test.js -sqwerty=aaa
```
OR
```
# node test.js -qwserty=aaa
```
OR
```
# node test.js -qwertys=aaa
```
and son on...
No error about missing option (demandOption) socket is given and app start to run.

**Comment by juergba** [comment]
I tried to reproduce your issue, but with v13.2.2 eveything is working fine, with/without `alias: 's'`
```
D:\yargs>node usage.js --socketqwerty=aaa
Missing required argument: socket

Usage: D:\yargs/usage.js [args]

Options:
  --version  Show version number                                       [boolean]
  --socket   unix socket path                                [string] [required]
  --help     Show help                                                 [boolean]
```

**Comment by subnetsRU** [comment]
I used yargs 12.0.5, that was installed via npm. I will try v13.2.2 from git.

**Comment by subnetsRU** [comment]
I`ve update yargs to v13.2.2. Problem is still there.
When you try to reproduce you use "--" (two dashed) in the arg. And in my test I use only "-" (one dash).
So run "node usage.js -socketqwerty=aaa" and no error given.

**Comment by juergba** [comment]
There is a configuration option `short-option-groups` in `yargs-parser`: [doc](https://github.com/yargs/yargs-parser#short-option-groups)
It's default value is `true`.
```js
const parse = require('yargs-parser');

args = parse('-sqwerty=aaa', {
    string: ['socket'],
    alias: { 'socket': ['s'] },
    configuration: { 'short-option-groups': true }
});
console.log(args);
```
So your `-sqwerty=aaa` is handled as a group of boolean flags:
```
{ _: [],
  s: '',
  socket: '',
  q: true,
  w: true,
  e: true,
  r: true,
  t: true,
  y: 'aaa' }
```
As you can see `s` and `socket` are set with an empty string and thus no error is printed.

To avoid this, use:
- two dashes `--`
- or set `short-option-groups: false`
=> `.parserConfiguration({'short-option-groups': false})`

PS: could you please edit and format your issue description, it's very difficult to read?

**Comment by subnetsRU** [comment]
Thanks for the help, its working correct with short-option-groups false.

P.S. Done.
