### ISSUE TITLE
positional arguments drop '+' in front of phone #

### ISSUE THREAD

**Issue by chee** [yargs/yargs#1279]
`yargs-parser` seems to coerce things to numbers if it can, even if `number: false`. 

So I have a program that takes phone numbers as arguments, and sometimes phone numbers have a `+` at the start.

If i use `yargs`, and set `type: "string"` on that option I get `"447473474347"` instead of `"+447473474347"`.

`require("yargs-parser")("+447473474347")`  returns `{ _: [ 447473465256 ] }`

**Comment by bcoe** [comment]
@chee I believe this will be a bug with yargs and not yargs-parser, related to some of the pre-parsing that takes place on positional arguments before they're passed into yargs-parser.

**Comment by chee** [comment]
this is a duplicate of #1099
