### ISSUE TITLE
Global arguments, required for all commands

### ISSUE THREAD

**Issue by mikeerickson** [yargs/yargs#1285]
Hello Gang

I am trying to figure out a way to define a `global` argument which should be required for ALL commands, thus I don't have to define for each command.

Is this possible?

**Comment by mikeerickson** [comment]
Well, I managed to find it after scouring the source code.   Use the `global` option 

```js
  .option('filename', {
    alias: ['f'],
    global: true,
    describe: 'Desired filename if not default workspace setting.json'
  })
```

**Comment by bcoe** [comment]
👍 exactly what that's there for.
