### ISSUE TITLE
Please publish 13.0.0 to npm

### ISSUE THREAD

**Issue by whyboris** [yargs/yargs#1288]
Looks like `13.0.0` has been released: https://github.com/yargs/yargs/blob/master/CHANGELOG.md#1300-2019-02-02

But `npm` has version `12.0.5` as latest: https://www.npmjs.com/package/yargs

**Comment by bcoe** [comment]
@whyboris `13.1.0` is now released, we will sometimes have a version published to `next` on npm, `npm i yargs@next`, while working on a release.
