### ISSUE TITLE
Suggestion: Add `scriptName` usage in docs @ yargs.js.org # Getting Started

### ISSUE THREAD

**Issue by sarpik** [yargs/yargs#1298]
Hello,

I'm a new user and I the first thing I got confused about was following the example tutorial @ https://yargs.js.org at "Getting Started" section

Specifically when running `example.js --help` and getting `-`expected/`+`actual output
```diff
  example.js <cmd> [args]

  Commands:
-	hello [name]  welcome ter yargs!
+	example.js hello [name]  welcome ter yargs!

  Options:
    --help  Show help     
```

I spent about 5-10 minutes googling and found out that all I needed was to pass a `.scriptName("yourScriptName")` to the `yargs` builder. Now, 5-10 minutes aren't much, but I think that just letting everyone know about this small but awesome utility `.scriptName` from the very start would be really useful!

That's my $0.02, thanks for the awesome package - will indeed be using it in the future!

**Comment by bcoe** [comment]
@sarpik would happily take a pull request with this change to https://github.com/yargs/yargs.github.io

thanks for the suggestion.

**Comment by sarpik** [comment]
Thanks for the encouragement @bcoe - I just made my first pull request!

https://github.com/yargs/yargs.github.io/pull/44

I'd recommend you to read the commit messages - there might be some minor glitches whom I mentioned.
