### ISSUE TITLE
over-eager deprecation message

### ISSUE THREAD

**Issue by boneskull** [yargs/yargs#1304]
Mocha specifies a config in its `package.json` using yargs@12.  Any consumer using yargs@13 will get a warning about *Mocha's* config in *its* `package.json`.  This seems like a bug.

**Comment by boneskull** [comment]
Ref: mochajs/mocha#3742

**Comment by plroebuck** [comment]
[Already asked](https://github.com/yargs/yargs/pull/1262#issuecomment-465218465).
See also #1302 which determines whether we have to wait for backport or not.

**Comment by plroebuck** [comment]
Believe this can be closed now...

**Comment by boneskull** [comment]
closed via e6542538

**Comment by boneskull** [comment]
that's weird
