### ISSUE TITLE
Add doc for `--no-` boolean prefix

### ISSUE THREAD

**Issue by AndrewFinlay** [yargs/yargs#1307]
I bumped into this the other day and it had me scratching my head.  I found the answer in some older issues but it should really be on the API doc page.

**Comment by AndrewFinlay** [comment]
Just found mention of it on the 'tricks' page, maybe not such an issue after all.

**Comment by willstott101** [comment]
Here is a link dump of some various bits of scattered docs about this:

https://github.com/yargs/yargs-parser#boolean-negation
#122
https://github.com/yargs/yargs/blob/master/docs/advanced.md#customizing-yargs-parser
https://yargs.js.org/docs/#api-configobject

**Comment by AndrewFinlay** [comment]
@willstott101 this change has been merged into the docs, if you're happy with this solution then I'll close the issue.  Thanks.

**Comment by willstott101** [comment]
LGTM I'm guessing that comes up here? http://yargs.js.org/docs/#api-booleankey

Can Ctrl-F for `--no-` and it'll be obvious straight away.

Thanks!
