### ISSUE TITLE
yargs is just not working for me!

### ISSUE THREAD

**Issue by pyrrhicman** [yargs/yargs#1310]
Hi, I'm new in nodejs and it's just not working for me.
I don't even know if it's the right place for this question or not.

I use yargs@13.2.1 

> const argv = require('yargs');
> 
> console.log(argv.argv)
>
> argv.command({
>     command: 'add',
>     describe: 'Add Something',
>     handler: function(argv){
>         console.log('Shit');
>     }
> });

so when I start my program with 

> node app.js add

it just gives me the 

> { _: [ 'add' ], '$0': 'app.js' }

which is from console.log(argv.argv)

but my argv.command does nothing.
what I am doing wrong

**Comment by subnetsRU** [comment]
Read docs http://yargs.js.org/docs/#api-commandcmd-desc-builder-handler and see examples.
There is an answer on what you doing wrong.

**Comment by Zephilim** [comment]
Hi subnetsRU, I am having similar issues and have looked at the examples you show. The handler function fr the command is only called, if you call argv at the end. But what do you do with argv?
The following code as taken from the the examples does not work, because I havent called argv at the end.
```
  yargs
    .command(
      'get',
      'make a get HTTP request',
      function (yargs) {
        return yargs.option('u', {
          alias: 'url',
          describe: 'the URL to make an HTTP request to'
        });
      },
      function (argv) { // THIS IS NOT BEING INVOKED!
        console.log('>>> ' + argv.url);
      }
    );
```
However if I change the last line to:

> ).argv;

...then the function call back does work. But what do I do with the returned argv. The reason why this is a problem is that linting processes don't allow you to declare a variable and not use it. So why does the function call back only occur if you refer to a variable that is seemingly not used? The example shown in the documentation, shows too little code.

**Comment by saurabhkanswal** [comment]
I am also getting the same issue.

> Hi, I'm new in nodejs and it's just not working for me.
> I don't even know if it's the right place for this question or not.
> 
> I use yargs@13.2.1
> 
> > const argv = require('yargs');
> > console.log(argv.argv)
> > argv.command({
> > command: 'add',
> > describe: 'Add Something',
> > handler: function(argv){
> > console.log('Shit');
> > }
> > });
> 
> so when I start my program with
> 
> > node app.js add
> 
> it just gives me the
> 
> > { _: [ 'add' ], '$0': 'app.js' }
> 
> which is from console.log(argv.argv)
> 
> but my argv.command does nothing.
> what I am doing wrong

I am also getting the same issue. did you find any solution?

**Comment by saurabhkanswal** [comment]
> Hi subnetsRU, I am having similar issues and have looked at the examples you show. The handler function for the command is only called, if you call argv at the end. But what do you do with argv?
> The following code as taken from the the examples does not work, because I havent called argv at the end.
> 
> ```
>   yargs
>     .command(
>       'get',
>       'make a get HTTP request',
>       function (yargs) {
>         return yargs.option('u', {
>           alias: 'url',
>           describe: 'the URL to make an HTTP request to'
>         });
>       },
>       function (argv) { // THIS IS NOT BEING INVOKED!
>         console.log('>>> ' + argv.url);
>       }
>     );
> ```
> However if I change the last line to:
> 
> > ).argv;
> 
> ...then the function call back does work. But what do I do with the returned argv. The reason why this is a problem is that linting processes don't allow you to declare a variable and not use it. So why does the function call back only occur if you refer to a variable that is seemingly not used? The example shown in the documentation, shows too little code.

when iam trying this 
```
const yargs = require('yargs')
yargs.version('1.0.0')
//create add command
yargs.command({
    command: 'add',
    describe: 'to add note',
    handler: function() {
        console.log('note has been added')
    } 
})
```
result:
```
node app.js --help
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```
the add command is not added to commands.
but when i try this
```
const yargs = require('yargs')

yargs.version('1.0.0')

//create add command
yargs.command({
    command: 'add',
    describe: 'to add note',
    handler: function() {
        console.log('note has been added')
    } 
})


console.log(yargs.argv)`
```
the  add command got addded to commands 
result: 
```
node app.js --help
app.js [command]

Commands:
  app.js add  to add note

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```
how iam getting the result when i use` console.log(yargs.argv)` ?

**Comment by shivanik6z** [comment]
write console.log(argv.argv) in the end of your code, after declaring the commands.

**Comment by bcoe** [comment]
@pyrrhicman, @Zephilim, does @shivanik6z's advice do the trick for you? You need to eventually call either `.argv` or `.parse()` to run `yargs` once you've configured everything.

**Comment by bcoe** [comment]
(move `console.log(argv.argv)` below the command initialization).

**Comment by Prateek-K** [comment]
@bcoe 's suggestion worked for me. Any idea why console.log would have that effect.

**Comment by mleguen** [comment]
It has nothing to do with console.log, but with what is inside: arg.argv. Yargs won't do anything until its .parse() methode is called (or its .argv getter which calls .parse()).

In @pyrrhicman 's example, the parsing is done when argv.argv is called, so before the command is initialized.

In @Zephilim 's example, there is no parsing at all, as neither yargs.parse() nor yargs.argv are called.

**Comment by pyrrhicman** [comment]
Thank you all, after this issue, I completely gave up on this because I didn't need it that much and tonight I tried latest version of yargs, and it's working perfectly 👍 . thank you all
I'm gonna include my test here which i took from npm page
it's Typescript btw :)
`npm i yargs`
`npm i @types/yargs --save-dev`

> import yargs from 'yargs';
yargs    
.option('port', {
      alias: 'p',
      type: 'number',
      default: 8000,
      description: 'put the fucking port'
    })
.option('host', {
      alias: 'h',
      type: 'string',
      default: '127.0.0.1',
      description: 'put the fucking host'
    })
    .argv;

And after these lines of configuration if you run 
`console.log(yargs.argv.port);`
`console.log(yargs.argv.host);`

And run the application with 
ts-node-dev server.ts --p 1200 -h "0.0.0.0"
you will get these data inside if you don't include them you will get default values.

**Comment by ibm-demand** [comment]
> move `console.log(argv.argv)`

Worked for me as well

**Comment by abhishree1** [comment]
> Hi, I'm new in nodejs and it's just not working for me.
> I don't even know if it's the right place for this question or not.
> 
> I use yargs@13.2.1
> 
> > const argv = require('yargs');
> > console.log(argv.argv)
> > argv.command({
> > command: 'add',
> > describe: 'Add Something',
> > handler: function(argv){
> > console.log('Shit');
> > }
> > });
> 
> so when I start my program with
> 
> > node app.js add
> 
> it just gives me the
> 
> > { _: [ 'add' ], '$0': 'app.js' }
> 
> which is from console.log(argv.argv)
> 
> but my argv.command does nothing.
> what I am doing wrong

try  > argv.parse()

**Comment by paurush11** [comment]
write at the end - console.log(yargs.argv)

**Comment by ashwynh21** [comment]
Please help, I must be doing something wrong or there is an actual issue. I'm using typescript and Webpack as a bundler to build a CLI.

```
yargs(process.argv)
    .command('init [name]', 'Start a new project', (cli) => {
        console.log('working');
        return cli.positional('name', {
            description: 'name of application',
            default: 'app'
        })
    }, (args) => {
        console.log(args);
    })
    .parse();
```

Simply does not work, none of the callback functions provided are called.

**Comment by fendis0709** [comment]
> write at the end - console.log(yargs.argv)

Thanks, @paurush11 It works now.
I wonder why this could happen?
What's the point of using `console.log(yargs.argv)` at the end of the code?

**Comment by sgupta98mnit** [comment]
> > write at the end - console.log(yargs.argv)
> 
> Thanks, @paurush11 It works now.
> I wonder why this could happen?
> What's the point of using `console.log(yargs.argv)` at the end of the code?

@fendis0709 try yargs.parse() at the end instead.

**Comment by fendis0709** [comment]
> @fendis0709 try yargs.parse() at the end instead.

Thanks @sgupta98mnit 
I think we should use "yargs.parse()" after declaring yargs code (or at the end of code), in order to initialize yargs command.
