### ISSUE TITLE
feat: being able to set the text for the "default value" showing in usage

### ISSUE THREAD

**Issue by yxliang01** [yargs/yargs#1311]
Sometimes, the default value of an argument can be very long or not so understandable and therefore unsuitable to be shown directly in the usage message. So, I think it would be great if there is an option to set the default value showing in the usage message, instead of directly showing the actual default value. Such option can be called `defaultText`.

Thanks!

**Comment by subnetsRU** [comment]
And why not just delete 'default' from your options and set default value below arguments checking ?
That`s all. No flags needed.

**Comment by yxliang01** [comment]
@subnetsRU I think putting the values associated to an arg together is better than sparse. I have modified the issue title and description to make this feature request more general that we might want to describe the default value in a more understandable way and this is not achievable by your method except that you put the text in the description field which is not very pretty to me.

**Comment by yxliang01** [comment]
Oops... For some reason, I overlooked the option `defaultDescription` which was implemented quite some time ago. Closing this.
