### ISSUE TITLE
Declaration File Missing

### ISSUE THREAD

**Issue by jstig** [yargs/yargs#1314]
Hello. Perhaps a big newbie question, I'm not sure what I did, but I am receiving the following error about yargs: 'Could not find a declaration file for module 'yargs'.'  Everything was working fine earlier today, now commands set up using yargs don't work.

I've tried installing the module a few times after deleting node_modules, restarting my computer, changing versions of yargs, but to no avail.

I'm at a loss. Thanks for any insight.

I should also say that yargs is the only module affected by this. I've installed other modules and they work

**Comment by aorinevo** [comment]
Is your package installed globally?

**Comment by jstig** [comment]
Am I correct that to check this I would run npm list -g yargs? 

This is what I get back when I do: 

```
/usr/local/lib
└─┬ npm@6.7.0
  └─┬ libnpx@10.2.0
    └── yargs@11.0.0 
```

I also see yargs here: /usr/local/lib/node_modules/npm/node_modules/yargs

**Comment by jstig** [comment]
I just ended up completely uninstalling node and reinstalling. That fixed the issue. I have no idea what I did to break it in the first place. smh
