### ISSUE TITLE
about middleware's config for a specified command

### ISSUE THREAD

**Issue by kawhi66** [yargs/yargs#1326]
I was trying to set a middleware for a specified command, and when I set like this
```javascript
require(yargs).command({
        command: 'test1',
        description: false,
        builder: {},
        handler: argv => {
            console.log(argv)
        },
        middleware: [verifyPkgConfig] // WARNING: it won't work
    }).command('test2', false, {}, argv => {
        console.log(argv)
    }, [verifyPkgConfig]) // it work
    .argv
```

I am not sure it is a bug or not, I think the first config should be supported too.

**Comment by aorinevo** [comment]
Hi @kawhi66,

Middleware is set programmatically via the middleware method available on the yargs object.  

Not sure if it makes sense to add middleware to the object passed into the command method.  For most implementations requiring some sort of middleware, I would expect all middlewares to be added in one central place.

```
const myMiddlewares = require('./middleware'); // returns an array of middleware functions

require(yargs).middleware(myMiddlewares);
```

@bcoe, @trevorlinton:  Interested to know your thoughts on this?

**Comment by kawhi66** [comment]
> Hi @kawhi66,
> 
> Middleware is set programmatically via the middleware method available on the yargs object.
> 
> Not sure if it makes sense to add middleware to the object passed into the command method. For most implementations requiring some sort of middleware, I would expect all middlewares to be added in one central place.
> 
> ```js
> const myMiddlewares = require('./middleware'); // returns an array of middleware functions
> 
> require(yargs).middleware(myMiddlewares);
> ```
> 
> @bcoe, @trevorlinton: Interested to know your thoughts on this?
> 
> By the way, here's how you can add `verifyPkgConfig` middleware with existing api:
> 
> ```js
> const yargs = require(yargs);
> 
> yargs.middleware([verifyPkgConfig])
>    .command({
>         command: 'test1',
>         description: false,
>         builder: {},
>         handler: argv => {
>             console.log(argv)
>         }
>     }).command('test2', false, {}, argv => {
>         console.log(argv);
>     });
> ```
> 
> See [middlewaredocs](http://yargs.js.org/docs/#api-middlewarecallbacks-applybeforevalidation) for more.

hi @aorinevo 

When I add it via `require('yargs').middleware([verifyPkgConfig])`, this middleware becomes global. that's not what I want.

I was trying to add it to some of my commands. I know I can deal with it inside the middleware, but this, I mean the config as object won't work, really confuse me.

**Comment by aorinevo** [comment]
I see @kawhi66. 

Middleware v1 was implemented at the command level a while back.  I see how that can be confusing. 

What are your thoughts about using mixins instead?

**Comment by kawhi66** [comment]
> I see @kawhi66.
> 
> Middleware v1 was implemented at the command level a while back. I see how that can be confusing.
> 
> What are your thoughts about using mixins instead?

yeah, that will do.

**Comment by aorinevo** [comment]
Cool!  I'll go ahead and close this issue but feel free to reopen or ping me directly on our Yargs slack channel: https://node-tooling.slack.com/messages/C6GD3ELSJ

**Comment by kawhi66** [comment]
> Cool! I'll go ahead and close this issue but feel free to reopen or ping me directly on our Yargs slack channel: https://node-tooling.slack.com/messages/C6GD3ELSJ

okay
