### ISSUE TITLE
how to hide completion command from --help?

### ISSUE THREAD

**Issue by atian25** [yargs/yargs#1328]
```bash
➜  snippet --help
snippet [command]

Commands:
  snippet completion  generate bash completion script
```

any way to hide it?

**Comment by x3rAx** [comment]
You could work around that by using an environment variable (or something similar like a config file):

    if (process.env.YARGS_COMPLETION == 'true') {
        yargs.completion('completion')
    }
    const args = yargs
        .command(
            // ...
        )
        .parse(process.argv.slice(2))

Now you can generate the completion snippet using

    YARGS_COMPLETION=true your-program completion

without the `YARGS_COMPLETION` variable, the `completion` command does not show up but completion will still work.

You could also check if the first argument is `completion`:

    if (process.argv[2] === 'completion') {
        yargs.completion('completion')
    }
    const args = yargs
        .command(
            // ...
        )
        .parse(process.argv.slice(2))

**Comment by bcoe** [comment]
@atian25 what happens if you do:

```js
yargs.completion('completion').describe('completion', false)
```

**Comment by atian25** [comment]
@bcoe `YError: Invalid second argument. Expected string but received boolean.`

**Comment by jasonk** [comment]
FYI, after some experimenting I found that this will work:

```
yargs.completion( 'completion', false )
```
