### ISSUE TITLE
Run middlewares even if no commands specified

### ISSUE THREAD

**Issue by nikolay-borzov** [yargs/yargs#1329]
Use case: Parse variable number of file paths and remove extra `'`

> app file1.js 'file2.js' file3.js

This doesn't work
```
yargs
 .middleware(argv => {
   console.log('1', argv._);
   argv._ = argv._.map(path => path.replace(/'/g, ''));
   console.log('2', argv._);
  })
  .parse();
```
> No output

This works
```
yargs
  .middleware(argv => {
    console.log('3', argv._);
    argv._ = argv._.map(path => path.replace(/'/g, ''));
    console.log('4', argv._);
  })
  .command('$0', 'the default command')
  .parse()
```
> 3 [ 'file1.js', '\'file2.js\'', 'file3.js' ]
> 4 [ 'file1.js', 'file2.js', 'file3.js' ]

**Comment by aorinevo** [comment]
Hi @nicolay-borzov,

Can you log argv._  immediately before and after reassignment for both examples?

**Comment by nikolay-borzov** [comment]
Updated issue. The problem here is that middleware isn't called in first case

**Comment by aorinevo** [comment]
Strange, I’m assuming it’s because there are no commands added in the first example and hence no middleware would run.

@bcoe: Interested to know your thoughts on this.  Should middleware run even if no commands are added?  I’m leaning towards yes.

**Comment by bcoe** [comment]
@aorinevo I'd argue it should work if you specify a default command with:

```
.command('$0')
```

https://github.com/yargs/yargs/blob/master/docs/advanced.md#default-commands

But that it's beyond the scope of middle-ware to run if no commands are specified; I'm curious if it does work with a default command? would be good to add a test.

**Comment by bcoe** [comment]
Closing in favor of the newer https://github.com/yargs/yargs/issues/1351
