### ISSUE TITLE
Can yargs force options per command?

### ISSUE THREAD

**Issue by rcintron1** [yargs/yargs#1339]
Hi there,
If I have an command `list` that will just list remote data, I require no options.
But if I have a command that is called compare, where I require an option `-f` for the file I want to compare with remote data, is there a way to demand the option from yargs? I am currently handling it out of yargs but it would be awesome to have mandatory options depending on the command (or vice-versa).
Thank you!

**Comment by bcoe** [comment]
hey @rcintron1 👋 yes, good news, you can totally do this:

https://github.com/yargs/yargs/blob/master/docs/advanced.md#commands

If you use commands, the second argument you provide is a builder function, which can be used to add command specific options.

```js
require('yargs')
  .command('list', 'my list command', (yargs) => {
    yargs.option('f', {
      describe: 'this option will only exist for the list command'
    })
  }, (argv) => {
   // called with parsed argv.
  });
```
