### ISSUE TITLE
Support for a "finally" handler to be run after the command handler

### ISSUE THREAD

**Issue by nija-at** [yargs/yargs#1344]
When a command is specified through the `command` API or `commandDir` API, support a finally handler that runs at the end of the command handler both on success and failure.

Example - If there's an informational banner (new update to the tool being used) that needs to be displayed at the end of some or every command.

**Comment by bcoe** [comment]
@nija-at there is now an [onFinishCommand](https://github.com/yargs/yargs/pull/1769), which I believe should have the behavior you were looking for.

Let me know if there are any issues.

**Comment by nija-at** [comment]
Indeed. Thanks!

**Comment by ivan-kleshnin** [comment]
@bcoe thanks for the doc update! Shouldn't this `onFinishCommand` functionality by available to middlewares?
It seems logical to, say, open DB connection in some middleware and close it in the very same module (maybe in another handler or something).

**Comment by ryancat** [comment]
> @nija-at there is now an [onFinishCommand](https://github.com/yargs/yargs/pull/1769), which I believe should have the behavior you were looking for.
> 
> Let me know if there are any issues.

Nope this will work for the case when the async handler eventually passing. When anything goes wrong (error got thrown, promise got rejected), you would need to:

1. make sure you return the promise in async handler
2. Add `fail` API on command to catch the failures
