### ISSUE TITLE
Passing `process.argv` to yargs invalidates commands

### ISSUE THREAD

**Issue by sqren** [yargs/yargs#1345]
I'm running into an issue with yargs where commands are no longer triggered when manually passing `process.arv` to `yargs`. It can be demonstrated with the following script

**app.js**
```js
require('yargs')(process.argv)
  .command('start', 'Start up an app', () => {
    console.log('running start');
  })
  .command('setting', 'Change settings', () => {
    console.log('running setting');
  }).argv;
```

When running the `start` command I get the following:
```
node app.js start 
Output: <blank>
```

However, if I do not manually pass in `process.argv` it works as expected:
```diff
- require('yargs')(process.argv)
+ require('yargs')
```

```
node app.js start 
Output: "running start"
```

Am I doing something wrong or is this a bug?

**Comment by sqren** [comment]
@bcoe Seeing you are fairly active in here I hope you don't mind me mentioning you. Do you agree this looks like a bug, and should have the "bug" label applied?

**Comment by bcoe** [comment]
@sqren I think you would need to perhaps run:

```
require('yargs/yargs')(process.argv.slice(2))
```

To remove the `node` bin and the script being run from `argv`; this is done automatically when you use `.argv`. Perhaps, similarly to the section added [here](https://github.com/yargs/yargs/pull/1371) on yargs' quote handling, we could add a section to the docs that points out this edge-case?

what do you think @vidavidorra? also what do we think is the right section of the docs for this type of information (I'm wondering if we should add a new page).

**Comment by sqren** [comment]
@bcoe Ahh, thanks a lot. Much appreciated!

**Comment by vidavidorra** [comment]
> we could add a section to the docs that points out this edge-case?

I think so too. I do think this will fit better in the advanced usages or something although I'm not sure what this should be named (_manually passing arguments_?).
