### ISSUE TITLE
middleware doesn't work as expected when used in isolation

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#1351]
middleware doesn't work as I'd expect for `yargs.argv`; I would expect the middlware runs, it does not.

**Comment by wesleytodd** [comment]
I just ran into this, and here is my feedback:

- Should run even if no command is matched
- Should run for default command (it does not right now)

Right now I am doing the following:

```javascript
yargs()
  .middleware(common)
  .command('$0', 'default', (argv) => {
     common(argv)
    // ...
  })

function common (argv) {
  // common mw
}
```

This works, but it took me a bit to figure out why the middleware was not being run.

I looked into submitting a PR, but I dont have time right now to fully learn this codebase :(.  If I am pointed in the right direction I might be able to work it out, but at first read I was unsure where to make the change.

**Comment by bcoe** [comment]
@wesleytodd would very much appreciate help, I can at least point you at the right files when I have some cycles.

**Comment by mleguen** [comment]
@wesleytodd I tried to reproduce this issue with your code and master branch:
- your middleware is called as expected with default command (and it is called twice with your workaround)
- middleware is not run when no command is matched... but [the doc for `middleware()`](https://github.com/yargs/yargs/blob/master/docs/api.md#middlewarecallbacks-applybeforevalidation) states that the middlewares are called for commands only

So I do not think there is something to correct here.

**Comment by bcoe** [comment]
When a default command is used, middleware works as expected on the latest release (Refs: https://github.com/yargs/yargs/pull/1813).

I would like to make it so middleware is applied even if you don't specify a default command, perhaps we could refactor the codebase to always have a default command registered.

**Comment by bcoe** [comment]
Refs: #1823
