### ISSUE TITLE
Optional positional arguments (in a non-command case)

### ISSUE THREAD

**Issue by allenluce** [yargs/yargs#1355]
```
const argv = yargs
      .usage('$0 [-l] [outlet]', 'Power cycle an outlet')
      .option('l', {
        alias: 'list',
        boolean: true,
        default: false,
        describe: 'List available outlets'
      }).help('h').argv

console.log(argv)
```
I want to be able to define default behavior (which is an interactive menu) when no positional arguments are given. For the above, I'd expect either `argv.outlet` to be set or `argv._` to contain my argument when doing this:

```
script.js 1
```
Instead, my output is:

```
{ _: [],
  l: false,
  list: false,
  '$0': '/Users/allen/bin/outlet',
  '-l': false }
```
What am I doing wrong here? This is with 13.2.4 on MacOS with node v.11.10.1.

**Comment by bcoe** [comment]
@allenluce I don't really understand what you're getting at with the `-l` positional argument, this might be breaking parsing (positional arguments should not have a `-`).

The other thing that's confusing me is why would you want your positional argument and option argument to share a name?

**Comment by allenluce** [comment]
`-l` is not meant to be positional, I'm just showing my actual usage. `-l` isn't related to the positional argument except that it's another argument. Note that this is not a positional argument in the yargs sense, as [that's only applicable to commands.](https://yargs.js.org/docs/#api-positionalkey-opt).

I expected the '1' argument given on the command line to end up in the `argv._` array. Instead, it has completely disappeared.

What I'd really like is for that `1` to end up in `argv.outlet`. However, I could not find a way to get yargs to do this.

**Comment by bcoe** [comment]
@allenluce something like this will do the trick for you:

```js
const yargs = require('yargs')
const argv = yargs
      .usage('$0 [pos1] [pos2]', 'Power cycle an outlet', () => {}, (argv) => {
        if (!argv.pos1) {
          console.info('no positionals')
        } else {
          console.info('got positionals', argv)
        }
      })
      .option('l', {
        alias: 'list',
        boolean: true,
        default: false,
        describe: 'List available outlets'
      }).help('h').argv
```

drop the `-` from the positional name, and make sure the options and positional names don't collide; then you can just check whether or not a positional has been set.

**Comment by allenluce** [comment]
`-l` is an (optional) switch, not a positional. The actual usage should be `scriptname [-l|outlet]`.

**Comment by bcoe** [comment]
@allenluce I think I understand better, this just isn't how the DSL works. 

You can describe positional arguments in the `.usage` method, but not options`. Try this:

```js
const argv = yargs
      .usage('$0 [outlet...]', 'Power cycle an outlet')
      .option('l', {
        alias: 'list',
        boolean: true,
        default: false,
        describe: 'List available outlets'
      }).argv

console.log(argv)
```

options work differently than positionals, in that you could then execute `$0 1 2 --list` or `$0 --list 1 2` (which is part of why they're not described in a positional context).

I think, to get the behavior you're looking for, you could use the above example code, then check whether or not `argv.outlet` is empty, varying behavior depending.

**Comment by allenluce** [comment]
Yeah, I guess that's OK although it's strange that the usage message doesn't include switches.

**Comment by bcoe** [comment]
@allenluce :ok_hand: if you want to take a stab at updating the usage message that yargs generates, we'd be open to PR; as long as it's consistent across top-level usage and commands.
