### ISSUE TITLE
feat: add ESM module support

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#1360]
Now that we're starting to land on what the ESM module system looks like in Node.js, I would like to update yargs to export a module interface.

**Comment by mleguen** [comment]
I see the following options to implement this feature:
1. keep all modules in CJS format (including `index.js`), add an `index.ems` module in EMS format importing `index.js` in CJS, and remove extension from `main` in `package.json` for node to chose the right `index` when importing
1. same thing the other way (all modules in EMS export for an `index.js` in CMS importing `index.ems` in EMS)
1. switch to typescript (see #1359) and compile both to CMS and EMS

**Comment by bcoe** [comment]
@mleguen I've been playing around a bit with Node 12's implementation of `module.createRequire`:

https://nodejs.org/api/modules.html#modules_module_createrequire_filename

I believe we could use this to add a module entry point to yargs that behaves as one would hope (I wonder if @MylesBorins wants to chime in on whether this is a terrible idea ... experimenting with `createRequire` seems to work like a charm).

If we take the above approach, and aim to support modules once they're not behind a flag in Node.js, I think the question just becomes:

* what meta information do we need to put in our `package.json` to communicate the fact that yargs has a module entry point.
* what should yargs export? (I think, for starters, this is a good opportunity to drop the Singleton going forward).

**Comment by mleguen** [comment]
I understand `createRequire` could be used to write an ESM wrapper module (`esm.mjs` for example).

This way, yargs would still be required from CJS modules with `require(yargs)` as usual, and could also be imported in ESM modules with `import xxx from 'yargs/esm'`.

What I do not understand is why we would need a new entrypoint? And how to do it without impacting commonjs modules which use the current `index.js` entrypoint?

**Comment by bcoe** [comment]
@mleguen I would like someone to be able to include the module directly from https://unpkg.com/ in a modern browser ... this might mean that the `module.createRequire` doesn't quite cut it I suppose, but I'm curious if we could figure out an approach that introduces next to no build step, that allows the module to be included in browser.

**Comment by MylesBorins** [comment]
you don't need to use `createRequire` to make a wrapper. You can import cjs, you just can't do named exports.

heres an example

https://github.com/MylesBorins/node-osc/blob/current/esm.mjs

**Comment by bcoe** [comment]
@MylesBorins would an approach as simple as this work in modern browsers? or are we going to need some variety of build step.

**Comment by MylesBorins** [comment]
@bcoe It wouldn't work any less than createRequire... neither are supported by the browser

**Comment by Robbie-Cook** [comment]
To get around this I made a intermediary file so I could import yarg's argv in a `.mjs` file.

In my `yarg.js`:

```node
const argv = require('yargs').argv;

module.exports = argv;
```

Then in my .mjs file:

```node
import Yarg from './yarg.js'
```

**Comment by bcoe** [comment]
@Robbie-Cook what would we have to add to the module to allow you to use yargs directly?

**Comment by Robbie-Cook** [comment]
@bcoe It looks like you probably want `module.exports` to look like `module.exports = { argv, ..., ... }` (note that the name is important for ES6+). If you do this, it seems you can import the named items like so: `const argv = require('yargs').argv` and `import { argv } from 'yargs'`.

Here is an example: https://codesandbox.io/s/yargs-test-0bome

In general, I like @mleguen's answer (https://github.com/yargs/yargs/issues/1360#issuecomment-508103458) the best, except I would only output to CommonJS.

**Comment by Robbie-Cook** [comment]
This would be in `yargs.js` right? Happy to help with this with my limited knowledge.

**Comment by bcoe** [comment]
@Robbie-Cook if you have the time, and this is a feature that you'd like to use, I'd happily take a patch :smile:

**Comment by bcoe** [comment]
we should have full support for ESM now, I've been using it quite a bit.

**Comment by Robbie-Cook** [comment]
Great! Congratulations @bcoe et al. looks super good!

**Comment by jehon** [comment]
For those coming here, here is how I did:

```
import yargs from 'yargs';

fs.promises.readdir(folder)
    .then(list => list.filter(v => v.endsWith('.js')))
    .then((list) => Promise.all(
        list.map(f => import(path.join(folder, f)))
    ))
    .then(cmds => {
        let yparser = yargs(process.argv.slice(2));
        for (const c of cmds) {
            yparser = yparser.command(c.command,
                c.describe,
                c.builder ?? {},
                c.handler ?? '');
        }
        ...
   })

```

Hope it help someone...
