### ISSUE TITLE
Run with multiple commands in sequence

### ISSUE THREAD

**Issue by kuchta** [yargs/yargs#1362]
Hi guys,

I have a problem no other command line parsing library I've explored (probably) supports and since the generality of yargs, maybe you have some solution for it, but I can't really tell as from many options you provide, I'm a bit lost :).

I want to get a list of possibly multiple commands with arguments in a row as defined on the command line, so that I can build from it a "functional pipeline", that will be applied to some array/iterator/stream.

Is this case somehow solvable with yargs?

Many thanks...

**Comment by mleguen** [comment]
@kuchta To help us understand better your needs, could you please give us an example of what you expect yargs to do?

**Comment by kuchta** [comment]
Hi @mleguen,

I have a command with this usage:

```
Usage:
	janrain --file <mapper> <csv-file> [( -p <processor> [ <arg>... ])... ] [ Common options ]
	janrain --filter <janrain-filter> [ <greater-then-id> ] [ --fields <field>... ] [( -p <processor> [ <arg>... ])... ] [ Common options ]
	janrain --inspect-log <log-file> [ <id> ]

Options:
	--version                     Print program version
	--file                        Load records from <csv-file> and log file from <csv-file>.log and iterate over it using <mapper> to map the records to Janrain format
	--filter                      Load records from Janrain matching <janrain-filter> and iterate over it
	--inspect-log                 Load <log-file> and print processing report or concrete record if <id> is provided

Common options:
	--log <log-file>              Load log file from <log-file> or defaults to <csv-file>.log in case of --file operation
	--config <conf-file>          Load configuration from file configs/<conf-file>.json
	--dont-skip-after-error       Don't skip processing after an error has occured
	--print-errors-immediately    Print errors immediately as they occur

Mappers:
	from-ch                       Map record from CH format to Janrain format
	from-dotted                   Map record from Janrain dotted format to Janrain format
	from-uk                       Map record from UK format to Janrain format

Processors:
	check-required-fields         Check if record has all the required fields
	count (1)                     Count records
	create (+)                    Create record in Janrain setting log.result to return value
		Arguments:
			1: [<check-required-fields>] (type: boolean, default: true)
	delete (-)                    Delete record from Janrain setting log.result to return value
	exclude-by-field-value        Exclude records matching <field-name> = <field-value>
		Arguments:
			1: <field-name>
			2: [<field-value>]: Value could be string, /RegExp/ or any valid JSON object { /* object */ } or JSON array [ /* array */ ]
			3: [<is-log-field>] (type: boolean, default: false)
	exclude-erroneous             Exclude erroneous records
	exclude-fields                Exclude fields from records
		Arguments:
			1: <fields>...
	exclude-with-result           Exclude completed (create/update/delete...) records
	include-by-field-value        Include just records matching <field-name> = <field-value>
		Arguments:
			1: <field-name>
			2: [<field-value>]: Value could be string, /RegExp/ or any valid JSON object { /* object */ } or JSON array [ /* array */ ]
			3: [<is-log-field>] (type: boolean, default: false)
	include-erroneous             Include erroneous records
	include-fields                Include just these fields in records
		Arguments:
			1: <fields>...
	include-with-result           Include completed (create/update/delete...) records
	print                         Print record
		Arguments:
			1: [<record-decorator>]
			2: [<print-operational-fields>] (type: boolean, default: false)
	save (↓)                      Save record to file
		Arguments:
			1: <csv-file>
			2: [<save-log>] (type: boolean, default: false)
	set-field-value               Set field <field-name> value to <field-value>
		Arguments:
			1: <field-name>
			2: [<field-value>]: Value could be string or any valid JSON object { /* object */ } or JSON array [ /* array */ ]
			3: [<is-log-field>] (type: boolean, default: false)
	update (↑)                    Update record in Janrain setting log.result to return value
```

Processors (and special processors called mappers) that are used on the command line with -p option (which is repeatable) are used to build a functional pipeline of commands (unary functions) that will be applied to every item in the set created by --file or --filter option.

I've already implemented this by searching for processors in the file tree and parsing their arguments descriptions. This design proved to be so flexible, that I'm very likely to make use of it in the future. If yargs has some solution for this pattern, I would love to hear about it.

Many thanks

**Comment by mleguen** [comment]
@kuchta I do not think it is possible to do this with yargs at the moment.

Could you please provide an example of how you would like to specify this with yargs, ideally staying as consistent as possible with the rest of the yargs API?

**Comment by kuchta** [comment]
Yargs has multiple ways of doing the same thing and I'm really not the person with the right knowledge to do so, but what I want from yargs is this: "Be able to use repeating option like "-p" in my example and build from that array of arrays of strings passed to that option. Simplest implementation would be to parse the arguments until next option is introduced or the end of line is encountered, so that yargs won't has to know the arguments length (as they can actually be variable)

**Comment by noamshvacher** [comment]
Hi, I would like to have this feature as well :)
