### ISSUE TITLE
Is `v13.3.0` really bleeding edge? I.e. ok to use?

### ISSUE THREAD

**Issue by jstoiko** [yargs/yargs#1368]
Checking because it is tagged as `next` (as opposed to `latest`).

**Comment by bcoe** [comment]
@jstoiko no, yargs is quite mature at this point. Even major version changes are usually fairly small changes to the API surface.

**Comment by dlong500** [comment]
@bcoe it looks like npm is still pointing to v13.2.4 as latest even though v13.3.0 is tagged as latest release on Github.
