### ISSUE TITLE
How to set an option as boolean and string type.

### ISSUE THREAD

**Issue by vivaxy** [yargs/yargs#1370]
How can I manage to do so?
`bin` => `{ opt: false }`
`bin --opt` => `{ opt: true }`
`bin --opt value` => `{ opt: 'value' }`

**Comment by vivaxy** [comment]
Currently, if I set `{ opt: { type: 'string' } }`
`bin` => `{ opt: undefined }`
`bin --opt` => `{ opt: '' }`
`bin --opt value` => `{ opt: 'value' }`
That might help.

**Comment by themightychris** [comment]
This seems to have stopped working as of 14.2.0, maybe earlier. I now get `Not enough non-option arguments: got 0, need at least 1`

**Comment by bcoe** [comment]
@themightychris could you please open a new issue with a clear description of the issues you're seeing, and some example code? from that error, it sounds like your issue is with positional arguments, not with `string`/`boolean` types.

**Comment by themightychris** [comment]
@bcoe thanks, I suspect maybe it never worked like I thought. On further testing it seems the empty string arg has to be last, else it eat whatever is next as its value. That makes sense so I guess there's no issue, except maybe if I could require `=` for string param values such that `--ops` with no `=value` for a string evaluates to blank and never eats the next argv
