### ISSUE TITLE
Using `hasOwnProperty` breaks for config objects with null prototype

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#1372]
I'm loading a config object from a third-party library, then passing it to yargs.  This library happens to return an object with a null prototype.  yargs breaks because it's trying to call `config.hasOwnProperty`.

https://github.com/yargs/yargs/blob/master/lib/apply-extends.js#L22

**Comment by bcoe** [comment]
@cspotcode any chance you could provide a minimal reproduction of the issue?

**Comment by cspotcode** [comment]
https://runkit.com/5d12741cd8940e00146b7254/5d24bb163b4b940013e6d846

In my case the config object is coming from another library which is doing the right thing: it's returning an object with a null prototype, which is generally easier to work with as a dictionary.  That's all correct and good.  yargs just needs a tiny patch to fix how it's using `hasOwnProperty`.
