### ISSUE TITLE
getting message for "Invalid values:"  

### ISSUE THREAD

**Issue by khaulafatima** [yargs/yargs#1373]
Hi All, 
I am using `yargs` to develop a cli tool . Here is simple yargs code to process the cli option
```

let argv = require('yargs')
    .usage('$0 <command> [option]')
    .command(
        'validate_zip',
        'validate the directory structure for the zip to be uploaded',
        {
            'validate_zip': {
                alias: 'vz'
            }
        }

    )
    .option('s', {
        alias: 'stage',
        describe: 'stage',
        type: 'string',
        choices: ['dev', 'qa', 'uat', 'prod'],
        count: true
    })
    .demandCommand(1, 'You need at least one command before moving on!')
    .help('h')
    .alias('h', 'help')
    .example('$0 validate_zip -s dev', 'testing yargs')
    .showHelpOnFail(false, "Specify --help || -h for available options")
    .argv; 
```

Here is the cli command 
```node testYargs.js vz  -s dev  ``` . I tried passing ```"dev"```, but having the same issue.

and it displaying the following message 

```
Invalid values:
  Argument: s, Given: 1, Choices: "dev", "qa", "uat", "prod"

Specify --help || -h for available options
```

**Comment by bcoe** [comment]
@khaulafatima I think I see the problem, you should not have `count` set to `true`. Count has a special meaning, indicating that the number of occurrences of a flag should be counted:

https://github.com/yargs/yargs/blob/master/docs/api.md#countkey

So `-v -v -v` would set `v = 3`, this will break the Choices logic on you.

---

👍 I hope this unblocks you, please feel free to reopen this issue if you're continuing to have issues.
