### ISSUE TITLE
Command aliases are not recognized when .command(command, aliases, { builder: ..., handler: ... }) 

### ISSUE THREAD

**Issue by s059ff** [yargs/yargs#1380]
```js
import yargs from "yargs/yargs";

yargs()
.command("example", "####", (yargs) => yargs
  .command("add <a>", "####", {
    aliases: ["new", "a", "n"],
    builder: (yargs) => yargs,
    handler: (argv) => console.log("Success!")
  })
.parse("example new banana", {}, (err) => {
  // Error message: Unknown arguments: new, banana
});
```

My development environment:

|name|version|
|---|---|
|OS|Windows Home 64bit|
|Node.js|10.16.0|
|yargs|13.3.0|

**Comment by bcoe** [comment]
👋 hello @s059ff, the API doesn't quite work like this. If you want to alias `add`, with `new` and `n`, you could perhaps instead do something along the lines of:

```
.usage('$0 <add>', (yargs) => {
  yargs.positional('add', {
    aliases: ['a', 'new']
 })
})
```

see: https://github.com/yargs/yargs/blob/master/docs/api.md#positionalkey-opt

If I recall, there's not an option to alias commands, but you can alias positional arguments; which gives you close to what you're looking for I think?

**Comment by mleguen** [comment]
@bcoe However, the doc mentions command aliases: https://github.com/yargs/yargs/blob/master/docs/advanced.md#command-aliases

**Comment by mleguen** [comment]
@s059ff it looks like aliases can only be defined by providing an array as `command`'s 1st parameter, or an object with an `aliases` property.

This is well illustrated in the documentation.

**Comment by s059ff** [comment]
@bcoe @mleguen Thank you for your answer.
I was overlooked. It was written in the document...
I solved my question.
