### ISSUE TITLE
completions functions doesn't honor user defined FN

### ISSUE THREAD

**Issue by danielb2** [yargs/yargs#1391]
I was going to generate completion for fish shell but regardless of what I do, it outputs the completion for bash/zsh. Below is my test function, and I couldn't get past this.

Version: `13.3.0`

```
 yargs.completion('fish_complete', 'fish completion script', (current, argv) => {

   console.log(current, argv);
   return ['foo'];
 }).argv;

```

**Comment by mleguen** [comment]
I am afraid yargs only supports generating completion scripts for bash and zsh at the moment.

The 3rd parameter of `completion` is not a function to customize the completion script itself, but to customize the suggestions returned by the completion script.

You could however generate the completion script for bash or zsh, adapt it to your needs and package it with your application. It should not be that difficult as the completion script is only a wrapper: most of the completion work is performed by yargs completion function - the one you can customize with the 3rd argument of `completion`.q

A feedback on this or even a PR to add fish shell completion script generation would be much appreciated :-)

**Comment by danielb2** [comment]
> The 3rd parameter of completion is not a function to customize the completion script itself, but to customize the suggestions returned by the completion script.

I think it would be the most powerful to be able to override and produce customization for any shell. Is there any reason to limit ourself to a few hardcoded ones ?

**Comment by bcoe** [comment]
@danielb2 that's a good question, I think the idea was the `80/20` rule; a few types of shells are going to cover a large percentage of people's use cases.

We currently support zsh, and bash, I wonder if it wouldn't be worth adding fish as well?

**Comment by danielb2** [comment]
I'm biased because I've been using it for 5+ years. Most people I recommend it to end up switching over, as it's not a hard sell. I've also seen it grow a lot. But because of the bias, take it with a pinch of salt 😉

**Comment by bcoe** [comment]
@danielb2 if you had any interest in landing a fish completion script, based on the bash and zsh scripts, I would happily land it.

**Comment by danielb2** [comment]
can you explain what `--get-yargs-completions` outputs and how to use it ?

**Comment by mleguen** [comment]
@loilo As you have some experience with zsh completion, would you have a few minutes to help @danielb2 get started with fish completion?

**Comment by danielb2** [comment]
I see that yargs.getOptions() returns all the available options. Is there a way to get the descriptions for each option ?  Fish will use those... 

Example:

<img width="631" alt="Screen Shot 2019-09-27 at 00 17 43" src="https://user-images.githubusercontent.com/26678/65750017-3fc72500-e0bc-11e9-981f-dab7b6c5108a.png">

**Comment by loilo** [comment]
@mleguen I don't have a lot of experience with `zsh` itself (let alone `fish`). With [`completarr`](https://github.com/loilo/completarr), the only thing I do is parsing the `--help` out — so I'm afraid this is not something I can help with, sorry. 😕

**Comment by danielb2** [comment]
forget it
