### ISSUE TITLE
Return help if command args are incorrect (for discord bot)

### ISSUE THREAD

**Issue by dannytatom** [yargs/yargs#1401]
I'm using yargs for a discord bot, so it seems like the normal `showHelpOnFail(true)` won't work (or at least it doesn't).

What I do now is (simplified):

```typescript
parser.parse(command, (error, argv, output) => {
  if (argv.help) {
    message.channel.send('```' + output + '```) // Send `output` wrapped in backticks
  }

  message.channel.send(output) // Send output normally
})
```

This works when you send `help` as the command. I'm trying to find a way to send help when the user gets a command wrong, though. So if the command is `config set <config> <value>` and they send `config set <config>`, it should return the value of `config set help`.

Is there an obvious way to do this that I'm missing?

**Comment by mleguen** [comment]
If a validation error occurs, such as a missing `<value>` in `config set <config> <value>`, your callback function should be called with `error` set. In this case, you should just have to replace:
```js
if (argv.help) {
```
by:
```js
if (error || argv.help) {
```

**Comment by dannytatom** [comment]
Oh, well I feel dumb. Figured it'd be in output like it is if you run `help`. Thanks!
