### ISSUE TITLE
How to get around limitations of using a singleton

### ISSUE THREAD

**Issue by craigphicks** [yargs/yargs#1402]
Is it possible to make a non singleton Yargs something like this ? :

Create a file `yargs-factory.js`:

```
modules.export= (function(){
    // dynamically import yargs/index.js
})

```

Developer side:

```
YargsFactory=requires('yargs-factory')
let argv1 = YargsFactory().command(...).options(opt1).argv
let argv2 = YargsFactory().command(...).options(opt2).argv
```

or some equivalent method?

**Comment by mleguen** [comment]
What about modifying `Argv` for its default parameters to be the one used by the singleton?

`Argv` would then be your factory:
```js
yargs=requires('yargs')
let argv1 = yargs().command(...).options(opt1).argv
let argv2 = yargs().command(...).options(opt2).argv
```

**Comment by craigphicks** [comment]
@mleguen - Indeed that does seem to work when tested with differing properties.

**Comment by craigphicks** [comment]
Perhaps there is no pressing need, but because `yargs` is a singleton and it's conceivable that hidden state could theoretically pose a problem, I'll show code for turning 'yargs' into a class, each instance of the class with separate state.

This following is executed running `node` version 12.8.0 with the flag for esm:
```
node --experimental-modules ...
```

A file `yargs-obj.mjs` 
```
'use strict'
class YargsClass {
    constructor(yargs){
        this.yargs=yargs
    }
}
export default async function createYargsClass(){
    var yargs = await import('../node_modules/yargs/index.js')
    return new YargsClass(yargs)
}
```
Example calling code 
```
'use strict'

import createYargsClass from './yargs-obj.mjs'


(async function () {
    var yac = await createYargsClass()
    console.log(yac.yargs)
})()
```
