### ISSUE TITLE
Sharing code between subcommands

### ISSUE THREAD

**Issue by Myaamori** [yargs/yargs#1409]
I have a number of commands similar to

```
user <name> add [options..]
user <name> remove [options..]
user <name> modify [options..]
```

There is some code that needs to be run at the start and end of each subcommand which will be the same across all the commands, e.g. querying the database for the ID corresponding to a user, or notifying the system of a change. Is there currently a way to share this code between all subcommands in a simple way without having to add identical function calls to the start and end of every command?

I tried nesting yargs instances like this:

```js
let Yargs = require("yargs/yargs");

Yargs()
  .command("user <name> <command..>", () => {}, (argv) => {
    let id = findUserId(argv.name);
    if (id === null) {
      throw new YError("No such user");
    }

    Yargs()
      .command("add [options..]", () => {}, (argv) => {
        // ...
      })
      .command("remove [options..]", () => {}, (argv) => {
        // ...
      })
      .parse(argv.command)

    notifyUserChanged(id);
  })
  .parse(input)
```

But the issue here is that the top level yargs instance will eat any flags, including those that come after `name`.

**Comment by mleguen** [comment]
AFAIK, there is no way of doing this with nested yargs instances without adding "--" after the username.

I would suggest using regular subcommands instead, and having your pre and post subcommand code in a handler factory:

```js
function userHandlerFactory(subCommandHandler) {
  return (argv) => {
    let id = findUserId(argv.name);
    if (id === null) {
      throw new YError("No such user");
    }
    subCommandHandler(id, argv);
    notifyUserChanged(id);
  }
}
[...]
      .command("add [options..]", () => {}, userHandlerFactory((id, argv) => {
        // ...
      }))
```

**Comment by Myaamori** [comment]
I see. I guess doing something like what I'm looking for would require special support for partial parsing of the input. In lieu of that, I suppose a handler factory is a good alternative, thanks for the suggestion.
