### ISSUE TITLE
Wildcards and positional arguments with subcommands

### ISSUE THREAD

**Issue by Myaamori** [yargs/yargs#1427]
Is there any way to handle positional arguments that come *before* a subcommand? Consider e.g. commands of the structure

```
modify <item> add <attribute> <value>
modify <item> clear <attribute>
```

My attempt at representing this:

```js
yargs
    .command("modify <item>", '', (yargs) => {
        yargs
            .command("add <attribute> <value>", '', () => {}, (argv) => {
                console.log("Modifying attribute", argv.attribute, "of item", argv.item)
            })
            .command("clear <attribute>", '', () => {}, (argv) => {
                console.log("Clearing attribute", argv.attribute, "of item", argv.item)
            })
    })
    .parse("modify my_item add my_attribute 10")
```

I would expect this to execute the `add` handler with `{item: "my_item", attribute: "my_attribute", value: 10}`, but no handler is executed, and the actual return value is

```js
{
  _: [ 'modify', 'add', 'my_attribute', 10 ],
  '$0': '',
  item: 'my_item'
}
```

I'd also like to be able to use wildcards to represent commands like `* <item> add <attribute> <value>` (i.e. make it so the `modify` at the start isn't needed), but I run into the same issue here.

**Comment by mleguen** [comment]
With current yargs implementation, only the innermost command (add or clear in you example) can have positionals.

This is also the convention used by many cli tools, such as git:
```
git remote add <remote> <url>
git remote set-url <remote> <url>
```

or docker:
```
docker image rm <image>
docker image save <image>
```

So if you have the hand on specifications, I would recommend switching to this structure:
```
modify add <item> <attribute> <value>
modify clear <item> <attribute>
```

Or turn item into a global option (but this is less conventional and longer to type):
```
modify --item <item> add <attribute> <value>
modify --item <item> clear <attribute>
```

**Comment by arvidfm** [comment]
I see, thank you for the reply. Unfortunately I'm not sure that the structure you propose is appropriate for my use case, both for semantic reasons and because of backwards compatibility, but I'll see if I can adapt it somehow. Otherwise I will try to see if I can figure out a way to represent the required structure without the use of subcommands, or worst case see if there is another module more suited to my use case.

**Comment by Myaamori** [comment]
I see, thank you for the reply. I'm not sure the structure you propose is completely appropriate for my use case, both for semantic reasons and because of backwards compatibility, but I'll see if I can adapt it somehow. Otherwise, I'll try to see if I can implement the structure I need without the use of subcommands, or worst case see if there's another module that better suits my use case.
