### ISSUE TITLE
can't use longform of help

### ISSUE THREAD

**Issue by iamnewton** [yargs/yargs#1432]
I've been trying to figure out what I'm doing wrong below that prevents the long form of `--help` to show the proper menu.  When I run `-h` it shows properly with all things, but when I use `--help` it shows:

![image](https://user-images.githubusercontent.com/5769156/65935004-50351380-e3cc-11e9-9bb3-66f66d1698cf.png)

```
#!/usr/bin/env node

const {
	argv,
	help,
	usage,
	version,
	options,
} = require('yargs');

const USAGE = 'Usage: $0 <command> [options]';
const BASE_OPTS = {
	'a': {
		alias: ['accounts'],
		default: 100,
		describe: 'Account ID(s)',
		requiresArg: true
	},
	'e': {
		alias: ['environment'],
		choices: ['dev', 'qa'],
		default: 'dev',
		describe: 'Environment to run against',
		requiresArg: true
	},
	'u': {
		alias: ['users'],
		demandOption: 'You must provide a user',
		describe: 'User(s) to set',
		requiresArg: true,
		type: 'string'
	}
};
const ALIASES = {
	'h': 'help',
	'v': 'version',
};

usage(USAGE)
	.command('operation', 'Authorize user with operations')
	.example('$0 operation -u 10000 [operations..]', 'Authorize user with operations')
	.command('role', 'Authorize user with roles')
	.example('$0 role -u 10000 [roles..]', 'Authorize user with roles')
	.options(BASE_OPTS)
	.help('h')
	.version()
	.alias(ALIASES)
	.argv;

console.log(opts);
```

**Comment by bcoe** [comment]
@iamnewton not quite sure what's going on there, is the code you shared enough to create a reproduction?

One quick note, `--help` is enabled by default, you might try getting rid of:

```
.help('h')

and you can then just have:

.alias('h', 'help')
```

still, I think you might have unearthed a bug.

**Comment by iamnewton** [comment]
Yeah, should be enough.  I was able to work around it, but this was giving me trouble.

**Comment by forivall** [comment]
I was having the same issue, when i was importing yargs with `await import`.
I solved it via changing it to either
```
(require('yargs') as typeof import('yargs'))
...
```
or (using typescript `esInteropDefault`)
```
(await import('yargs/yargs'))
...
```

My guess is that under the main import, yargs is parsing the help when its imported and exiting before the async resolution finishes.

**Comment by forivall** [comment]
and on *actually* looking at @iamnewton's repro case, the
```
const {
	argv,
	help,
	usage,
	version,
	options,
} = require('yargs');
```
is doing the same thing, without the async hop that causes typescript'd code to fail

**Comment by bcoe** [comment]
@forivall thanks for digging into this, I have high hopes that I might do a little bit of work on yargs this weekend :smile:

@forivall you shouldn't have to `await import('yargs')`, only in certain situations does yargs' support promises, e.g., middleware before calling a command.

@forivall does this only fail when using TypeScript out of curiosity.

**Comment by forivall** [comment]
The `await import('yargs')` is typescript's imitation of the [dynamic `import` api](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#Dynamic_Imports), which always returns a promise.

In theory, this will still happen without the `await`, but I haven't performed a reproduction.

Notably, typescript (with esInteropDefault), will trigger the same bug if one does `import * as yargs from 'yargs'`, but it'll work fine if one does `import yargs from 'yargs'` or `import yargs = require('yargs')`.

The `const { ... } = require('yargs')` is pure js, from @iamnewton given above. All he needs to do is remove `argv` from the destructuring assignment.

**Comment by mleguen** [comment]
I can confirm that removing argv from `const { ... } = require('yargs')` solves the initial issue described bt @iamnewton .

However, @forivall , I am unable to reproduce a similar issue with `import * as yargs from 'yargs';` in typescript. Could you please provide an example?

**Comment by forivall** [comment]
I can reproduce with the following minimal example:

```ts
import * as yargs from 'yargs';

const opts = yargs
  .command('operation', 'Example command')
  .demandCommand()
	.help('h')
	.version()
	.argv;

console.log(opts);
```

```
» npx tsc --esModuleInterop ./repro.ts && node ./repro.js --help
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

~/code/sandbox/src
» node ./repro.js
repro.js <command>

Commands:
  repro.js operation  Example command

Options:
  -h         Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Not enough non-option arguments: got 0, need at least 1
```

note that i use the `esModuleInterop` option. (I misremembered the name in my comment above and said "esInteropDefault".)

**Comment by mleguen** [comment]
@forivall If you set `esModuleInterop`, you should use `import yargs from 'yargs';` to import a commonjs module, no longer `import * from 'yargs';`.

It is explained in the [typescript 2.7 release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-7.html#support-for-import-d-from-cjs-from-commonjs-modules-with---esmoduleinterop), when esModuleInterop was introduced.

Although it is not yargs related, we recently added a comment in the [typescript yargs documentation](https://github.com/yargs/yargs/blob/master/docs/typescript.md) to clarify this.

**Comment by mleguen** [comment]
@forivall My last advice was wrong, as I did not point to [the right paragraph in the typescript documentation](https://www.typescriptlang.org/docs/handbook/modules.html#export--and-import--require).

I fixed the examples in README.md, to use the right syntax to import a commonjs module:

```ts
import yargs = require('yargs');
```

Could you please confirm it solves this issue for your use case?

**Comment by forivall** [comment]
Yeah, `import yargs from 'yargs';` and `import yargs = require('yargs');` both solve the issue in the reproduction example.

I went back and looked at the code that was triggering it, and I realized it was in a dynamic import, rather than a top level import.

So, the exact reproduction case is the following:
```ts
import('yargs').then((yargs) => {
	const opts = yargs
		.command('operation', 'Example command')
		.demandCommand()
		.help('h')
		.alias('h', 'help')
		.version()
		.argv;
	
	console.log(opts);
})
```

which uses the same `importStar` logic with `esModuleInterop`.

The workaround for this is to just use require directly for a dynamic import, which kinda sucks, but that's the only option:

```ts
Promise.resolve().then<typeof import('yargs')>(() => require('yargs')).then((yargs) => {
	const opts = yargs
		.command('operation', 'Example command')
		.demandCommand()
		.help('h')
		.alias('h', 'help')
		.version()
		.argv;
	
	console.log(opts);
})
```
