### ISSUE TITLE
yargs --help command not working

### ISSUE THREAD

**Issue by shivanik6z** [yargs/yargs#1433]
While running "node app.js --help" command It should display the commands too but it is not showing anything not even any error. Just showing the 'msg'(which I imported from a different file)  please ignore the chalks and getNotes stuff, I copy pasted my app's code. I am a beginner in node.js and I don't know why it's not working.
`const yargs= require('yargs')

const chalk = require('chalk');

const getNotes = require('./notes.js');

const msg = getNotes();

console.log(msg);

yargs.command({
    command:'add',
    describe:'Add a new note',
    handler: function(){
        console.log('Adding a new note')
    }
})`

**Comment by HugsForDrugs99** [comment]
@shivanik6z 
You have used help command correctly. Actually, you are not using Console.log(yargs.argv) to get output in terminal.

**Comment by shivanik6z** [comment]
Issue resolved. Thanks:)
