### ISSUE TITLE
Deprecate Node.js 6.x?

### ISSUE THREAD

**Issue by trivikr** [yargs/yargs#1438]
Node.js 6.x got EoL in April 2019 https://github.com/nodejs/Release
Deprecate Node.js 6.x in major version 15.0.0?

**Comment by bcoe** [comment]
I think this is a good idea.

**Comment by trivikr** [comment]
Some history:
* Node.js 6.x was dropped from testing matrix in v13.x https://github.com/yargs/yargs/pull/1287
* However, it was reintroduced with planned deprecation in v14.x https://github.com/yargs/yargs/pull/1308

Looks like planned deprecation was missed, an can be done in v15.x

**Comment by bcoe** [comment]
as soon as we have another compelling breaking change, let's make sure we officially remove it.

**Comment by mleguen** [comment]
That's definitely good news to hear!

**Comment by trivikr** [comment]
Is there some label which can be assigned to this issue, so that we don't miss it while releasing 15.0.0?

**Comment by mleguen** [comment]
Using async/await will simplify the work I have just begun on #1420 , so this will be another reason for dropping node 6 support.

**Comment by trivikr** [comment]
> Using async/await will simplify the work

Yup, async functions support was shipped in [V8 5.5](https://v8.dev/blog/v8-release-55), which was added in [Node.js v7.6.0](https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V7.md#2017-02-21-version-760-current-italoacasas)

I've been using async-await in typescript for couple of year now, and it does make code easier to follow.
