### ISSUE TITLE
Warning about `parsed` in typescript

### ISSUE THREAD

**Issue by vidavidorra** [yargs/yargs#1439]
When using this with typescript and using `import * as yargs from 'yargs';`, I get the following log when running the code. I fixed this by using `import yargs from 'yargs';`, and think it has to do with exactly what is imported. If that indeed is the case, I think the [typescript example](https://github.com/yargs/yargs/blob/master/docs/typescript.md) should be updated. If so, I'd be happy to create a PR, but it really just is removing a couple of characters.

```
In future major releases of yargs, "parsed" will be a private field. Use the return value of ".parse()" or ".argv" instead
```

**Comment by bcoe** [comment]
@vidavidorra 👍 would happily take that patch. Excited to have some folks keeping an eye on yargs' TypeScript support.
