### ISSUE TITLE
implies behaves incorrectly

### ISSUE THREAD

**Issue by danielb2** [yargs/yargs#1442]
Yargs version 14.0.0

For the following code, when passing --check as an argument, the parser fails:

``` javascript
const Yargs = require('yargs');
const yargs = Yargs.usage('Usage: $0 [options]');

const options = {
  check: { type: 'boolean' },
  other: { type: 'boolean' },
  verify: { implies: 'other', type: 'boolean', default: true },
};

yargs.options(options);
yargs.argv;
```

`node play.js --check`

```
Missing dependent arguments:
 verify -> other
```

However, verify isn't implied when running check.  Bug ? Or am I just doing something wrong?

**Comment by danielb2** [comment]
I didn't notice that verify was default true here

**Comment by danielb2** [comment]
On the other hand, the default shouldn't really matter. If I just specify `--verify` without `--other` I would the imply check to fail.  

right now, in order to get check to even run, I have to remove the implies which I need for that option. That's not expected behavior.

**Comment by william-richard** [comment]
I've run into this same problem, where I had an option with a string default value, and I was thinking `implies` would just apply if someone overrode that default.  Instead, I saw the same behavior as you.
Here's an example:
```
      'check': {
        type: 'boolean',
        default: false,
      },
      'verify': {
        type: 'string',
        default: 'Test',
        implies: 'check',
      },
```
I would expect that `implies` to enforce its behavior only if someone passed a different value to the `verify` option.

**Comment by marikaner** [comment]
I think you are right. If you want to use conflicts or implies you should not use default. It should be fairly easy to set the default after parsing. I just wonder whether it is possible to hijack the help output then...

**Comment by bcoe** [comment]
As @william-richard points out, the problem is using implies with a default value, yargs will see this as `verify` being set, and in turn will expect `other` to be set.

I think this is working as intended, I suggest following @marikaner's suggestion of setting the default after parsing.

**Comment by danielb2** [comment]
@bcoe I don't think anyone was saying it works as intended here. maybe you want to re-read. This is clearly unexpected behavior and not inline with documentation. I have no idea how you came to your conclusion but whatever dude
