### ISSUE TITLE
<foo> syntax is now missing when unknown-options-as-args is on

### ISSUE THREAD

**Issue by kellyselden** [yargs/yargs#1444]
https://github.com/ember-cli/ember-cli-update/pull/688

unknown-options-as-args is working as expected for one of my commands https://github.com/ember-cli/ember-cli-update/pull/688/files#diff-2d1ba175f25c88b4ca647166ccdf58c8R22, but it's causing another command to fail https://github.com/ember-cli/ember-cli-update/blob/3b385ee9c1f2e44631b8bce3f4ab9a60b7bdbf54/bin/commands/install.js#L5 where `argv` only has

```
{ _: [ 'install' ],
  '$0': '/Users/kselden/code/ember-cli-update/bin/ember-cli-update' }
```

**Comment by mleguen** [comment]
Here is a simple use case to reproduce this issue.

First without `unknown-options-as-args`:
```js
const yargs = require('yargs')

console.log(
yargs
  .command('$0 <addon>')
  .parse()
)
```

`argv.addon` is populated as expected:
```bash
$ node index.js totoro
{ _: [], '$0': 'index.js', addon: 'totoro' }
```

Then with `unknown-options-as-args`:
```
const yargs = require('yargs')

console.log(
yargs
  .command('$0 <addon>')
  .parserConfiguration({
    'unknown-options-as-args': true
  })
  .parse()
)
```

`argv.addon` is no longer populated:
```bash
$ node index.js totoro
{ _: [], '$0': 'index.js' }
```
