### ISSUE TITLE
How to reuse a builder?

### ISSUE THREAD

**Issue by kopax** [yargs/yargs#1445]
I am using `yargs to create a CLI. 

I want to reuse a `builder`. builder are used to describe `options` within the CLI. 
Generally it look like: `(yargs) => yargs.option('p', { desc: 'print', type: 'boolean' }`. 

I want to store this function under a variable, and do `myVar(yargs).option('x', { desc: 'do something', type: 'boolean'})`. 

## Expected

When I do that, I expect it to work.

## Result

I have `Not enough non-option arguments: got 0, need at least 1`. 

## Reproduction:

`cmd1.js`:

```js
export const builder = (yargs) => yargs
  .positional('file', {
    describe: 'The source file to convert, it must be .doc or .docx document',
  })
  .positional('files', {
    describe: 'Additional sources files to convert, it must be .doc or .docx documents',
  })
  .option('generate-latex-file', {
    alias: 't',
    type: 'boolean',
    describe: 'Output a .tex source file next to the pdf.',
  });
```

`cmd2.js`:

```js
import { builder as docx2latexBuilder } from './docx2latex';
export const builder = (yargs) => docx2latexBuilder(yargs)
  .option('placeholders', {
    alias: 'ph',
    type: 'array',
    describe: 'Select placeholder script to be run on .tex files',
  });
```

**Comment by mleguen** [comment]
@kopax I can see no reason for this way of sharing builder code not to work.

Could you please provide an example of how you are using cmd1.js and cmd2.js to get the `Not enough non-option arguments: got 0, need at least 1` message you report?

**Comment by kopax** [comment]
I was able to make it work with this synthax.

Issue was solved using a `--` in the middle I don't know why but that's unconventional when using with `npx`.

This is far behind, but if I get the opportunity, I'll reopen this issue.
