### ISSUE TITLE
Handling extra args in strict mode

### ISSUE THREAD

**Issue by thehungrycoder** [yargs/yargs#1449]
Strict mode reports extra args as error which is by design. But now not sure how to use this with `config` option. 

Say I've to commands 
- `command1 <foo>` (`foo` option)
- `command2 <bar>` (`bar` option)

Now, I want to fetch `foo` and `bar` from config file if not provided. So i'm using like this
`.config({foo: 'fooval', bar: 'barval'})`. So here, `command1` will use value for `foo` & ignore value for `bar` while `command2` will use value for `bar` & ignore value for `foo`. 

Any idea how to achieve these or a better alternative?

**Comment by bcoe** [comment]
@thehungrycoder bother you to provide a snippet of code demonstrating what you'd like to achieve?

You should have the values populated in the keys `foo` and `bar` of the closure passed to the command handler.


```
yargs.command("command1 <foo>`, () => {}, (argv) => {
  console.info(argv.foo);
}).argv
```

**Comment by thehungrycoder** [comment]
@bcoe thanks. my setup is much more complicated but I tried to simplify in the question. I've separate command per file and using commandDir. 

For now, I've actually taken a different route as I thought `strict` is doing what it is designed to do and `config` won't be useful unless EVERY command depends on some options. So, i've removed `config` but used `default` for each `option` inside the builder function. This is working fine.

**Comment by bcoe** [comment]
@thehungrycoder sounds like we can perhaps close this if you're unblocked? unless there are any specific bugs you think we should open?

**Comment by thehungrycoder** [comment]
Yeah. Thanks
