### ISSUE TITLE
How to get command name?

### ISSUE THREAD

**Issue by speller** [yargs/yargs#1451]
Sample code:

```js
import yargs from 'yargs'
const cfg = yargs
  .command({
    command: 'cmd',
  })
  .argv
console.log(cfg.command)
```

Will print `undefined` even if the command `cmd` is passed. How to get the command name in this case? I don't want to setup handlers, I just want to get data.

**Comment by mleguen** [comment]
@speller Parsed commands and subcommands are the first items of argv._:
```
console.log(cfg._[0])
```

**Comment by speller** [comment]
Thanks!
