### ISSUE TITLE
unknown-options-as-args is causing parser to be ambiguous

### ISSUE THREAD

**Issue by johanblumenberg-symphony** [yargs/yargs#1481]
When using `unknown-options-as-args`, the parsing of unknown arguments becomes ambiguous.

These commands produce different results.

`my-executable --unknown-arg x --array-arg y`

This produces the expected output:

```json
{
  "_": [ "--unknown-arg", "x" ],
  "array-arg": [ "y" ]
}
```

However, just switching the order of the arguments produces a completely different result.

`my-executable --array-arg y --unknown-arg x`

This produces the unexpected output:

```json
{
  "_": [],
  "array-arg": [ "y", "--unknown-arg", "x" ]
}
```

I don't think that the order of arguments should affect the outcome.

If I disable `unknown-options-as-args` I get the expected result in the second example. I don't think that `unknown-options-as-args` should affect what is parsed into arguments and what is not. It should only affect where the result is stored, as argument properties or on `_`.

**Comment by johanblumenberg-symphony** [comment]
When using `unknown-options-as-args`, the parsing of unknown arguments becomes ambiguous.

These commands produce different results.

`my-executable --unknown-arg x --array-arg y`

This produces the expected output:

```json
{
  "_": [ "--unknown-arg", "x" ],
  "array-arg": [ "y" ]
}
```

However, just switching the order of the arguments produces a completely different result.

`my-executable --array-arg y --unknown-arg x`

This produces the unexpected output:

```json
{
  "_": [],
  "array-arg": [ "y", "--unknown-arg", "x" ]
}
```

I don't think that the order of arguments should affect the outcome.

If I disable `unknown-options-as-args` I get the expected result in the second example. I don't think that `unknown-options-as-args` should affect what is parsed into arguments and what is not. It should only affect where the result is stored, as argument properties or on `_`.

**Comment by mleguen** [comment]
@johanblumenberg-symphony  Could you please provide some code of how you are using yargs in `my-executable`?

**Comment by johanblumenberg-symphony** [comment]
`my-executable.js`:

```js
#!/usr/bin/env node

const yargs = require('yargs');

const args = yargs
    .parserConfiguration({
        'strip-aliased': true,
        'unknown-options-as-args': true
    })
    .option('array-arg', { type: 'array' })
    .argv;

console.log(args);
```

output:

```bash
$ ./my-executable.js --array-arg x --unknown-arg y
{ _: [],
  'array-arg': [ 'x', '--unknown-arg', 'y' ],
  arrayArg: [ 'x', '--unknown-arg', 'y' ],
  '$0': 'my-executable.js' }

$ ./my-executable.js --unknown-arg y --array-arg x
{ _: [ '--unknown-arg', 'y' ],
  'array-arg': [ 'x' ],
  arrayArg: [ 'x' ],
  '$0': 'my-executable.js' }
```

**Comment by juergba** [comment]
The yargs-parser [docu](https://github.com/yargs/yargs-parser#unknown-options-as-args) implies that this behavior is intended, not a bug. Have a closer look at `--unknown-option2`.

**Comment by johanblumenberg-symphony** [comment]
> The yargs-parser [docu](https://github.com/yargs/yargs-parser#unknown-options-as-args) implies that this behavior is intended, not a bug. Have a closer look at `--unknown-option2`.

@juergba I've read those docs, and it indeed looks like the behavior is intended.

I still believe that the behavior is not what you would expect, so I think it is a bug.

**Comment by mleguen** [comment]
I agree with @juergba on the fact that is is not a bug, but the intended behavior: using array args **implies** that the order of arguments will have an impact on the outcome.

You do not even need `unknown-options-as-args` to show this:

```bash
$ my-executable --array-arg y arg x
{
  "_": [],
  "array-arg": [ "y", "arg", "x" ]
}

$ my-executable arg x --array-arg y
{
  "_": [ "arg", "x" ],
  "array-arg": [ "y" ]
}
```
