### ISSUE TITLE
How to disable help subcommand?

### ISSUE THREAD

**Issue by christianbundy** [yargs/yargs#1490]
I have an subcommand called `help` that's not getting called because yargs is assuming that I mean `--help`. How can I disable this?

```console
$ over the rainbow help
over the rainbow

Commands:
  over the rainbow help
  over the rainbow snazzy

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
```

**Comment by bcoe** [comment]
@christianbundy you can specify `.help(false)` if I recall, and then implement your own help logic with `showHelp()`.

**Comment by daguej** [comment]
`.help(false)` does not appear to be working correctly.  See #1516

**Comment by mleguen** [comment]
@daguej As commented in #1516, `help(false)` seems to be working as expected.

Could you please provide some sample code with your `help` subcommand not being called?

**Comment by mleguen** [comment]
@christianbundy Could you please provide some sample code with your help subcommand not being called?

**Comment by daguej** [comment]
See [this comment](https://github.com/yargs/yargs/issues/1516#issuecomment-572277796), it looks like the bug only happens when you have a default command with `help(false)` and other commands with help enabled.

**Comment by mleguen** [comment]
Closing as `.help(false)` answers the initial question here, and #1516 is about a more specific use case (disabling global help, and re-enabling help for some subcommands).
