### ISSUE TITLE
Instructions on serving the docs locally

### ISSUE THREAD

**Issue by glenwinters** [yargs/yargs#1504]
I couldn't find any instructions on serving the docs locally to test my changes.

**Comment by glenwinters** [comment]
I found the website's repo and added it to the docs in https://github.com/yargs/yargs/pull/1505, but I'm still not sure how to run locally modified markdown files in the local website. Do you guys do this? I was trying to test links which is why I wanted the website running and not just a markdown preview.

**Comment by mleguen** [comment]
@glenwinters I personnally use the vscode markdown preview which does follow links.

**Comment by glenwinters** [comment]
This answers my question if `yargs.org` is no longer maintained as you hinted at in #1505, but otherwise, it would be nice to document a workflow to view markdown changes in the website locally.
