### ISSUE TITLE
Execute a previous command in all cmd before starting the process

### ISSUE THREAD

**Issue by acortcab** [yargs/yargs#1514]
Hello,

We would like to check if a file exist for all the cmd, is it possible to do this ?

Thanks

**Comment by mleguen** [comment]
@acortcab Could you be a bit more precise about what you'd like to do? Do you mean that all your commands would have a common option or positional which would be a file name, and you would have to check if this file exists?

**Comment by acortcab** [comment]
Yes sure.
I would like to check for all my commands if it exists a specific file in the path I am running the process.
Thanks in advance

**Comment by mleguen** [comment]
Perhaps you could use a global middleware with [`.middleware()`](https://github.com/yargs/yargs/blob/master/docs/api.md#middlewarecallbacks-applybeforevalidation)?

**Comment by acortcab** [comment]
ok cool, I thought it was just for transforming information but I think it could work. 
Thanks so much ;)
