### ISSUE TITLE
.help(false) does not disable --help when used in a default command

### ISSUE THREAD

**Issue by daguej** [yargs/yargs#1516]
`.help(false)` does not appear to be working correctly in v15.0.2 when used in a default command.  It does hide the `--help` option from the help text, but yargs still prints the help text if you run `myapp --help` or `myapp help`.

This is contrary to the [docs](https://github.com/yargs/yargs/blob/master/docs/api.md#help), which say
> If the boolean argument `false` is provided, it will disable `--help`.

I got the desired behavior (ie, yargs did nothing with `--help`) in v8.0.2 by not calling `.help(…)` at all.  I noticed this issue when trying to upgrade.

**Comment by mleguen** [comment]
Reproduced with master branch.

**Comment by mleguen** [comment]
Oups! Sorry, inverted `help(false)` and `parse()` in my test code.

I cannot reproduce this issue with the following test code, using either 15.0.2, 15.1.0 or master branch:
#### index.js
```js
const yargs = require('yargs')

console.log(
  yargs
    .help(false)
    .parse()
)
```

`--help` does not show help, as expected (it is only seen as a regular option):
```bash
$ node index.js --help
{ _: [], help: true, '$0': 'index.js' }
```

@daguej Could you please provide a sample code reproducing this issue?

**Comment by daguej** [comment]
@mleguen looks like my situation was a bit complex.  You have to have a default command with help disabled *and* another command with help enabled.

```js
var yargs = require('yargs');

var argv = yargs
.command('foo', 'bar', function(yargs) {
	yargs.option('baz', {
		describe: 'qux'
	})
})
.command('*', 'foo', function(yargs) {
	yargs
	.option('help', {
		boolean: true
	})
	.help(false)
})
.argv;

console.log(argv);
```

**Comment by mleguen** [comment]
@daguej `.help()` is not designed to work for subcommands, but at the global level.

If I understand well what you are intending to do:
  - `test foo --help`should mean "display help for foo"?
  - and `test --help` should mean something else than "display help for the default command"?

I doubt this is a use case we would cover. However, we should state in the doc that `.help()` is not to be called on commands.

**Comment by daguej** [comment]
@mleguen Yes, you understand my intention.  I want to manually handle the display of help content for my default command, but let yargs handle help for all other commands.

Are you sure that `help()` is not meant to be used with commands?

A quick reading of [the code](https://github.com/yargs/yargs/blob/7293ad50d20ea0fb7dd1ac9b925e90e1bd95dea8/yargs.js#L858-L879) shows that `yargs.help()` is mostly a shortcut for `yargs.boolean('help').describe('help', …)`, and then also sets an internal var `helpOpt` (and I'd bet this bug is related to the handling of that var).  So there's no reason that `help()` should not work with commands.

I can get my desired behavior by inverting how I call `help()` (disabling globally and then enabling selectively), and everything works as expected; I can configure help per-command:

```js
var yargs = require('yargs');

var argv = yargs
.command('foo', '2', function(yargs) {
	yargs.option('baz', {
		describe: 'opt'
	})
	.help()
})
.command('bar', '3', function(yargs) {
	yargs.option('qux', {
		describe: 'opt'
	})
	.help('info')
})
.command('*', '1', function(yargs) {
	yargs
	.option('help', {
		boolean: true
	})
})
.help(false)
.argv;

console.log(argv);
```
```
$ test --help
{ _: [], help: true, '$0': 'test' }

$ test foo --help
test foo

2

Options:
  --version  Show version number                                       [boolean]
  --baz      opt
  --help     Show help                                                 [boolean]

$ test bar --help
{ _: [ 'bar' ], help: true, '$0': 'test' }

$ test bar --info
test bar

3

Options:
  --version  Show version number                                       [boolean]
  --qux      opt
  --info     Show help                                                 [boolean]
```

And, having help enabled globally and disabling it selectively in normal commands also works:

```js
var yargs = require('yargs');

var argv = yargs
.command('foo', '2', function(yargs) {
	yargs.option('baz', {
		describe: 'opt'
	})
	.help(false)
})
.argv;

console.log(argv);
```
```
$ test --help
test [command]

Commands:
  test foo  2

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

$ test foo --help
{ _: [ 'foo' ], help: true, '$0': 'test' }
```

So it's only when a default command is involved that the behavior of `help()` is broken.

This wouldn't be the first time there's a bug with default command help: #810

**Comment by mleguen** [comment]
@daguej Thanks for your analysis.

In fact this occurs only when there is other commands, or when the default command has no aliases, and I thing it is rather a wanted behavior than a bug (set `skipDefaultCommand` to false in `yargs.js`, run `npm test` and look at the uses cases described by broken tests).

As I understand it, yargs distinguishes global help and default command help:
- global help (`node index.js --help`) lists the default command with its aliases and the other commands
- default command help (`node index.js alias --help` with `alias` being a default command alias) displays only the default command options and subcommands

The only exception is when there is neither other commands, nor aliases to the default command. In that case, yargs replaces the global (which would have no interest) by the default command help.

So in your use case, as you stated, you indeed have first to disable the global help, then to reenable it in the commands where you do not want to handle help yourself.

**Comment by 1dotd4** [comment]
>closing w/o fixing

# true opensource!

**Comment by 1dotd4** [comment]
```
yargs
  .command('doStuff', '', () => {}, doStuff)
  .command('help', '', () => {}, myHelp)
  .help(false)
  .parse()
```

`yargs` doesn't use `myHelp` and it's related to `help(false)`.
