### ISSUE TITLE
PSA: tightening up yargs' permissions 

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#1517]
I've been tightening up yargs' team permissions, in prep for fully automating publication. This has included:

1. switching most folks to `triagers` rather than `maintainers` or `admins`.
2. enforcing 2FA on GitHub.
3. adding branch protection rules, such that one code review must have taken place before a PR may be merged.

These changes will put us in a position to more fully automate the yargs project, and were not related to any specific contributors actions (you're all great).

**Comment by shadowspawn** [comment]
Closing this as old. Thanks for PSA @bcoe.
