### ISSUE TITLE
Javascript options file

### ISSUE THREAD

**Issue by euberdeveloper** [yargs/yargs#1522]
I found the config option very useful, but I noticed that it only supports json files.

Is there an alternative or a trick to do the same with an object exported by a javascript file?
I think it could be very useful, especially when you need types such as RegExp that are not allowed in json files

**Comment by mleguen** [comment]
@euberdeveloper You can pass directly an object to `.config()`

**Comment by euberdeveloper** [comment]
> @euberdeveloper You can pass directly an object to `.config()`

But what if I want a file containing the JavaScript object?  

The user to be able to specify --config ./config.js 
Instead of --config ./config.json

**Comment by mleguen** [comment]
@euberdeveloper Then you should use `.config()` with a function as its 2nd parameter, as in the example from [the doc](https://github.com/yargs/yargs/blob/master/docs/api.md#configkey-description-parsefn).

This function would take the config.js path, evaluate the file, and return the resulting config object.

**Comment by euberdeveloper** [comment]
I tried it and it worked, thank you.

It was because of this statement:

`Because the file is loaded using Node's require(), the filename MUST end in .json to be interpreted correctly.`

But it referred only to the default parser, not to the custom one
