### ISSUE TITLE
Bug: .parse not resetting context

### ISSUE THREAD

**Issue by billxinli** [yargs/yargs#1533]
Sample code as `bug.js`:
```
const yargs = require('yargs')

const parser = yargs
  .command({
    command: 'foo <bar>',
    description: 'foo subcommand',
    handler: async ({ bar }) => {
      await new Promise((resolve) => {
        setTimeout(() => {
          resolve()
        }, 100)
      })
      console.log('foo command', bar)
    }
  })
  .demandCommand(1, 'You need at least one command before moving on')
  .strict(true)
  .version()
  .help()
  .example('bot [command] --help', 'get detailed help on any command')

parser.parse(process.argv.slice(2), {}, (err, argv, output) => {
  if (err) {
    console.error(output)
    process.exit(1)
  } else if (output) {
    console.log(output)
  }
})

setTimeout(() => {
  parser.parse('', {}, (err, argv, output) => {
    if (err) {
      console.error(output)
      process.exit(1)
    } else if (output) {
      console.log(output)
    }
  })
}, 1000)
```

When `yargs` is `^15.1.0` we see the output:
```
$ node bug.js foo foo-bar
foo command foo-bar
bug.js foo <bar>

foo subcommand

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

You need at least one command before moving on
```

When `yargs` is `13.3.0` we see the output:
```
$ node bug.js foo foo-bar
foo command foo-bar
bug.js <command>

Commands:
  bug.js foo <bar>  foo subcommand

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Examples:
  bot [command] --help  get detailed help on any command

You need at least one command before moving on
```

The issue is that we are using `yargs` in a bot setting, where `.parse` is called multiple times. 

With older version of `yargs` we see that on every `.parse` call it reset the context, where every command will be parsed properly, with newer versions of `yargs` when `.parse` is called multiple times, the context is not reset. 

This happened in v14 and later

**Comment by bcoe** [comment]
@mleguen any thoughts on this one, I'm guessing it relates to some of the work that's landed related to resetting state.

**Comment by mleguen** [comment]
@bcoe I'll try to dig into this on wednesday

**Comment by mleguen** [comment]
Reproduced with master branch.

**Comment by mleguen** [comment]
It only happens when the handler is async

**Comment by mleguen** [comment]
@bcoe 

> I'm guessing it relates to some of the work that's landed related to resetting state.

I thought that too, first, but it is not the case: this bug is coming from the help message caching introduced in september to try to deal with async handlers. The cache is set, but never removed, so all further calls to showHelp will use the cache.

I also found a 2nd bug linked to this caching: if the handler fails, showHelp is called after yargs is unfreezed, so a 2nd parse is performed, itself failing. As a result, the error message is displayed twice. I am going to open another issue for this one.

Perhaps trying to half deal with async handlers itself is a bad idea. I would recommend entirely dropping async callback support for now, until yargs is fully async itself.

**Comment by mleguen** [comment]
Separate issue opened for the duplicate error message when using async command handlers with `.exitProcess(false)` : #1534

**Comment by bcoe** [comment]
@mleguen thanks for digging into this, really appreciate the work you've been putting into yargs.

**Comment by billxinli** [comment]
@mleguen @bcoe  Thank you for this.

> Perhaps trying to half deal with async handlers itself is a bad idea. I would recommend entirely dropping async callback support for now, until yargs is fully async itself.

I am curious, there are other issues open regarding this, but is there a suggested solution for where async is needed for things like command calling a remote resource, and then displaying some data from that remote resource?

**Comment by mleguen** [comment]
@billxinli Well, as long as yargs is sync (ie not returning promises, or not having (err, value) callback functions in its API **and** its internal functions), the only solution I can see is to store a promise in the handler and to wait for it after calling parse:

```js
let dataPromise ;
yargs.
  command(("cmd", "test cmd", {}, (argv) => {
    dataPromise = asyncCallToRemoteResource(argv)
  })
  .parse()
displaySomeData(await dataPromise);
```

Does it answer your question?
