### ISSUE TITLE
Help is displayed twice when an async handler fails with exitProcess(false)

### ISSUE THREAD

**Issue by mleguen** [yargs/yargs#1534]
#### index.js
```js
const yargs = require('yargs')

yargs()
  .command('cmd', 'test command', {}, () =>
    new Promise((resolve, reject) => 
      setTimeout(reject, 10)
    )
  )
  .exitProcess(false)
  .parse('cmd')
```

Results:
```bash
$ node index.js
index.js cmd

test command

Options:
  --help     Affiche de l'aide                                         [booléen]
  --version  Affiche le numéro de version                              [booléen]

index.js cmd

test command

Options:
  --help     Affiche de l'aide                                         [booléen]
  --version  Affiche le numéro de version                              [booléen]
```

Expected:
```bash
$ node index.js
index.js cmd

test command

Options:
  --help     Affiche de l'aide                                         [booléen]
  --version  Affiche le numéro de version                              [booléen]
```

**Comment by mleguen** [comment]
Probably due to showHelp beeing called when the handler fails, after yargs is unfreezed, so showHelp calls parse again, calling the handler a second time and failing a second time.

**Comment by mleguen** [comment]
I recommend:
- leaving this bug as is
- and adding a warning in the doc not to use an async handler if parse is intended to be called several times, as an help message for an async handler failure can occur in the middle of the next call to `.parse()`

I can see no way of dealing "cleanly" with async handlers while yargs is sync.

@bcoe what is your opinion on this?

**Comment by bcoe** [comment]
@mleguen I agree with adding a caveat for `async` handlers for the time being.
