### ISSUE TITLE
How do I set up the “<anything> <subcommand>” command?

### ISSUE THREAD

**Issue by issuefiler** [yargs/yargs#1537]
How do I set up a command as follows?

-----

```
<anything> <subcommand>
```
- Positional argument `anything`: anything.
- Positional argument `subcommand`: one of `alpha`, `bravo`, `charlie`, and `delta`.

-----

> node main.js anything alpha
> node main.js qwerty delta
> node main.js apple charlie

**Comment by mleguen** [comment]
Yargs does not support positionals before subcommands.

But yargs supports:
- either using a positional after the subcommand, which I personnaly see as the "standard" (git, docker, etc.) way, for example:
  ```
  node main.js command argument
  ```
- or replacing the positional by a global option:
  ```
  node main.js --option argument command
  ```
