### ISSUE TITLE
Strange process.argv behavior when testing with jest

### ISSUE THREAD

**Issue by gempain** [yargs/yargs#1573]
I have the following `index.ts`:
```typescript
require('yargs')
  .command({ command: 'test', handler: args => console.log(args) })
  .parse(process.argv)
```

And a jest test which works great:
```typescript
it('should call console.log', async () => {
    const spy = jest.spyOn(console, 'log');
    process.argv = ['test'];
    require('./index.ts');
    expect(spy).toHaveBeenCalled();
  });
```

For some strange reason, if I change `.parse(process.argv)` to `.parse()`, my test breaks, which doesn't make sense since Yargs parses `process.argv` under the hood, if I am not mistaken.

**Comment by mleguen** [comment]
@gempain Yargs parses `process.argv` under the hood *at the moment you call `require('yargs')`*, which means, in your case, before you set `process.argv` with your test value.

If you want to test using `process.argv`, you need to "unrequire" yargs and require it again in your test, after setting `process.argv`.

**Comment by mleguen** [comment]
@gempain You can find an example of this way of doing [in yargs' tests](https://github.com/yargs/yargs/blob/c36c571e4e15dfe26be1d919e4991fb6ab6ed9fd/test/yargs.js#L20)

**Comment by gempain** [comment]
@mleguen for such quick answers :) I've placed a few console logs in `yargs.js` and `process.argv` seems to be properly set though:

```
self.scriptName = function (scriptName) {
    self.customScriptName = true
    self.$0 = scriptName
    return self
  }

  console.log('process.argv', process.argv);

  // ignore the node bin, specify this in your
  // bin file with #!/usr/bin/env node
  if (/\b(node|iojs|electron)(\.exe)?$/.test(process.argv[0])) {
    self.$0 = process.argv.slice(1, 2)
  } else {
    self.$0 = process.argv.slice(0, 1)
  }
```

Which prints:
```
  console.log node_modules/yargs/yargs.js:52
    process.argv [ 'test' ]
```

**Comment by gempain** [comment]
@mleguen okay, looking at the code, it makes sense as the singleton is exported once. However, even running the test as follows fails:
```typescript
jest.resetModules();
jest.isolateModules(() => {
    require('./index');
});
```

I expect jest to re-require `index`, and also related modules. I see in your test that you delete something from the require cache, is that the key ? Jest docs mention that [`jest.resetModules()`](https://jestjs.io/docs/en/jest-object#jestresetmodules) does clean the module registry, so I'd expect it to.

**Comment by mleguen** [comment]
@gempain Yes, it the key, as you say. Node only instanciates a module once, the first time it is required, and takes it already instanciated from the cache if it is required again later.

So as you need yargs to be re-instanciated, for it to take into account the modified process.argv, you need to remove it from node's cache first:
```js
delete require.cache[require.resolve('yargs')]
```

**Comment by gempain** [comment]
@mleguen interesting, I thought jest would take care of that. Thanks for the hint, and keep up the great work - we use your lib in pretty much every single cli we write.

**Comment by brlodi** [comment]
Sorry to bring up a closed issue, but what's the current path for testing in an ESM environment? There's no `require` cache to clear in that case.

I get that reading at require-time is likely a performance consideration, but would it be possible for yargs to have a method to force it to re-read `process.argv` and `process.env` after the initial import?
