### ISSUE TITLE
Coerce an option's array of values into strings

### ISSUE THREAD

**Issue by garyking** [yargs/yargs#1588]
If I have `yargs.option('items', { type: 'array' })` and I pass `--items abc 123` then I get `['abc', 123]`. 

But is it possible to instead get all items as a string, like `['abc', '123']`? 

Is it possible to do this via a setting in `.option`, rather than a global Yargs parser setting, and rather than converting the array myself?

**Comment by mleguen** [comment]
@garyking `.option('items', { type: 'string', array: true })` should be what you need.

**Comment by garyking** [comment]
Amazing thanks, this is great!
