### ISSUE TITLE
Default options are parsed in a wrong way.

### ISSUE THREAD

**Issue by wdanilo** [yargs/yargs#1590]
Hi, I'm using following options description:
```javascript
optParser.options('frame', {
    group       : styleOptionsGroup,
    describe    : 'Draw window frame [false]'
    default     : false,
})
```

When I run my program as `prog --frame`, the `frame` is set to `false` by yargs. When I run it as `prog --frame true`, it is set to `'true'` (string) by yargs. However, if I change the config to:

```javascript
optParser.options('frame', {
    group       : styleOptionsGroup,
    describe    : 'Draw window frame [false]'
    default     : false,
})
```

It behaves correctly. I mean, when I run it as `prog --frame`, then `frame` is set to `true`. I believe this is some serious bug, right?

**Comment by mleguen** [comment]
@wdanilo I cannot see any difference in the 2 code samples you give?

**Comment by bcoe** [comment]
@wdanilo I think thinks will work as you expect if you also add the key:

```
type: 'boolean'
```

to provide a hint to the parser that `frame` is a boolean argument.

**Comment by wdanilo** [comment]
@bcoe yes, that solves the issue, thanks!
