### ISSUE TITLE
Can I make the following command with Yargs?

### ISSUE THREAD

**Issue by ffMathy** [yargs/yargs#1593]
Look at https://docs.docker.com/compose/reference/overview/

More specifically:

> Usage:
>   docker-compose [-f <arg>...] [options] [COMMAND] [ARGS...]
>   docker-compose -h|--help
> 
> Options:
>   -f, --file FILE             Specify an alternate compose file
>                               (default: docker-compose.yml)
>   -p, --project-name NAME     Specify an alternate project name
>                               (default: directory name)
>   --verbose                   Show more output
>   --log-level LEVEL           Set log level (DEBUG, INFO, WARNING, ERROR, CRITICAL)
>   --no-ansi                   Do not print ANSI control characters
>   -v, --version               Print version and exit
>   -H, --host HOST             Daemon socket to connect to
> 
>   --tls                       Use TLS; implied by --tlsverify
>   --tlscacert CA_PATH         Trust certs signed only by this CA
>   --tlscert CLIENT_CERT_PATH  Path to TLS certificate file
>   --tlskey TLS_KEY_PATH       Path to TLS key file
>   --tlsverify                 Use TLS and verify the remote
>   --skip-hostname-check       Don't check the daemon's hostname against the
>                               name specified in the client certificate
>   --project-directory PATH    Specify an alternate working directory
>                               (default: the path of the Compose file)
>   --compatibility             If set, Compose will attempt to convert deploy
>                               keys in v3 files to their non-Swarm equivalent
> 
> Commands:
>   build              Build or rebuild services
>   bundle             Generate a Docker bundle from the Compose file
>   config             Validate and view the Compose file
>   create             Create services
>   down               Stop and remove containers, networks, images, and volumes
>   events             Receive real time events from containers
>   exec               Execute a command in a running container
>   help               Get help on a command
>   images             List images
>   kill               Kill containers
>   logs               View output from containers
>   pause              Pause services
>   port               Print the public port for a port binding
>   ps                 List containers
>   pull               Pull service images
>   push               Push service images
>   restart            Restart services
>   rm                 Remove stopped containers
>   run                Run a one-off command
>   scale              Set number of containers for a service
>   start              Start services
>   stop               Stop services
>   top                Display the running processes
>   unpause            Unpause services
>   up                 Create and start containers
>   version            Show the Docker-Compose version information

Can I immitate that form of command structure with Yargs? If not, what is the closest I can get to it?

**Comment by mleguen** [comment]
@ffMathy I am not sure what exactly your question is. Are you asking if yargs supports handling commands such as `my-app build`, `my-app bundle`, etc. ?

**Comment by ffMathy** [comment]
More specifically, I am interested in replicating this part:

> docker-compose [-f ...] [options] [COMMAND] [ARGS...]

In other words, an optional parameter that can be repeated X amount of times (the `[-f ...]` part or the `[ARGS...]` part), and then displaying the "help" exactly like the output above (custom formatting of Help).

**Comment by mleguen** [comment]
@ffMathy 

> In other words, an optional parameter that can be repeated X amount of times (the [-f ...] part or the [ARGS...] part).

You should try:
```js
    .option('f', {
      array: true,
      nargs: 1
    })
```

> In addition, I'm interested in being able to display the "help" exactly like the output above (custom formatting of Help).

In that case you must disable the default help with `.help(false)` and display your custom help by yourself (for example when a `--help` flag is set).

**Comment by ffMathy** [comment]
Thank you so far.

If I were to format the help message myself, would I have to provide a hard-coded string, or can I instead provide a function?

For instance:

`.help(({options, positionals}) => "List of options: " + options.map(x => x.name).join(", "))`

?

**Comment by ffMathy** [comment]
Also, I tried with the following command module:

```
{
    command: 'compose [-f <arg>...] [options] [COMMAND] [ARGS...]',
    describe: '',
    builder: yargs => yargs
        .positional('COMMAND', {
            type: 'string',
            demand: true
        })
        .options({
            'file': {
                alias: 'f',
                description: 'Specify an alternate compose file',
                type: 'string',
                demand: false,
                default: 'docker-compose.yml',
                array: true,
                nargs: 1
            }
        }),
    handler: (argv) => {
        console.log(argv);
    })
}
```

But when I invoke it using:

`compose -f lol -f omg up`

I get:

```
{ _: [ 'compose' ],
  f: [ 'lol', 'omg' ],
  file: [ 'lol', 'omg' ],
  '$0': 'dist\\index.js',
  '-farg': 'up',
  farg: 'up',
  ARGS: [],
  args: [] 
}
```

I would expect to get `COMMAND` set to `up`. Also, I don't need the `farg` that it sets - it should only be there in the description of the command.

**Comment by mleguen** [comment]
@ffMathy 

> .help(({options, positionals}) => "List of options: " + options.map(x => x.name).join(", "))

`.help` is only the function to call to enable/disable the automated help, not the place to provide your custom help.

After the automated help is disabled with `.help(false)`, you have to display your custom help by yourself, either in command handlers, or in your main code after the call to `yargs.parse()`.

> I would expect to get COMMAND set to up

The comand property you gave:
```
command: 'compose [-f <arg>...] [options] [COMMAND] [ARGS...]'
```
means you want the 1st positional to be named `-fargs`, the 2nd `options`, the 3rd `COMMAND`, etc.

So this is `-fargs` which is set to `up`.

**Comment by bcoe** [comment]
Hey @ffMathy if you bump into any issues with the command interface, let's open some ticket for specific problems.

I'm open to specific issues/incremental work to gradually improve the output of yargs, but it's not a goal of the project to provide a level of customization for help output, that would allow you to match `docker-compose` exactly.
