### ISSUE TITLE
The updateStrings() could not work on 'Options:' 

### ISSUE THREAD

**Issue by tianyingchun** [yargs/yargs#1598]
```
   .updateStrings({
        command: chalk.cyan('command'),
        'Examples:': cyanUnderline('Examples:'),
        'Commands:': cyanUnderline('Commands:'),
        'Options:': cyanUnderline('Options:'),
        'Invalid values:': `${chalk.bgBlack.red('ERR! ')}${chalk.bold('Invalid values:')}`,
      })
```
the `Options:` location update can't work correctly.  cause of 
```
  // below line is always execute before  updateStrings();
  const defaultGroup = __('Options:')
  self.help = function help () {
```
while we show help like `cmd -h` the defaultGroup has been initialized earlier that updateLocale().

it's bug?     `BTW  yargs v15.1.0  works fine.`

**Comment by bcoe** [comment]
@mleguen I think there were some tweaks to translations recently that might have effected this?

**Comment by mleguen** [comment]
@bcoe It *does* is something I changed recently.

I should be able to have a closer look at this tomorrow.

**Comment by mleguen** [comment]
@bcoe It definitely *was* something I changed recently...

Fix ready to review in #1600.

**Comment by bcoe** [comment]
@mleguen I landed the yargs-parser fix and released it.

**Comment by mleguen** [comment]
Thanks @bcoe
