### ISSUE TITLE
set command line option to value starting with `--` (double dash) fails

### ISSUE THREAD

**Issue by rriemann** [yargs/yargs#1602]
Dear all,

I have a tool with this option:

```js
var args = require('yargs')
  .describe('browser-options', 'Arguments passed over to the browser (Chrome)')
  .nargs('browser-options', 1)
  .array('browser-options')
  .default('browser-options', [])

However, calling my tool with options `--browser-options=--test` does not work. I get the error:

    Not enough arguments following: browser-options

Do I need to apply special shell escaping? I reproduced the problem with both bash and zsh.

**Comment by mleguen** [comment]
Reproduced with master:
- `.array()` and `.nargs()` seem not to be working with `--option=--value` (value is seen as an independant option)
- when `.array()` and `.nargs()` lines are commented out, `--value` is seen as the value of `option`, as expected

**Comment by mleguen** [comment]
I traced the issue back to yargs-parser and will open an issue there.

**Comment by mleguen** [comment]
Issue yargs/yargs-parser#261 opened.

**Comment by mleguen** [comment]
Waiting for yargs/yargs-parser#262 to be merged upstream before fixing it in yargs.

**Comment by mleguen** [comment]
Fix released upstream (thanks again @bcoe). I will include it in yargs ASAP.

**Comment by bcoe** [comment]
@rriemann if you get rid of your `package-lock.json` and reinstall fresh, this should already be fixed for you.
