### ISSUE TITLE
Options that are demanded appear in help text multiple times

### ISSUE THREAD

**Issue by NickHeiner** [yargs/yargs#1604]
```js
var yargs = require("yargs")

yargs
    .option('f <x>', {type: 'string'})
    .demandOption('f')
    .showHelp()
```

Produces this output: 

```
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --f <x>                                                               [string]
  -f                                                                  [required]
```

Strangely, `f` appears twice. One, it's `[string]`, and the other time, it's `[required]`. Additionally, it only has one `-` the second time.

Here's a [runkit which repros this](https://runkit.com/nickheiner/5e7e787daefb7900139267fe).

**Comment by bcoe** [comment]
```
.option('f <x>', {type: 'string'})
```

☝️ the `<foo>`, `[bar]` syntax is for positional arguments in `commands` (doesn't work for options). So you've created an option `f <x>` and an option `x`.

I would rewrite this as:

```
var yargs = require("yargs")

yargs
    .option('f', {type: 'string'})
    .demandOption('f')
    .showHelp()
```

If you do want to define a command that takes positional arguments, take a look at the `.command()` documentation, it should do the trick for you 👌

**Comment by NickHeiner** [comment]
Perfect! Thanks for the super fast response.
