### ISSUE TITLE
How to require non-hyphenated option before hyphenated options?

### ISSUE THREAD

**Issue by dmoini** [yargs/yargs#1616]
Is it possible to require the first `n` arguments called after the command to be a non-hyphenated argument and then everything else afterwards can be either hyphenated or non-hyphenated?

Examples: 
- `command arg1 --option1 value1 --option2 value2` (valid for `n=1`)
- `command arg1 arg2 --option1 value1 --option2 value2` (valid for `n=2`)
- `command --option1 value1 --option2 value2 arg1` (invalid for `n=1`)
- `command arg1 --option1 value1 --option2 value2` (invalid for `n=2`)

**Comment by mleguen** [comment]
@dmoini I don't think it is possible at the moment.

Could you please describe the use case behind this technical need? Perhaps we could find alternatives.

**Comment by dmoini** [comment]
If I am trying to make a CLI with the ability to upload and download files. For example, the command would be run in the format of `command [upload|download] [options]`. It would look like the following:

`command upload --option1 value1` or `command download --option1 value1 --option2 value2`

Since yargs does not check the ordering of non-hyphenated arguments in relation to hyphenated arguments, or at least I cannot find any documentation that says it does, yargs would also allow these commands to run exactly the same as the previous examples respectively:

`command --option1 value1 upload` and `command -option1 value1 -option2 value2 download`

I do not want my CLI to allow arguments to be in that order. The only thing I have thought to resolve this issue is look at `process.argv[2]` before using yargs and make sure that is `process.argv[2] === "upload"` or `process.argv[2] === "download"`, otherwise throw an error.

**Comment by mleguen** [comment]
What you describe in yargs' terms is command being a command, and download and upload its subcommands.

However, Yargs will not forbid your users to specify options before the subcommands.

Why don't you want your users to be allowed to do so, when they can do it with other CLI tools?

**Comment by dmoini** [comment]
Subcommands is definitely what I am looking for. It is just a personal preference. If yargs is unable to do so, then that is fine.
