### ISSUE TITLE
Bad/not enough Japanese translation

### ISSUE THREAD

**Issue by hogashi** [yargs/yargs#1617]
### must

- It seems that the translation for "Given" in Japanese is wrong: https://github.com/yargs/yargs/blob/262e796329f4a09083ca07e49f926ae43ac850e9/locales/ja.json#L37
  - `指定できるのは %s つです。` means "you can give %s" ( `%s` is expected to be the number of option such as 1, 2, 3)
  - It should be `与えられた値: %s` which means "the value that you gave me: %s"

### may

- The word correspond to "value" is missing in Japanese: https://github.com/yargs/yargs/blob/262e796329f4a09083ca07e49f926ae43ac850e9/locales/ja.json#L25-L26
  - `引数が見つかりません: %s` only means "I can't find the argument: %s"
  - It should be `引数の値が見つかりません: %s` which means "I can't find the value of the argument: %s"
- The word "deprecated" is not translated yet.
  - `deprecated` should be `非推奨` which means "not recommended"
  - `deprecated: %s` should be `非推奨: %s` which means "%s is not recommended"

**Comment by mleguen** [comment]
@hogashi Thank you for pointing this out. Would it be possible for you to fix these files and submit a PR?

**Comment by hogashi** [comment]
@mleguen Thank you for your reply, too. Yes, I will submit PR for this!

**Comment by hogashi** [comment]
@mleguen I have just made a PR for this issue. Would you please take a look? #1619
