### ISSUE TITLE
How to get the defualt argument content?

### ISSUE THREAD

**Issue by houcy** [yargs/yargs#1623]
Hi there,
This yargs is very powerful and useful in my project. But I don't know how to get the correct argument. I wrote code as below.

const argv = require('yargs')
    .command('*', 'the sb3 file handler', () => {}, (argv) => {
               console.log('sb3 file name:' + argv);
    }).argv;

So the program can be run with argument as below:
myprogram  c:\app\test.sb3

myprogram need to accept whatever filename as the argument. But how to get the filename??
Thanks!

**Comment by mleguen** [comment]
> myprogram need to accetp whatever filename as the argument

Then you should define filename as a positional argument, to be able to read it from `argv.filename`:
```js
const argv = require('yargs')
  .command('* <filename>', 'the sb3 file handler', () => {}, (argv) => {
    console.log('sb3 file name:' + argv.filename);
  }).argv;
```

See: https://github.com/yargs/yargs/blob/master/docs/advanced.md#positional-arguments

**Comment by houcy** [comment]
Thanks mleguen for your kind reply! 

myprogram runs on Windows platform and associates filename suffix with .sb3,  so when double clicking *.sb3 file,  windows operating system automatically pass the full filename to myprogram as argument. And the OS doesn't add positional-argument, it just send the .sb3 full filename.

Say when double clicking *.html file,  the default browser program accepted the html file and opens the web page,  double clicking *.txt file, the notepad opens it. 
So myprogram opens *.sb3 file by grabbing the filename argument.

So is there any other way to get the command line argument for electron application? (mypgrom is electron app).
Thanks very much!

**Comment by houcy** [comment]
> > myprogram need to accetp whatever filename as the argument
> 
> Then you should define filename as a positional argument, to be able to read it from `argv.filename`:
> 
> ```js
> const argv = require('yargs')
>   .command('* <filename>', 'the sb3 file handler', () => {}, (argv) => {
>     console.log('sb3 file name:' + argv.filename);
>   }).argv;
> ```
> 
> See: https://github.com/yargs/yargs/blob/master/docs/advanced.md#positional-arguments

Great thanks to you!  
The arguement is successfully retrieved.
