### ISSUE TITLE
How to get zero or one argument?

### ISSUE THREAD

**Issue by houcy** [yargs/yargs#1628]
Hi there,

I wrote myprogram to accept zero or one argument as below:

const argv = require('yargs').command('* <filename>', 'the sb3 file handler', () => {}, (argv) => {
        console.log(argv.filename, 'utf8');
    }).argv;

When running myprogram.exe, if there is one argument, it run successfully. But it crashed when no argument was passed to it. The crash log shows as below:

myprogram.exe   filename

the sb3 file handler

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
undefined
Not enough non-option arguments: got 0, need at least 1

So how to make it work with zero or one arugment? Thanks very much!

**Comment by houcy** [comment]
problem fixed by checking if the property exists first.

**Comment by mleguen** [comment]
@houcy Instead of checking it first, you only have to write `.command('* [filename]', ...` to indicate you want an optional positional argument.

See https://github.com/yargs/yargs/blob/master/docs/advanced.md#positional-arguments
