### ISSUE TITLE
How to use option without command (for example: <commandName> --option)?

### ISSUE THREAD

**Issue by ghost** [yargs/yargs#1630]
Hello, I'm Wojcraft. I want to create very simple cli with yargs, but i have problem. I was looking for this problem in google, but I didn't find the answer, that's why I'm asking here. If this question repeats, please direct me to the original question. Thanks :).

**Comment by mleguen** [comment]
@WojCraft With `.option()`, see https://github.com/yargs/yargs/blob/master/docs/api.md#optionkey-opt

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
