### ISSUE TITLE
Creating a parameter called "version" silently breaks

### ISSUE THREAD

**Issue by russellrobinson** [yargs/yargs#1651]
This code fails to work:
```.options({
        'version': {
          describe: 'The version to set in the database.',
          demandOption: true,
          requiresArg: true,
          nargs: 1,
          type: 'string'
        }
      })
```

The result is the parsed arguments always have `version: false`

It seems "version" is an undocumented special word to yargs.

**Comment by mleguen** [comment]
`--version` is already an option displaying the cli version. You have to disable it first with `.version(false)` to be able to reuse it for something else.

See https://github.com/yargs/yargs/blob/master/docs/api.md#version

**Comment by russellrobinson** [comment]
Yes, we discovered that.  But we lost 2 man hours because of this problem.

**Comment by mleguen** [comment]
@russellrobinson Do not hesitate to submit a PR to rephrase the doc if you think it could save some time to someone else facing the same problem.
