### ISSUE TITLE
.demand and .demandCommand

### ISSUE THREAD

**Issue by petriusus** [yargs/yargs#1653]
Maybe I missunderstand something, but the only thing that works to demand a command is .demand, and not .demandCommand.

Error when using demandCommand: .demandCommand is not a function.

npm: yargs 15.3.1.

**Comment by mleguen** [comment]
Could you please provide some code to reproduce?

**Comment by petriusus** [comment]
Sorry, sure:
argv = require("yargs").demandCommand(2).argv;

**Comment by petriusus** [comment]
Ohh no.. My bad. Npm was out of sync on my testing machine. 

Sorry for wasting you time.

Thank you for a fast response.

**Comment by mleguen** [comment]
@petriusus No problem, glad to see you found what was wrong.
