### ISSUE TITLE
[q] How onFinishCommand works with commandDir

### ISSUE THREAD

**Issue by SkeLLLa** [yargs/yargs#1658]
Does `onFinishCommand` work with `commandDir`? And if it does, then how it should be configured?

**Comment by mleguen** [comment]
@SkeLLLa Yest, it should work with `commandDir`, and the configuration should be the same as with `command`, as the same handler is used for all commands.

Have a look at the example in the docs here:
https://github.com/yargs/yargs/blob/master/docs/advanced.md#command-finish-hook

**Comment by bcoe** [comment]
@SkeLLLa I've added the `onFinishCommand` to the API docs, should be working. Let us know if there are any bugs.
