### ISSUE TITLE
Can't override --version

### ISSUE THREAD

**Issue by jtbennett** [yargs/yargs#1660]
I'm using `yargs@15.3.1`.

With `yargs.version(false)` I can disable the `--version` and `-v` options. However, this sets the value of `argv.version` and `argv.v` to `false` and prevents using those option names for anything else. 

The value of an option declared like this:
```js
yargs
  .version(false)
  .options({ version: { string: true, alias: "v" } })
```
is treated as a positional argument. It's as if the `--version` isn't in the command line at all.

I would like to use `--version` for my own option that takes a non-boolean value. Is that possible?

**Comment by bcoe** [comment]
duplicate of: https://github.com/yargs/yargs/issues/416

Keeping this one open since it's easier to find.

**Comment by bcoe** [comment]
@jtbennett I tried to reproduce your issue, and I think I'm misunderstanding the problem. I ran this code:

```js
const yargs = require('yargs')
const argv = yargs
  .version(false)
  .options({ version: { string: true, alias: "v" } }).argv
console.info(argv)
```

Without passing any arguments, the output is:

`{ _: [], '$0': 'foo.cjs' }`

Here's the output setting `--version`:

```
bencoe-macbookpro3:test-yargs bencoe$ node foo.cjs --version

{ _: [], version: '', v: '', '$0': 'foo.cjs' }

bencoe-macbookpro3:test-yargs bencoe$ node foo.cjs --version hello

{ _: [], version: 'hello', v: 'hello', '$0': 'foo.cjs' }
```

**Comment by jtbennett** [comment]
I know I did have that problem, because I remember being very frustrated by it. But now I can't reproduce it, with either v15 or v16 of yargs. 

My apologies!

Closing this issue.

**Comment by kentnsw** [comment]
Hello, would the below code explain this issue?

```js
const yargs = require("yargs");

const y1 = yargs(["--Version", "1.2.3"]);
console.log(y1.argv);

const y2 = yargs(["--version", "1.2.3"]);
console.log(y2.argv);

// ❯ node test-yargs.js
// { _: [], Version: '1.2.3', '$0': 'test-yargs.js' }
// 1.0.0
```
