### ISSUE TITLE
Compatibility with deno

### ISSUE THREAD

**Issue by quilicicf** [yargs/yargs#1661]
Hi guys, 

Do you have any plans to add compatibility for [deno](https://deno.land/)?

The 1.0.0 is out so it's a good time to think about it I guess.

I'd be thrilled to test it!

**Comment by bcoe** [comment]
I'm not sure what this entails, would happily accept a patch moving us in that direction? I would guess that we need to get the library fully migrated to TypeScript first?

**Comment by quilicicf** [comment]
To migrate to deno you need to perform the following actions (this is gathered from documentary research and trying to migrate one of my own npm modules, which lead me here :laughing:).

* Migrate imports from CommonJS to ES: :warning: this pushes minimum NodeJS requirement for your module to version 13+ (the 12 will be the LTS until Oct 2020 when the LTS will switch to 14)
* Migrate dependencies (there should be two entry-points for the module, one that uses Deno deps and one that uses node's). For the dependencies, I think the strategy might be:
  * If they're already Deno-compatible, no issue just import them Deno-like
  * Or one can ask the dependency's maintainer to migrate (what I'm doing here XD)
  * Or one can use another Deno dependency with similar features (more risky IMO)
  * Or one can re-implement the dependency (only makes sense for tiny dependencies I guess)

> Note:  TS is not gonna be an issue because being a superset of JS, any valid JS is valid TS.

**Comment by bcoe** [comment]
closing in favor of https://github.com/yargs/yargs/issues/1706
