### ISSUE TITLE
Combine same name command

### ISSUE THREAD

**Issue by vipzhicheng** [yargs/yargs#1672]
I mainly use yargs by commandDir to register commands, that will lead to same commands in different directory. When I run --help, they are all shown, but if I run the command, only last command effected.

I think maybe need to clean up commands array by command name before showing help. Is this idea reasonable?

**Comment by vipzhicheng** [comment]
Related code: usage.js

find:

```
commands.push([cmd, description || '', isDefault, aliases])
```

add this line above:

```
    commands = commands.filter(cmdArray => {
       return cmdArray[0] !== cmd
    })
```

It works for me, but don't know if has any bad effects.

**Comment by bcoe** [comment]
To me it seems like the last command with the same name taking effect would be the ideal behavior?

It does sounds like it's a bug that we display the same command multiple times in the help output.

Perhaps we should:

* warn to the console if you load the same command twice.
* only display help for the last command registered.

It feels a little too fancy to me to support multiple versions of the same command.

**Comment by vipzhicheng** [comment]
I prefer the option 2. For option 1, in my scenario, I create a "plugin system" to register command from each plugin directory, it's possible to register same command, but may not need to warn in help.

**Comment by bcoe** [comment]
@vipzhicheng so, you'd prefer not to have a warning, but you want only the last command registered to show up in help, is what I'm understanding 👍

**Comment by vipzhicheng** [comment]
Exactly!   👍
