### ISSUE TITLE
Passing "help" as the only positional arguments leads to printing the help message

### ISSUE THREAD

**Issue by fa93hws** [yargs/yargs#1675]
Say I have a cli tools that is implemented by yargs as
```
  yargs.command('$0 <pageName>', 'Builds a specific page as a standalone app into target/<page>.', {
    builder: (): yargs.Argv<CliArgs> => yargs
    .positional('pageName', {
      describe: 'name of a folder containing a harness page entry point under web/src/pages',
      type: 'string',
    })
    handler,
  }).strict(true)
  .exitProcess(true)
  .demandCommand()
  .showHelpOnFail(false, 'Specify --help for available options')
  .help()
  .parse();
```

When passing the positional argument `"help"` to the command, it prints the help message instead of treating it as the positional argument...
Is that expected?

**Comment by mleguen** [comment]
Yes, it is expected. `.help()` creates both a `--help` option and a `help` command, so when you type `my-cli help`, the `help` command is triggered. See https://github.com/yargs/yargs/blob/master/docs/api.md#help

**Comment by crazyxhz** [comment]
Can I disable the positional help command, leave only `-h` and `--help` options?
