### ISSUE TITLE
Drop Node.js 8 and 13 support and add Node.js 14 and 15 support instead

### ISSUE THREAD

**Issue by mleguen** [yargs/yargs#1678]
- Node.js 8 and 13 are no longer maintained
- Node.js 8 is being dropped from yargs-parser
- Node.js 8 support prevents use from using latest versions of gts (for linting), eslint, and mocha
- etc.

**Comment by mleguen** [comment]
Do not forget :
- [ ] to upgrade the typescript target in `tsconfig.json` to es2017
- [ ] to look after To-dos in comments mentioning limitations of older versions of es or node

**Comment by xiaoxiangmoe** [comment]
@mleguen Add support for esm with conditional exports will be great.

**Comment by mleguen** [comment]
> Add support for esm with conditional exports will be great

@xiaoxiangmoe This is something we are talking about, and will be easier to do in a near future, as we are currently switching to typescript.

However, it will remain a tricky point as:
- we cannot stop publishing cjs modules before node 10 support is dropped (from memory, esm import is supported without experimental flags only from node 12)
- we do not want to double the package size by publishing both esm and cjs modules

So we are thinking about an intermediary step, with a node-only esm entrypoint (node-only as it would itself require cjs inner modules, as most of yargs would stay cjs until node 10 support is dropped).

**Comment by xiaoxiangmoe** [comment]
```js
import {argv} from 'yargs';
```
This will report an error in mjs.

```js
import yargs from 'yargs';
const {argv} = yargs;
```
But this will perform well.

Should we encourage everyone to use default import in mjs?

**Comment by xiaoxiangmoe** [comment]
> So we are thinking about an intermediary step, with a node-only esm entrypoint (node-only as it would itself require cjs inner modules, as most of yargs would stay cjs until node 10 support is dropped).

Are there any plans for this?

If I can know which modules we should export, I can submit a PR and write an index.mjs file.

**Comment by mleguen** [comment]
> If I can know which modules we should export, I can submit a PR and write an index.mjs file.

I'd like index.mjs to be a mix of current entrypoints: index.js and yargs.js. It should export:
- the singleton index.js exports as `yargs` (lowercase) not to change anything for people used to the singleton. By the way, you would have to refactor first Argv and singletonify into a separate `singleton` module in lib, as it would be used both in index.js and index.mjs
- our main function yargs.js exports as `Yargs` (uppercase)` for people not using the singleton

**Comment by bcoe** [comment]
@xiaoxiangmoe yargs now provides ESM support, documented in the README.md.

**Comment by bcoe** [comment]
Node 8 has been dropped, will swap 13 for 15 when it's released.
