### ISSUE TITLE
Consider renaming whitelist/blacklist in docs?

### ISSUE THREAD

**Issue by fiznool** [yargs/yargs#1685]
Other open source projects and organisations are renaming certain terms to avoid offence. Two such terms are whitelist and blacklist.

After reading through the source, I realise that the only reference to these terms are in the docs, so it might be prudent to alter the documentation to remove these terms altogether?

**Comment by fiznool** [comment]
I can see

**Comment by bcoe** [comment]
@fiznool would happily make this change, want to send a patch for where you saw this language?

**Comment by bcoe** [comment]
@fiznool docs have been updated, thank you for the recommendation.
