### ISSUE TITLE
.strict() works unexpectedly on macOS 11

### ISSUE THREAD

**Issue by BinarySoftware** [yargs/yargs#1688]
Hello,
I'm trying to solve an issue, where our app crashes while loading on macOS 11 beta, with yargs 15.3 (also tested with 15.4).
Here's the [code](https://github.com/enso-org/ide/blob/main/src/js/lib/client/src/index.js) - line 44. What's strange is that it all worked perfectly fine on all platforms, except on Big Sur.

## Expected result
Electron window opens

## Actual result
App crashes. Solved by commenting out `.strict()`

## Steps to reproduce:
- clone [IDE](https://github.com/enso-org/ide) repo
- install everything necessary according to [guideline](https://github.com/enso-org/ide/blob/main/docs/CONTRIBUTING.md)
- run `./run dist`
- open `Enso Studio.app` from ide/dist/client/mac
(You don't need to run the Enso Engine to open the electron window)

Thank you for looking at this issue! any help will really be appreciated!

**Comment by bcoe** [comment]
@BinaryBrain is there a stack trace you can provide? strict exits with the status code `1` rather than `0`, perhaps Big  Sur fails loudly on non-zero exit codes?
