### ISSUE TITLE
Missing CHANGELOG entry for v15.4.1?

### ISSUE THREAD

**Issue by willdurand** [yargs/yargs#1690]
Hi, npm has a version [15.4.1(https://www.npmjs.com/package/yargs/v/15.4.1) of this package listed but I don't find any reference to this version in the changelog or even a tag. Could you please tell us what has changed between `15.4.0` and `15.4.1`? Thanks!

**Comment by bcoe** [comment]
yargs@15.4.0 was published with decamelize@3.x.x which pulls in the whole unicode character set, making the library 12mb.

**Comment by bcoe** [comment]
this is now documented in releases.

**Comment by dlong500** [comment]
Was there a reason for not going with decamelize@4.x?  It dropped the xregexp dependency which I think is what caused it to be so large.  Just curious--I don't have any specific reason to need the later version.
