### ISSUE TITLE
yargs.js.org is broken, since there is no version tag for v15.4.1

### ISSUE THREAD

**Issue by aloisklink** [yargs/yargs#1691]
Hi!

I'm not sure if the yargs.js.org website is affiliated with you guys, but it's currently broken.

It seems to be detecting the current version of yargs as v15.4.1 from npm, but when it tries to download the markdown from https://raw.githubusercontent.com/yargs/yargs/v15.4.1/docs/api.md, it's getting a 404 not found error, since there isn't a v15.4.1 version release tag on GitHub.

Possibly related to #1690, since it looks like v15.4.1 is missing from this Git repo's package.json file as well.

## To fix

Make a git tag/release for v15.4.1.

**Comment by bcoe** [comment]
this is fixed now, thank you for the bug report.
