### ISSUE TITLE
Update  yargs-parser>=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2  

### ISSUE THREAD

**Issue by TANAYTAPANSHU** [yargs/yargs#1692]
This is the package.json file, I am getting one vulnerability  in my project 

 "dependencies": {
    "cliui": "^4.0.0",
    "decamelize": "^1.2.0",
    "find-up": "^3.0.0",
    "get-caller-file": "^1.0.1",
    "os-locale": "^3.0.0",
    "require-directory": "^2.1.1",
    "require-main-filename": "^1.0.1",
    "set-blocking": "^2.0.0",
    "string-width": "^2.0.0",
    "which-module": "^2.0.0",
    "y18n": "^3.2.1 || ^4.0.0",
    "yargs-parser": "^11.1.1"
  },

it showing to update yargs-parser >=13.1.2 <14.0.0 || >=15.0.1 <16.0.0 || >=18.1.2

**Comment by bcoe** [comment]
👋 hey @TANAYTAPANSHU it looks like  you'er on a fairly old version of `yargs-parser`, running:

```
npm i yargs-parserr@latest --save
```

Should do the trick for you.
