### ISSUE TITLE
yargs.command(module) signature missing in YargsInstance definition

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#1704]
I see that the source no longer declares the `command(module)` signature on `YargsInstance`, where you can pass a single options object describing the command.  Is this function signature intentionally being removed?

https://github.com/yargs/yargs/blob/master/lib/yargs.ts#L1449-L1456

I ask because it effects decisions I make writing yargs code.  If it's likely to be removed in the next release, I can avoid it.

**Comment by bcoe** [comment]
@mleguen can you speak to this design decision?

**Comment by mleguen** [comment]
>  Is this function signature intentionally being removed?

No, it isn't intentional.

It is something we will probably fix (by adding the missing signature) when aligning yargs.d.ts and yargs.ts

**Comment by mleguen** [comment]
I finally fixed this in #1707
