### ISSUE TITLE
Add missing /// <reference>s to ./typings/*

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#1705]
EDIT I was initially mistaken; I think the correct fix is to add `/// <reference>`s to the contents of `./typings/`.

This is only a bug if you intend for consumers of yargs to eventually be able to use the bundled `.d.ts` declarations instead of `@types/yargs`.  I don't know if you do or not.

Yargs imports modules which do not have type declarations.  With `"strict": true`, this is an error, which can be fixed by explicitly declaring those modules as dynamic.

```
// in a .d.ts file that you /// <reference>
declare module "require-directory";
declare module "y18n";
```
 
As far as I know, the best-practice for library authors is to declare `"strict": true` in their own tsconfig file.  This ensures their declarations will be compatible with consumers' projects.

**Comment by bcoe** [comment]
CC: @mleguen.

**Comment by mleguen** [comment]
@cspotcode , as I can see only a proposed solution here, could you please also describe the issue itself: what did you do? What did you expect to happen? What happened?

**Comment by cspotcode** [comment]
Here's a reproduction.  I don't know if you intend for yargs consumers to eventually use the bundled declarations emitted by tsc.  *Iff* you do, then you'll want to add `/// <reference>`s to the ./typings for require-directory, etc, to avoid the errors shown in the repro log.

https://github.com/cspotcode/repros/tree/yargs-declarations

**Comment by mleguen** [comment]
Thanks @cspotcode, I got it.

At the moment, ./typings was only a temporary dev artifact, and was not intended to be used by end users (we shouldn't publish types for third party modules). So this directory should disappear by moving its contents to `@type/xxx` modules before we publish our own index.d.ts.

However, feel free to make a PR to add `/// <reference>` to these temporary files if it helps alpha-testing our new types.

Also keep in mind `build/lib/yargs` is not intended to be an entrypoint of yargs, so its signature could change without notice.

**Comment by cspotcode** [comment]
Ok, good to know that you intend to eventually allow consumers to use the declarations emitted from `tsc`.  I assumed but wasn't sure.

When you eventually publish a version of yargs with stable bundled types, it will be exposed via something like this?

```
// index.d.ts
export {Foo, Bar, Baz} from './build/lib/yargs';
```

Are there any other tickets or discussions I should be following to stay up-to-date on your plans, changes to the declarations, etc?  Is there an "epic" to track the TS work?

**Comment by bcoe** [comment]
@cspotcode closing the loop here.  For the next major version of yargs at lest, I would like to not yet ship types with the library.

**Comment by cspotcode** [comment]
Understood; am I correct that the types will be omitted entirely from the
package, so I will not be able to refer to them even via `/// <reference>`?

**Comment by bcoe** [comment]
@cspotcode I think we can close this, since in `v16` we've opted to continue pointing users towards `@types/yargs`?

**Comment by bcoe** [comment]
Let me know if this is still an issue, cleaning up some old issues.
