### ISSUE TITLE
Road to ESM/Deno support 

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#1706]
With ESM modules [landing in Node 14](https://nodejs.org/api/esm.html), our ongoing effort to convert fully to TypeScript (which easily targets ESM), and Deno (which leverages ESM and TypeScript) reaching v1, **I think it's worth the effort to try to build yargs such that it targets all these environments**.

I did an initial [spike on yargs-parser](https://github.com/yargs/yargs-parser/pull/295) and was able to achieve this goal.

_Known limitations/challenges:_

* shipping both CJS and ESM increases the size of the package (_this limitation will go away in the future when ESM is more widely adopted and we can drop CJS_).
* TypeScript and Deno import files differently, which requires some fiddling during the build process.
* Deno, Node.js, and the browser have different standard libraries, which requires some additional fiddling...

All this said, I think it's a worthwhile goal to target these other environments. The work to be done is as follows.

### In Yargs Itself

- [x] [finish work converting yargs itself to TypeScript](https://github.com/yargs/yargs/issues/1586) (**@mleguen leading work**). _update: I'm happy with where we've landed for yargs' TypeScript conversion, even though it potentiallstill means pointing users towards `@types/yargs`._
- [x] target ESM/CJS in yargs. **in progress [see](https://github.com/yargs/yargs/pull/1708)**

### In Dependencies

- [x] convert yargs-parser to TypeScript/ESM/Deno (**thanks @QmarkC**).
- [x] convert y18n to TypeScript/ESM/Deno (**@bcoe/@QmarkC work in progress**).
- [x] pull small helper libraries into yargs (**which-module**, **set-blocking**, **require-main-filename**, **get-caller-file**) (**help wanted**).
- [x] ~**require-directory** will not work well with ESM, come up with plan for replacement (**help wanted**).~ for the next major version of yargs, I would like to finally tackle async functionality in a more holistic way. If you had to `await yargs.parse()`, then we can use Dynamic imports for this functionality.
- [x] **find-up** switched to [escalade](https://github.com/lukeed/escalade) which supports ESM.
- [x] convert **cliui** to TypeScript/ESM/Deno (**help wanted**). [see](https://github.com/yargs/cliui/pull/82).

CC: @QmarkC, @quilicicf

**Comment by bcoe** [comment]
@QmarkC let me know if you're interested in taking on any of these tasks, and we can toss our names next to them as we do the work.

**Comment by quilicicf** [comment]
I'll look around and see if I'm up to any of the tasks above but that'll have to wait until September, holidays are coming :) 
Glad to see this become a target for yargs though!

**Comment by quilicicf** [comment]
Awesome! 
I'll give it a spin ASAP thanks!

**Comment by quilicicf** [comment]
As for the terminal width, there have been discussions about it and I've taken the time to follow the thread. 

It's been implemented in Deno 1.3.1 but is still unstable. 

You can currently get the terminal size with: 

```js
Deno.consoleSize(Deno.stdout.rid); // returns something like { columns: 93, rows: 50 }
```

But you'd have to run the script with:

```js
deno run --unstable yourscript.ts
```

I have found no clue about whether/when this can land in the stable features but one can always ask :) 

> The PR that added the feature for reference: https://github.com/denoland/deno/pull/6520

There are other solutions but this is the most elegant as it will eventually be portable (I think it currently does not work on windows). You can for example use `Deno.run` like:

```js
const cmd = Deno.run({ cmd: [ 'tput', 'cols'], stdout:'piped' });
const columnsUintArray = await cmd.output();
const columnsString = new TextDecoder().decode(columnsUintArray);
cmd.close();
```

But you'll need to use something other than `tput` on systems that don't have it and it is hacky anyway :-(

**Comment by bcoe** [comment]
@quilicicf I was thinking we probably just wait for `consoleSize` to be stable?

**Comment by quilicicf** [comment]
This would be the safest option IMO too yes :+1: 
Deno seems to progress pretty fast, hopefully this won't take long. 
And it's fine for the port of yargs to Deno to follow Deno's own pace :-)

**Comment by tshinnic** [comment]
In beginning project with package.json "type": "module", I installed yargs@next "v16.0.0-deno.beta.1" (which I _think_ is "modified-api-surface"?)

Tried out `.command(module)` api, as indeed `require-directory` completely dependent on `module.require` and `.commandDir()` is unavailable.  The below is working for me:
```javascript
main.js:

import futhark from './futhark.js'
...
  .command(futhark)


futhark.js:

const command = 'futhark [rune]' 

const describe = 'rune faster'

const builder = {
//  elder: {
//    default: true
//  },
}

const handler = function (argv) {
  // do something with argv
  console.log('  futhark():', argv)
}

const module = {
  command,
  describe,
  builder,
  handler,
}

export default module
```

Thank you for this timely (for me anyway) work on enabling Yargs for ESM.

Will this issue be the center for news on ESM work? I barely caught the transition to 
`let argv = yargs(hideBin(process.argv)) ` ...

**Comment by bcoe** [comment]
> Will this issue be the center for news on ESM work? I barely caught the transition to

Yes, and I expect there will be a couple more beta releases before we publish for real.

**Comment by quilicicf** [comment]
@bcoe I tried taking Yargs for a spin with Deno and I'm facing some weird issue. 

My code runs OK when run via `deno run` but fails miserably when run via `deno install`. 

The trace:

```
deno install --allow-run --allow-read="$FORGE" index.ts
Download https://deno.land/std/fmt/colors.ts
...
Check file:///home/cyp/talend/forge/github/quilicicf/Gut/index.ts
error: TS2614 [ERROR]: Module '"https://deno.land/x/yargs@v16.0.0-deno.beta.1/deno"' has no exported member 'YargsType'. Did you mean to use 'import YargsType from "https://deno.land/x/yargs@v16.0.0-deno.beta.1/deno"' instead?
import { YargsType } from 'https://deno.land/x/yargs/deno.ts';
         ~~~~~~~~~
    at file:///home/cyp/talend/forge/github/quilicicf/Gut/src/commands/simple/pile.ts:1:10
...
+ Three more errors like the one above but in index.ts
```

> My code is here: https://github.com/quilicicf/Gut/tree/master_deno

I've had a look at the code and from https://deno.land/x/yargs@v16.0.0-deno.beta.1/deno and I don't have a clue what's going on ATM. Any idea? Or should I open an issue on Deno's repo?

**Comment by bcoe** [comment]
@quilicicf types are in their own file:

```ts
import yargs from 'https://deno.land/x/yargs/deno.ts'
import { Arguments, YargsType } from 'https://deno.land/x/yargs/types.ts'

yargs()
  .command('download <files...>', 'download a list of files', (yargs: YargsType) => {
    return yargs.positional('files', {
      describe: 'a list of files to do something with'
    })
  }, (argv: Arguments) => {
    console.info(argv)
  })
  .strictCommands()
  .demandCommand(1)
  .parse(Deno.args)
```

**Comment by quilicicf** [comment]
Ooooh, it's changed a bit since your [first code snippet](https://github.com/yargs/yargs/issues/1706#issuecomment-678673266) apparently. 
The Deno integration in IntelliJ is misleading here, I ctrl-clicked the import URL (https://deno.land/x/yargs/deno.ts) and it pointed me to what seems to be an old cached file that was exposing the types.
Thanks for the answer. I'll continue testing Yargs. Looks fine to me up to now :-)

**Comment by bcoe** [comment]
@tshinnic I would just install `16.0.0-beta.1`, the `Deno` version is just a tag that includes the `build` directory.

**Comment by bcoe** [comment]
this work is shipped in `v16`.

**Comment by ffMathy** [comment]
Doesn't work anymore. See #1794
