### ISSUE TITLE
Typescript typings manifest is missing a definition for "strictCommands" method.

### ISSUE THREAD

**Issue by chevtek** [yargs/yargs#1721]
![image](https://user-images.githubusercontent.com/874394/90974649-5d7a5580-e4ea-11ea-817f-68b7363fc405.png)

I've opened a PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46984

**Comment by bcoe** [comment]
@chevtek thank you for submitting the patch. Mind updating here when it lands?

**Comment by bcoe** [comment]
Going ahead and closing this, since it looks like it's being addressed upstream.
