### ISSUE TITLE
No index.js file present in yargs

### ISSUE THREAD

**Issue by jhechtf** [yargs/yargs#1723]
yargs got installed due to my usage of Ava. My yarn.lock file has the resolved version as 15.4.1

However, trying to use Ava breaks with the following error because the `yargs` directory in node_modules does not have an `index.js` file:

```
Error: Cannot find module 'C:\Users\Jim\projects\tailwind-shades\node_modules\yargs\index.js'. Please verify that the package.json has a valid "main" entry
    at tryPackage (internal/modules/cjs/loader.js:323:19)
    at Function.Module._findPath (internal/modules/cjs/loader.js:680:18)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1001:27)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (C:\Users\Jim\projects\tailwind-shades\node_modules\ava\lib\cli.js:7:15)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32) {
  code: 'MODULE_NOT_FOUND',
  path: 'C:\\Users\\Jim\\projects\\tailwind-shades\\node_modules\\yargs\\package.json',
  requestPath: 'yargs'
}
```

Below is a screenshot of the sidebar in my VSCode

![image](https://user-images.githubusercontent.com/8152471/91101608-4d629300-e61c-11ea-9fc2-f554bb3b2f8c.png)

The entry in the yarn.lock file, just in case it is necessary is

```
yargs@^15.3.1, yargs@^15.4.1:
  version "15.4.1"
  resolved "https://registry.yarnpkg.com/yargs/-/yargs-15.4.1.tgz#0d87a16de01aee9d8bec2bfbf74f67851730f4f8"
  integrity sha512-aePbxDmcYW++PaqBsJ+HYUFwCdv4LVvdnhBy78E57PIor8/OVvhMrADFFEDh8DHDFRv/O9i3lPhsENjO7QX0+A==
  dependencies:
    cliui "^6.0.0"
    decamelize "^1.2.0"
    find-up "^4.1.0"
    get-caller-file "^2.0.1"
    require-directory "^2.1.1"
    require-main-filename "^2.0.0"
    set-blocking "^2.0.0"
    string-width "^4.2.0"
    which-module "^2.0.0"
    y18n "^4.0.0"
    yargs-parser "^18.1.2"
```

I'm unsure where this error could be coming from, but it persists even in an entirely blank project whose only dependency is yargs@15.4.1

**Comment by jhechtf** [comment]
Hmm, I think this might have something to do with yarn more than yargs. I tried installing yargs through npm and it worked just fine. I'm looking through the yarn issues to see if this is reported anywhere else, but i find it weird that it is only the yargs library that this happens to. Will update as I know more.

**Comment by bcoe** [comment]
@jhechtf the `index.js` is definitely present in `15.4.1`:

```
npm notice 1.5kB  build/lib/completion-templates.js  
npm notice 6.2kB  build/lib/completion.js            
npm notice 1.1kB  index.js  
```

I'm going to assume this might have been a blip from a bad install.

Let me know if you continue to bump into issues.

**Comment by jhechtf** [comment]
Yeah, closing for now is a good idea. It seems to be working now, but it was occurring only with yargs every time I tried to install it for a few days on multiple machines. Unsure what seems to have changed, but it appears to work just fine now.
