### ISSUE TITLE
How to give an error if command not found?

### ISSUE THREAD

**Issue by Aminadav** [yargs/yargs#1731]
I have yargs with 2 commands?
```
yargs
.command('test-all','',handler)
.command('test-file','',handler)
.argv
```

The user inputs:
```
node myapp.js other-command
```

But `yargs` don't throw an error. What should I do?

https://stackoverflow.com/questions/63699184/in-yargs-npm-package-how-to-give-an-error-if-command-not-specfied

**Comment by bcoe** [comment]
@Aminadav if you use the setting `.strictCommands` it will throw on an unknown command 👍
