### ISSUE TITLE
(16.0.0 regression) Missing demandOption gives exit code 0, should be non-zero

### ISSUE THREAD

**Issue by dbjorge** [yargs/yargs#1740]
In <16.0.0, yargs exited with a non-zero exit code if a required option (`demandOption: true`) is omitted by a user. In 16.0.0, this no longer results in a non-zero exit code. Technically, [the API docs for demandOption](https://github.com/yargs/yargs/blob/master/docs/api.md#demandOption) do only guarantee that yargs exits in this scenario, not that it exits with any particular exit code, but I'm guessing/hoping this is unintentional since it isn't documented among the v16 changelog's breaking changes.

Minimal example:

`cli.js`
```js
require('yargs').option('foo', { demandOption: true }).argv;
```

With yargs 15.4.0 (working as expected):

```powershell
> npm install yargs@15.4.0
> node ./cli.js
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --foo                                                               [required]

Missing required argument: foo
> $LASTEXITCODE
1
```

With yargs 16.0.0 (regression):

```powershell
> npm install yargs@16.0.0
> node ./cli.js
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --foo                                                               [required]

Missing required argument: foo
> $LASTEXITCODE
0
```

Motivating test failure in our consuming repo in https://github.com/microsoft/axe-sarif-converter/pull/394

**Comment by bcoe** [comment]
@dbjorge thank you for the bug report, this will be fixed in `16.0.1`, which was just released.
