### ISSUE TITLE
v16.0.0 build fails due to rollup error

### ISSUE THREAD

**Issue by kevinoid** [yargs/yargs#1741]
If I run the following commands:
```sh
git clone https://github.com/yargs/yargs.git
cd yargs
npm install
```
The last command fails with the following error:

    > yargs@16.0.0 build:cjs /tmp/yargs
    > rollup -c rollup.config.cjs
    
    
    ./lib/cjs.ts → ./build/index.cjs...
    (!) Circular dependency
    lib/yargs-factory.ts -> lib/command.ts -> lib/yargs-factory.ts
    [!] Error: 'notStrictEqual' is not exported by ../node_modules/assert/assert.js, imported by lib/platform-shims/cjs.ts
    https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
    lib/platform-shims/cjs.ts (1:9)
    1: import { notStrictEqual, strictEqual } from 'assert'
                ^
    2: import * as processArgv from '../utils/process-argv.js'
    Error: 'notStrictEqual' is not exported by ../node_modules/assert/assert.js, imported by lib/platform-shims/cjs.ts
        at error (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:5211:30)
        at Module.error (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:9716:16)
        at handleMissingExport (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:9638:28)
        at Module.traceVariable (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:10111:24)
        at ModuleScope.findVariable (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:8670:39)
        at Identifier$1.bind (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:4116:40)
        at Property$1.bind (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:2844:23)
        at Property$1.bind (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:8284:15)
        at ObjectExpression.bind (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:2840:31)
        at ObjectExpression.bind (/tmp/yargs/node_modules/rollup/dist/shared/rollup.js:7975:15)

Bisection showed that ac6d5d105a75711fe703f6a39dad5181b383d6c6 is the first bad commit.

For reference, my system has node v12.18.3 and npm 6.14.8.

Let me know if I'm doing something wrong or if there is anything else I can do to help.

Thanks,
Kevin

**Comment by bcoe** [comment]
@kevinoid this seems like a misconfiguration in your local environment, it should not be looking for `assert` inside `node_modules`.

If you create a `test.mjs` like this:

**teset.mjs**

```
import { notStrictEqual, strictEqual } from 'assert'
```

Does it have the same issues?

**Comment by kevinoid** [comment]
I created `test.mjs` with the content you suggested.  If I run `./node_modules/.bin/rollup test.mjs` it completes successfully with the following output:

    test.mjs → stdout...
    (!) Unresolved dependencies
    https://rollupjs.org/guide/en/#warning-treating-module-as-external-dependency
    assert (imported by test.mjs)
    (!) Unused external imports
    notStrictEqual,strictEqual imported from external module 'assert' but never used

I'll try running the commands in a fresh VM to see if I can reproduce it there.

**Comment by kevinoid** [comment]
You were right, the problem was in my local environment.  The project in the parent directory had [assert](https://www.npmjs.com/package/assert) as a dependency, which gets picked up by rollup and causes the error.  Sorry for the noise!

**Comment by bcoe** [comment]
@kevinoid awesome \o/ glad you're able to compile again ... I don't love that `assert` found that dependency, I guess we might need to occasionally help folks who bump into that.

**Comment by kevinoid** [comment]
@bcoe Indeed.  I agree.  I wouldn't be surprised if it popped up in other places when a module on npm has the same name as a built-in.  It looks like the [CJS resolution algorithm](https://nodejs.org/api/modules.html#modules_all_together) matches built-in modules first (step 1) and the [ESM resolution algorithm](https://nodejs.org/api/esm.html#esm_resolution_algorithm) only matches built-in modules if they are not found (see `PACKAGE_RESOLVE` step 7-9).

(Although it looks like there might be a bug in rollup, since built-ins should be checked before parent directories in step 10 - but I could be reading that wrong.)
