### ISSUE TITLE
Should `deprecate/deprecated` be included in the docs and types?

### ISSUE THREAD

**Issue by NathanYocum** [yargs/yargs#1760]
https://github.com/yargs/yargs/blob/8aae3332251d09fa136db17ef4a40d83fa052bc4/yargs.js#L636

I see this was added in #1559 (added in v15.2.0) - but I don't see it listed in the docs in [option](http://yargs.js.org/docs/#api-reference-optionkey-opt)'s documentation or in `@types/yargs@15.0.5`.

It would be nice to use in my typescript project without a `@ts-ignore`

---

Relevant issue: #1518

**Comment by bcoe** [comment]
@NathanYocum we've opted to not ship types for yargs, so to add this to the type definition I suggest creating an issue on the `@types/yargs` definition in definitely typed.

I agree we should definitely document this feature in the API, if it hasn't been 😄 

I would happily take a patch for this.
