### ISSUE TITLE
yargs is throwing a ExperimentalWarning

### ISSUE THREAD

**Issue by kmadsen** [yargs/yargs#1763]
Cross posting this one https://stackoverflow.com/questions/63892611/yargs-is-throwing-a-experimentalwarning

How do you get rid of this experimental warning?

Here's a CLI to reproduce

[yargs-test.zip](https://github.com/yargs/yargs/files/5263018/yargs-test.zip)
```
➜  cd yargs-test
➜  npm install
➜  node index.js testing
Verified test
(node:67006) ExperimentalWarning: Conditional exports is an experimental feature. This feature could change at any time
```

index.js example
``` js
const argv = require('yargs')
    .command('testing', 'Simple test', (argv) => {
        console.log("Verified test")
    })
    .help()
    .demandCommand(1)
    .parse()
```

**Comment by cyungmann** [comment]
Looks to be caused by #1708. See also https://github.com/nodejs/node/issues/31819

**Comment by kmadsen** [comment]
thanks @cyungmann! experimental warning is gone. 

``` 
➜  node --version
v13.7.0
➜  ...
lots of commands to update my node
...
➜  node --version
v14.11.0
➜  node index.js testing
Verified test
```
