### ISSUE TITLE
typescript alias options not parsing off CommandModule in jest

### ISSUE THREAD

**Issue by joekiller** [yargs/yargs#1780]
I'm trying to test some modules of yargs and noticed in my jest tests that yargs didn't seem to be processing aliases on options like I expected. Below I expect the option 'flag' to end up making argv entries 'flag' and 'f', the alias. Instead it seems to not process the flag on my builder. How can I ensure my CommandModule tests work with alias options? PS is this the best way to drive this code path?

```
mkdir tmp/
cd tmp/
npm init -y
npm install jest typescript yargs ts-jest
```

jest.config.js
```
module.exports = {
	  transform: {'^.+\\.ts?$': 'ts-jest'},
	  testEnvironment: 'node',
	  testRegex: '.*\\.(test|spec)?\\.(ts|tsx)$',
	  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node']
};
```

yargs.test.ts
```
import yargs = require('yargs');
import { Arguments, CommandModule } from 'yargs';
const spyConsole = jest.spyOn(console, 'log').mockImplementation();

interface MyArgs extends Arguments {
  flag: string;
  f?: string;
}

const flagCmd: CommandModule = {
  command: 'flag it',
  describe: 'flag a flag',
  builder: {
    flag: {
      type: 'boolean',
      description: 'Boolean Flag',
      alias: 'f',
      default: false,
    },
  },
  handler: async (argv: MyArgs) => {
    console.log(JSON.stringify(argv));
  },
};

it('parses an alias for the test', async () => {
  await flagCmd.handler(yargs(['-f']).command(flagCmd).parse());
  expect(spyConsole.mock.calls.length).toBe(1);
  expect(spyConsole.mock.calls[0][0]).toContain('"f":true');
  expect(spyConsole.mock.calls[0][0]).toContain('"flag":true');
});

```

```
node node_modules/jest/bin/jest.js yargs.test.ts
# returns a fail because the "flag":true key is missing.
```

**Comment by bcoe** [comment]
@joekiller we rely on `@types/yargs` for our types, might be worth opening an issue on DefinitelyTyped too.

**Comment by joekiller** [comment]
With my newly discovered `onFinishCommand` this now works with the following:

```typescript
import * as yargs from 'yargs';
import { Arguments, CommandModule } from 'yargs';
const spyConsole = jest.spyOn(console, 'log').mockImplementation();

interface MyArgs extends Arguments {
  flag: string;
  f?: string;
}

const flagCmd: CommandModule = {
  command: 'flag',
  describe: 'flag a flag',
  builder: {
    flag: {
      type: 'boolean',
      description: 'Boolean Flag',
      alias: 'f',
      default: false,
    },
  },
  handler: async (argv: MyArgs) => {
    console.log(JSON.stringify(argv));
    return Promise.resolve(argv);
  },
};

it('parses an alias for the test', async (done) => {
  await new Promise((resolve, reject) => {
    try {
      yargs
        .command(flagCmd)
        .onFinishCommand(async (r) => resolve(r))
        .exitProcess(false)
        .parse('flag -f');
    } catch (e) {
      reject(e);
    }
  });
  expect(spyConsole.mock.calls.length).toBe(1);
  expect(spyConsole.mock.calls[0][0]).toContain('"f":true');
  expect(spyConsole.mock.calls[0][0]).toContain('"flag":true');
  done();
});

```

**Comment by bcoe** [comment]
@joekiller 👍 I'd like to make this a little more intuitive eventually, with the ability to do something like:

```
const parsed = await yargs.parse()
```

But it's a bit of an overhaul to get there.

**Comment by joekiller** [comment]
@bcoe yes I literally had to "async" everything on a project recently. It is a virus. Thanks for great attention you give to yargs.

**Comment by jltwheeler** [comment]
@joekiller / @bcoe any advice on how to best test error handling of async command handlers?

Example, if we had a command handler function like:

```ts
  handler: async (args: Arguments<args>): Promise<boolean> => {
    if (condition) {
      const result = await callAsyncFunc();
      console.log(result)
      return Promise.resolve(true);
    } else {
      return Promise.reject(
        new Error(
          "There was an error.",
        ),
      );
    }
  },
```

How could we best do this?

I've tried implementing @joekiller's code snippet above, but because it is setting `exitProcess(false)` jest can't seem to pick up that I'm throwing an error with a rejected promise i.e. by running await expect(someAsyncCommand).rejects.toThrow(Error)`.

However, if I don't set `exitProcess(false)`, yargs will exit the jest worker which then results in `process.exit called with "1"` shown in the terminal. Because yargs has exited the process, jest is then not able to execute the `expect`

Any advice would be much appreciated, thanks!

**Comment by joekiller** [comment]
I've only been able to spy the error console on the side otherwise I think
yargs will swallow it.

Sent via mobile

**Comment by joekiller** [comment]
So you want to spy the error instead of log console

const spyConsole = jest.spyOn(console, 'error').mockImplementation();

**Comment by jltwheeler** [comment]
> So you want to spy the error instead of log console
> 
> const spyConsole = jest.spyOn(console, 'error').mockImplementation();

Thanks for the speedy reply!!

Does that mean I should also add a console.error to my handler code (below) in order for the spy to work?

And does that mean that there is no way to test the rejected promise and the thrown error then?

```diff
  handler: async (args: Arguments<args>): Promise<boolean> => {
    if (condition) {
      const result = await callAsyncFunc();
      console.log(result)
      return Promise.resolve(true);
    } else {
+   console.error("There was an error")
      return Promise.reject(
        new Error(
          "There was an error.",
        ),
      );
    }
  },
```

**Comment by joekiller** [comment]
I believe the rejected promise message will regurgitate into the error log so that it should catch exceptions too

**Comment by joekiller** [comment]
@jltwheeler it appears you are correct that the handler will swallow the rejected promise. I've had to wrap my handlers in a generic catch to pick up errors in the test...

```
try {
  ...
} catch (e) {
console.trace(e)
}
```

**Comment by joekiller** [comment]
@jltwheeler If you chain in a [.fail(async (msg, err, yargs) => reject(err))](https://yargs.js.org/docs/#api-reference-failfn) handler in there and reject your test will pick up the error. hurray! It doesn't print it to log though (boo). But if you catch the error you can inspect it. 

Here is an updated example:

```typescript
import * as yargs from 'yargs';
import { Arguments, CommandModule } from 'yargs';
const spyConsole = jest.spyOn(console, 'log').mockImplementation();

let fail = false;
interface MyArgs extends Arguments {
  flag: string;
  f?: string;
}

const flagCmd: CommandModule = {
  command: 'flag',
  describe: 'flag a flag',
  builder: {
    flag: {
      type: 'boolean',
      description: 'Boolean Flag',
      alias: 'f',
      default: false,
    },
  },
  handler: async (argv: MyArgs) => {
    console.log(JSON.stringify(argv));
    if (fail) return Promise.reject(new Error('fail'));
    else return Promise.resolve(argv);
  },
};

export async function execCmd(cmd: CommandModule, args: string): Promise<void> {
  return new Promise((resolve, reject) => {
    return yargs
      .command(cmd)
      .onFinishCommand(async (r) => resolve(r))
      .fail((msg, err, yargs) => reject(err))
      .exitProcess(false)
      .parse(args);
  });
}

it('parses an alias for the test', async (done) => {
  fail = false;
  await execCmd(flagCmd, 'flag -f');
  expect(spyConsole.mock.calls.length).toBe(1);
  expect(spyConsole.mock.calls[0][0]).toContain('"f":true');
  expect(spyConsole.mock.calls[0][0]).toContain('"flag":true');
  fail = true;
  await expect(execCmd(flagCmd, 'flag -f')).rejects.toThrow(Error);
  done();
});

```

**Comment by joekiller** [comment]
Note that I could only attach the fail reject to my test handler, not to the real cmd as `.fail` rejecting the promise in the _real_ yargs handler yargs will blow up with an uncaught promise failure exception.

**Comment by jltwheeler** [comment]
Thanks @joekiller! So this method works perfectly with testing your command error handling in jest. When you say _It doesn't print it to log though (boo)_, do you mean when you come across the error when calling yargs normally (outside of jest), users aren't able to see the error message in their console? Or by wrapping your entire yargs process in a try and except, it is possible?
