### ISSUE TITLE
Documentation for commandDir?

### ISSUE THREAD

**Issue by shadowtime2000** [yargs/yargs#1786]
The current documentation for `commandDir` only specifies the parameters a usage would be nice because I can't seem to figure out how the commands inside of the folder are supposed to be structured.

**Comment by shadowspawn** [comment]
I see that `commandDir` is used in one of the examples which might help:
- https://github.com/yargs/yargs/blob/63e1173bb47dc651c151973a16ef659082a9ae66/example/command_hierarchy.js

(Example added in #1058)
