### ISSUE TITLE
bug: validation conflicts object should only run forEach on props

### ISSUE THREAD

**Issue by alisonailea** [yargs/yargs#1787]
I'm using a module which uses yargs as a dependency and it is passing in an empty object to yargs which is throwing an error at validation.ts:406

```
node_modules/yargs/build/lib/yargs.js:1132
                throw err;
                ^

TypeError: conflicting[key].forEach is not a function
```

adding `conflicting.hasOwnProperty(key)` to yargs solves the problem.

**Comment by bcoe** [comment]
@alisonailea would you be able to provide a minimal failing example? I'm curious as to how a user of the library would get into this situation (_we do our best to validate parameters as they're passed  to the API._)

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
