### ISSUE TITLE
Not working with Deno 1.5.1

### ISSUE THREAD

**Issue by ffMathy** [yargs/yargs#1794]
I ran the sample. Latest TypeScript, latest Deno.

`deno --version` yields:

> deno 1.5.1
> v8 8.7.220.3
> typescript 4.0.3

Code:

```typescript
import yargs from 'https://deno.land/x/yargs/deno.ts'
import { Arguments, YargsType } from 'https://deno.land/x/yargs/types.ts'

yargs(Deno.args)
  .command('download <files...>', 'download a list of files', (yargs: YargsType) => {
    return yargs.positional('files', {
      describe: 'a list of files to do something with'
    })
  }, (argv: Arguments) => {
    console.info(argv)
  })
  .strictCommands()
  .demandCommand(1)
  .argv
```

Command: `deno run main.ts`

Result:

> Check file:///C:/Users/Mathias%20Lorenzen/source/repos/cli/src/main.ts
> error: TS2305 [ERROR]: Module '"https://deno.land/x/cliui@v7.0.0-deno/build/lib/index.js"' has no exported member 'UIOptions'.
> import { cliui, UIOptions, UI } from './build/lib/index.js'
>                 ~~~~~~~~~
>     at https://deno.land/x/cliui@v7.0.0-deno/deno.ts:2:17
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs_parser@v20.2.0-deno/build/lib/common-types.js"' has no exported member 'Dictionary'.
> import type { Dictionary, KeyOf, ValueOf } from './common-types.js';
>               ~~~~~~~~~~
>     at https://deno.land/x/yargs_parser@v20.2.0-deno/build/lib/yargs-parser-types.d.ts:1:15
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs_parser@v20.2.0-deno/build/lib/common-types.js"' has no exported member 'KeyOf'.
> import type { Dictionary, KeyOf, ValueOf } from './common-types.js';
>                           ~~~~~
>     at https://deno.land/x/yargs_parser@v20.2.0-deno/build/lib/yargs-parser-types.d.ts:1:27
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs_parser@v20.2.0-deno/build/lib/common-types.js"' has no exported member 'ValueOf'.
> import type { Dictionary, KeyOf, ValueOf } from './common-types.js';
>                                  ~~~~~~~
>     at https://deno.land/x/yargs_parser@v20.2.0-deno/build/lib/yargs-parser-types.d.ts:1:34
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js"' has no exported member 'CommandInstance'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:1:10
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js"' has no exported member 'CommandHandler'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:1:27
> 
> TS2724 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js"' has no exported member 'CommandBuilderDefinition'. Did you mean 'isCommandBuilderDefinition'?
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:1:43
> 
>     'isCommandBuilderDefinition' is declared here.
>     export function isCommandBuilderDefinition(builder) {
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
>         at https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js:356:17
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js"' has no exported member 'CommandBuilder'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:1:69
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js"' has no exported member 'CommandHandlerCallback'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:1:85
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js"' has no exported member 'FinishCommandHandler'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:1:109
> 
> TS2724 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js"' has no exported member 'CommandHandlerDefinition'. Did you mean 'isCommandHandlerDefinition'?
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:1:131
> 
>     'isCommandHandlerDefinition' is declared here.
>     export function isCommandHandlerDefinition(cmd) {
>                     ~~~~~~~~~~~~~~~~~~~~~~~~~~
>         at https://deno.land/x/yargs@v16.1.0-deno/build/lib/command.js:353:17
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/common-types.js"' has no exported member 'Dictionary'.
> import { Dictionary, RequireDirectoryOptions, PlatformShim, RequireType } from './typings/common-types.js';
>          ~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:2:10
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/common-types.js"' has no exported member 'RequireDirectoryOptions'.
> import { Dictionary, RequireDirectoryOptions, PlatformShim, RequireType } from './typings/common-types.js';
>                      ~~~~~~~~~~~~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:2:22
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/common-types.js"' has no exported member 'PlatformShim'.
> import { Dictionary, RequireDirectoryOptions, PlatformShim, RequireType } from './typings/common-types.js';
>                                               ~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:2:47
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/common-types.js"' has no exported member 'RequireType'.
> import { Dictionary, RequireDirectoryOptions, PlatformShim, RequireType } from './typings/common-types.js';
>                                                             ~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:2:61
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/yargs-parser-types.js"' has no exported member 'ArgsOutput'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:3:10
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/yargs-parser-types.js"' has no exported member 'DetailedArguments'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:3:22
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/yargs-parser-types.js"' has no exported member 'Configuration'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:3:68
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/yargs-parser-types.js"' has no exported member 'Options'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:3:106
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/yargs-parser-types.js"' has no exported member 'ConfigCallback'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:3:132
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/typings/yargs-parser-types.js"' has no exported member 'CoerceCallback'.
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:3:148
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/usage.js"' has no exported member 'UsageInstance'.
> import { UsageInstance, FailureFunction } from './usage.js';
>          ~~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:5:10
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/usage.js"' has no exported member 'FailureFunction'.
> import { UsageInstance, FailureFunction } from './usage.js';
>                         ~~~~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:5:25
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/completion.js"' has no exported member 'CompletionFunction'.
> import { CompletionFunction } from './completion.js';
>          ~~~~~~~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:6:10
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/validation.js"' has no exported member 'ValidationInstance'.
> import { ValidationInstance, KeyOrPos } from './validation.js';
>          ~~~~~~~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:7:10
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/validation.js"' has no exported member 'KeyOrPos'.
> import { ValidationInstance, KeyOrPos } from './validation.js';
>                              ~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:7:30
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/middleware.js"' has no exported member 'MiddlewareCallback'.
> import { MiddlewareCallback, Middleware } from './middleware.js';
>          ~~~~~~~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:8:10
> 
> TS2305 [ERROR]: Module '"https://deno.land/x/yargs@v16.1.0-deno/build/lib/middleware.js"' has no exported member 'Middleware'.
> import { MiddlewareCallback, Middleware } from './middleware.js';
>                              ~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/build/lib/yargs-factory.d.ts:8:30
> 
> TS2739 [ERROR]: Type '{ middleware: (callback: any, applyBeforeValidation?: boolean, ...args: any[]) => any; scriptName(scriptName: any): ...; $0: any; getContext(): { resets: number; commands: never[]; fullCommands: never[]; files: never[]; }; ... 92 more ...; _runValidation(argv: any, aliases: any, positionalMap: any, parseErrors: any,...' is missing the following properties from type 'YargsInstance': customScriptName, parsed
>   return WrappedYargs(args);
>   ~~~~~~~~~~~~~~~~~~~~~~~~~~
>     at https://deno.land/x/yargs@v16.1.0-deno/deno.ts:9:3
> 
> Found 29 errors.

**Comment by ffMathy** [comment]
Hmmm this could also be why #1793 is failing.

**Comment by bcoe** [comment]
@ffMathy I haven't had a chance to dig into this yet, but it seems like there was a change in how Deno loads types that will need to be fixed in each dependency.

**Comment by ffMathy** [comment]
I unfortunately don't have time to fix this myself. Is there any chance you'll have time anytime soon?

**Comment by KhushrajRathod** [comment]
Hi!
I'm not completely sure what needs to be changed -- I'm willing to work on this if someone can give me a brief
:)

**Comment by toddwseattle** [comment]
So the deno sample in the readme still doesn't seem to work as the type of yargs is {}? working around by recasting to any but that's pretty ugly.  Would be happy to do something different if I'm not understanding.
