### ISSUE TITLE
High severity vulnerability detected in dependencies

### ISSUE THREAD

**Issue by kamalyzl** [yargs/yargs#1796]
A security assessment was performed and vulnerabilities were found to dependency sane

It is requested to update from version  " y18n": "^4.0.0" to " y18n": "^5.0.5"

reference:
https://github.com/yargs/yargs/blob/v15.0.0/package.json
https://github.com/yargs/y18n/pull/109

**Comment by bcoe** [comment]
Hey @kamalyzl, thanks for taking the time to open an issue. This bug has already been patched in the latest version of yargs and y18n,

**Comment by SymbioticKilla** [comment]
Can you update it in Version 15? Or it is EOL Version?
Thanks!

**Comment by bcoe** [comment]
@kamalyzl @SymbioticKilla, I've back ported the fix.

**Comment by SymbioticKilla** [comment]
@bcoe back ported means it will be also released for 15.x version?
