### ISSUE TITLE
in strict mode first part of dot-path option incorrectly marked as unknown

### ISSUE THREAD

**Issue by SkReD** [yargs/yargs#1811]
**Problem**
Error raised for part of the dot-path option key

**Example**
```
yargs('--obj.path 10')
  .usage('Usage: $0 [options]')
  .option('obj.path')
  .strict()
  .parse();
```

**What is actual behaviour**
Error `Unknown argument: obj` is raised

**What is expected behaviour**
No error

**How to reproduce**
Here is PR with failing test on the problem
https://github.com/yargs/yargs/pull/1810

**Comment by bcoe** [comment]
Hey @SkReD, thank you for opening this issue. See the [comment here](https://github.com/yargs/yargs/pull/1810#issuecomment-731770689), yargs doesn't support configuring individual properties on objects.

If you'd like to open a feature request on `yargs-parser`, this is something folks have requested in the past.
