### ISSUE TITLE
Is there a (built-in) way to make arg required unless other arg is present?

### ISSUE THREAD

**Issue by eponymous301** [yargs/yargs#1840]
Sort of a `demandUnless` or `impliesOptional` directive, e.g. contrived example:

```
# create new thing with name 'foo'
$ createNewThing --name "foo"  

# copy old thing
$ createNewThing --oldThingId 123  

# copy old thing but rename
$ createNewThing --name "foo"  --oldThingId 123 

$ createNewThing
--name is required unless --oldThingId is supplied
```

I'm guessing that the general way to handle this is by making a function and adding via  .check() at top level, but in my current project I've been defining options as JSON and using .options(myOpts), was hoping there was a way to do this directly within the definition of a single option, like:
```
{
  name: {
    demandUnless: "oldThingId",
    desc: "Name for new thing",
    type: "string"
  },
  oldThingId: {
    desc: "Name for new thing",
    type: "number"
  }
}  
```

**Comment by bcoe** [comment]
@eponymous301 I'd be tempted to implement this as a `.check()`:

https://github.com/yargs/yargs/blob/master/docs/api.md#checkfn-globaltrue

I'm hesitant to grow the validation API, if we can instead make sure that *check* works for these needs.

**Comment by eponymous301** [comment]
No worries, that's what I wound up doing.
