### ISSUE TITLE
Package subpath "./node_modules/yargs/package.json" is not defined by exports in undefined

### ISSUE THREAD

**Issue by YashTotale** [yargs/yargs#1843]
My rollup build is unable to resolve yargs. 

Here's the full error: 
> Plugin node-resolve: Could not resolve import "./src/cli/index.ts" in ".". Package subpath 
"./node_modules/yargs/package.json" is not defined by "exports" in undefined

Here's my [GitHub repository](https://github.com/gator-org/gator).

There's another issue (#1817) that referenced a similar problem, however, the fix for that one does not seem to work for this issue.

My Yargs version is `16.2.0`.

**Comment by bcoe** [comment]
@YashTotale I suggest opening an issue with rollup as well. As I don't know where to start investigating this, and yargs is working for our own usage of rollup.

If there's additional configuration I can add to the export map that helps, I'm happy to.

**Comment by YashTotale** [comment]
@bcoe I decided not to use Rollup and use Yargs' recommended [`@vercel/ncc`](https://www.npmjs.com/package/@vercel/ncc) to build and compile my project.

**Comment by bcoe** [comment]
@YashTotale 👍 sounds good, I'd still love to know what the heck is happening, I will need to dig into it at some point.

Is `ncc` working well?

**Comment by YashTotale** [comment]
Yeah, `ncc` is working great!
