### ISSUE TITLE
project module link to yargs on Windows attempts to run "rimraf build && tsc" and fails to find tsc

### ISSUE THREAD

**Issue by nikmalenovic** [yargs/yargs#1845]
I ran into a problem installing on a fresh installation of Windows (Version 10.0.19041.685 x64) using node (v15.5.0 x64) with npm (7.3.0). I installed yargs in global cache without problem, e.g.

```
C:\...>npm -g install yargs

added 16 packages, and audited 17 packages in 2s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```

but linking to my local project fails miserably because somehow yargs thinks it needs to recompile:

```
C:\...>npm link yargs
npm ERR! code 1
npm ERR! path C:\Users\...\AppData\Roaming\npm\node_modules\yargs
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c npm run compile
npm ERR! > yargs@16.2.0 compile
npm ERR! > rimraf build && tsc
npm ERR! 'tsc' is not recognized as an internal or external command,
npm ERR! operable program or batch file.
npm ERR! npm ERR! code 1
npm ERR! npm ERR! path C:\Users\...\AppData\Roaming\npm\node_modules\yargs
npm ERR! npm ERR! command failed
npm ERR! npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c rimraf build && tsc
npm ERR!
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2020-12-29T23_21_10_836Z-debug.log

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\...\AppData\Local\npm-cache\_logs\2020-12-29T23_21_10_877Z-debug.log
```

I've attached the complete log [2020-12-29T23_21_10_877Z-debug.log](https://github.com/yargs/yargs/files/5753105/2020-12-29T23_21_10_877Z-debug.log), but here's the key excerpt:

```
53 timing command:link Completed in 3683ms
54 verbose stack Error: command failed
54 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\@npmcli\promise-spawn\index.js:64:27)
54 verbose stack     at ChildProcess.emit (node:events:376:20)
54 verbose stack     at maybeClose (node:internal/child_process:1063:16)
54 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:295:5)
55 verbose pkgid yargs@16.2.0

```

subsequent `npm link yargs` seem to not error out, and yargs seems functional.

so, more of an annoyance then an actual problem?

**Comment by bcoe** [comment]
@nikmalenovic `tsc` is only required if you're cloning yargs and running in development mode; so this seems potentially like a bug with npm on Windows related to installing globally.

You could isntead run `npm i --production -g`, which would avoid running development dependencies.

In general though, I recommend not installing yargs globally, it should be a local dependency for a library (_I think you'll bump into all sorts of bugs having it installed globally on your system._)
