### ISSUE TITLE
strict() and strictCommands() do not appear to complain on unknown commands

### ISSUE THREAD

**Issue by biggianteye** [yargs/yargs#1861]
The documentation for `strict()` says that

> Unrecognized commands will also be reported as errors.

But this is not the behaviour I am seeing with version 16.2.0

Here is my test code:

```javascript
const yargs = require('yargs');

const argv = yargs.strict().argv;

console.log(argv);
```

In the above code, no commands or options are defined and so everything is unknown. Here is an example of an unknown command (`foo`) being accepted:

```
[burhan@enceladus yargs-test] {0} $ node index.js foo
{ _: [ 'foo' ], '$0': 'index.js' }
```

Unknown options behave as expected, based on the documentation. Here is an example of an unknown option (`--foo`) being treated as an error.

```
[burhan@enceladus yargs-test] {0} $ node index.js --foo
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Unknown argument: foo
```

Am I misunderstanding the `strict()` documentation? If so, how do I ensure that any unknown command is treated as an error?

**Comment by jly36963** [comment]
The check [here](https://github.com/yargs/yargs/blob/master/lib/validation.ts#L175) gets skipped because `currentContext.commands` is an empty array, and so is `commandKeys`. A few lines later, `unknown.length` is 0, so `usage.fail` never gets called.

I'll look into this tomorrow, hopefully I can figure out why this happens.

**Comment by jly36963** [comment]
@biggianteye Let me know if there's anything more to investigate/fix on this

**Comment by biggianteye** [comment]
> @biggianteye Let me know if there's anything more to investigate/fix on this

Looks good to me. 👍🏽
