### ISSUE TITLE
yargs v15.4 has a breaking change in a minor version

### ISSUE THREAD

**Issue by ljharb** [yargs/yargs#1862]
`npx publishers publishers` worked fine with yargs v15.1, v15.2, and v15.3, but v15.4.0 has broken it. It may be related to the major updates of yargs-parser (altho there's a major bump of yargs-parser in each yargs minor, and only v15.4 caused the problem).

I'm using `.command('*'`, in case that's relevant. (I can't upgrade to yargs 16, since that drops node 8, so hopefully a backport is possible here)

**Comment by shadowspawn** [comment]
I see publishers is no longer pinned, so closing this as stale. Sorry about the breakage, thanks for the report.

https://github.com/ljharb/publishers/blob/2927c9ea3130603cc56928dbcf51f9d66be01de1/package.json#L63

**Comment by ljharb** [comment]
Unfortunately this is not stale or resolved; it's no longer pinned because i shipped a breaking change that dropped these versions. It should still be fixed.

**Comment by shadowspawn** [comment]
This is a two year old issue for a yargs version from two major versions ago, without any explicit details about the nature of the failure. Implicitly it might be reproducible by trying `publishers publishers. I'll give it a try...

I cloned out publishers and tried changing yargs version in `package.json`. The tests pass and `publishers publishers` works with node 10. Nothing is output with node 8. But nothing is output with node 8 with yargs@15.3.0 either. (For me.)

Changing the close status, but sticking with closed!

```
publishers % n 8                                                                                                                                   main
     copying : node/8.17.0
   installed : v8.17.0 (with npm 6.13.4)
publishers % npm ls yargs                                                                                                                          main
publishers@2.0.1 /Users/john/Documents/Sandpits/publishers
├─┬ aud@2.0.2
│ ├─┬ libnpx@10.2.4
│ │ └── yargs@14.2.3 
│ └─┬ npm-lockfile@3.0.5
│   └── yargs@17.7.1 
├─┬ evalmd@0.0.19
│ └── yargs@3.32.0 
├─┬ nyc@15.1.0
│ └── yargs@15.4.1 
├─┬ safe-publish-latest@2.0.0
│ └── yargs@17.7.1 
└── yargs@15.0.0 

publishers % node bin/publishers publishers                                                                                                        main
publishers %                                                                                                                                       main
```

**Comment by ljharb** [comment]
Certainly if you can't check out https://github.com/ljharb/publishers/commit/0c9e3cf8f8336dc331d0a7a39c858937e9a42d73~1 and reproduce the issue on node 15.1, 15.2, or 15.3, then it should be closed. However, I can no longer reproduce the error - it's a shame it took over 2 years to get to - so perhaps it was fixed in the interim, and "closed" is appropriate.
