### ISSUE TITLE
Update y18n to version 5.0.5

### ISSUE THREAD

**Issue by kertsman** [yargs/yargs#1868]
Hello, could you , please, update y18n to version 5.0.5 because "black duck software" says it will be more secure. Thx

**Comment by bcoe** [comment]
The latest version of yargs, yargs@16.2.0, already has y18n set to `5.0.5`:

```
  "dependencies": {
    "cliui": "^7.0.2",
    "escalade": "^3.1.1",
    "get-caller-file": "^2.0.5",
    "require-directory": "^2.1.1",
    "string-width": "^4.2.0",
    "y18n": "^5.0.5",
    "yargs-parser": "^20.2.2"
  },
```

**Comment by bcoe** [comment]
If there is a specific version of yargs you would like to request a back port for, please leave a comment here #1839.
