### ISSUE TITLE
yargs.showHelp() not print all commands from the default command (*) handler.

### ISSUE THREAD

**Issue by adoyle-h** [yargs/yargs#1877]
I want to print the same help info when entering `cli` and `cli -h` in shell. But now it only prints options, no commands. How to achieve it?

Same case to https://github.com/yargs/yargs/issues/893#issuecomment-307696373 .

**Comment by OsmanAltun** [comment]
I think #1826 fixes this.

**Comment by shadowspawn** [comment]
This was likely fixed by #1826 (thanks @OsmanAltun  and @bcoe).

This issue has not had any activity in over six months.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
