### ISSUE TITLE
Question: two commands, one with positional arg, one without it

### ISSUE THREAD

**Issue by doitadrian** [yargs/yargs#1879]
I thought this was possible but it seems it's not working:

```
            yargs.command(
                "xyz",
                `Command 'xyz'`,
                yargs => {},
                () => {
                    console.log(`Run command 'xyz'`);
                }
            );

            yargs.command(
                "xyz <something>",
                `Command 'xyz <something>'`,
                yargs => {
                    yargs.positional("something", {
                        describe: `Project application folder`,
                        type: "string"
                    });
                },
                () => {
                    console.log(`Run command 'xyz <something>'`);
                }
            );
```

So, one command is `xyz`, and the other is `xyz <something>`.

No matter in which order these are, the second command will always get triggered.

Am I maybe missing something here?

I might do it just with a single command, and use `[something]` instead `<something>`, used in the example above. But just wanted to double-check.

Thank you! 🍺

**Comment by bcoe** [comment]
@doitadrian you can have subcommands on a single command, so you could have:

```
xyz subcommand
```

and configure these separately. But, you can't have the same command `xyz` both accept arguments and not accept arguments.

I would instead use `[something]` to indicate that the positional is optional, and have logic in your program that deals with the case where no positional argument is provided.

**Comment by doitadrian** [comment]
Thanks a lot @bcoe for the response.

I went with the `[something]`, but I also understand the solution you proposed here.

I will close this issue just so it doesn't create a mess.
