### ISSUE TITLE
How do I make Yargs exit if it is passed an invalid flag?

### ISSUE THREAD

**Issue by Zamiell** [yargs/yargs#1890]
Hello and thanks for the excellent library.
I am not sure if this is a Yargs feature or not, so I am asking here. I searched around and wasn't able to find anything at all!

The following is a Hello-World-style Yargs program.
By default, it includes `--help` and `--version`.
I am adding a 3rd option, `--copy`:

```typescript
const argv = yargs(process.argv.slice(2))
  .boolean("copy")
  .alias("c", "copy")
  .describe("c", "run the copy function")
  .argv;
```

However, running the program with a bogus flag (e.g. `--foo`) will still work. I want the program to throw an error and exit if an invalid flag is passed. How do I do this?

I know that I can manually iterate over the argv object and search for invalid flags, but that kind of defeats the purpose of using a library in the first place. (i.e. it violates DRY to have to specify the arguments twice)

**Comment by bcoe** [comment]
@Zamiell try setting [`.strictOptions()`](https://github.com/yargs/yargs/blob/master/docs/api.md#strictoptionsenabledtrue).

Let me know if this does the trick 👍

**Comment by bcoe** [comment]
@Zamiell I think that's a good suggestion 👍 mind submitting a patch with your recommendation for the docs?
