### ISSUE TITLE
Nested Sub-Commands don't follow through. 

### ISSUE THREAD

**Issue by seivan** [yargs/yargs#1905]
Running 
`$ mybin mycommand sub hello`
Will output `Missing required argument: command` 

```ts
Yargs
  .default(YargsHelper.hideBin(process.argv))
  .scriptName(ProjectPackage.name)
  .command("mycommand <command>", "", (yargs) => {
    return yargs
      .positional("command", {
        choices: ["sub", "some", "choices", "would-love-if-this-was-dynamic"],
      })
      .command("sub <other>", "", (otherYarg) => {
        return otherYarg
          .positional("other", { type: "string" })
        }, (args) => { })
```

This works if you remove the first `positional` under `mycommand` for `<command>`

I am just not sure how this is supposed to be, am I not allowed to have a positional for a subcommand to describe more or offer choices?

**Comment by bcoe** [comment]
```js
Yargs
  .default(YargsHelper.hideBin(process.argv))
  .scriptName(ProjectPackage.name)
  . strictCommands()
  .command("mycommand", "", (yargs) => {
    return yargs 
      .positional("command", {
        choices: ["sub", "some", "choices", "would-love-if-this-was-dynamic"],
      })
      .command("sub <other>", "", (otherYarg) => {
        return otherYarg
          .positional("other", { type: "string" })
        }, (args) => { })
```

☝️ if `mycommand` accepts additional commands, it should not use positionals. Instead you should be able to do something like above.

**Comment by seivan** [comment]
@bcoe Thanks for getting back so quickly.
Yes I did mention that 
> This works if you remove the first positional under mycommand for <command>


And that's what I've done now, but I am bit confused over the concept of positional. 
Shouldn't a subcommand be considered a positional? 

Since I'm getting the impression that this isn't a bug, could it be worth documenting? 

It's not unreasonable to assume that this would work: 
```ts
  .command("mycommand <sub>", "", (yargs) => {
    return yargs 
      .positional("sub", {
        type: ["string"],
      })
      .command("oneOftheSubs <other>", "", (otherYarg) => {
        return otherYarg
          .positional("other", { type: "string" })
        }, (args) => { })
```

Either way I'm closing the ticket since the impression I get, that this isn't a bug. 

Thanks for the help!

**Comment by bcoe** [comment]
@seivan I think it would be worth documenting, the fact that `positionals` behave like `options`, whereas commands are their own beast.

I think the behavior is correct, mainly because `<sub>` implies there would be a variable called `sub` with some value you've provided, whereas the behavior is actually that if the single constant value `oneOfthesubs` is provided, that command should execute.
