### ISSUE TITLE
coercion in yargs?

### ISSUE THREAD

**Issue by xgbuils** [yargs/yargs#191]
Is there something like [coercion](https://github.com/tj/commander.js?utm_source=jobboleblog#coercion) in yargs?

I want to use for [range arguments](http://stackoverflow.com/questions/31027744/cli-range-arguments-convention?answertab=votes#tab-top).

Thank you.

**Comment by xgbuils** [comment]
Hi?

I asked this because if this feature does not exists I'm interested to implement it. And, maybe, somebody could suggest the name of method. I don't like `coercion` name. I suggest `transform` method.

**Comment by bcoe** [comment]
Hey @xgbuils, haven't had a chance to dig into this issue yet but I'll be hacking on yargs a bit this weekend and will get you some feedback.

**Comment by xgbuils** [comment]
Thanks, @bcoe

**Comment by bcoe** [comment]
closing in favor of https://github.com/yargs/yargs/issues/535

let's actually tackle this!
