### ISSUE TITLE
Positional argument description does not show up with showHelp(), but works with --help

### ISSUE THREAD

**Issue by gardenappl** [yargs/yargs#1912]
As the title suggests:
```js
	.command("* [source]", __`Process HTML input`, (yargs) => { 
		yargs.positional("source", {
			desc: __`A file, an http(s) URL, or '-' for standard input`,
			type: "string"
		});
	})
```
With --help I get this:
```
index.js [source]

Process HTML input

Позиційні:
  source  A file, an http(s) URL, or '-' for standard input                                 [строка]
```
But with an explicit call to `showHelp()` I only get this:
```No input provided
index.js [source]

Process HTML input

Позиційні:
  source                                                                                    [строка]
```

(I explicitly call showHelp() whenever there is no [source] argument, and nothing is piped into stdin)

Tested with yargs 17.0.0-candidate.11, link to my [full source code is here](https://gitlab.com/gardenappl/readability-cli/-/blob/09fe1b8bdaf8271ea200dd86742c3a6b4da4ad06/index.js) in case that matters.

**Comment by bcoe** [comment]
@gardenappl fix published to `next` (`yargs@17.0.0-candidate.12`) let me know if you continue to find any issues.

**Comment by gardenappl** [comment]
Thanks for the fix

**Comment by Airkro** [comment]
description still missing when fail to parse

version: 17.0.1
