### ISSUE TITLE
Prevent sub-command name being populated in `args._`

### ISSUE THREAD

**Issue by ashutoshvarma** [yargs/yargs#1927]
It seems command names are also included in `argv._`, is there a way to prevent this?

I plan to use `argv._` as a means to store args that will be passed to another cli, like `npm run script -- scriptarg1 scriptarg2 ... scriptargn`.

For example,
```console
$ ./bin/test build --wat -- index.ts a a a c
{
  _: [ 'build', 'index.ts', 'a', 'a', 'c' ],
  '$0': 'bin/test',
  wat: true,
}
```

I have been using this kind of setup
```ts
  yargs
    .command(BuildCmd)
    .help()
    .parse();
```

```ts
export const BuildCmd: yargs.CommandModule = {
  command: "build",
  describe: "Compile a local package and all of its dependencies",
  aliases: ["compile", "make", "$0"],
  builder: (y) =>
    y
      .option("wat", {
        description: "Output wat file to outDir",
        default: false,
        boolean: true,
      })
  handler: (args) => {
    console.log(args)
  },
};
```

**Comment by bcoe** [comment]
@ashutoshvarma you can use the [populate--](https://github.com/yargs/yargs-parser#populate---) configuration setting to get the behavior you're looking for, it will populate `--` rather than `_` with everything after `--`.

Let me know if this does the trick for you 👍

**Comment by ashutoshvarma** [comment]
Yeah, that's exactly what I was look for
Thanks for the help !

**Comment by ashutoshvarma** [comment]
@bcoe Sorry for pinging you again
Can you tell me how can I set `yargs-parser.populate()`  from `yargs` itself?
