### ISSUE TITLE
how to bundle yargs with esbuild

### ISSUE THREAD

**Issue by hardfist** [yargs/yargs#1929]
It seems that esbuild will leave import.meta untouched when bundling, which make the bundle code not working for cjs format

**Comment by bcoe** [comment]
@hardfit could you provide a minimal example I could run, demonstrating the build process.

`import.meta` should only be used by the ESM version of yargs. If you instead bundle `build/index.cjs`, it does not expose `import.meta`.

**Comment by hardfist** [comment]
you can reproduce the problem here, https://github.com/hardfist/yargs-bundle
```
$ yarn install && yarn bundle && node bundle.js
```

**Comment by Wallacy** [comment]
FWIW: Change from `import yargs from 'yargs'` to `const yargs = require('yargs')` fix my bundle, but that is not ideal anyway.

**Comment by bcoe** [comment]
@Wallacy @hardfist perhaps we could add a guide in bundling, with this workaround for `esbuild`?

**Comment by baob** [comment]
Would this be the same problem I'm seeing as `Cannot resolve module ...../node_modules/yargs/index.cjs` ? when running flow against versions 16 & 17 of yargs ?

**Comment by bcoe** [comment]
Perhaps we should add an esbuild sample? anyone interested in contributing?

**Comment by xkn1ght** [comment]
@hardfist @Wallacy Any doc or reference about why this error occur? I got a familiar error.
My esbuild config is:
```
target: 'node14.17.4',
treeShaking: true,
platform: 'node',
format: 'cjs'
```
But the bundle contain `// node_modules/yargs/lib/platform-shims/esm.mjs`  
And then break in the next several line:
```js
var import_meta = {};
"use strict";
var REQUIRE_ERROR = "require is not supported by ESM";
var REQUIRE_DIRECTORY_ERROR = "loading a directory of commands is not supported yet for ESM";
var mainFilename = (0, import_url.fileURLToPath)(import_meta.url).split("node_modules")[0]; <----import_meta.url is undefined
```
I have no idea why esm file would appear in cjs bundle.
Actually the comment should occur in esbuild's issue or sth, but wondering might get some help here. Sorry about that.

**Comment by xkn1ght** [comment]
seems relative issue: https://github.com/evanw/esbuild/issues/1492
