### ISSUE TITLE
How to test parsers using Jest

### ISSUE THREAD

**Issue by akefirad** [yargs/yargs#1930]
Not sure if it's a bug or feature (of Jest perhaps?). I've got a simple prototype with subcommands (within a folder, just like the [example](https://github.com/yargs/yargs/blob/master/example/command_hierarchy.js)). Everything works just fine. I can use the parser and the output of the parser (err, output, and argv) is exactly what I expect:
```typescript
parser.parse("remote add foo bar", (err: Error, argv: Arguments<any>, output: string) => {
  console.log(JSON.stringify(argv));
  if (err) {
    console.log("ERROR\n" + err);
  }
  if (output) {
    console.log("OUTPUT\n" + output);
  }
});
```
However when I try to write a test, it seems that the parse doesn't see anything inside `cmds` folder, meaning for example it doesn't fail when the required positional parameters are missing:
```typescript
describe("remote", () => {
  test("add", async () => {
    const argv = parser.parse(
      "remote add foo bar",
      (err: Error, argv: Arguments<any>, output: string) => {
        console.log(JSON.stringify(argv));
        if (err) {
          console.log("ERROR\n" + err);
        }
        if (output) {
          console.log("OUTPUT\n" + output);
        }
      },
    );
    expect(argv.name).toEqual("foo");
    expect(argv.url).toEqual("bar");
  });
});
```
Again, if I put everything in the test file, it seems to work. It's just that with Jest, somehow the configuration in `cmds` directory doesn't get used.
What am I missing?
Thanks.

**Comment by bcoe** [comment]
@akefirad I think it might be better to open a question with the Jest folks, if this is working fine in isolation not using Jest.

Feel free to reference this issue, and there's anything that needs to change on yargs' side to accommodate.
