### ISSUE TITLE
yargs.command is not working (error msg: yargs.command is not a function)

### ISSUE THREAD

**Issue by ahmedsalah92** [yargs/yargs#1941]
I am trying to create yargs command, when I run the app I get an error.

When I run the following:
```
node app.js add
```
on my node.js code:
```
const yargs = require('yargs')
yargs.command({
    command:'add',
    describe:'Adding command',
    handler:function(){
        console.log('Adding notes')
    }
}).parse()

console.log('yargs.argv')
```

Error:

```
C:\node\notes-app\app.js:3
yargs.command({
      ^
**TypeError: yargs.command is not a function**
    at Object.<anonymous> (C:\node\notes-app\app.js:3:7)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
```
Yargs version:1.1.0
node version: v14.16.0
vs code version
1.55.2(user setup) OS:Window 10

**Comment by bcoe** [comment]
Hello @ahmedsalah92, yargs@1.1.0 is very old (_it was released 7 years ago_), and predates the addition of commands.

Try installing the latest version of yargs, `npm i yargs@ 17.0.1`, it should do the trick for you.

**Comment by ahmedsalah92** [comment]
@bcoe It worked! Thank you very much.

To explain why I used this old version: 
The latest version didn't work, So I used yargs@1.1.0 because this is the version that was used in the tutorial I am following.
