### ISSUE TITLE
How do I show choices without validating them?

### ISSUE THREAD

**Issue by khrome** [yargs/yargs#1942]
I have an array of algorithms I want to present to the user, but it's also legal to `+` the strings together. 

Ideally I'd like to have my own validation for the field, but just disabling the auto validation would be great and `.skipValidation()` does not seem to have any effect.

Suggestions?

**Comment by khrome** [comment]
I wound up building my own thing on top of yargs that rolls it's own choices, justifies it then stuffs it in the description. Not the most optimal solution, and def not a yargs fix... but it works for my use case. Close or keep open depending on your desire to cover this case in the future.

**Comment by bcoe** [comment]
@khrome I think for these advanced cases, my advice would be to try using yargs' custom check functionality, which allows you to provide your own validation for arguments.
