### ISSUE TITLE
How to build yargs parser for multiple executions?

### ISSUE THREAD

**Issue by OnkelTem** [yargs/yargs#1946]
I'm writing a program running as a service which should parse incoming commands.
So I don't parse them once when program starts. Instead I should process them multiple times using the same parser.
But the docs here suggest CLI usage only, and parser construction and execution phases are merged into one solid block:

```js
const y = yargs(input).command(...)....
```

How can I build the parser and then use it separately?

**Comment by karizma** [comment]
You already pretty much answered your question, just don't add an input or call .argv or .parse and save it to a variable.

Example:

```js
const cli = yargs.command({ ... }).scriptName('math');
```

**Comment by bcoe** [comment]
@karizma thank you for your help fielding this question.

@OnkelTem does this approach work for you? an alternative would be instantiating the parser each time:

```js
function parse(args) {
  const cli = yargs().command({
    command: "add <first> <second>",
    handler: (a) => console.log(a.first + a.second)
 });
  return cli.parse(args); // => 3
}
```

which has the advantage that there's no shared state between executions.

**Comment by shadowspawn** [comment]
An answer was provided (thanks @kitesi and @bcoe), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
