### ISSUE TITLE
Optionally create options based off typescript interface

### ISSUE THREAD

**Issue by ermish** [yargs/yargs#1951]
It would be awesome to be able to create options by passing in a typescript interface. 

It should be able to automatically pull:
- property name 
- value type
- required (optional)

It would still be missing default values, descriptions, etc. but would be great for simple projects!

**Comment by karizma** [comment]
I don't think this is possible. A typescript interface is not a real value, you can't pass it into a function or derive a real value from it.
You can pass it in as a generic but that still can't help you create the actual value.

Although I am not a typescript expert, so correct me if I'm wrong.

**Comment by ermish** [comment]
hmmm, I think you're right @karizma. I did some digging to see if you could compile an interface in any way, and it's not something realistically possible. 

Closing.
