### ISSUE TITLE
❓ Rename 'Positionals:' group?

### ISSUE THREAD

**Issue by rivy** [yargs/yargs#1954]
Is it possible to rename the 'Positionals:' group?

I don't see anything in the documentation; in reviewing the code, it looks like I'd need to replace the `getPositionalGroupName` function, but there's no API to do that...

**Comment by karizma** [comment]
`updateStrings()` should do the trick.

https://yargs.js.org/docs/#api-reference-updatestringsobj

**Comment by rivy** [comment]
Thank you kindly!
