### ISSUE TITLE
how to make a option, that doesnt require the -- prefix

### ISSUE THREAD

**Issue by devomaa** [yargs/yargs#1959]
basically what im tryign to do is
```
program convert FILE TOFILE
```
but i dont seem to find a method that can parse the arguments for this
if this exists, sorry for wasting your time!

**Comment by karizma** [comment]
Do you mean positional arguments?

You can use the command property to define positional arguments like this:

```js
yargs(process.argv.slice(2)).command({
        command: "convert <from-file> <to-file>",
        ...
});
```

The `<>` means the option is required, if you wanted it to be optional you would just wrap it in brackets instead: `[from-file]`

After that if you want to define properties for the option you can use [`#positional()`](https://yargs.js.org/docs/#api-reference-positionalkey-opt)

```js
yargs(process.argv.slice(2)).command({
	command: 'convert <from-file> <to-file>',
	builder: (y) => {
		return y
			.positional('from-file', {
				describe: 'the file you want to convert from',
				type: 'string',
			})
			.positional('to-file', {
				describe: 'the file you want to convert to',
				type: 'string',
			});
	},
	handler: (args) => {
		console.log(args);
	},
}).argv;
```

**Comment by devomaa** [comment]
oh, thanks! this is exactlly what i was looking for!
