### ISSUE TITLE
When convert script to exe with pkg , version result is unknown

### ISSUE THREAD

**Issue by salsan** [yargs/yargs#1969]
This is code I used for yargs

```
const yargs = require('yargs');
const argv = yargs
  .command('import [input]', 'import theme obs', {
    input: {
      description: 'insert path of theme want import',
      alias: 'i',
      type: 'string',
      default: 'theme.json',
    },
    output: {
      description: 'insert path where save',
      alias: 'o',
      type: 'string',
			default: ''
    }
  })
  .demandCommand(1, 'You need at least one command before moving on')
	.command('export', 'export your themes with files', {
    input: {
      description: 'insert path of theme want export',
      alias: 'i',
      type: 'string',
    },
    output: {
      description: 'insert path where save',
      alias: 'o',
      type: 'string',
      default: 'theme.json'
    }
  })
  .help()
	.showHelpOnFail(false, 'Specify --help for available options')
  .alias('help', 'h')
  .alias('version', 'v')
  .argv;
```
When try flag ( --version ) version from node return the right number 

> D:\dev\projects\otu>node otu.js --version
> 0.0.2

When try exe version created with [pkg ](https://github.com/vercel/pkg)( 4.4.9 version ) this is the result

> D:\dev\projects\otu>otu-win.exe --version
> unknown

**Comment by karizma** [comment]
Can you see what happens when you explicitly define the version by calling `version('0.0.2')`?

**Comment by salsan** [comment]
> Can you see what happens when you explicitly define the version by calling `version('0.0.2')`?

Show in terminal `0.0.2` as result, is as don't load correctly `package.json`

**Comment by salsan** [comment]
I solved the problem

I added  `"bin": "./otu.js"` on `package.json` and create exe with this command `pkg package.json`
