### ISSUE TITLE
Parameter `version` should not be allowed or should be overrided

### ISSUE THREAD

**Issue by giovanni-bertoncelli** [yargs/yargs#1979]
Yargs behaves unexpectedly when declaring a parameter named `version`, like this:

```javascript
const { argv } = require('yargs')
  .string('version')
  .alias('version', 'v')
  .describe('version', 'Target version')
```

Usually in the result you get that `argv.version` is always false and the parameter passed gets hyphenated, like this:
```bash
node . --version abc
```

```javascript
{"_": ["abc"], "version": false}
```

I think this parameter does not correctly override the default `version` parameter expected by yargs. It should be returned a warning for the default behaviour to be overridden or it should return an error if that parameter should not be overridden.

**Comment by bcoe** [comment]
@giovanni-bertoncelli, @jly36963 has added a descriptive warning that will help prevent someone using yargs from falling into this trap (_suggesting that folks either turn off the automatic version behavior, or rely on its default behavior_).

**Comment by xkn1ght** [comment]
actually it did have a way to mock version global and mainwhile maintain subcommand --version functional.https://github.com/yargs/yargs/issues/1918
