### ISSUE TITLE
 Error: Missing required argument #1

### ISSUE THREAD

**Issue by natasha1234567890** [yargs/yargs#1980]
natalia@ubuntu-client:~/f5-apm-schema/templates/src/samlsp$ sudo npm install -g yargs
▐ ╢░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 4.15.0-143-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "yargs"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:190:5
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
npm ERR! typeerror     at Array.forEach (<anonymous>)
npm ERR! typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
npm ERR! typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/natalia/f5-apm-schema/templates/src/samlsp/npm-debug.log
----------------------------------------------------------------------------------
[npm-debug.log](https://github.com/yargs/yargs/files/6772151/npm-debug.log)

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'install', '-g', 'yargs' ]
2 info using npm@3.5.2
3 info using node@v8.10.0
4 silly loadCurrentTree Starting
5 silly install loadCurrentTree
6 silly install readGlobalPackageData
7 silly fetchPackageMetaData yargs
8 silly fetchNamedPackageData yargs
9 silly mapToRegistry name yargs
10 silly mapToRegistry using default registry
11 silly mapToRegistry registry https://registry.npmjs.org/
12 silly mapToRegistry uri https://registry.npmjs.org/yargs
13 verbose request uri https://registry.npmjs.org/yargs
14 verbose request no auth needed
15 info attempt registry request try #1 at 11:47:06 AM
16 verbose request id 76b6f104e01d66ec
17 verbose etag W/"fb618b4373642969b833551dc8b92d34"
18 verbose lastModified Mon, 03 May 2021 23:57:26 GMT
19 http request GET https://registry.npmjs.org/yargs
20 http 304 https://registry.npmjs.org/yargs
21 verbose headers { date: 'Tue, 06 Jul 2021 18:47:06 GMT',
21 verbose headers   connection: 'keep-alive',
21 verbose headers   'cf-ray': '66aaffea296f211b-SJC',
21 verbose headers   age: '1094',
21 verbose headers   'cache-control': 'public, max-age=300',
21 verbose headers   etag: '"fb618b4373642969b833551dc8b92d34"',
21 verbose headers   'last-modified': 'Mon, 03 May 2021 23:57:26 GMT',
21 verbose headers   vary: 'Accept-Encoding',
21 verbose headers   'cf-cache-status': 'HIT',
21 verbose headers   'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
21 verbose headers   server: 'cloudflare' }
22 silly get cb [ 304,
22 silly get   { date: 'Tue, 06 Jul 2021 18:47:06 GMT',
22 silly get     connection: 'keep-alive',
22 silly get     'cf-ray': '66aaffea296f211b-SJC',
22 silly get     age: '1094',
22 silly get     'cache-control': 'public, max-age=300',
22 silly get     etag: '"fb618b4373642969b833551dc8b92d34"',
22 silly get     'last-modified': 'Mon, 03 May 2021 23:57:26 GMT',
22 silly get     vary: 'Accept-Encoding',
22 silly get     'cf-cache-status': 'HIT',
22 silly get     'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
22 silly get     server: 'cloudflare' } ]
23 verbose etag https://registry.npmjs.org/yargs from cache
24 verbose get saving yargs to /home/natalia/.npm/registry.npmjs.org/yargs/.cache.json
25 silly install normalizeTree
26 silly loadCurrentTree Finishing
27 silly loadIdealTree Starting
28 silly install loadIdealTree
29 silly cloneCurrentTree Starting
30 silly install cloneCurrentTreeToIdealTree
31 silly cloneCurrentTree Finishing
32 silly loadShrinkwrap Starting
33 silly install loadShrinkwrap
34 silly loadShrinkwrap Finishing
35 silly loadAllDepsIntoIdealTree Starting
36 silly install loadAllDepsIntoIdealTree
37 verbose stack Error: Missing required argument #1
37 verbose stack     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
37 verbose stack     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
37 verbose stack     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
37 verbose stack     at /usr/share/npm/lib/install/deps.js:190:5
37 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
37 verbose stack     at Array.forEach (<anonymous>)
37 verbose stack     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
37 verbose stack     at Array.forEach (<anonymous>)
37 verbose stack     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
37 verbose stack     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
38 verbose cwd /home/natalia/f5-apm-schema/templates/src/samlsp
39 error Linux 4.15.0-143-generic
40 error argv "/usr/bin/node" "/usr/bin/npm" "install" "-g" "yargs"
41 error node v8.10.0
42 error npm  v3.5.2
43 error code EMISSINGARG
44 error typeerror Error: Missing required argument #1
44 error typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
44 error typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
44 error typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
44 error typeerror     at /usr/share/npm/lib/install/deps.js:190:5
44 error typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:35
44 error typeerror     at Array.forEach (<anonymous>)
44 error typeerror     at /usr/share/npm/node_modules/slide/lib/async-map.js:52:11
44 error typeerror     at Array.forEach (<anonymous>)
44 error typeerror     at asyncMap (/usr/share/npm/node_modules/slide/lib/async-map.js:51:8)
44 error typeerror     at exports.loadRequestedDeps (/usr/share/npm/lib/install/deps.js:188:3)
45 error typeerror This is an error with npm itself. Please report this error at:
45 error typeerror     <http://github.com/npm/npm/issues>
46 verbose exit [ 1, true ]

**Comment by bcoe** [comment]
👋 Hello @natasha1234567890 this looks like an issue with `npm` and not yargs.

Having said this, I would suggest not installing yargs with the `-g` flag, or using `sudo`. Instead, in your project folder with a local `node_modules`, simply type:

`npm i yargs`

This will add `yargs` as a dependency to your project. Let me know if this helps.

**Comment by natasha1234567890** [comment]
thanks
