### ISSUE TITLE
Default values and options with dashes not working

### ISSUE THREAD

**Issue by nylen** [yargs/yargs#20]
Originally reported by @Krinkle at https://github.com/chevex/yargs/commit/898ad06983af0b0768ae642ecbcdb9bf68b315a2#commitcomment-6581926

[A previous change to turn options with dashes into camelCased properties] doesn't cover default values, leading to confusing/inconsistent behaviour.

```
var yargs = require('yargs');

var arg = yargs.usage('Example.\nUsage: $0')
    .option('server-port', {
        desc: 'Port for socket.io server to listen on',
        default: 20080
    })
    .argv;

console.log(arg.serverPort);
```

```
$ node index.js
undefined

$ node index.js --server-port 8080
8080
```

**Comment by mikermcneil** [comment]
@nylen seeing this in values with dashes, e.g.

```bash
machinepack exec get-price-estimate --apiKey='asdg' --startLatitude='123' --startLongitude='23' --endLatitude='-13' --endLongitude='13'
```

**Comment by mikermcneil** [comment]
(e.g. `-13` gets parsed as two separate options: `3: true` and `1:true`, while `endLatitude` ends up being `true` as well)

**Comment by nylen** [comment]
@mikermcneil that looks like something different, open a new issue.
