### ISSUE TITLE
eslint conflicts with yargs

### ISSUE THREAD

**Issue by rostyslavnikitin** [yargs/yargs#2002]
When I'm trying to lint file that contains yargs import

`const { hideBin } = require("yargs/helpers");
`

I getting errors:

```
Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read property 'split' of undefined

Occurred while linting index.js:5 // pointer to yargs import
```

So I need to ignore such files

* eslint & yargs versions is latest

**Comment by rostyslavnikitin** [comment]
still actual

**Comment by rostyslavnikitin** [comment]
or

```
const yargs = require("yargs/yargs");
const helpers = require("yargs/helpers");
```


> ./node_modules/.bin/eslint yargsTest.js 

```
Oops! Something went wrong! :(

ESLint: 7.32.0

TypeError: Cannot read property 'split' of undefined
```

**Comment by bcoe** [comment]
@rostyslavnikitin can you confirm whether this fixed things? wondering if I can close.

**Comment by rostyslavnikitin** [comment]
> @rostyslavnikitin can you confirm whether this fixed things? wondering if I can close.

yep
