### ISSUE TITLE
[Question] More adequite way to use with TS

### ISSUE THREAD

**Issue by btd** [yargs/yargs#2008]
Hi,

could you clarify for me like what is expected use with ts (4.3.5):
```ts
const argv2 = yargs(hideBin(process.argv))
  .options({
    title: {
      describe: "Output file title",
      type: "string",
      default: "Title",
    },
  })
  .help().argv;

/* infered type
const argv2: {
    [x: string]: unknown;
    title: string;
    _: (string | number)[];
    $0: string;
} | Promise<{
    [x: string]: unknown;
    title: string;
    _: (string | number)[];
    $0: string;
}>
*/
```

and now the thing that is very unclear - i need to do type assertion to check that returned type is actually not a promise.

It is a bit not clear why i need to do it if i clearly do not use any async here. Maybe split api for async and not-async version?

**Comment by bcoe** [comment]
@btd `.parseSync` was added as an alternative to `.argv`, if you know that you won't be returning a Promise.

**Comment by btd** [comment]
Thank you, i will try

**Comment by btd** [comment]
Yep it works, thanks again.
