### ISSUE TITLE
How to require a path for a command?

### ISSUE THREAD

**Issue by waynebloss** [yargs/yargs#201]
What is the proper way to setup a path argument that does not have a key, but which is required by a command?

Here is the syntax for my program. Currently I'm adding the path usage via the yargs ~~`epilogue`~~ `usage` function. That is all yargs knows about the path, so it ends up in the `_` array. I'd rather not go fishing in that array if I don't have to, but when I tried using `required` and `demand` methods, it just ate the path and didn't put it anywhere in `argv`.

```
> staticbuild -h
staticbuild v0.2.5 - Static front-end build tools with an Express development server, 
Less, Nunjucks and Gulp.

Usage:
  staticbuild <command> [options]

Commands:
  dev    Run the development web server.
  setup  Setup a new project.

Options:
  -v, --version  Show version number.  [boolean]
  -V, --verbose  Enables verbose output.
  -h, --help     Show help.  [boolean]
```

```
> staticbuild dev -h
staticbuild v0.2.5 - Development server.

Usage:
  staticbuild dev [options] <path>

Options:
  -n, --norestart      Disables the built-in nodemon server restart.  [boolean]
  -r, --restart-delay  Number of seconds to delay nodemon restarts.
  -h, --help           Show help.  [boolean]

  path           Path to a staticbuild.json file or directory to find one.
                 If no path is supplied, the current directory is used.
```

And here is the relevant code from [my yargs lab](https://github.com/devoptix/staticbuild/blob/master/test/try-yargs.js).

``` javascript
var Yargs = require('yargs');

function configureYargs(yargs) {
  yargs = yargs || Yargs;
  return yargs.wrap(null);
}

function run() {
  argv = configureYargs()
  .usage(mainUsage())
  .version(titleVersion(), 'v', 'Show version number.')
  .alias('v', 'version')

  .command('dev', 'Run the development web server.', runDevServer)

  .command('setup', 'Setup a new project.', runSetup)

  .option('V', {
      alias: 'verbose',
      description: 'Enables verbose output.'
    })

  .help('h', 'Show help.').alias('h', 'help')
  .argv;

  console.dir(argv);
}

function runDevServer(yargs) {
  argv = configureYargs(yargs)
  .usage(commandUsage('dev', '[options] <path>', 'Development server.'))
  .option('n', {
    alias: 'norestart',
    description: 'Disables the built-in nodemon server restart.',
    type: 'boolean'
  })
  .option('r', {
    alias: 'restart-delay',
    description: 'Number of seconds to delay nodemon restarts.',
    type: 'number'
  })
  .help('h', 'Show help.').alias('h', 'help')
  .epilogue('  path           Path to a staticbuild.json file or directory to find one.\n' +
'                 If no path is supplied, the current directory is used.')
  .argv;

  console.log('running dev server...');

}
```

**Comment by waynebloss** [comment]
I am just using `_` array for now and here's what I came up with to document it - I tacked a new "Required:" section below "Usage:" instead of documenting it at the end with `epilogue`.

```javascript
function runDevServer(yargs) {
  var requirements = [
    '\n',
    'Required:',
    '  path           Path to a staticbuild.json file or directory to find one.',
    '                 If no path is supplied, the current directory is used.'
  ].join('\n');

  argv = configureYargs(yargs)
  .usage(commandUsage('dev', '[options] <path>' + requirements, 'Development server.'))
  .option('n', {
    alias: 'norestart',
    description: 'Disables the built-in nodemon server restart.',
    type: 'boolean'
  })
  .option('r', {
    alias: 'restart-delay',
    description: 'Number of seconds to delay nodemon restarts.',
    type: 'number'
  })
  .help('h', 'Show help.').alias('h', 'help')
  .argv;
  
  console.log('running dev server...');
  
  if (argv._.length < 2)
    console.error('Path required. See `staticbuild dev -h`.');
  argv.path = argv._[1];

  console.log('Operating on path: ' + argv.path);
  console.log('');
}
```
and here's how it looks
```
> staticbuild dev -h
staticbuild v0.2.5 - Development server.

Usage:
  staticbuild dev [options] <path>

Required:
  path           Path to a staticbuild.json file or directory to find one.
                 If no path is supplied, the current directory is used.

Options:
  -n, --norestart      Disables the built-in nodemon server restart.  [boolean]
  -r, --restart-delay  Number of seconds to delay nodemon restarts.
  -h, --help           Show help.  [boolean]
```

**Comment by waynebloss** [comment]
So, that's good enough for me right now. I was just wondering if there was a better way to do it. Thanks!

**Comment by bcoe** [comment]
@waynebloss I'll get you some feedback this weekend, going to put in a yargs hacking day.

**Comment by wraithan** [comment]
I'm in a similar boat. I'd like to be able to set a default and a describe for the positional args. Without looking at the docs I tried:

```
yargs.describe('_', 'Directories to search in')
yargs.default('_', process.cwd, 'Current working directory')
```

Figuring that it would state it for the positional args. Also figured because it would call the function you hand to it for a value that the `process.cwd` thing would work. Might try to do something like what @waynebloss did to work around.

**Comment by bcoe** [comment]
@wraithan, @waynebloss what about a syntax like this:

```js
yargs.describe('_.0', 'working directory');
yargs.default('_.0', process.cwd());
yargs.describe('_.1', 'file to modify');
// and so on.
```

I think this could be pretty slick?

**Comment by wraithan** [comment]
In my case I'd like to say that anything that is grabbed as a positional argument is a directory to search. So I'd rather have it be on the `_` instead of a specific position of `_`, that said, I can see why that API is appealing for other use cases.

**Comment by waynebloss** [comment]
@bcoe Any way you do it is fine with me, I was just trying to find out if there was an official way that I had missed.

Originally, I expected that yargs would let me to give names to the expected paths just like it does for flags. Otherwise, I just do it myself, for instance `args.path = args._[1];` (from [my project](https://github.com/devoptix/staticbuild/blob/master/lib/bincmd/cli.js#L156)).

**Comment by bcoe** [comment]
@waynebloss @wraithan do you think it would be sufficient to be able to document `_`?

```js
yargs.option('_', {
  default: ['./foo.json']
  describe: 'perform some sort of action on this path'
})
```

**Comment by wraithan** [comment]
@bcoe that looks fantastic to me! Exactly matches my use case.

**Comment by waynebloss** [comment]
@bcoe Looks good!

**Comment by bcoe** [comment]
you can now describe both positional arguments and default arguments, I think these features in conjunction should address this old issue:

https://github.com/yargs/yargs/blob/master/docs/advanced.md#default-commands
