### ISSUE TITLE
bundle with esbuild fails because `yargs/yargs` does not have file extension

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#2014]
Possible duplicate of #1929 but I'm not sure because that ticket is too vague.

esbuild determines content types based on file extension.  [esbuild docs](https://esbuild.github.io/content-types/)

But [yargs/yargs](https://unpkg.com/yargs@17.1.1/yargs) does not have a file extension.

This raises an error:

```
$ echo 'import createYargs from "yargs/yargs";' | yarn esbuild --bundle --loader=js
 > <stdin>:1:24: error: Do not know how to load path: node_modules/yargs/yargs
    1 │ import createYargs from "yargs/yargs";
      ╵                         ~~~~~~~~~~~~~

1 error
```

**Comment by bcoe** [comment]
> Do you have a link to the issues or PRs where this decision was discussed?

@cspotcode no, this design grew organically while trying to support both CJS and ESM in the same module.

The approach is discussed, without much detail, [here](https://dev.to/bcoe/esm-doesn-t-need-to-break-the-ecosystem-4p8b).

Open to other approaches as long as all existing tests continue working, and we verify functionality on all supported Node runtimes.

**Comment by bcoe** [comment]
In the next major I'll look at dropping the `yargs/yargs` hack.

**Comment by Creative-Difficulty** [comment]
> > Do you have a link to the issues or PRs where this decision was discussed?
> 
> @cspotcode no, this design grew organically while trying to support both CJS and ESM in the same module.
> 
> The approach is discussed, without much detail, [here](https://dev.to/bcoe/esm-doesn-t-need-to-break-the-ecosystem-4p8b).
> 
> Open to other approaches as long as all existing tests continue working, and we verify functionality on all supported Node runtimes.

For me This worked!

**Comment by hongaar** [comment]
This should be fixed with https://github.com/yargs/yargs/pull/2151 (note this fix is only available from NPM after https://github.com/yargs/yargs/pull/2185 is merged & released)

**Comment by JuanCruzTrinidad** [comment]
Hello!
I am here to share my solution.
You can get around this error by using the following esbuild plugin:[ esbuild-plugin-alias](https://www.npmjs.com/package/esbuild-plugin-alias)
With the plugin, you can alias some file call, like this:
![image](https://user-images.githubusercontent.com/53027244/199977024-4959f6f7-1ca6-451f-9ab1-b63e86b44ca4.png)

**Comment by bcoe** [comment]
I believe there are a couple workaround in this thread now, also @hongaar's update was merged and released.

**Comment by LuisAzeved** [comment]
I'm using puppeteer and I have this error:

`ERROR: Do not know how to load path: ../../node_modules/@puppeteer/browsers/node_modules/yargs/yargs`

It fails on this line:

`const yargs_1 = __importDefault(require("yargs/yargs"));`

Any idea on how to fix this?

**Comment by shadowspawn** [comment]
You have a different problem @LuisAzeved than this issue is about. Would you please open a new issue, and include how you are including yargs in your code. (The example line you gave is useful but looks like from the transpired code.)

**Comment by chrisowebb** [comment]
@LuisAzeved did you manage to fix your issue?

**Comment by DanielJSottile** [comment]
> I'm using puppeteer and I have this error:
> 
> `ERROR: Do not know how to load path: ../../node_modules/@puppeteer/browsers/node_modules/yargs/yargs`
> 
> It fails on this line:
> 
> `const yargs_1 = __importDefault(require("yargs/yargs"));`
> 
> Any idea on how to fix this?
> 
> Some relevant files:
> 
> tsconfig.json
> 
> ```
>   {
>   "extends": "../../tsconfig.base.json",
>   "compilerOptions":  { 
>      
>     "jsx": "react-jsx",
>     /* Language and Environment */
>     "target": "ES2015",
>     "lib": [
>       "es6",
>       "DOM"
>     ],
> 
>     /* Modules */
>     "module": "commonjs" /* Specify what module code is generated. */,
>     "resolveJsonModule": true /* Enable importing .json files */,
> 
>     /* Module Resolution */
>     "baseUrl": "." /* This must be specified if "paths" is. */,
> 
>     /* JavaScript Support */
>     "allowJs": true /* Allow JavaScript files to be a part of your program. Use the `checkJS` option to get errors from these files. */,
>     "sourceMap": true /* Enables the generation of sourcemap files */,
> 
>     /* Emit */
>     "declaration": true,
>     "downlevelIteration": true,
>     "outDir": "dist" /* Specify an output folder for all emitted files. */,
> 
>     /* Interop Constraints */
>     "esModuleInterop": true /* Emit additional JavaScript to ease support for importing CommonJS modules. This enables `allowSyntheticDefaultImports` for type compatibility. */,
>     "forceConsistentCasingInFileNames": true /* Ensure that casing is correct in imports. */,
> 
>     /* Type Checking */
>     "strict": true /* Enable all strict type-checking options. */,
>     "noImplicitAny": true /* Enable error reporting for expressions and declarations with an implied `any` type.. */,
>     "noEmitOnError": true,
>     /* Completeness */
>     "skipLibCheck": true /* Skip type checking all .d.ts files. */
>   },
>   "include": [
>     "./config/**/*",
>     "serverless.ts",
>     "./src/**/*",
>     "./lib/**/*",
>     "./middleware/**/*",
>     "./__tests__/**/*",
>     "res/**/*",
>     "**/*.tsx",
>     "**/*"
>   ]
> }
> ```

To solve your issue @LuisAzeved, I have also run into this issue personally.  From what I know, certain compilers such as webpack, lambda-build, and I'm supposing esbuild incorrectly give the wrong imports for the node modules for `yargs` in both `puppeteer` and `puppeteer-extra`, but I used this postinstall.js script to fix the incorrect node module imports:

```javascript
// postinstall.js
import { fileURLToPath } from "url";
import { dirname, resolve } from "path";
import { readFile, writeFile } from "fs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

for (const path of [
  "node_modules/@puppeteer/browsers/lib/cjs/CLI.js",
  "node_modules/puppeteer-core/node_modules/@puppeteer/browsers/lib/cjs/CLI.js", // can remove if not using puppeteer-extra
]) {
  const cliFilePath = resolve(__dirname, path);
  const oldImport = `const yargs_1 = __importDefault(require("yargs/yargs"));`;
  const newImport = `const yargs_1 = __importDefault(require("yargs"));`;

  readFile(cliFilePath, "utf8", (err, data) => {
    if (err) {
      console.error(`Error reading ${cliFilePath}:`, err);
      return;
    }

    if (data.includes(oldImport)) {
      const result = data.replace(oldImport, newImport);
      writeFile(cliFilePath, result, "utf8", (err) => {
        if (err) {
          console.error(`Error writing ${cliFilePath}:`, err);
        } else {
          console.log(`Successfully patched ${cliFilePath}`);
        }
      });
    } else {
      console.log(`No patch needed for ${cliFilePath}`);
    }
  });
}

```
