### ISSUE TITLE
how to reference other arguments in an argument

### ISSUE THREAD

**Issue by ghost** [yargs/yargs#2020]
like (dont mind that its typescript)
```ts
let argv: any = yargs
	.command('get <app>', "Get an app", (yargs: Argv) => {
		return yargs.positional('app', {
			describe: "The app to get.",
			type: 'string',
			required: true
		}).option('file', {
			alias: 'f',
			describe: "The path to the file you want the app to be saved to.",
			default: argv.app + '.apk'
		})
```

oh and ive already tried this code, complained about `TypeError: Cannot read property 'app' of undefined`

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months, and the original reporter account has been deleted. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.

**Comment by shadowspawn** [comment]
The original poster is gone.

This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
