### ISSUE TITLE
Can we use it in non-cli apps?

### ISSUE THREAD

**Issue by nabtron** [yargs/yargs#2047]
Can we use yargs in a non-cli app? Like passing the command as a string variable to it?

I want to use it in a discordjs bot i'm coding. 

Thanks.

**Comment by karizma** [comment]
You might find [yargs-parser](https://www.npmjs.com/package/yargs-parser) useful enough for non-cli usage. But there are some things you might still want baked into the library like defining exactly what arguments are allowed. 

First thing you will want to do is call `help(false)`, this will make it so it does not log the help message when `--help` is given.

Next you will want to add a custom `fail()` callback so when the user makes a mistake, it does not log the output, plus this way you can relay the message back on discord.

```

`--get-yargs-completions` can still be called, which will log to your console, Not entirely sure how to turn it off.

**Comment by nabtron** [comment]
Its too complex for my simple use case. I have coded my own lib / npm package now and using it.

Thank you. 

https://github.com/nabtron/dash-commands

`npm i dash-commands`

Example use: 
`-id 24 -category "something double quoted or single"`

**Comment by bcoe** [comment]
Hey @nabtron, if you can use the `.parse()` method you can pass in any string to yargs for parsing. You can find some code here to help you get started:

https://github.com/yargs/yargs/blob/59a86fb83cfeb8533c6dd446c73cf4166cc455f2/docs/api.md#parseargs-context-parsecallback
