### ISSUE TITLE
Check not possible to export in a module

### ISSUE THREAD

**Issue by dan-klasson** [yargs/yargs#2049]
In the [advanced section of the documentation](https://github.com/yargs/yargs/blob/main/docs/advanced.md#providing-a-command-module), it makes no mention of being able to use `check` in a module. 

I think it would make sense to be able to handle the validation logic in `check` instead of having to do that in the `handler`. 

I.e, to do something like this

    export const check = (options: InferredOptionTypes<typeof builder>) => {
      // handle validation here
    };

To not violate single responsibility.

**Comment by shadowspawn** [comment]
You can attach a `check` function in the builder function using `.check()` on the passed yargs instance in the usual way.

Does that answer your question? (Or have I misunderstood!)

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
