### ISSUE TITLE
How to "catch-all" unhandled exceptions

### ISSUE THREAD

**Issue by peterp** [yargs/yargs#2053]
I'm trying to catch all exceptions that are not handled and print an error message that's a bit more supportive than an uncaught exception. I initially thought that I could wrap the `yargs.argv` in a try-catch block, but it appears that sub-commands are not handled by this block.

Is there something that I'm not fully appreciating about the yargs runtime that invalidated my mental model of how to implement this?

**Comment by jly36963** [comment]
If I understand your question correctly, using `.fail(false)` might fix your problem.
Providing false (instead of a function) as an argument will prevent yargs from handling the error and exiting, and it relinquishes control to the try/catch block.

## Example

```js
const yargs = require("yargs");

try {
  yargs('cmd1 cmd2')
  .command(
    'cmd1',
    'cmd1 desc',
    yargs => yargs
      .command(
        'cmd2 [name]',
        'cmd2 desc',
        yargs => yargs.fail(false),
        argv => {
          const { name } = argv
          console.log(`Hello there, ${name || 'friend'}!`)
          throw new Error('I am an error in the nested command')
        }
      )
      .fail(false)
      .parse(),
    argv => {
      console.log(argv)
      throw new Error('I am an error in the command')
    }
  )
  .fail(false)
  .parse()
} catch {
  console.log('OOPS')
}
```

## Output

```
Hello there, friend!
OOPS
```

**Comment by bcoe** [comment]
@peterp have you tried awaiting yargs:

```
try {
  await yargs.parseAsync()
} catch (err) {
  // do something.
}
```

If this isn't supporting sub-commands, I think it's a bug we should make an effort to fix.

**Comment by peterp** [comment]
Thanks @bcoe, that's exactly what we ended up doing.
