### ISSUE TITLE
Help

### ISSUE THREAD

**Issue by NotMarx** [yargs/yargs#2054]
How do I make something like the below example?

```bash
$ ./arg.js --test Test 123 --test2 Test2 321
{ _: [], test: 'Test 123', test2: 'Test2 321', $0: 'arg' }
```

**Comment by pjalsGit** [comment]
you could try reading the docs...

**Comment by NotMarx** [comment]
I'm not sure if I could find them anywhere around the docs. could you help me link them here? it would be helpful and appreciated 😅

**Comment by pjalsGit** [comment]
that is a very simple example, so it should be easy to recreate from the docs, https://github.com/yargs/yargs/blob/main/docs/api.md

**Comment by NotMarx** [comment]
found them already, it was `.array(key)`. thanks for the help :)
