### ISSUE TITLE
argv's type is missing camelCased variants of hyphenated options

### ISSUE THREAD

**Issue by kevinji** [yargs/yargs#2055]
yargs automatically generates camelCased versions of hyphenated options (e.g. `full-page` -> `fullPage`) inside of the `argv` object, but the TypeScript type for yargs doesn't include the camelCased variants. This seems like an omission, but I'm not familiar enough with the TypeScript type system to know whether this is possible to fix or not.

**Comment by bcoe** [comment]
@kevinji the types are maintained in the DefinitelyTyped project, it might be worth opening an issue there as well.

**Comment by forivall** [comment]
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50722

**Comment by kevinji** [comment]
Going to close this as the linked PR has been merged (a while ago!).
