### ISSUE TITLE
--help or help option throws exception

### ISSUE THREAD

**Issue by dcrystalj** [yargs/yargs#2060]
# code to reproduce
```
const yargs = require('yargs/yargs')
const { hideBin } = require('yargs/helpers')

yargs(hideBin(['node', 'some', 'args', '--help'])).argv
```
having `help` or `--help` in args breaks parsing

# screenshot
![image](https://user-images.githubusercontent.com/1460727/140601793-f67f4e44-2fbd-4b3f-8c1a-a7af2705d709.png)

# version
^17.2.1

**Comment by bcoe** [comment]
@dcrystalj passing `--help` causes `yargs` to print the `help` output and exit with `0`.

This is the behavior I'm seeing in `17.2.1`, would you be able to provide an example of the exception that you're seeing?

**Comment by shadowspawn** [comment]
Looks like you are running node in the interactive REPL.

As @bcoe said, invoking the help during parsing causes Yargs to call `process.exit` as you usually want to terminate the program after displaying the help. The exit will terminate the REPL.

You can disable the exit behaviour using `.exitProcess(false)` which will let you stay in the REPL and try other commands. (Seen in the docs, but I have not tried myself.)

**Comment by dcrystalj** [comment]
Well problem was not in reply only

**Comment by bcoe** [comment]
@dcrystalj di dsetting `exitProcess(false)` work for you?

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
