### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by IanMoroney** [yargs/yargs#2062]
@bcoe , would it be possible to get a patch release to incorporate the fixes done in October?
I'm particularly keen on the CVE patch, as it impacts some upstream projects like `mochawesome` and `cypress-mochawesome-reporter`.

Many thanks!

**Comment by bcoe** [comment]
@IanMoroney there aren't any security patches, that I know of, in the next release of yargs itself.

Have you made sure you're on the latest version of dependencies in your `pckage-lock.json`, etc.? I'm guessing your talking bout `ansi-regex`? which should have been fixed in a patch release.

**Comment by IanMoroney** [comment]
specifically, it's this one:
https://github.com/yargs/yargs/pull/2044
`string-width`
Is that update now included in a specific version of yargs?
Thanks!

**Comment by bcoe** [comment]
@IanMoroney because yargs uses `^` for its SemVer range, the fix will be pulled in without a new release of the library being necessary.
