### ISSUE TITLE
Completion for `choices` doesn't work with `alias` or short options

### ISSUE THREAD

**Issue by gmahomarf** [yargs/yargs#2088]
For options that use `choices` (i.e. have a set of valid arguments), completion doesn't work with an option's aliases nor with short options (i.e. options with a single hyphen).

I've opened a PR: #2083

**Comment by bcoe** [comment]
@gmahomarf thank you for the bug report.

**Comment by gmahomarf** [comment]
I noticed this was included in v17.4.0, so I'm closing this. Thanks for the awesome work!
