### ISSUE TITLE
7.1.0 introduces a potentially breaking change, not called out in release notes

### ISSUE THREAD

**Issue by serhalp** [yargs/yargs#2089]
Hi there.

I think the bug fix in 7.1.0 in https://github.com/yargs/yargs/pull/1985 is arguably a breaking change. Per [semver](https://semver.org/):
> PATCH version when you make backwards compatible bug fixes

For example, we had code that looked roughly like:
```js
.implies('dry-run', '--fix false')
```

Our intent was to imply `--fix false` when `dry-run` is provided. Elsewhere, we had a `default: false` on the `dry-run` arg.

With yargs@17.0.0, this skipped validation in the default case. With yargs@17.1.0, our script no longer works in the default case, because `--dry-run` defaults to `false` and yargs spits out:
```
Missing dependent arguments:
 dry-run -> --fix false
```

(I think arguably this makes sense – what our code was trying to express is that we want to imply `--fix false` when `dry-run` is _true_.)

I realize 17.1.0 was released ~4 months ago at this point, so it's too late to reconsider the choice of versioning. I would maybe just recommend updating the CHANGELOG to call out this change as "potentially breaking" in bold or something?

**Comment by bcoe** [comment]
@serhalp thanks for bringing this up. Since the behaviro that was modified wasn't captured in tests, I'd prefer not to bump from `v17` to `v18`, or rollback the work, since it has been in the wild for 4 months.

However, would be happy to add this information to the CHANGELOG 👍

**Comment by shadowspawn** [comment]
Thanks for the detailed description. This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
