### ISSUE TITLE
17.3.0 introduces a regression for handling quoted string

### ISSUE THREAD

**Issue by jy95** [yargs/yargs#2091]
Hello,

When upgrading my dependancies to their latest versions on a [branch](https://github.com/jy95/i18n-tools/pull/39), I detected a regression in yargs (that wasn't present in 17.2.1). 

![image](https://user-images.githubusercontent.com/9306961/145732588-e6445307-2925-4192-b7bd-c46e5f3a2ef2.png)

I created the following [diff](https://github.com/jy95/i18n-tools/blob/updates/src/cmds/diff.ts) command in my project : 
```bash
    diff [files..]
    
    Compare at least two i18n files & generate a report
    
    Options :
      --version             Affiche le numéro de version                   [booléen]
      --help                Affiche l'aide                                 [booléen]
      --filename, --of      Name of the output file generated by this CLI (without
                            extension)
                                  [chaîne de caractères] [défaut : (valeur générée)]
      --outputDir, --od     Output folder where to store the output file
                         [chaîne de caractères] [défaut : "D:\workspace\i18n-tools"]
      --keySeparator, --ks  Char to separate i18n keys. If working with flat JSON,
                            set this to false  [chaîne de caractères] [défaut : "."]
      --outputFormat        Output format         [choix : "JSON"] [défaut : "JSON"]
      --operations          Array of operations (such as ["ADD", "PUT"]) that should
                            be checked when comparing files
                                            [tableau] [défaut : ["DEL","ADD","PUT"]]
      --settings            Chemin du fichier de configuration JSON
```

When running this command on Windows in my [diff.test.ts](https://github.com/jy95/i18n-tools/blob/updates/test/diff.test.ts) in test "JSON reporter - Inline paths should be accepted" : 
```bash
diff --filename "diff_inline-JSON" --outputDir "D:\\\\TEMP\\\\TEMP" "D:\\\\TEMP\\\\TEMP\\\\tests-for-diff\\\\correct\\\\file1.json" "D:\\\\TEMP\\\\TEMP\\\\tests-for-diff\\\\correct\\\\file1.json"
```

I got the following stacktrace : 

```bash
  console.error
    index.js diff [files..]
    
    Compare at least two i18n files & generate a report
    
    Options :
      --version             Affiche le numéro de version                   [booléen]
      --help                Affiche l'aide                                 [booléen]
      --filename, --of      Name of the output file generated by this CLI (without  
                            extension)
                                  [chaîne de caractères] [défaut : (valeur générée)]
      --outputDir, --od     Output folder where to store the output file
                         [chaîne de caractères] [défaut : "D:\workspace\i18n-tools"]
      --keySeparator, --ks  Char to separate i18n keys. If working with flat JSON,
                            set this to false  [chaîne de caractères] [défaut : "."]
      --outputFormat        Output format         [choix : "JSON"] [défaut : "JSON"]
      --operations          Array of operations (such as ["ADD", "PUT"]) that should
                            be checked when comparing files
                                            [tableau] [défaut : ["DEL","ADD","PUT"]]
      --settings            Chemin du fichier de configuration JSON

      at error (node_modules/yargs/build/index.cjs:1:43554)
      at Object.showHelp (node_modules/yargs/build/index.cjs:1:19441)
      at Jt.showHelp (node_modules/yargs/build/index.cjs:1:40813)
      at Object.fail (node_modules/yargs/build/index.cjs:1:13247)
      at node_modules/yargs/build/index.cjs:1:9269

  console.error
    undefined

      at Object.error (node_modules/yargs/build/index.cjs:1:43554)
      at Object.fail (node_modules/yargs/build/index.cjs:1:13267)
      at node_modules/yargs/build/index.cjs:1:9269

  console.error
    [Error: ENOENT: no such file or directory, open 'D:\workspace\i18n-tools\"D:\TEMP\TEMP\tests-for-diff\correct\file1.json"'] {
      errno: -4058,
      code: 'ENOENT',
      syscall: 'open',
      path: 'D:\\workspace\\i18n-tools\\"D:\\TEMP\\TEMP\\tests-for-diff\\correct\\file1.json"'
    }

      at Object.error (node_modules/yargs/build/index.cjs:1:43554)
      at Object.fail (node_modules/yargs/build/index.cjs:1:13286)
      at node_modules/yargs/build/index.cjs:1:9269

  ●  process.exit called with "1"

      at Object.exit (node_modules/yargs/build/index.cjs:1:58603)
      at Jt.exit (node_modules/yargs/build/index.cjs:1:33445)
      at Object.fail (node_modules/yargs/build/index.cjs:1:13377)
      at node_modules/yargs/build/index.cjs:1:9269
```

As you can see  : 

- `D:\workspace\i18n-tools\"D:\TEMP\TEMP\tests-for-diff\correct\file1.json` seems to be a weird concatenation of two things : 
- "D:\workspace\i18n-tools\" : the cwd
- "D:\TEMP\TEMP\tests-for-diff\correct\file1.json" : the path I provided 

Thanks in advance

**Comment by jy95** [comment]
@jly36963  I found the answer in [`ember-template-lint`](https://github.com/ember-template-lint/ember-template-lint/pull/2257) project : 

> There's a change in the yargs-parser dep that changes the handling of quotes inside CLI option value strings. So we have to fix our test to remove the extra quotes.

I guess it should be reported as a change at the end

**Comment by jly36963** [comment]
Yeah, I knew it had to do with [this PR](https://github.com/yargs/yargs-parser/pull/407). yargs-parser had a bug where it would remove more quotes than it should (examples shown in the PR). I need to spend more time with your use case, to make sure there aren't unintended side effects to my fix.

I'm currently working on another bug, but I'll get to this one soon.

**Comment by jy95** [comment]
Sure, take your time ;)
For info, I removed some quotes in my code so that I can finally merge that PR. 
To reproduce the bug on that branch, please refer to the commit with SHA 1acb97c21175e7e38bd2bbd21d028a07ddcce58a

**Comment by bcoe** [comment]
@jly36963 @jy95  is there anything we need to do for this one, other than perhaps call out the behavioral change more loudly in the CHANGELOG?

**Comment by jly36963** [comment]
@bcoe 
I want to do some digging to make sure that my fix has no unintended side-effects. I'll let you know when I've finished investigating.

**Comment by shadowspawn** [comment]
Thanks for the detailed report. This got a good explanation, and has not had any activity in over six months.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
