### ISSUE TITLE
[Question] how do I set custom quotes?

### ISSUE THREAD

**Issue by Dragonizedpizza** [yargs/yargs#2104]
How do I set set custom quotes on yargs?

For example, how would I treat `;;` as quotes, like how `"` is treated?

**Comment by bcoe** [comment]
@Dragonizedpizza this isn't something that's supported in yargs.

What do you need the functionality for?

**Comment by Dragonizedpizza** [comment]
I'm trying to have yargs work with codeblocks

**Comment by bcoe** [comment]
Working backwards, does codeblocks use `;` for quoting strings rather than `"` and `'`? Mind providing an example, you've tickled my curiosity.

**Comment by Dragonizedpizza** [comment]
Codeblocks use \`\`\`, the ;; was just an example.

**Comment by Dragonizedpizza** [comment]
@bcoe you there?

**Comment by bcoe** [comment]
@Dragonizedpizza I'm trying to understand the use case where you would need yargs to parse codeblocks, could you elaborate a bit?

This would provide quite a bit of tweaking to the parser, and I'm wondering why you wouldn't just replace `\`\`\`` with `"`?

**Comment by Dragonizedpizza** [comment]
![image](https://user-images.githubusercontent.com/70718540/152246701-21b0fbab-fd10-4755-9be4-5e883a3f55b4.png)

I just noticed that is possible, how does yargs realize which quote closes the string all together, and which quote is a string inside the string?

**Comment by bcoe** [comment]
@Dragonizedpizza I think what you want is support for bash escape codes in parsing, then you could do something like:

```
'"eval(\"
```

This is already a feature request here: https://github.com/yargs/yargs-parser/issues/346
