### ISSUE TITLE
How to launch yargs middleware function after command processing is finished?

### ISSUE THREAD

**Issue by MurzNN** [yargs/yargs#2106]
I need to run a finalizer function after any command processing is finished, is it possible?

I can launch it manually in end of each command processing function, but one place to declare it via yargs - will be much more convenient!

We already have a very similar `middleware` function, but it launches _before_ the command is processed.

**Comment by bcoe** [comment]
@MurzNN you could do something like this now:

```
await yargs
  .command('one', 'desc', () => {}, async () => { ... })
  .command('two', 'desc', () => {}, async () => { ... })
  .parseAsync();
doSomething();
```

👆 with yargs' new async support you would not reach `doSomething()` until after any command had finished.

Would this give you what you need? Or were you picturing something a bit different?

**Comment by MurzNN** [comment]
Thanks for the quick reply! I'm already going this way, but have faced other issue with detecting executed command afterwise: https://github.com/yargs/yargs/issues/2107
