### ISSUE TITLE
No autocompletion, how to debug?

### ISSUE THREAD

**Issue by alexbjorlig** [yargs/yargs#2109]
I'm migrating my teams CLI to Github codespaces. The CLI installs fine and is available globally in the container with `npm link`. Added the output of the `completion` command to the `.bashrc`, and sourced the file.

However, there is no auto-complete. How can I debug this?

**Comment by bcoe** [comment]
I haven't personally bumped into issues with the completion feature, so haven't been in a position to debug. I think your best bet would be following instructions like [this](https://superuser.com/questions/370952/how-do-i-debug-bash-completions), for putting your bash script in verbose mode.

You could also potentially `echo` log lines to a temporary file, e.g., `>> /tmp/completion.out`
