### ISSUE TITLE
How to show command descriptions when completion runs for a singel command?

### ISSUE THREAD

**Issue by alexbjorlig** [yargs/yargs#2110]
Let's say I have a function:

```
.command(
        'resetLocalDb',
        'Connects to Mongodb locally and resets data to dev hosted.',
        () => {},
        async (argv) => {
            const { resetLocalDb } = await import('./cli-helpers/reset-local-db');
            await resetLocalDb();
        }
    )
```

But when completion runs for this in `bash`, It only shows the possible flags I can use. How can I make it output the description also?
![Screen Shot 2021-12-30 at 16 38 05](https://user-images.githubusercontent.com/9967422/147766131-412794ea-47ea-44f7-ada5-d768bb9e191c.png)

Ideally I would like some nice outputted format like the Heroku CLI 😅

**Comment by bcoe** [comment]
@alexbjorlig this is not a feature that's currently implemented. Could you provide an edample of the behavior you're picturing, I'm not accustomed to completions with descriptions.

**Comment by alexbjorlig** [comment]
hmm I think what I'm looking for is maybe more something like [fig.io](https://fig.io/) - but that's probably out of scope for yargs. I will just close the issue 😅
