### ISSUE TITLE
yargs cannot find `package.json` on ESM

### ISSUE THREAD

**Issue by jopemachine** [yargs/yargs#2122]
Related issue: https://github.com/avajs/ava/issues/2942

In [this code](https://github.com/yargs/yargs/blob/main/lib/platform-shims/esm.mjs#L24), yargs's `platform-shims/esm.mjs` takes different value on `mainFilename` with `platform-shims/cjs.ts`.

And in my thought, because the line stores a wrong value in `mainFilename` in ESM, yargs cannot find `package.json` in the `kPkgUp`.

Maybe, I think this line needs to be changed like below or something.

```js
const mainFilename = __dirname.substring(0, __dirname.lastIndexOf('node_modules'));
```

**Comment by bcoe** [comment]
@jopemachine if you have the time, a failing test would be greatly appreciated. I'm not sure what the best way to get equivalent behavior in ESM is?

**Comment by jopemachine** [comment]
> if you have the time, a failing test would be greatly appreciated.

I just made the [smallest failing module](https://www.npmjs.com/package/yargs-version-fail-test) because the existing code will not fail on local (including `node_modules` once).

You can check the above cli module logs `unknown` when using `--version` because the `dirname` includes `node_modules` twice 

(__dirname is `/usr/local/lib/node_modules/yargs-version-fail-test/node_modules/yargs/lib/platform-shims/esm.mjs`)

> I'm not sure what the best way to get equivalent behavior in ESM is?

I'm not sure this is equivalent behavior with cjs though, 
I think what we need here is to find out the module's (using `yargs`) entry point's directory path.
So, I've thought it is enough to set the `mainFilename` as the above value.
