### ISSUE TITLE
yargs.argv returns undefined

### ISSUE THREAD

**Issue by manojuppala** [yargs/yargs#2132]
The below code returns undefined
`
import yargs from "yargs";
const command = yargs.argv._[0];
console.log(command);
`

`$ node index.js help`
i have also tried `yargs.argv.$0`

**Comment by Sseroan** [comment]
import yargs from "yargs";

console.log(yargs.arg)

This returns undefined too. 
How did you resolve this?

**Comment by Sseroan** [comment]
> import yargs from "yargs";
> 
> console.log(yargs.arg)
> 
> This returns undefined too. How did you resolve this?

This helped me ....

import yargs from "yargs";

console.log(yargs(process.argv).argv);

**Comment by Hardikbhadru** [comment]
This out it will work
import yargs from 'yargs';
console.log(yargs(process.argv).argv)

**Comment by KartikeyaMohan** [comment]
```
import yargs from 'yargs'
import { hideBin } from 'yargs/helpers'

console.log(yargs(hideBin(process.argv)).argv)
```

This worked for me, same is mentioned in the yargs documentation.

**Comment by AdleeAfif** [comment]
hello, may i know

> ```
> import yargs from 'yargs'
> import { hideBin } from 'yargs/helpers'
> 
> console.log(yargs(hideBin(process.argv)).argv)
> ```
> 
> This worked for me, same is mentioned in the yargs documentation.

May i know which documentation are you mentioning? I did some searching but failed to find it

**Comment by KartikeyaMohan** [comment]
> hello, may i know
> 
> > ```
> > import yargs from 'yargs'
> > import { hideBin } from 'yargs/helpers'
> > 
> > console.log(yargs(hideBin(process.argv)).argv)
> > ```
> > 
> > This worked for me, same is mentioned in the yargs documentation.
> 
> May i know which documentation are you mentioning? I did some searching but failed to find it

This is the documentation I referred
https://www.npmjs.com/package/yargs

**Comment by AdleeAfif** [comment]
> > hello, may i know
> > 
> > > ```
> > > import yargs from 'yargs'
> > > import { hideBin } from 'yargs/helpers'
> > > 
> > > console.log(yargs(hideBin(process.argv)).argv)
> > > ```
> > > 
> > > This worked for me, same is mentioned in the yargs documentation.
> > 
> > May i know which documentation are you mentioning? I did some searching but failed to find it
> 
> This is the documentation I referred
> https://www.npmjs.com/package/yargs

Sorry for the reply but thanks😊

**Comment by SangameshHudage** [comment]
> > import yargs from "yargs";
> > console.log(yargs.arg)
> > This returns undefined too. How did you resolve this?
> 
> This helped me ....
> 
> import yargs from "yargs";
> 
> console.log(yargs(process.argv).argv);



This is also helped me >
console.log(yargs().argv);
