### ISSUE TITLE
[low prio hint] please change the main page link from http to https

### ISSUE THREAD

**Issue by ReneWerner87** [yargs/yargs#2135]
![image](https://user-images.githubusercontent.com/7063188/153872858-c70f93b6-29f0-43fd-8258-93721275b741.png)

-> 
![image](https://user-images.githubusercontent.com/7063188/153872962-56234777-4d05-4a12-89eb-e47ee69d6a9d.png)

please use https://yargs.js.org/

**Comment by bcoe** [comment]
done 👍
