### ISSUE TITLE
Config file gets read as individual letters when using ES6 imports

### ISSUE THREAD

**Issue by BadIdeaException** [yargs/yargs#2145]
Reading a config file with the `config` option parses every letter as a separate option when yargs is used through an ES6 import.

For example, if this is `foo.json`:
```
{
	"foo": "bar"
}
```
The following code:
```
import _yargs from 'yargs'
const yargs = _yargs(process.argv);
const config = yargs.config().argv;
console.log(config);
```
Produces this result:
```
{
  '0': '{',
  '1': '\n',
  '2': '\t',
  '3': '"',
  '4': 'f',
  '5': 'o',
  '6': 'o',
  '7': '"',
  '8': ':',
  '9': ' ',
  '10': '"',
  '11': 'b',
  '12': 'a',
  '13': 'r',
  '14': '"',
  '15': '\n',
  '16': '}',
  _: [ '/usr/bin/node', '/vagrant/test.js' ],
  config: 'foo.json',
  '$0': 'test.js'
}
```
Evidently, every character from `foo.json` gets parsed as a separate, number-keyed option.

It works fine when using yargs through `require`:
```
const _yargs = require('yargs');
const yargs = _yargs(process.argv);
const config = yargs.config().argv;
console.log(config);
```
gives the expected result:
```
{
  _: [ '/usr/bin/node', '/vagrant/test.cjs' ],
  config: 'foo.json',
  foo: 'bar',
  '$0': 'test.cjs'
}
```

**Comment by bcoe** [comment]
@BadIdeaException thank you for the bug report. Would happily take a patch if anyone is interested in contributing.

**Comment by jly36963** [comment]
At one point, there were problems with the way config files were imported (esm):
[issue](https://github.com/yargs/yargs/issues/2040)
[fix](https://github.com/yargs/yargs-parser/pull/416)

Instead of iterating through keys of a parsed object, it was iterating through indices of the unparsed json string. Does this make sense?

I'm having trouble reproducing, but I'm using the (post-fix) yargs version 17.4

## Example

index.js

```js
yargs("cmd1 --settings ./config.json")
  .command(
    "cmd1",
    "cmd1 desc",
    (yargs) =>
      yargs.option("opt1", {
        describe: "opt1 description",
        type: "string",
        required: true,
      })
      .config("settings"),
    (argv) => {
      console.log({ argv });
    }
  )
  .parse()
```

config.json

```json
{
  "opt1": "The day will come when people truly understand one another"
}
```

output

```
{
  argv: {
    _: [ 'cmd1' ],
    settings: './config.json',
    opt1: 'The day will come when people truly understand one another',
    '$0': 'index.js'
  }
}
```

**Comment by bcoe** [comment]
@BadIdeaException is this still happening to you on the most up-to-date version of yargs?

**Comment by BadIdeaException** [comment]
Now working as expected. Thank you for the quick fix. :+1:
