### ISSUE TITLE
Global false does not work when also set the `coerce` property in `v17`

### ISSUE THREAD

**Issue by Alive-Fish** [yargs/yargs#2162]
I am upgrading the `yargs` version from `16.2.0` to `17.4.0` in order to use the async builder feature, but after upgrading, our sub commands do not work well because the `global` property seems being broken.

I write a piece of code for testing the `global` property and the true reason may be the `coerce` property conflicts with the `global`.

```TypeScript
import yargs from "yargs";
import { hideBin } from "yargs/helpers";

yargs(hideBin(process.argv))
  .command("new", "new a project", async (yargs) => {
    return yargs
      .options("op1", {
        description: "option1",
        default: "option1",
        global: false,
        type: "string",
        coerce: (arg?: string) => arg?.toLocaleLowerCase(), // if comment this line, it works well.
      })
      .command(
        "template",
        "new a project from a template",
        async (yargs) => {
          return yargs.options("op2", {
            description: "option2",
            default: "option2",
          });
        },
        async (args: any) => {
          console.log(args);
        }
      );
  })
  .strict()
  .help().argv;
```

The following is the result when run this code.
![image](https://user-images.githubusercontent.com/15262146/161935059-ecf29e4f-ad4b-4a19-8e9f-7001fb167f6e.png)

Is this a bug or there are some different usages about the global property?

Thanks.

**Comment by jly36963** [comment]
It's a problem with `coerce`. I mentioned it in a PR that fixes the upstream problem.
coerce was adding keys to argv that weren't provided by the user. This causes strict to fail (because argv is polluted with arguments that weren't provided, and the `template` command is unaware of the accidentally-added argument)

**Comment by Alive-Fish** [comment]
@jly36963 Thank you. Do you mean it will be fixed in the next `yargs` version? Is it the version `17.4.1`?

**Comment by jly36963** [comment]
I believe so -- the changelog has it listed under 17.4.1

**Comment by shadowspawn** [comment]
Closing as fixed by https://github.com/yargs/yargs/pull/2161.
