### ISSUE TITLE
Split showHelpOnFail error level

### ISSUE THREAD

**Issue by artembeep** [yargs/yargs#2170]
Is it possible to customize somehow error level for `showHelpOnFail` to show help only for `cli` notation level errors.
E.g. wrong option set provided,  unknown command etc. 

But same time to skip usage screen if an application level error is raised.

Thx!

**Comment by shadowspawn** [comment]
I am not sure I understand. What is an example of an application level error? (Like a throw, or accessing undefined variable in own code?)

**Comment by Macil** [comment]
I've noticed that help is shown either when the user specifies an invalid command/option, or when an *async* command handler throws an error. I wonder if that's what OP is running into and trying to disable. I've opened an issue with more details about this case at https://github.com/yargs/yargs/issues/2394.

**Comment by shadowspawn** [comment]
There is a new issue open with more details, and no followup to the original issue. Closing this as stale.
