### ISSUE TITLE
[Typescript] Array option with default return as "string" type not "string[]"

### ISSUE THREAD

**Issue by r1si** [yargs/yargs#2174]
I have try to set an option with this object:
```
{
      exchange: {
        alias: 'e',
        description: 'Bla Bla',
        default: 'all',
        type: 'array'
      }
 }
```
After parsing  yargs the Obj return indicate as "string" type not "string[]"

If I try to cast after TS return me an error: 
"TS2352: Conversion of type 'string' to type 'string[]' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first."

The only workaround is cast to any or unknown
```
(argv.exchange as any).forEach((element) => {
})
```

**Comment by jly36963** [comment]
I think it's because you want the option to be `string[]`, but your default is `string`. Try `default: ['all']`, so that your option's type and default's type are in agreement.

## example

```js
const input = 'cmd1 -f apples mangoes'
// const input = 'cmd1'

yargs(input)
  .command(
    'cmd1',
    'cmd1 desc',
    yargs => yargs.option('foods', { 
      desc: 'a list of foods',
      type: 'array', 
      alias: 'f',
      default: ['apples'] // string[]
    }),
    argv => {
      const { foods } = argv
      console.log(`I like ${foods.join(' and ')}`)
    })
  .strict()
  .parse()
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
