### ISSUE TITLE
How to return a result from the command handler?

### ISSUE THREAD

**Issue by OnkelTem** [yargs/yargs#2177]
I have a code like this:

```js
const parse = yargs(["asdsad"])
  .demandCommand()
  .command(
    "$0",
    "the default command",
    () => {}, // <<<<
    (argv): Foo => {
      return {
        a: "asdad",
      };
    }
  );
```

But it doesn't compile leading to an error in the `<<<<` line:

```
No overload matches this call.
  The last overload gave the following error.
    Argument of type '() => void' is not assignable to parameter of type '{ [key: string]: Options; }'.
      Index signature for type 'string' is missing in type '() => void'.(2769)
index.d.ts(155, 9): The last overload is declared here.
```

So command handler cannot return a value. Then how to still do it?

Here is a sandbox:

https://www.typescriptlang.org/play?#code/JYWwDg9gTgLgBATwIZQOYGc4DMoRHAImTXQIG4AoCgYwgDt14wV0BTOAXkRQwAoBtAknQATdEhEEAugEoKcOADoRrEEjoiAwnjUbechYtohdI3vIWEAJAAYCAGgsKCMABbsVWJAFcANvGNTByc4fU4APjgAbwBfR0tQngA3GQAuOAAxCAgI6JCFKFYYbyg6PISEpHShUQlgirgYygSYixlKChgEMHYsnK4oiyq4RihgOlRKJqpeMI5IwYVaBnhkzjhmKDZFZKmZfUogA

**Comment by jly36963** [comment]
What is your specific use case? 

## Parse (with handler)

I use `.parse()` -- but it only returns argv.

```js
const input = 'cmd1 -f Hello -b world'

const parsed = yargs(input)
  .command(
    'cmd1',
    'cmd1 desc',
    yargs => yargs
      .option('foo', { type: 'string', alias: 'f', required: true })
      .option('bar', { type: 'string', alias: 'b', required: true }),
    argv => {
      const { foo, bar } = argv
      console.log(`${foo} ${bar}`)
    })
  .strict()
  .parse()
```

## Parse (handled externally)

If is possible to omit the fourth argument to command (the handler function), and to implement the handler logic yourself

```js
const input = 'cmd1 -f Hello -b world'

const parsed = yargs(input)
  .command(
    'cmd1',
    'cmd1 desc',
    yargs => yargs
      .option('foo', { type: 'string', alias: 'f', required: true })
      .option('bar', { type: 'string', alias: 'b', required: true })
      .middleware(argv => {
        const { foo, bar } = argv
        argv.baz = `${foo} ${bar}`
      })
  )
  .strict()
  .parse()

const { foo, bar } = parsed
console.log(`${foo} ${bar}`)
```

## Default command

If you only have one command, and you want to handle it externally, you could skip the command builder and instead chain on yargs directly.

```js
const input = '-f Hello -b world'

const parsed = yargs(input)
  .command('$0', 'default desc')
  .option('foo', { type: 'string', alias: 'f', required: true })
  .option('bar', { type: 'string', alias: 'b', required: true })
  .strict()
  .parse()

const { foo, bar } = parsed
console.log(`${foo} ${bar}`)
```

## My opinion

In general, I prefer the first approach, as I think it scales best and is most flexible. 
As a program includes more commands with varying options, nested commands, global and local options, etc, the first pattern keeps it most organized.

**Comment by shadowspawn** [comment]
An answer was provided (thanks @jly36963 ), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
