### ISSUE TITLE
Error in ESM build when importing 'yargs' and trying to use the global singleton

### ISSUE THREAD

**Issue by segevfiner** [yargs/yargs#2190]
Steps to reproduce:
1. `git clone https://github.com/segevfiner/yargs-bug`
2. `npm install`
3. `npm start`

**Comment by hongaar** [comment]
A workaround I use:

```js
import yargs from 'yargs/yargs'

yargs()
  .scriptName('pirate-parser')
  // ...
  .help()
  .parse(process.argv.slice(2))
```

**Comment by dvtate** [comment]
![image](https://user-images.githubusercontent.com/15305612/173912094-d09116dc-c121-4d74-96a2-209c5cd62947.png)

**Comment by hongaar** [comment]
Works for me:

```
node@e27613d3479f: /workspaces/yargs-bug on main [!?]
$ npm run build

> yargs-bug@0.1.0 build
> tsc

node@e27613d3479f: /workspaces/yargs-bug on main [!?]
$ npm start

> yargs-bug@0.1.0 start
> node dist/index.js
```

With `index.ts`:

```ts
import yargs from 'yargs/yargs'

yargs()
    .option("hello", {})
    .strict()
    .parse(process.argv.slice(2))
```

I notice the `package-lock.json` is slightly out of date in your repository. Maybe this has something to do with your error?

If you want I can open a PR in your repo with a devcontainer for you to reproduce what I'm seeing.

**Comment by dvtate** [comment]
it seems to have been an issue with my tsconfig.json, had to enable `esModuleInterop` which is disabled by default

**Comment by bcoe** [comment]
@segevfiner please let us know if you continue to have problems, I believe one of the workarounds discussed in this issue should do the trick for you.

**Comment by hongaar** [comment]
@bcoe it's my impression the issue with `tsconfig.json` only helped with the workaround I suggested, not the original issue. I was able to reproduce the original issue here: https://stackblitz.com/edit/yargs-esm?file=singleton.mjs,factory.mjs&view=editor

Running `node singleton.mjs`:

```
Error: _yargs.default.scriptName is not a function
```

The workaround (`factory.mjs`) works fine as a module.

**Comment by segevfiner** [comment]
@bcoe The underlying issue here is that `index.mjs` isn't exporting the exact same interface as `index.cjs`, it isn't exporting the singleton `Argv` singleton proxy thing, but rather a factory for yargs that won't type check properly as the types for the module "yargs" are for the `Argv` singleton proxy thing.

It would be nice to solve it so others it won't happen to others.
