### ISSUE TITLE
the help command not working with default keyword"help"

### ISSUE THREAD

**Issue by ghost** [yargs/yargs#2194]
I spent last hour or so trying to figured out why the help command wasnt working properly if the keywords was left as help meanwhile it was working if it was set to anything else.

This is the code im working with, just basic things to help me find the issue:

```js
const yargs = require("yargs");

const helpers_1 = require("yargs/helpers");
const argv = yargs(helpers_1.hideBin(process.argv)).argv;

yargs.command("test", "this is a test for the command test", {}, () => {
    console.log("the test was sucess");
});
yargs.help().parse();
console.log(argv);
```

 I tracked it down to this line:

```js
const argv = yargs(helpers_1.hideBin(process.argv)).argv;
```

And then more specifically to the argv Getter method called on the Xt object returned by ``` yargs(helpers_1.hideBin(process.argv))```.
If the .argv method is called help doesn't display the test command or any other command, only the options, if i just delete .argv from the end of that line help and --help work just fine as intended.

calling .argv:
![image](https://user-images.githubusercontent.com/106703515/171490108-ef375cde-e834-4655-8bef-b5b1d67252bf.png)

not calling .argv:
![image](https://user-images.githubusercontent.com/106703515/171490201-62806f24-5163-4567-8ab2-5756ab05b88a.png)

nothing else was changed.

the same happens if .parse() is called.

**Comment by shadowspawn** [comment]
In particular, `.argv` is a getter than calls a function and is not just a property.

An answer was provided (thanks @bcoe), and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
