### ISSUE TITLE
How can I user browser parser with Typescript?

### ISSUE THREAD

**Issue by alamtellez** [yargs/yargs#2197]
Hi, I've been trying to use the browser shim for a project but I get different errors. 
Is there an easy way to import the browser compatible version of yargs without needing to call unpkg cdn?

`import { Yargs } from 'https://unpkg.com/yargs@16.0.0-alpha.3/browser.mjs';`

I'm building a chrome extension and loading scripts from urls violates chrome's policies.

I think that @types/yargs is not up to date because it doesn't allow me to import `browser.mjs` module.

I tried abandoning typescript to avoid it complaining about the the missing references from @types/yargs to see if that would help but it didn't work either. versions 17 and up throw error
```
Uncaught TypeError: __classPrivateFieldGet(...).Parser.looksLikeNumber is not a function
    at [parsePositionalNumbers] (yargs-factory.js:1075:79)
    at [postProcess] (yargs-factory.js:1238:25)
    at [runYargsParserAndExecuteCommands] (yargs-factory.js:1372:41)
    at YargsInstance.parse (yargs-factory.js:701:29)
    at handleKeyDown (App.jsx:40:27)
    at HTMLDocument.eventHandler (dev.js:349:47)
```

I'd really appreciate your help. Thanks!

**Comment by bcoe** [comment]
@alamtellez did you manage to figure this out? If there are any updates we could make to the documentation, I would happily accept a patch.
