### ISSUE TITLE
-- breaks strict mode; also ends parsing after array

### ISSUE THREAD

**Issue by JC3** [yargs/yargs#2202]
yargs 17.5.1

`--` seems to disable the parser more than it should.

## example 1

```
yargs(['--', 'barnacles']).strict().argv
```

**expected**: failure due to unrecognized parameter "barnacles"
**actual**: `barnacles` added to `_`.

## example 2

note [docs state](https://github.com/yargs/yargs/blob/main/docs/api.md#arraykey):

> When the option is used with a positional, use `--` to tell yargs to stop adding values to the array.

i read this as "stop adding values to the array" being implicitly followed by "and then continue parsing arguments".

code:

```
console.log(
    yargs(['-t', 'pokemon', '-a', 'squirtle', 'buzzwole', '--', '-w', 'disembowel'])
        .positional('t', {type:'string'})
        .positional('w', {type:'string'})
        .option('a', {type:'array'})
        .strict()
        .argv
);
```

**expected:** t, a, and w values set
**actual:** t and a set, remaining args added to `_`: 

```
{
  _: [ '-w', 'disembowel' ],
  t: 'pokemon',
  a: [ 'squirtle', 'buzzwole' ],
  '$0': 'yargteststuff.js'
}
```

## complete example

```
import yargs from 'yargs';

let SECTION = msg => console.log(`\n======${msg?` ${msg} `:''}======\n`);

// should fail; instead adds 'barnacles' to _
SECTION('--');
console.log(
    yargs(['--', 'barnacles'])
        .strict()
        .argv
);
    
// should fail; instead adds '-x' to _
SECTION();
console.log(
    yargs(['--', '-x'])
        .strict()
        .argv
);
    
SECTION();
console.log(
    yargs(['-t', 'pokemon', '-a', 'squirtle', 'buzzwole', '--', '-w', 'disembowel'])
        .positional('t', {type:'string'})
        .positional('w', {type:'string'})
        .option('a', {type:'array'})
        .strict()
        .argv
);
```

outputs:

```
====== -- ======

{ _: [ 'barnacles' ], '$0': 'yargteststuff.js' }

============

{ _: [ '-x' ], '$0': 'yargteststuff.js' }

============

{
  _: [ '-w', 'disembowel' ],
  t: 'pokemon',
  a: [ 'squirtle', 'buzzwole' ],
  '$0': 'yargteststuff.js'
}
```

**Comment by bcoe** [comment]
This is working as intended, purpose of `--` is to stop parsing entirely. Any arguments after `--`, including arguments that look like flags, will be placed in the `_` array.

If there's anywhere you think this could be better described in docs, would accept patch for a documentation update. This behavior is working as intended.

**Comment by bcoe** [comment]
FYI, here's where the behaviour of `--` is described:

https://github.com/yargs/yargs/blob/main/docs/tricks.md#stop-parsing

**Comment by JC3** [comment]
makes sense! thanks!
