### ISSUE TITLE
question: validating numbers

### ISSUE THREAD

**Issue by JC3** [yargs/yargs#2205]
when i tell yargs that an option is a number:

```
let argv = yargs(hideBin(process.argv)).option('n', {type:'number'}).argv;
```

and the user supplies a non-number, then that's a command line usage error.

but yargs stores NaN instead of printing a usage error message.

is there a built-in option to make yargs print error messages on usage errors involving numeric parameters?

i can validate it afterwards but i'd like to avoid adding a bunch of boilerplate command line parsing stuff, especially if i have a lot of numeric parameters.

**Comment by bcoe** [comment]
Hey @JC3, I think you should be able to use [coerce](https://github.com/yargs/yargs/blob/main/docs/api.md#coercekey-fn) to get the behavior you would like:

```js
const yargs = require('yargs')
console.info(yargs.option('foo', {
  type: 'number',
  coerce: (num) => { if (Number.isNaN(num)) { return 33 } else { return num } }
}).argv)
```

**Comment by bcoe** [comment]
(let me know if this doesn't do the trick for you).

**Comment by JC3** [comment]
> (let me know if this doesn't do the trick for you).

i settled on this:

```
coerce: v => { if (isNaN(v)) throw Error(`Expected a number, got '${v}'.`) }
```

still a bit boiler-platey and basically amounts to "validating it afterwards" but at least its in the yargs statement, so i'll take it.

thank you!!!

**Comment by bcoe** [comment]
> still a bit boiler-platey and basically amounts to "validating it afterwards" but at least its in the yargs statement and it outputs the usage info like other errors do, so i'll take it.

@JC3 it might be worth adding an advanced example with this behavior 🤔
