### ISSUE TITLE
Multiple and variable keys and parsing them

### ISSUE THREAD

**Issue by thanpolas** [yargs/yargs#2207]
Hello there, apologies if this has been addressed before, I've searched for over an hour and could find anything relevant.

I want to create a command that accepts any number of variable directives, i have this declaration:

```js
  yargsStatement
    .command({
      command: 'call <address> <function>',
      desc: 'Call a command',
      builder: (yargs) => {
        yargs.positional('address', {
          describe: 'Contract address',
          type: 'string',
        });
        return yargs;
      },
      handler: handleCall,
    });
```

There are two positional keys here, `address` and `function`. I expect from this command, to accept any number of follow up keys, which would act as arguments to the function called, like so:

```
program 0x999 balanceOf 0x111
```

There are two issues I am having and would like to figure out:

## 1. Document the variable keys

How do I signal to yargs that I expect any number of positional keys after the second positional (`function`)? Something like a spread operator: `      command: 'call <address> <function> <...args>',`.

If that's not possible, then what would be the best practice to accomplish the same with yargs?

## 2. Parsing of undeclared keys

I did figure out how to capture all the undeclared arguments, past the final one (`function`), using this statement:

```js
const callArgs = yargs._.slice(1);
```

However, when the input are ethereum addresses that start with `0x000`, yargs will automatically parse them as numbers.

I could not find a way to have them get parsed as string since those "variable key arguments" are not declared on the yargs config...

Thank you for the awesome library!

**Comment by shadowspawn** [comment]
Add an extra argument to your `command` property for the optional extra arguments, and `name...` makes it variadic. For example:

```
      command: 'call <address> <function> [callArgs...]',
```
