### ISSUE TITLE
yargs parses some values incorrectly 

### ISSUE THREAD

**Issue by VineetKumarKushwaha** [yargs/yargs#2218]
yargs version: 16.0.0
node version: 10, 12, 14, 16 (*not tested on rest*)

We have used this library in [this package](https://github.com/commercetools/nodejs) and exactly [here](https://github.com/commercetools/nodejs/blob/master/packages/resource-deleter/src/cli.js#L50). we have bunch of options however `projectKey` and `resource` options are mandatory. When I run this command `resource-deleter --resource discountCodes --accessToken "<accessKey>" --projectKey test-test` and print the [args](https://github.com/commercetools/nodejs/blob/master/packages/resource-deleter/src/cli.js#L16) I see something like this
```
{ '1': [ true, true ],
  '2': true,
  '3': [ true, true ],
  '5': true,
  '7': true,
  _: [],
  resource: [ 'discountCodes', '', '' ],
  r: [ 'discountCodes', '', '' ],
  accessToken: true,
  'access-token': true,
  B: true,
  k: [ true, true ],
  n: true,
  t: true,
  Z: true,
  s: true,
  K: true,
  A: true,
  u: true,
  e: true,
  U: true,
  J: true,
  g: [ true, true ],
  h: true,
  R: true,
  c: true,
  confirm: true,
  H: true,
  O: true,
  C: true,
  N: true,
  projectKey: 'treedom-test',
  p: 'treedom-test',
  'project-key': 'treedom-test',
  output:
.......
```
Below is output of process.argv
```
[ '/home/nik/.nvm/versions/node/v10.24.1/bin/node',
  '/mnt/work/alldata/commercetools/nodejs/packages/resource-deleter/bin/resource-deleter.js',
  '--resource',
  'discountCodes',
  '--accessToken',
  '#######',
  '--projectKey',
  'test-test' ]
```
So I am not sure why `resource` is array and why it has some empty values :thinking: . I even tried pass `type: "string"` to `resource` nothing changes. However if we see the `projectKey` it comes as string.

**Comment by bcoe** [comment]
@VineetKumarKushwaha does this problem happen when you use the latest release of yargs (v17?).

**Comment by VineetKumarKushwaha** [comment]
Yes

**Comment by VineetKumarKushwaha** [comment]
@bcoe I haven't tried the latest version. Is this a known issue ??

**Comment by bcoe** [comment]
@VineetKumarKushwaha quite a few bugs were fixed between `v16` and `v17`, some may have addressed the issue you are reporting.

**Comment by shadowspawn** [comment]
I am pretty sure the issue was that your `<accessKey>` started with a dash, and was processed as if it was lots of boolean options instead of being read as the value for the `accessToken` option. Using a toy program with similar options:

```javascript
var argv = require('yargs/yargs')(process.argv.slice(2))
    .option('resource', { alias: 'r', type: 'string' })
    .option('project-key', { alias: 'p' })
    .option('confirm', { alias: 'c', type: 'boolean' })
    .argv;

console.log(argv);
```

```console
$ node index.js --resource discountCodes --accessToken -12357rrBkkntZsKAueUJgghRcHOCN --projectKey test-test
{
  '1': true,
  '2': true,
  '3': true,
  '5': true,
  '7': true,
  _: [],
  resource: [ 'discountCodes', '', '' ],
  r: [ 'discountCodes', '', '' ],
  accessToken: true,
  B: true,
  k: [ true, true ],
  n: true,
  t: true,
  Z: true,
  s: true,
  K: true,
  A: true,
  u: true,
  e: true,
  U: true,
  J: true,
  g: [ true, true ],
  h: true,
  R: true,
  c: true,
  confirm: true,
  H: true,
  O: true,
  C: true,
  N: true,
  projectKey: 'test-test',
  'project-key': 'test-test',
  p: 'test-test',
  '$0': 'index.js'
}
```

A work-around for supplying a value which may start with a dash is to supply the value using an equals, like:

```console
$ node index.js --resource discountCodes --accessToken=-12357rrBkkntZsKAueUJgghRcHOCN --projectKey test-test
{
  _: [],
  resource: 'discountCodes',
  r: 'discountCodes',
  accessToken: '-12357rrBkkntZsKAueUJgghRcHOCN',
  projectKey: 'test-test',
  'project-key': 'test-test',
  p: 'test-test',
  '$0': 'index.js'
}
```

**Comment by bcoe** [comment]
@VineetKumarKushwaha please feel free to follow up, and I can reopen if @shadowspawn's recommendation fails to do the trick.
