### ISSUE TITLE
Electron: hideBin does not regard Playwright's paremeters

### ISSUE THREAD

**Issue by c3er** [yargs/yargs#2225]
If an Electron application is executed via [Playwright](https://playwright.dev/), the `hideBin` function does not work properly.

Here is the `process.argv` that Playwright passes to the Electron application:

```
[
  '/Users/c3er/devel/my/electron-playwright-yargs/node_modules/electron/dist/Electron.app/Contents/MacOS/Electron',
  '--inspect=0',
  '--remote-debugging-port=0',
  '/Users/c3er/devel/my/electron-playwright-yargs/app/main.js'
]
```

Code snippet for parsing the `process.argv`:

```javascript
const argv = yargs(hideBin(process.argv)).argv
```

Yargs' output:

```
{
  _: [ '/Users/c3er/devel/my/electron-playwright-yargs/app/main.js' ],
  'remote-debugging-port': 0,
  remoteDebuggingPort: 0,
  '$0': 'node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'
}
```

Expected:

```
{
  _: [],
  'remote-debugging-port': 0,
  remoteDebuggingPort: 0,
  '$0': 'node_modules/electron/dist/Electron.app/Contents/MacOS/Electron'
}
```

I.e. the array with positional arguments should be empty. This interferes with positional arguments that the application itself wants to process e.g. a file name.

I made [a minimal Electron application](https://github.com/c3er/electron-playwright-yargs) to showcase this problem.

**Comment by shadowspawn** [comment]
The way node handles this sort of situation is to remove the flags that are for node from `process.argv`, which in this case is `--inspect` and `--remote-debugging-port`. They are available if needed by looking at `process.execArgv`. 

See: https://nodejs.org/dist/latest-v18.x/docs/api/process.html#processexecargv

Electron appears to be passing through the node specific flags in `process.argv`. Can you reproduce this problem by launching your Electron app on the command-line with those flags, without using PlayWright?

**Comment by c3er** [comment]
Hi @shadowspawn, sorry for the late response!

I cannot reproduce this by starting via `npm` -- interestingly.

**But:** The [issue in Playwright](https://github.com/microsoft/playwright/issues/16614) is solved in the mean time by adding these arguments after the user provided arguments instead of before -- so they don't interfere with the `hideBin` function anymore.

For my part this issue here can be closed, though these arguments (`--inspect` and `--remote-debugging-port`) still appear in Yarg's argument list.

Does anyone want to keep this issue open? If not, I'd just close this myself next week or so.

**Comment by bcoe** [comment]
@shadowspawn I wonder, does your implementation in `parseArgs` solve this issue, perhaps I can pull it into yargs.

**Comment by shadowspawn** [comment]
Checking... The code in `parseArgs` is detecting the node REPL, which doesn't apply in this case (and is looking for different options): https://github.com/pkgjs/parseargs/blob/67749086a6cb216a4896283de200b1f36646afdd/index.js#L61

I feel like this is a problem with Playwright and/or Electron rather than Yargs. Having the node specific debugging options arriving in `process.argv` is not the expected behaviour compared with Node.js. 

Full disclosure, I don't use either Playwright or Electron! Given Electron has some other inconsistencies with `process.args` I lean towards blaming it. 😄

**Comment by shadowspawn** [comment]
Closing this as probably not solvable from Yargs end. Removing `--inspect` and `--remote-debugging-port` needs to happen upstream, Yargs does not have any information to tell the source of the option flags. Thanks for the good description @c3er.
