### ISSUE TITLE
Error in ESM build when importing 'yargs' and trying to use the global singleton

### ISSUE THREAD

**Issue by segevfiner** [yargs/yargs#2226]
Reopening https://github.com/yargs/yargs/issues/2190

### Steps to reproduce
1. `git clone https://github.com/segevfiner/yargs-bug`
2. `npm install`
3. `npm start`

### Workaround
```js
import yargs from 'yargs/yargs';
import { hideBin } from 'yargs/helpers';

yargs(hideBin(process.argv))
  // ...
  .parse()
```

### Cause
The underlying issue here is that `index.mjs` isn't exporting the exact same interface as `index.cjs`, it isn't exporting the singleton `Argv` singleton proxy thing, but rather a factory for yargs that will falsely type check properly as the types for the module "yargs" are for the `Argv` singleton proxy thing.

It would be nice to solve it so others it won't happen to others.

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

The main take-away is stop using the global singleton.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.
