### ISSUE TITLE
Mandatory Variadic Positional Argument

### ISSUE THREAD

**Issue by Digicrat** [yargs/yargs#2230]
I don't see any option to specify a variadic positional argument as mandatory.  The syntax "[foo..]" works to declare a positional variadic argument, but omitting the brackets (ie: "foo..") seems to give undefined behavior.  Specifically "cmd foo" is accepted but the argument is not parsed, while "cmd foo bar" yields an unknown parameter 'bar' error.

I'd expect that declaring the last argument as variadic without brackets would cause it to be processed as an array that must contain at least one element.  I can of course explicitly add a check() function to enforce this, but that doesn't mark the field as required in the help menu, and this seems like a basic enough feature that it should be built-in

**Comment by shadowspawn** [comment]
I think the expected syntax is `<foo...>`.

Reference: https://github.com/yargs/yargs/blob/main/docs/advanced.md#positional-argument-aliases

**Comment by Digicrat** [comment]
That did it, thanks.  Normal positional argument definitions work without the brackets, so I never noticed that syntax.
