### ISSUE TITLE
Confusing undocumented `type` defaults of options

### ISSUE THREAD

**Issue by webknjaz** [yargs/yargs#2232]
## sup?

The documentation at https://yargs.js.org/docs/#api-reference-optionskey-opt demonstrates that options may have various types. But it does not specify what happens then `type` is not declared.

I've experimentally verified that if `type` is not set, the value is interpreted as a number. This has unexpected side-effects of dropping the trailing zeroes from number-like values as they are parsed as floats.

One would expect the input to be preserved in such cases without losing any bits.

## Repro

Given this simple script
```js
// yargs_test.js

console.log(
  require('yargs').option(
    'flags',
    {
      alias: 'F',
      name: 'flags',
      default: '',
      description: 'Flag the upload to group coverage metrics',
    }
  ).argv
)
```
that outputs the following
```console
$ node yargs_test.js -F 1234.23000 --flags 564.0450
{
  _: [],
  F: [ 1234.23, 564.045 ],
  flags: [ 1234.23, 564.045 ],
  '$0': 'yargs_test.js'
}
```
it's clear that it an undocumented (possibly untested?) corner case.

## Suggested action items

There's a few possibilities of dealing with this problem:
1) Just document what is happening
2) Write tests so that the behavior doesn't change in the future
3) "Fix" this as a bug and preserve the string value
4) Infer the default type from the `default` param

**Comment by bcoe** [comment]
@webknjaz this is working as expected, you can turn off automatic parsing of numbers using:

```
yargs.parserConfiguration({
  "parse-numbers": false
})
```

Let me know if I'm misunderstanding.
