### ISSUE TITLE
ne is not a function

### ISSUE THREAD

**Issue by axetroy** [yargs/yargs#2233]
![截屏2022-09-09 14 26 14](https://user-images.githubusercontent.com/9758711/189285406-fb22752b-2ccb-4c78-b68f-b24ea1223d17.png)

"version": "17.5.1"

nodejs env: 14.x.y

Here is the version 16.x.x

![截屏2022-09-09 14 35 35](https://user-images.githubusercontent.com/9758711/189286779-46205f1e-695f-48f6-8724-b4d390e98a5e.png)

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you  for your contributions.
