### ISSUE TITLE
Not getting cmd argument in well format while i use npm start in node project 

### ISSUE THREAD

**Issue by Darshan-upadhyay1110** [yargs/yargs#2250]
this is my package.json file 
`
  "scripts": {
    "build": "tsc --project ./",
    "start": "ts-node ./src/index.ts",
    "test": "echo \"Error: no test specified\" && exit 1"
  },`

and i use to run cmd 
`npm start --first 10`
but it is executed as `ts-node ./src/index.ts "10"`
so by it my argv will be `

Result  : { _: [ 10 ], '$0': 'node_modules\\ts-node\\dist\\bin.js' }`
Expected  : `{first: 10, '$0': 'node_modules\\ts-node\\dist\\bin.js' }`

**Comment by bcoe** [comment]
Hey @Darshan-upadhyay1110, this looks like it's most likely an issue with how `ts-node` is processing arguments, it may be worth opening an issue there (It's not immediately clear to me that this involves yargs).

**Comment by shadowspawn** [comment]
Try `npm start -- --first 10`.

`npm` is greedy and eats all the options unless you tell it to stop processing options using a `--` argument.

Reference: https://docs.npmjs.com/cli/v8/commands/npm-run-script

(Only spotted it because I answered a similar question earlier today!)
