### ISSUE TITLE
Incorrect behavior for non-negated keys starting with `no-`

### ISSUE THREAD

**Issue by dvtate** [yargs/yargs#2251]
Project has a flag called `--no-rt` as by default the compiler includes the runtime. Is it possible to have only a `--no-rt` flag and not have an `rt` flag? Ideally [key negation](https://github.com/yargs/yargs/blob/HEAD/docs/tricks.md#negate) should only apply when a key with the corresponding name (in this case `rt`) is defined, otherwise `no-*` flags should behave like one would expect, without this weird behavior which I've only now figured out the root cause of after several months of typing `--no-rt=true` in projects.

```
.command('file <name> [options]', 'compile a file to WAT',
        yargs => yargs
            .positional('name', {
                describe: 'name of the entry file',
                type: 'string',
            })
            .options({
               // ...
                'no-rt' : {
                    describe: '(advanced) do not include boilerplate code which might be required for program to run',
                    type: 'boolean',
                },
            }),
// ...
```

**Comment by shadowspawn** [comment]
You can achieve this by disabling the negation according to this similar issue on yargs-parser:

- https://github.com/yargs/yargs-parser/issues/124

(Assuming you don't have other flags which are meant to allow negation.)

**Comment by dvtate** [comment]
I'm currently using this workaround although I still feel behavior is not correct

**Comment by bcoe** [comment]
@dvtate I think the right approach in this case is to turn off boolean negation, otherwise there are lots of side effects I believe you might bump into with a key called `no-*`.

Sorry for the nuisance, but fixing is just a config setting away 👍
