### ISSUE TITLE
How to code command with no args using declarative approach?

### ISSUE THREAD

**Issue by chaeron** [yargs/yargs#2264]
We have some code that looks like this:

```
 const _yargs = yargs();
_yargs.version( "1.0.0" );

_yargs.command( {
  command:  "info",
  describe: "Show info",
  alias:    "i",
  builder:  {
    patch: {
      alias:        "p",
      describe:     "Id AAA-###",
      demandOption: true,
      type:         "string",
    },
  },
  handler: async args => {
    console.log( "show info here..." );
  },
} ).check( ( args, _options ) => {
  const { patch } = args;
  validatePatchName( patch );
  return true;
} );

_yargs.command( {
  command:  "list",
  describe: "List stuff",
  alias:    "l",
  handler:  async args => {
    console.log( "show list here..." );
  },
} );

await _yargs.parseAsync( hideBin( argv ) );
```

The first info command works fine, but I can't get the list command (which has no args) to work and call the handler.

Any ideas on what to change to make the list command work using this approach?

Thanks!

**Comment by shadowspawn** [comment]
I am not able to reproduce this problem.

Using your example code with some minor tweaks for missing code (like `validatePatchName`):

```
% node index.js info --patch minor
Checking args
show info here...
% node index.js list              
Checking args
show list here...
```

Did you sort out your problem?

**Comment by shadowspawn** [comment]
This issue has not had any activity in over six months. It isn't likely to get acted on due to this report.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
 
Thank you for your contributions.
