### ISSUE TITLE
Export type definitions

### ISSUE THREAD

**Issue by Semigradsky** [yargs/yargs#2272]
There are any plans to generate and export type definitions? I see that most code written on TypeScript, but users still need to use `@types/yargs`.

**Comment by shadowspawn** [comment]
Some background from a couple of years ago. (I don't have anything newer.)

This blog explains that the `@types` available from before the conversion to TypeScript are still being used for backwards compatibility (and are quite different to the built-in types):
https://dev.to/bcoe/yargs-v16-released-14p7

There is an open issue about making the built-in (simpler) types available somehow: #1751

**Comment by bcoe** [comment]
Closing in favor of #1751.
