### ISSUE TITLE
JSON with Comments config

### ISSUE THREAD

**Issue by R35007** [yargs/yargs#2280]
Hi,

Can you please provide a support for JSON with comments file (`.jsonc`) as a config.
I am trying to give a `.jsonc` file path to config but its always giving me an invalid json.

Is there any other way or option to do this ?

**Comment by bcoe** [comment]
Hey @R35007 👋 

By providing a callback to the `config` option, you can provide your own custom config file loader:

https://github.com/yargs/yargs/blob/main/docs/api.md#configobject
