### ISSUE TITLE
options name parsed error case.

### ISSUE THREAD

**Issue by lvjiaxuan** [yargs/yargs#2286]
Config:
```
.scriptName('demo')
// ...
.options('bump', {
  array: true,
  default: []
})
.options('no-bump', {
  array: true,
})
```

CLI Input:
```
demo --no-bump
```

Error argv got:
```
{
  bump: [ false ], // `[ ]` expected
  'no-bump': false, // `true` expected
  noBump: false, // `true` expected
}
```

**Comment by shadowspawn** [comment]
There is automatic support for negating an option. You may be able to skip adding the `no-bump` option and get consistent results. See for example:

https://github.com/yargs/yargs/blob/main/docs/tricks.md#negating-boolean-arguments
