### ISSUE TITLE
Multi-line description formatting?

### ISSUE THREAD

**Issue by Slapbox** [yargs/yargs#2288]
It seems like the formatting currently expects a set number of characters per line and considers `\t` and `\n` to be characters for those purposes, so if you manually insert a linebreak into the description, it will look something like below. I'm assuming 15 characters per line to make the example easier

`Some text \nSome more text`

**I'd expect it to look something like:**

```
Some text
Some more text
```

**But instead it looks more like:**

```
Some text
some
more text
```

**With explanatory comments:**

```
Some text << Linebreak caused by \n
some << Linebreak caused by yargs line length limit
more text
```

**Comment by bertyhell** [comment]
I ran into the same issue. You can fix this manually by disabling line wrapping and if you want limiting the lines yourself
```
.wrap(null)
```
https://yargs.js.org/docs/#api-reference-wrapcolumns

Consider closing this issue if this answers your question.

**Comment by bcoe** [comment]
@Slapbox closing given that @bertyhell has provided a workaround. It also sounds like we have another potential solution described here:

https://github.com/yargs/yargs/issues/1640

Which I'm open to landing a patch for.
