### ISSUE TITLE
Import hideBin yargs/helpers lead to exception on compiled js 

### ISSUE THREAD

**Issue by StanislavKharchenko** [yargs/yargs#2289]
Good day!
I have the next issue with using yargs/helpers on ESM module.
With ESM, all import paths should have .js extensions on runtime.

So, when my sources compiled we change typescript import:
`import { hideBin } from 'yargs/helpers'`

into

`import { hideBin } from 'yargs/helpers/index.js'`

Then, when compiled module run, we got the following exception:
`Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './helpers/index.js' is not defined by "exports" in /**/node_modules/yargs/package.json imported from /**/myModule.js`

Is there workaround to import hideBin maybe from 'yargs' module directly with our paths like 'yargs/helpers'?

**Comment by shadowspawn** [comment]
I think the correct import string is still `'yargs/helpers'` and you had it right with

```js
import { hideBin } from 'yargs/helpers'
```

For how it works, see: https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#import-specifiers

> _Bare specifiers_ like `'some-package'` or `'some-package/shuffle'`. They can refer to the main entry point of a package by the package name, or a specific feature module within a package prefixed by the package name as per the examples respectively. _Including the file extension is only necessary for packages without an_ ["exports"](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#exports) _field_.

> Like in CommonJS, module files within packages can be accessed by appending a path to the package name unless the package's [package.json](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#nodejs-packagejson-field-definitions) contains an ["exports"](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#exports) field, in which case files within packages can only be accessed via the paths defined in ["exports"](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#exports).

`helpers` is listed in the exports: https://github.com/yargs/yargs/blob/f37ee6f7da386a1244bf0a0c21b9572f2bb3131b/package.json#L15

**Comment by hung-cybo** [comment]
@StanislavKharchenko 

I'm facing the same problem as you.

I'm using `file-extension-in-import-ts` and `import/no-unresolved` for ESLint. And, now if I use
`import { hideBin } from 'yargs/helpers'`

It throws an eslint error:
`ESLint: require file extension '.js'.(file-extension-in-import-ts/file-extension-in-import-ts)`

But, when I change to `import { hideBin } from 'yargs/helpers.js'`
It throws another error:
`ESLint: Unable to resolve path to module 'yargs/helpers.js'.(import/no-unresolved)`

I'm still looking forward to having a workaround for this issue.

**Comment by shadowspawn** [comment]
@hung-cybo 

This might be an issue with `file-extension-in-import-ts`:
- https://github.com/AlexSergey/eslint-plugin-file-extension-in-import-ts/issues/2

This thread includes a potential work-around, but I am unclear whether it is suppressing real errors too:
- https://stackoverflow.com/questions/59265981/typescript-eslint-missing-file-extension-ts-import-extensions

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
