### ISSUE TITLE
Allow adding options to single commands instead of to all

### ISSUE THREAD

**Issue by JoernBerkefeld** [yargs/yargs#2293]
I have a package in npm called mcdev that offers multiple commands (mcdev retrieve, mcdev deploy, and others). So far web used positional parameters because each command has its own set.  Going forward,  using flags (options) per command would be preferred. I cannot seem to figure this out without making the option available to all commands

**Comment by shadowspawn** [comment]
You can add options specific to the subcommands using the `builder` parameter. Have a look at the API docs for the command routines for some examples of passing an object or supplying a function to build the configuration.

https://yargs.js.org/docs/#api-reference-commandcmd-desc-builder-handler

**Comment by JoernBerkefeld** [comment]
i gotta say thats not well documented - but thanks to your hint and intellisense I figured it out - thank you!
if anyone else is wondering how that can look like, this is an example from my library:

![image](https://user-images.githubusercontent.com/1917227/216769863-7ef1356a-a302-41dd-a5ee-fdf3f8925403.png)
