### ISSUE TITLE
Middleware is called twice

### ISSUE THREAD

**Issue by ivan-kleshnin** [yargs/yargs#2296]
Hi! I see a couple of similarly named **closed** issues, but it still doesn't work correctly, as far as I can tell 😢 :

The bug reappears in TypeScript where I have to `await yargs.argv` according to [the documentation](https://github.com/yargs/yargs/blob/main/docs/typescript.md).

```ts
#!ts-node
import yargs from "yargs/yargs"

await yargs(process.argv.slice(2))
  .scriptName("CLI")
  .usage("$0 <cmd> [args]")
  .command("create", "Create something, just an example", async (yargs) => {
    const argv =  await yargs.argv // if all such lines are removed, there's no duplicate call...
    console.log("Create")
  })
  .command("delete", "Delete something, just an example", async (yargs) => {
    const argv =  await yargs.argv // !!! but we need them !!!
    console.log("Delete")
  })
  .help()
  .middleware(() => {
    console.log("Connect to DB...")
  })
  .argv
console.log("Disconnect from DB...")
```

Calling with no arguments:

**$ ./cli.t**

```
Connect to DB...
Disconnect from DB...
```

Calling with an argument:

**$ ./cli.t create**

```
Connect to DB...
Create
Connect to DB...
Disconnect from DB...
```

---

Tested with Yargs 17.6.2 in MacOS Monterey.

**Comment by bcoe** [comment]
@ivan-kleshnin do you bump into the same issue if you use `.parse()` rather than `.argv`? It seems like we have a test for pretty close to this behaviour, I'm wondering what might be different:

**Comment by bcoe** [comment]
Oh, I see the issue. The third argument to `.command` is used to provide additional configuration options to yargs, for instance adding a flag that's only available for the given command.

You should use the fourth argument to handle the parsed value form yargs, and it will be passed the parsed options from yargs directly (no need to call yargs.argv).

```js
import yargs from "yargs/yargs"

await yargs(process.argv.slice(2))
  .scriptName("CLI")
  .usage("$0 <cmd> [args]")
  .command("create", "Create something, just an example", () => {}, async (opts) => {
     console.info(opts);
     console.log("Create")
  })
  .command("delete", "Delete something, just an example", () => {}, async (opts) => {
    console.info(opts);
    console.log("Delete")
  })
  .help()
  .middleware(() => {
    console.log("Connect to DB...")
  })
  .argv
```

☝️  let me know if this does the trick for you.

**Comment by ivan-kleshnin** [comment]
Thank you, I see my mistake (two `await ...argv`). The problem with `middleware` is that it's not convenient to use in TypeScript. Whatever I add to `argv` from the `middleware` is not typed properly. I'd suggest to utilize a `return` which is currently `void` and merge both `return` and generated `argv` types.
