### ISSUE TITLE
[Q] How to add alias for the builtin version option

### ISSUE THREAD

**Issue by evil-shrike** [yargs/yargs#2301]
I want my tool to support `-v` and `--version` options to dump its version.

If I use just built-in method:
```
yargs(hideBin(process.argv)).version()
```
it only adds support for `version` option and not for `-v` shortcut.

If I add an explicit option additionally to `option()` method:
```
yargs(hideBin(process.argv)).
  .version()
  .option('version', {alias: "v"})
```
I'm getting the following warning in console:
```
(node:64130) Warning: "version" is a reserved word.
Please do one of the following:
- Disable version with `yargs.version(false)` if using "version" as an option
- Use the built-in `yargs.version` method instead (if applicable)
- Use a different option key
https://yargs.js.org/docs/#api-reference-version
(Use `node --trace-warnings ...` to show where the warning was created)
```

Indeed I can use my own 'version' option only, but in that case I'll have to provide the value for it on my own. But I'd prefer the built-in `version()` because it nicely parses version from package.json.

**Comment by mshrtsr** [comment]
@evil-shrike 
Hello! I think the `alias()` method is suitable for your usage.
https://yargs.js.org/docs/#api-reference-aliaskey-alias

```javascript
yargs(hideBin(process.argv))
  .version()
  .alias("v", "version").argv;
```

**Comment by evil-shrike** [comment]
terrific, thank you!
