### ISSUE TITLE
Question: How can I use yargs/lib/platform-shims/esm.mjs

### ISSUE THREAD

**Issue by hung-cybo** [yargs/yargs#2302]
## Background

I'm using [Vite](https://github.com/vitejs/vite) to bundle my pure ESM application (It's a CLI tool).
After the cli tool is bundled, there is an error when executing the CLI

```
ReferenceError: require is not defined in ES module scope, you can use import instead
This file is being treated as an ES module because it has a '.js' file extension and 'package.json' contains "type": "module". To treat it as a CommonJS script, rename it to use the '.cjs' file extension.
```

After that, I checked the built file of yargs, `node_modules/yargs/build/index.cjs`, and saw that It includes [platform-shims/cjs.ts](https://github.com/yargs/yargs/blob/main/lib/platform-shims/cjs.ts) instead of [platform-shims/esm.mjs](https://github.com/yargs/yargs/blob/main/lib/platform-shims/esm.mjs)

## Question
My question is: How can I use yargs/lib/platform-shims/esm.mjs to build yargs

**Comment by shadowspawn** [comment]
Yargs uses [conditional exports](https://nodejs.org/dist/latest-v18.x/docs/api/packages.html#conditional-exports) to support both cjs and esm. The entry point for esm is `index.mjs`. Is that included in your bundle? 

https://github.com/yargs/yargs/blob/663c1b61557eee97b0ff2f1d68017495d2347126/package.json#L8-L14

**Comment by hung-cybo** [comment]
@shadowspawn 

Thank you so much for your reply.

I will explain what I understand now.

https://github.com/yargs/yargs/blob/663c1b61557eee97b0ff2f1d68017495d2347126/package.json#L95-L100

Based on the npm script `prepare`, after `npm install`, there only have `node_modules/yargs/build/index.cjs`.

https://github.com/yargs/yargs/blob/663c1b61557eee97b0ff2f1d68017495d2347126/rollup.config.cjs#L5-L9

https://github.com/yargs/yargs/blob/663c1b61557eee97b0ff2f1d68017495d2347126/rollup.config.cjs#L28-L32

And that file `yargs/build/index.cjs` includes [lib/platform-shims/cjs.ts](https://github.com/yargs/yargs/blob/main/lib/platform-shims/cjs.ts#L23) which contains commonjs syntax: `require`

https://github.com/yargs/yargs/blob/663c1b61557eee97b0ff2f1d68017495d2347126/lib/platform-shims/cjs.ts#L23

So, when I bundle my pure ESM CLI tool with [Vite build](https://github.com/vitejs/vite), the error above is thrown due to containing commonjs syntax.

My Vite config `vite.config.ts` is as below :
```js
import { defineConfig } from "vite";
import path, { resolve } from "node:path";
import autoExternal from "rollup-plugin-auto-external";
import { visualizer } from "rollup-plugin-visualizer";
import checker from "vite-plugin-checker";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

export default defineConfig({
  build: {
    lib: {
      entry: resolve(__dirname, "src/cli/main.ts"),
      formats: ["es"],
    },
    rollupOptions: {
      plugins: [autoExternal(), visualizer()],
    },
  },
  plugins: [checker({ typescript: true })],
});
```

Thank you in advance.

**Comment by shadowspawn** [comment]
There are files at multiple levels, so it is confusing. The entry points are at the top of the installed yargs folder.

```
$ npm init -y
$ npm install yargs
$ ls node_modules/yargs 
LICENSE		browser.d.ts	build		index.cjs	lib		package.json	yargs.mjs
README.md	browser.mjs	helpers		index.mjs	locales		yargs
```

Do you have a repo with Vite set up?

**Comment by hung-cybo** [comment]
@shadowspawn 

I made a repo for reproducing this issue: https://github.com/hung-cybo/yargs-2302-build-with-vite

Thank you.

**Comment by shadowspawn** [comment]
Thanks. I didn't reproduce the problem. When I do `npm run build` I get a `yargs import` in the generated file, and it runs ok. (First time using Vite so no insights to offer on that side!)

```console
% head dist/cli.js
import yargs from "yargs";
...
```

```console
% ./cli.js                                                                                                                   main
cli.js <command>

Commands:
  cli.js curl <url>  fetch the contents of the URL

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
```

**Comment by shadowspawn** [comment]
Do you have a recent version of node installed? (Wondering if it does not understand the conditional import.)

**Comment by hung-cybo** [comment]
@shadowspawn I'm very appreciative of your help.

I have tried three versions of Node, but none of them works.

```sh
$ nvm list
       v16.15.1
       v18.14.1
->      v19.6.1
```

**Comment by shadowspawn** [comment]
I had a bit of trouble getting setup as I did not have Yarn. I'll try reproducing again and note the commands I run.

**Comment by hung-cybo** [comment]
@shadowspawn 

Can you show me which files are inside the folder `node_modules/yargs/build`?

> I had a bit of trouble getting setup as I did not have Yarn. I'll try reproducing again and note the commands I run.

Sorry, I updated the script. Now, you can run without yarn.

**Comment by shadowspawn** [comment]
This time I can reproduce the error!

> Can you show me which files are inside the folder node_modules/yargs/build?

```
% ls -R node_modules/yargs/build
index.cjs	lib

node_modules/yargs/build/lib:
argsert.js		completion-templates.js	middleware.js		typings			utils			yargs-factory.js
command.js		completion.js		parse-command.js	usage.js		validation.js		yerror.js

node_modules/yargs/build/lib/typings:
common-types.js		yargs-parser-types.js

node_modules/yargs/build/lib/utils:
apply-extends.js	levenshtein.js		obj-filter.js		set-blocking.js
is-promise.js		maybe-async-result.js	process-argv.js		which-module.js
```

**Comment by shadowspawn** [comment]
Ok, I get a working file when I use `yarn install`, `yarn run build`. The generated `./dist/cli.js` file starts like:

```
import yargs from "yargs";
import { format, inspect } from "util";
import { normalize, resolve, dirname, basename, extname, relative } from "path";
import { readFileSync, statSync, readdirSync, writeFile } from "fs";
import { notStrictEqual, strictEqual } from "assert";
import { fileURLToPath } from "url";
class YError extends Error {
...
```

 I get a broken file as you described when I run `npm install`, `npm run build`. The generated `cli.js` file looks very different.

```
import yargs from "yargs";
import require$$0$1 from "assert";
import require$$0 from "fs";
import require$$1 from "util";
import require$$1$1 from "path";
function commonjsRequire(path) {
  throw new Error('Could not dynamically require "' + path + '". Please configure the dynamicRequireTargets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.');
}
...
```

**Comment by shadowspawn** [comment]
I have not worked out which package was the critical one to update, but:

```
$ npm install
$ npm update
$ npm run build
$ ./cli.js
cli.js <command>

Commands:
  cli.js curl <url>  fetch the contents of the URL

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
```

**Comment by hung-cybo** [comment]
@shadowspawn 

It also works on my source after running `npm update`

And the `./dist/cli.js` file is the same as when you use `yarn install`, `yarn run build` above

```js
import yargs from "yargs";
import { format, inspect } from "util";
import { normalize, resolve, dirname, basename, extname, relative } from "path";
import { readFileSync, statSync, readdirSync, writeFile } from "fs";
import { notStrictEqual, strictEqual } from "assert";
import { fileURLToPath } from "url";
class YError extends Error {
```

But, the strange is: I found this error while running with `yarn`, not `npm`.

**Comment by bcoe** [comment]
@hung-cybo have you worked around the error with yarn? It may be worth opening an issue on the yarn project itself (even if you have found a workaround). We can't commit to testing yargs with every combination of package manager (npm, yarn, pnpm, etc), in combination with build tool (WebPack, rollup, etc).

We'll certainly except patches for fixes, if there are any small tweaks we can make to our bundling.

**Comment by hung-cybo** [comment]
@bcoe 

Okay, I will check and open an issue on the yarn project if necessary.
This issue may be not related to yargs, so I will close now.
If I have any info, I will share it.

Thank you for the great package and support.
