### ISSUE TITLE
parserConfiguration "strip-aliased" causes "coerce" not be applied for expanded-camelcase

### ISSUE THREAD

**Issue by gomain** [yargs/yargs#2307]
```bash
$ node -e 'const p = require("yargs")(["--n-e", "1"]).option("n-e", { coerce: n => n + 1}).parserConfiguration({ "strip-aliased": true }).parse(); console.log(p)'
{ _: [], 'n-e': 2, nE: 1, '$0': '' }
```

without is ok
```bash
$ node -e 'const p = require("yargs")(["--n-e", "1"]).option("n-e", { coerce: n => n + 1}).parse(); console.log(p)'
{ _: [], 'n-e': 2, nE: 2, '$0': '' }
```

**Comment by shadowspawn** [comment]
Possibly related: #2159

**Comment by shadowspawn** [comment]
At this point in the parsing, the `aliases` includes an entry for the camel-case version of the option, and not just the user supplied aliases. This might be the source of the problem.

https://github.com/yargs/yargs/blob/2b6ba3139396b2e623aed404293f467f16590039/lib/yargs-factory.ts#L412

```
{
  aliases: { help: [], version: [], 'n-e': [ 'nE' ], nE: [ 'n-e' ] },
  keys: 'n-e'
}
```

**Comment by shadowspawn** [comment]
There were problems mixing coerce with parser configuration which removes keys from argv. I took a more general approach in #2308 to remove assumptions about configuration.
