### ISSUE TITLE
how can I use default command and help simultaneously

### ISSUE THREAD

**Issue by PengBoUESTC** [yargs/yargs#2312]
yargs(hideBin(process.argv))
	.command("$0", "init rspack project", async argv => {
          consosle.log('111')
         })
        .help()
        .parse()

if the `builder` is an async function, the help command will run the builder without the help message

**Comment by shadowspawn** [comment]
I have reproduced the problem (calls `exit()` before displaying help) when the default command has an async builder. Looks like a bug.

**Comment by 4i8** [comment]
> yargs(hideBin(process.argv)) .command("$0", "init rspack project", async argv => { consosle.log('111') }) .help() .parse()
> 
> if the `builder` is an async function, the help command will run the builder without the help message

just use [clinei](https://www.npmjs.com/package/clinei) 🤣

**Comment by shadowspawn** [comment]
I got a test working, but uncovered an interesting issue in the process. I think the async triggered during the help processing  is not returned as a promise, so calling await on the parse result does not block and allow the help to display before the test completes. I think this PR still makes sense on its own so not considering that a blocker! I'll open a PR to your branch.

**Comment by shadowspawn** [comment]
This has been fixed by #2313
