### ISSUE TITLE
tuyen 

### ISSUE THREAD

**Issue by phamhongtuyen95** [yargs/yargs#2315]
Tham gia hội thoại trên Skype. https://join.skype.com/invite/qlbVhl6aVLge![Skype_QR_2023_03_20T12_45_50_564Z.png](https://user-images.githubusercontent.com/122416490/226342715-fe33d113-92c9-42d8-ae4e-d70c93d57fe3.png)

@https://join.skype.com/invite/qlbVhl6aVLge

**Comment by shadowspawn** [comment]
Please stop experimenting with GitHub in a shared project and creating noise and distraction for other users. Use a project of your own.

Please stop spamming this project with links to unrelated content.

**Comment by shadowspawn** [comment]
You may be getting confused between whether you are working in your own fork of `yargs` or the original. Pay attention to the project path up in the top left of the page.

![Screen Shot 2023-03-21 at 11 32 32](https://user-images.githubusercontent.com/15719847/226479808-e71ca68c-35d1-42dc-ae7f-e7aa2fc145ee.png)

![Screen Shot 2023-03-21 at 11 32 48](https://user-images.githubusercontent.com/15719847/226479849-f78869d6-f81c-4637-864e-411700770944.png)
