### ISSUE TITLE
Feature Request: Tandem flags

### ISSUE THREAD

**Issue by reggi** [yargs/yargs#233]
Given code similar to this.

``` js
#!/usr/bin/env node
var argv = require('yargs')
  .default('e', true)
  .default('P', false)
  .argv

console.log(argv)
```

I'd like to enable these to flags as tandem flags, so they are opposite from each other. If one is set the other is set to the opposite.

So given `command -P`, I'd expect:

``` js
{
  P: true,
  e: false
}
```

Is this something that yargs already provides? Here's my ugly solution:

``` js
function tandem (argv, item, linkedItem) {
  argv[linkedItem] = !argv[item]
  return argv
}

var argv = tandem(argv, 'P', 'e')
```

And it doesn't work with aliases :(

**Comment by reggi** [comment]
I created this:

```
function argvMerger (argv, asProp, props) {
  argv[asProp] = _.chain(props)
  .map(function (prop) {
    if (typeof prop === 'string') return argv[prop]
    return argv._[prop]
  })
  .flatten()
  .value()
  return argv
}

argv = argvMerger(argv, 'files', ['file', 'files', 0])
```

It would be nice if there was an easy way to create a chainable function then I can just create custom functions and not have to do the redundant `argv = something(argv)`.

**Comment by nexdrew** [comment]
@reggi Sorry for the long silence!

No, yargs does not currently support this concept. See similar request in #189, although it sounds a bit more restrictive than what you want. In the meantime, perhaps you could use a custom [`.check()`](https://www.npmjs.com/package/yargs#check-fn) function, though admittedly it wouldn't be much different than your example above, except you could possibly handle aliases as well (via the 2nd argument).

I wonder, what kind of behavior would you expect/suggest if `command -P -e` were executed? Last one wins? Both set to `true`?

**Comment by errorx666** [comment]
I'd like to amend this proposal somewhat: instead of limiting it to two flags that are always opposed, we should be able to specify *n* flags, only one of which can be set.  Setting one to true sets the others to false.
This is just a degenerate case of the broader functionality.

**Comment by Morishiri** [comment]
I was just looking for some issues to close and I think this is really nice idea to implement and I think I will do it, but we need to make some agreements first.

How should it behave if more than one flag is set? I think it should be treaten the same way as `conflicts`, but I need confirmation on that.
@bcoe , @errorx666 do you have any other ideas on how should it behave?

**Comment by errorx666** [comment]
That sounds right.

**Comment by bcoe** [comment]
I think this feature would be better supported at the application layer, or potentially using our `middleware` functionality (which allows you to modify arguments during the parsing step).
