### ISSUE TITLE
How to merge options object in Typescript

### ISSUE THREAD

**Issue by shunyun-bp** [yargs/yargs#2336]
Building from the Typescript example, I'd like to include a "library" of shared options as an object.  When I use expansion to merge the object, Typescript complains.

Let's say I have an option that I want to use in all of my projects, "g".  I'd put it in a JSON file, import into my script, and then merge in using expansion. For simplicity, I'll just hardcode into my example:
> example.ts
```ts
`import yargs from 'yargs';
import { hideBin } from 'yargs/helpers'

const shared_opts = {
    g: { type: 'string'}
}

const argv = yargs(hideBin(process.argv))
    .options({
        a: { type: 'boolean', default: false },
        b: { type: 'string', demandOption: true },
        c: { type: 'number', alias: 'chill' },
        d: { type: 'array' },
        e: { type: 'count' },
        f: { choices: ['1', '2', '3'] },
        ...shared_opts
    }).argv;

```

Whereas the yargs example (docs/typescript.md) shows signature for argv including a-f,
merging in shared_opts generates a Typescript error:
```
TS2345: Argument of type '{ g: { type: string; }; a: { type: "boolean"; default: boolean; }; b: { type: "string"; demandOption: true; }; c: { type: "number"; alias: string; }; d: { type: "array"; }; e: { type: "count"; }; f: { choices: string[]; }; }' is not assignable to parameter of type '{ [key: string]: Options; }'.
  Property 'g' is incompatible with index signature.
    Type '{ type: string; }' is not assignable to type 'Options'.
      Types of property 'type' are incompatible.
        Type 'string' is not assignable to type '"array" | "count" | PositionalOptionsType | undefined'.
```

And then the signature is just 
```
const argv: {
    [x: string]: unknown;
    _: (string | number)[];
    $0: string;
} | Promise<{
    [x: string]: unknown;
    _: (string | number)[];
    $0: string;
}>
```
I'll freely confess, I don't know if this is bug or user error; I'm fairly new to TS so I may just be doing something wrong, but would very much appreciate some guidance on how to make this work.  I'm trying to refactor over 30 CLI utilities (including implementing TS) and I use Yargs in them all; would love to standardize my options without having to cut/paste.
Thank you!

**Comment by shadowspawn** [comment]
Just add a const assertion to your shared options, like:

```ts
const shared_opts = {
    g: { type: 'string'}
} as const; // <-- const assertion
```

This is a bit tricky to talk about with a property called "type" and a string containing the string "string"!

Let's take instead:
```
const a = { b: 3 };
const c = { d: 4 } as const;
```

In the first case, `b` is a property of type `number`. In the second case `d` is a readonly property of type `4`.

Reference: https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#literal-inference

**Comment by shunyun-bp** [comment]
@shadowspawn THANK YOU!!!
That's perfect!  Here's my working solution, then.

arg_shared_config.ts
`
export const std_options = {
  "log_level": {
    "describe": "Logging level for logs",
    "choices": ["error", "warn", "info", "verbose", "debug"],
    "type": "string",
    "default": "error"
  },
  "verbosity": {
    "describe": "Level of verbosity for console messages",
    "choices": ["error", "warn", "info", "verbose", "debug"],
    "type": "string",
    "default": "info"
  }
} as const;
`

utility.ts
`
import {std_options} from './lib/arg_shared_config'
import yargs from 'yargs'
import { hideBin } from 'yargs/helpers'

var argv = yargs(hideBin(process.argv))
  .options({
    ...std_options,
    "api_key": {
      describe: "API Key",
      type: "string",
      demandOption: true,
      group: "Required arguments",
    },...
  .help()
  .parseSync();
`

and now the type signature for argv is:
`var argv: {
    [x: string]: unknown;
    api_key: string;
    log_level: "error" | "warn" | "info" | "verbose" | "debug";
    verbosity: "error" | "warn" | "info" | "verbose" | "debug";
    _: (string | number)[];
    $0: string;
}`

Perfect. Thank you!

**Comment by ChuckJonas** [comment]
The `.parseSync();` was what I was missing.  Before I was just referencing the `.argv`  property and that was returning the type `| Promise<...>`.
