### ISSUE TITLE
"command" parameter for commands that depend on -- 

### ISSUE THREAD

**Issue by isaacdcm** [yargs/yargs#2341]
I have a cli that is a generic wrapper that does some things to the environment and then executes another arbitrary command.

The use model is something like bellow (mirroring how docker or kubectl exec would work)

`mycli run -- ls -al`

I am able to get this to work using 
```
    .parserConfiguration({
      "populate--": true,
    })
```

What doesn't work is for me to set the command as
`export command = "run -- <command>"`
so I have to set the command to "run" and then explain the usage in the description.

I hope this makes sense. I am not sure if I am doing something wrong or if this type of functionality isn't implemented.

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
