### ISSUE TITLE
Yargs always exits with code 0 (even if there was an error)

### ISSUE THREAD

**Issue by jwartofsky-yext** [yargs/yargs#2345]
Hi all,

I'm using Yargs and am trying to get an error code of 1 in case of an error. I've tried throwing uncaught errors, using the fail() and parse() options in the controller, yargs().exit(1, new Error("bad thing")), and process.exit(1). How can I get an exit code of 1 after calling a Yargs command?

Here's an example of something I've tried:

Controller:
```
yargs(hideBin(process.argv))
  .scriptName("pages")
  .command(buildCommandModule)
  .demandCommand()
  .version(false)
  .strict()
  .help()
  .parse();
```

Handler:
```
const handler = async (args: yargs.ArgumentsCamelCase<BuildArgs>) => {
    return yargs().exit(1, new Error("Failed"));
};


export const buildCommandModule: CommandModule<unknown, BuildArgs> = {
  command: "build",
  describe: "Build website",
  handler,
};
```

Thanks!

**Comment by shadowspawn** [comment]
I am not able to reproduce with a trimmed version of your example code using node v18. I am seeing an exit code of 1 as expected. Does this simple example work for you too?

(I made the async explicit, but I see same behaviour with call to `.parse()` too.)

```js
const yargs = require('yargs');

const handler = async (args) => {
    console.log('async builder');
    return yargs().exit(1, new Error("Failed"));
};

const buildCommandModule = {
  command: "build",
  describe: "Build website",
  handler,
};

yargs(process.argv.slice(2))
  .command(buildCommandModule);

yargs.parseAsync().then(() => console.log('async parse complete'));
```

```console
% node index.js build
async builder
% echo $?
1
```

**Comment by shadowspawn** [comment]
Note that there is an open issue about the error passed to `.exit()` not being displayed: #1725

**Comment by jwartofsky-yext** [comment]
I'm still getting an exit code of 0.

I'm using node v17.9.1
Typescript compiler option: ESNext

ESNext doesn't allow for 'requires', so I have to use import.
Running this prints 'async builder', but I'm still getting code 0:

```
import yargs from "yargs";

const y = yargs(process.argv.slice(2))
  .command(buildCommandModule);

y.parseAsync().then(() => console.log('async parse complete'));

const handler = async ({ scope }: BuildArgs) => {
  console.log("async builder");
  return yargs().exit(1, new Error("failed"));
};

export const buildCommandModule: CommandModule<unknown, BuildArgs> = {
  command: "build",
  describe: "build website",
  handler,
};
```

**Comment by shadowspawn** [comment]
I have tried Typescript with `module` set to CommonJS and to ESNext. I see exit code of 1 with both. How are you running your program? How are you checking the exit status?

Does my javascript example code show exit code of 1 for you? You might have to compare that with your failing case and work your way towards the middle to find the critical difference.

There is what I think is a usage error in your example with `yargs().exit` which should be called on a yargs instance rather than the default import. (However, that is not the source of your problem. I am using that code to reproduce.)

**Comment by jwartofsky-yext** [comment]
I found out it was being run from a thread spawned from spawnSync. The error code was being swallowed there.

Thanks for the help!
