### ISSUE TITLE
Command module should not need to provide a handler

### ISSUE THREAD

**Issue by JoshMcCullough** [yargs/yargs#2362]
Specifically when using `commandDir`, `handler` shouldn't be required for intermediary commands. Looking at the [docs](https://github.com/yargs/yargs/blob/main/docs/advanced.md#commanddirdirectory-opts)...

cmds/init.js:

```js
exports.command = 'init [dir]'
exports.desc = 'Create an empty repo'
exports.builder = {
  dir: {
    default: '.'
  }
}
exports.handler = function (argv) {
  console.log('init called for dir', argv.dir)
}
```

Provides a handler but it should not be needed since there is no "action" for this command, it is just a means to get to the inner commands.

**Comment by shadowspawn** [comment]
`init` is a subcommand which has an option called `dir`.

```console
% node command_hierarchy.js init --help
command_hierarchy.js init [dir]

Create an empty repo

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
  --dir                                                           [default: "."]
```

`remote` is an intermediate command, and although the code example does have a handler it can be omitted. The code in `addHandler` allows `handler` to be undefined:

https://github.com/yargs/yargs/blob/e517318cea0087b813f5de414b3cdec7b70efe33/lib/command.ts#L86-L96

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
