### ISSUE TITLE
How to demand intermediary commands?

### ISSUE THREAD

**Issue by JoshMcCullough** [yargs/yargs#2363]
Using `commandDir`, how to make sure the user has provided a full command?

Given structure:
```
/
    |- index.ts    -- targs entrypoint
    |- commands
        |- init.ts
        |- level1
            |- level1.ts
            |- level2
                |- say-hi.ts
```

## `index.ts`
```ts
yargs
    .commandDir("commands")
    .demandCommand()
    .help()
    .usage();
```

## `commands/init.ts`
```ts
export = {
    command: "level1",
    description: "level1 commands.",
    builder: argv => argv.commandDir("level1"),
};
```

## `commands/level1/level1.ts`
```ts
export = {
    command: "level2",
    description: "level2 commands.",
    builder: argv => argv.commandDir("level2"),
};
```

## `commands/level1/level2/say-hi.ts`
```ts
export = {
    command: "say-hi",
    description: "Says hello.",
    handler: () =: console.log("HI!"),
};
```

Given the above, the user should be shown usage info if they were to do any of:
- `my-app level1`
- `my-app level1 level2`

The only valid command here is:
```bash
my-app level1 level2 say-hi
```

Currently, "calling" any intermediary command (e.g. `level1`, `level2`) does _not_ show usage, but instead just exits.

I tried adding `demandCommand: true` to `init.ts` and `level1.ts` but it does not seem to work.

**Comment by shadowspawn** [comment]
I can reproduce the problem if the export is not actually working at all, or if the subcommand does not specify that it expects a positional argument (i.e. another subcommand). Try adding a positional to the `command` export like:

```js
// commands/init.ts
export = {
    command: "level1 <command>",
    description: "level1 commands.",
    builder: argv => argv.commandDir("level1"),
};
```

```console
% node index.js level1 
index.js level1 <command>

level1 commands.

Commands:
  index.js level1 level2 <command>  level2 commands.

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]

Not enough non-option arguments: got 0, need at least 1
% node index.js level1 level2 say-hi
HI!
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
