### ISSUE TITLE
Idea: Adding the #hacktoberfest label

### ISSUE THREAD

**Issue by NabiKAZ** [yargs/yargs#2365]
I think it would be good if the project was part of this hacktoberfest event by adding the #hacktoberfest label.
https://hacktoberfest.com/

Also I think the Discussions section in github is useful if you enable it.

**Comment by shadowspawn** [comment]
Hacktoberfest #10 2023 has passed, so closing this issue. Thanks for the suggestion.

I have not used Discussions much. If you want visibility on that suggestion, please open a new, um, issue.
