### ISSUE TITLE
Matching strings with initials in dashes is confusing

### ISSUE THREAD

**Issue by NeapolitanIcecream** [yargs/yargs#2371]
Here is my code:

```js
const yargs = require("yargs/yargs");
const { hideBin } = require("yargs/helpers");
const argv = yargs(hideBin(process.argv)).string("test").argv;
console.log(argv);
```

Here are two sets of inputs and outputs, the only difference being whether the dash is used as the first letter of the string:

```sh
❯ node main.js --test " --a --b" 
{ _: [], test: ' --a --b', '$0': 'main.js' }

❯ node main.js --test "--a --b" 
{ _: [], test: true, 'a --b': true, 'a B': true, '$0': 'main.js' }
```

The first output (if the spaces are removed) is what I would expect.

I've just started using yargs, let me know if this isn't a problem.

**Comment by shadowspawn** [comment]
This is expected behaviour.

To make it a little clearer, I added
```js
console.log(process.argv.slice(2));
```

The speech marks make the enclosed text a single argument but are removed by the shell and do not reach yargs. If the argument after an option starts with a dash, it is treated as another option instead of as an option-value.

```console
% node main.js --aaa bbb         
[ '--aaa', 'bbb' ]
{ _: [], aaa: 'bbb', '$0': 'main.js' }
% node main.js --aaa --bbb 
[ '--aaa', '--bbb' ]
{ _: [], aaa: true, bbb: true, '$0': 'main.js' }
% node main.js --test " --a --b" 
[ '--test', ' --a --b' ]
{ _: [], test: ' --a --b', '$0': 'main.js' }
% node main.js --test "--a --b" 
[ '--test', '--a --b' ]
{ _: [], test: '', 'a --b': true, 'a B': true, '$0': 'main.js' }
% node main.js --a-b            
[ '--a-b' ]
{ _: [], 'a-b': true, aB: true, '$0': 'main.js' }
```

**Comment by NeapolitanIcecream** [comment]
Since this is the default behaviour of the shell, I think it is indeed acceptable. My eventual solution for those who encountered the same problem later was this:

```sh
❯ node main.js --test="--a --b" 
{ _: [], test: '--a --b', '$0': 'main.js' }
```
