### ISSUE TITLE
`terminalWidth` appears to be typed incorrectly

### ISSUE THREAD

**Issue by Thenlie** [yargs/yargs#2381]
# Description

When using `terminalWidth` as shown in [the docs](https://yargs.js.org/docs/#api-reference-wrapcolumns) and invoking it as a function, I get the following error:
```
TypeError: yargs.terminalWidth is not a function
```
This error is thrown and my application can not run. If I instead call `.wrap(yargs.terminalWidth)`, the application runs as expected.

## Full command

```ts
#!/usr/bin/env node

import yargs from 'yargs';
import { hideBin } from 'yargs/helpers';
import { Props, main } from '.';

yargs(hideBin(process.argv))
    .options({
        o: {
            alias: 'outputFile',
            default: 'stdio',
            describe: 'Filename to write response to',
            type: 'string',
        },
        // truncated for brevity
    })
    .command(
        'run',
        'run the CLI tool',
        () => {},
        (argv) => {
            const { outputFile, inputFile, inputPath, useDefault } = argv as unknown as Props;
            main({ outputFile, inputFile, inputPath, useDefault });
        }
    )
    .demandCommand(1)
    .wrap(yargs.terminalWidth()) // <-- ❌ Does not work
    .wrap(yargs.terminalWidth)   // <-- ✅ Works
    .parse();
```

**Comment by shadowspawn** [comment]
`.terminalWidth()` is a method on a yargs instance. It is a bit subtle, but the trick is to make the instance separately from configuring it so that you can call the method.

```js
import yargsFactory from 'yargs/yargs';
import { hideBin } from 'yargs/helpers';

const yargsInstance = yargsFactory(hideBin(process.argv));
yargsInstance.wrap(yargsInstance.terminalWidth());
```

This is actually covered in the [TypeScript usage examples](https://github.com/yargs/yargs/blob/main/docs/typescript.md#typescript-usage-examples), albeit I think with a typo where `myYargs` is used instead of `yargsInstance`.

**Comment by Thenlie** [comment]
Thanks @shadowspawn for the explanation!
