### ISSUE TITLE
Allow positional of type array to handle trailing positionals

### ISSUE THREAD

**Issue by djohnson-aperture** [yargs/yargs#2409]
I have a script that I'd like to collect the args at the end of the command as under a key, and still get type safety. Currently this isn't possible, as `yargs.positional` doesn't allow array as a type. Here's what I've had to resort to:
```ts
yargs(hideBin(process.argv))
.scriptName('do-something')
.command<{
  first: string;
  second: string;
  requiredRest: (number | string)[];
}>(
  '$0 <first> <second> <requiredRest..>',
  false,
  function (yargs) {
    return yargs
      .positional('first', { type: 'string', demandOption: true })
      .positional('second', { type: 'string', demandOption: true })
      .positional('requiredRest', { demandOption: true });
  },
  function (argv) {
    console.log(argv.first);
    console.log(argv.second);
    console.log(argv.requiredRest);
  },
)
.help().argv;
```
This does function, however, it requires me to do extra work by overriding the generic type for `.command`. Ideally, the builder would determine the type, which allowing positional to take type array would solve this. I'm not sure if there's a reason this isn't allowed, other than an array positional anywhere other than the end of the command doesn't make sense.

**Comment by shadowspawn** [comment]
The `array` property is separate from the `type` property. For your example:

```
.positional('requiredRest', { type: 'string', array: true, demandOption: true });
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
