### ISSUE TITLE
Object data isn't set via environment variables

### ISSUE THREAD

**Issue by augjoh** [yargs/yargs#2413]
When using `env({prefix})` object data isn't set. I would expect, that the object data equals the camelCase values. Please see example below.

```
import { inspect } from 'node:util';
import assert from 'node:assert';

import yargs from 'yargs/yargs';

process.env['X_A_A'] = '2';
let input = ["--a.b", "1"];

const argv = yargs(input)
  .env('X')
  .option("a.a", { })
  .option("a.b", { })
  .argv;

console.log(inspect(argv.a));
assert.equal(argv.a.a, argv.aA);
```

**Comment by shadowspawn** [comment]
There is not any expectation that `a.a` and `aA` should match in your example. I'll try and explain:

Quoting from the [documentation](https://yargs.js.org/docs/#api-reference-envprefix):

> Use the “__” separator in the environment variable to indicate nested options. (e.g. prefix_nested__foo => nested.foo)

So `X_ALPHA_BETA` is like `--alpha-beta` and sets the parsed property `alphaBeta`.

And `X_ROOT__PROPERTY` (note the two underscores) is like `--root.property` and sets the parsed property `root.property`.

**Comment by augjoh** [comment]
Ah, missed that part. Thank you.
