### ISSUE TITLE
`parserConfiguration` doesn't behave well if called multiple times

### ISSUE THREAD

**Issue by dleavitt** [yargs/yargs#2414]
Some surprising behavior as the result of having a global singleton parser instance.

1. Calling it more than once overwrites the whole thing instead of merging:

```typescript
const argv1 = yargs
  .parserConfiguration({ "parse-numbers": false })
  .parserConfiguration({ "boolean-negation": true })
  .option("a", {});

const opts = argv1.parse(["-a", "1"]);
// Expected
opts[a] == "1"
// Actual
opts[a] == 1
```

2. Calling it within a command overwrites the config for the entire yargs instance:

```typescript
const argv2 = yargs
  .parserConfiguration({ "parse-numbers": false })
  .option("a", {})
  .command("cmd1", "", (y) => y.parserConfiguration({}).option("b", {}))
  .command("cmd2", "", (y) => y.option("c", {}));

console.log(argv2.parse(["cmd1", "-a", "1", "-b", "2"]));
console.log(argv2.parse(["cmd2", "-a", "1", "-c", "2"]));

// Expected
{ _: [ 'cmd1' ], a: "1", b: "2" }
{ _: [ 'cmd2' ], a: "1", c: "2" }

// Actual
{ _: [ 'cmd1' ], a: 1, b: 2 }
{ _: [ 'cmd2' ], a: 1, c: 2 }
```

These issues sort of combine to negatively affect the composability of commands - a command in one module changing a single config setting will reset _all_ config settings in _all_ modules.

Ideally:
1. Calling `parserConfiguration` should merge the newly passed options with any previously passed options.
2. Each `CommandBuilder` should probably get its own `#parserConfig`
3.  Also, each yargs instance should probably get its own parser config? Calling it anywhere appears to overwrite values for all yargs instances: **Because I'm using yargs wrong, see responses below**.

```typescript
const cli = yargs.parserConfiguration({ "parse-numbers": false }).option("a", {});

// in some other file perhaps
const otherCli = yargs.parserConfiguration({}).option("a", {});

const opts = cli.parse(["-a", "1"]);
// Expected
opts["a"] == "1"
// Actual
opts["a"] == 1
```

**Comment by shadowspawn** [comment]
> Some surprising behavior as the result of having a global singleton parser instance.

I will response to this part first. The answer here is don't use a global singleton parser instance! 😄 

The singleton was an old pattern which has (hopefully) been removed from the documentation. It has been dropped from the newer exports. The new pattern is the default export is a factory function.

```js
# legacy and deprecated
const yargsSingleton = require('yargs'); // only works from CommonJs for backwards compatibility
const argv = yargsSingleton.parse();
```

```js
const yargsFactory = require('yargs/yargs');
const argv = yargsFactory(process.argv.slice(2)).parse();
```

**Comment by shadowspawn** [comment]
The intention is you call `.parserConfiguration()` once on the root yargs instance to configure the command. This configures the whole of the parsing, for the command and subcommands.

(Thanks for the clear example code and expected/actual outcomes.)

**Comment by dleavitt** [comment]
Thanks! When I use yargs as intended it does indeed seem to work as expected :)

> The singleton was an old pattern which has (hopefully) been removed from the documentation.

`require('yargs')` is all over the place in the documentation but that itself isn't a problem, right? As long as it's then doing `require('yargs')().stuff` instead of `require('yargs').stuff`, which it seems to be in most places.

**Comment by shadowspawn** [comment]
> `require('yargs')` is all over the place in the documentation, but that itself isn't a problem, right? As long as it's then doing `require('yargs')().stuff` instead of `require('yargs').stuff`, which it seems to be in most places.

Correct. The imports that still supply a singleton _also_ support the preferred factory approach, using the same default export.
