### ISSUE TITLE
Conflict between `no` prefix and `strict()`

### ISSUE THREAD

**Issue by jcs090218** [yargs/yargs#2419]
I have following code:

```js
'no-proxy': {
      description: `set no-proxy to host`,
      type: 'string',
      group: TITLE_PROXY_OPTION,
    },
```

and 

```
.strict()
```

I'm trying to make `--no-proxy` receive one argument, but it doesn't allow to do that after adding `strict()`. What can I do to achieve this? Can `--no-` prefix be treated as a normal option? 🤔 

Full file: https://github.com/emacs-eask/cli/blob/master/eask

**Comment by shadowspawn** [comment]
You can turn off negation using a `yargs-parser` configuration setting:
- https://github.com/yargs/yargs-parser#boolean-negation

In Yargs, this is done using `.parserConfiguration({...})`
- https://yargs.js.org/docs/#api-reference-parserconfigurationobj

Like:
```js
yargs.parserConfiguration({ "boolean-negation": false })
```

**Comment by jcs090218** [comment]
Thank you! It works! :D
