### ISSUE TITLE
Yargs handler not running in Typescript project. 

### ISSUE THREAD

**Issue by Atlinx** [yargs/yargs#2420]
I've copied the following example code into a TypeScript project and it does not print anything when I run the `serve 1000`, the serve command handler doesn't print anything. Only the final `console.log("done")` is printed. Note that the `help` command works fine.

I'm using
```json
"typescript": "^5.3.3",
"@types/yargs": "^17.0.32",
"yargs": "^17.7.2"
```

```typescript
#!/usr/bin/env node
import yargs from "yargs";
import { hideBin } from "yargs/helpers";

yargs(hideBin(process.argv))
	.command(
		"serve [port]",
		"start the server",
		(yargs) => {
			return yargs.positional("port", {
				describe: "port to bind on",
				default: 5000,
			});
		},
		(argv) => {
			console.info(`start server on :${argv.port}`);
		},
	)
	.option("verbose", {
		alias: "v",
		type: "boolean",
		description: "Run with verbose logging",
	})
	.parse();

console.log("done");
```

**Comment by Atlinx** [comment]
It seems like I have to use `.argv` instead of `.parse` to get it to work.

**Comment by shadowspawn** [comment]
What is in your `tsconfig.json`?

I tried your example program with a default `tsconfig.json` created using `npm tsc --init` with latest TypeScript and working ok.

```
% node index.js serve 2000
start server on :2000
done
```

**Comment by Atlinx** [comment]
Weird, I've been working on my CLI tool for a few days, and recently I changed `argv` back to parse just to see what happens. This may have been a Typescript compilation issue (maybe it didn't compile properly and was running old code?).
