### ISSUE TITLE
`strictOptions()` doesn't work with kebab case options

### ISSUE THREAD

**Issue by Atlinx** [yargs/yargs#2421]
I have a kebab case option called `no-prompt`, and I've enabled strict mode for yargs:

```typescript
#!/usr/bin/env node

yargs(hideBin(process.argv))
	.option("no-prompt", {
		desc: "automatically answers yes to all prompts",
		type: "boolean",
	})
	.demandCommand()
	.strictOptions()
	.parse();
```

When I run `my_cli.js --no-prompt`, I get the error "Unknown argument: prompt".

**Comment by shadowspawn** [comment]
Yargs supports adding `--no-` on the front of an option to set the option value to false. So yargs assumes `--no-prompt` is negating the `prompt` option.

- https://github.com/yargs/yargs/blob/main/docs/tricks.md#negating-boolean-arguments

A couple of ideas. 

You could use a different option name. One I am familiar with from `npm` is `--yes` in `npm init --yes`. From the npm command-line help.

>        Automatically answer "yes" to any prompts that npm might print on the command line.

You could turn off the negate behaviour by passing in configuration to the underlying `yargs-parser` engine:

- https://github.com/yargs/yargs-parser#boolean-negation
- http://yargs.js.org/docs/#api-reference-parserconfigurationobj

**Comment by Atlinx** [comment]
Thanks for the clarification. I ended up disabled boolean negation with 
```typescript
yargs(...).parserConfiguration({
    "boolean-negation": false,
})
```
