### ISSUE TITLE
Async await not working with esbuild

### ISSUE THREAD

**Issue by Atlinx** [yargs/yargs#2427]
Hey all, I'm trying to bundle my typescript yargs cli using esbuild, and the async commands aren't working.

Here's a simplified version of my cli setup:
```
const cli = yargs(hideBin(process.argv));
cli.command(
	"new [name]",
	"Create a new migration",
	(yargs) =>
		yargs.positional("name", {
			desc: "Name of the new migration",
			type: "string",
			demandOption: true,
		}),
	async (vargs) => {
		await cmdMigrateNew(vargs.name);
	},
)
cli.parseAsync();
```

I run my cli with `parseAsync()`. Only `--help` works, but all my async commands don't work.

**Comment by shadowspawn** [comment]
Technically I think you should await the result of `.parseAsync()`. Not sure that is the problem though!

```
await cli.parseAsync();
```

TypeScript does a transpile with a lot of configuration options, and esbuild is another layer of processing. Have you got a project or reproduction steps to allow reproducing the problem you are seeing?

**Comment by Atlinx** [comment]
I ended up fixing the problem by not using async in my command handler. I'm not sure why that works though.

**Comment by shadowspawn** [comment]
This issue has not had any activity in a few months. It isn't likely to get acted on due to this report. With a build in the steps, there are multiple moving parts to understand what the problem is.

Feel free to open a new issue if it comes up again, with new information.
 
Thank you for your contributions.

**Comment by shadowspawn** [comment]
(Change close status.)
