### ISSUE TITLE
Unable set array types

### ISSUE THREAD

**Issue by insidesecurity-yhojann-aguilera** [yargs/yargs#2428]
By example in a array:

```javascript
yargs.option('test', { alias: 't', type: 'array' }).parse();
```

Can set the `test` type but can not set the items types, like as array of numbers only.

**Comment by shadowspawn** [comment]
You use a property rather than the type to make it an array. Try:

```
yargs.option('test', { alias: 't', type: 'number', array: true });
```

**Comment by shadowspawn** [comment]
An answer was provided, and no further activity in a month. Closing this as resolved.

Feel free to open a new issue if it comes up again, with new information and renewed interest.
