### ISSUE TITLE
Using getHelp() returns the main help instead of subcommand's

### ISSUE THREAD

**Issue by g-roman-2024** [yargs/yargs#2429]
Hello yargs team, 

I am currently finding a potential bug - or maybe I'm doing something wrong. I want to get the help menu for a subcommand when the arguments passed to yargs are in the form `<command> --help` by using the `getHelp()` method, as I later want to handle the help stored in a variable. 

For context, I am using yargs to parse a string of arguments within a third party platform able to run NodeJS code. 

Consider the code below: 

```
const yargs = require('yargs');
const { hideBin } = require('yargs/helpers');

let args = "test --help";

let parser = yargs(args)
  .exitProcess(false)
  .command('test', 'test stuff')
  ;

let argv;
try {
  argv = parser.parse();
} catch (error) {
  return {
    json: {
      error: error + "\n```" + parser.getHelp() + "```"
    }
  }
}

//console.log(argv);
console.log(parser.getHelp());
```

Upon execution, what I'm getting back is, first, the correct help menu for the "test" command (I would also want to supress this behaviour if possible). Later, you can see the promise returned by `getHelp()`, but the help shown belongs to the wider application and not the "test" command. 

```
~$ node test2.js
test2.js test

test stuff

Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
Promise {
  'test2.js [command]\n' +
    '\n' +
    'Commands:\n' +
    '  test2.js test  test stuff\n' +
    '\n' +
    'Options:\n' +
    '  --help     Show help                                                 [boolean]\n' +
    '  --version  Show version number                                       [boolean]'
}
```

Any advice will be welcome.

**Comment by shadowspawn** [comment]
I think `getHelp()` just returns the top level help.

You can capture the parse output by passing a custom `parseCallback` to `.parse()`. There is an example in the documentation: https://yargs.js.org/docs/#api-reference-parseargs-context-parsecallback

```
  parser.parse(['test', '--help'], function (err, argv, output) {
    console.log(`Captured output: ${output}`);
  });
```

**Comment by shadowspawn** [comment]
(Thanks for the full example code and output.)

**Comment by g-roman-2024** [comment]
Thank you @shadowspawn, I really appreciate the prompt answer. 

In that case, is there any way to get the help text for a specific subcommand? I could deactivate standard help with `.help(false)` and create a custom `--help` option for each subcommand, but then again I would need to generate the help text somehow (other than manually hardcoding it).

**Comment by shadowspawn** [comment]
In the example code I gave, it is capturing the help text for the `test` subcommand. Is that what you wanted?

```
parser.parse(['test', '--help'], function (err, argv, output) {
    console.log(`Captured output: ${output}`);
  });
```

**Comment by g-roman-2024** [comment]
Thank you @shadowspawn , that indeed did the trick - I had thought that was just for preventing the parser output to be displayed, but it does also capture the help menu. Very much appreciated :) Closing this one as completed.
