### ISSUE TITLE
Alias flags to option values

### ISSUE THREAD

**Issue by ByScripts** [yargs/yargs#275]
Given a `buy` command which can take one or more fruits:

`./buy --fruit=apple --fruit=orange`

Is there a way to add multiple aliases to `fruit`, each one having a different value ?

For example,`-a` to be an alias of `--fruit=apple` and `-o` to be an alias of `--fruit=orange`

So `./buy -a -o` would be the same as the first example.

**Comment by ByScripts** [comment]
Something like this would be great:

```js
yargs
    .option('fruit')
    .alias('a', 'fruit', 'apple')
    .alias('o', 'fruit', 'orange')
    .alias('b', 'fruit', 'banana')
    // ...
```

**Comment by jonatasnona** [comment]
maybe a better way to do what you want is redesign your options args:

```
yargs
       .option('fruits', {alias: 'f'})
       // ...

// array of fruits
args.fruits.split(',');
```
and use like that
```
./buy --fruits=apple,orange
```
what do you think?

**Comment by ByScripts** [comment]
No need to split in this case, there already is an option for accepting arrays :)

And that doesn't solve the problem, the use is still having to type the entire words.

My first example wasn't about accepting multiple values for an option, but to alias a short flag to a long option (which could accept values)

For example, being able to alias `-p` to `--output-format=pdf` or `-b` to `--primary-color=blue`

BTW, not only short flag should be accepted... A `--pdf` should alias `--output-format=pdf` and a `--html` should alias `--output-format=html`.

Would be great :)

**Comment by nexdrew** [comment]
@ByScripts Thanks for the suggestion!

I finally got a chance to look at this. The tl;dr answer is no - the current version of yargs (3.27.0 at time of this comment) does not allow you to use a boolean/flag alias to represent a particular default value for the option it's aliasing. I think this is an interesting feature request. :+1:

Oddly enough, I can get yargs to behave in (almost) the opposite way, when it comes to the aliases. (And using `nargs` doesn't help.) **Disclaimer: this doesn't work - don't do this!**

```js
var argv = require('yargs')
  .describe('fruit', 'nutritious and delicious')
  .option('a', {
    alias: ['app', 'fruit'],
    default: 'apple'
  })
  .option('b', {
    alias: ['ban', 'fruit'],
    default: 'banana'
  })
  .option('o', {
    alias: ['org', 'fruit'],
    default: 'orange'
  })
  .help('h').alias('h', 'help')
  .argv
console.log(argv.fruit)
```

```sh
$ node issue275.js
[ 'apple', 'banana', 'orange' ]
$ node issue275.js -a -o
banana
$ node issue275.js --app --org
banana
```

In the meantime, hopefully it's not too difficult to work around? **This works - try it!**

```js
var defaults = {
  'a': 'apple',
  'b': 'banana',
  'o': 'orange'
}

var argv = require('yargs')
  .option('fruit', {
    describe: 'nutritious and delicious',
    type: 'string'
  })
  .option('a', {
    alias: 'app',
    describe: 'Alias for --fruit=apple',
    type: 'boolean'
  })
  .option('b', {
    alias: 'ban',
    describe: 'Alias for --fruit=banana',
    type: 'boolean'
  })
  .option('o', {
    alias: 'org',
    describe: 'Alias for --fruit=orange',
    type: 'boolean'
  })
  .help('h').alias('h', 'help')
  .argv

Object.keys(defaults).forEach(function (key) {
  if (argv[key]) argv.fruit = [].concat(argv.fruit || []).concat(defaults[key])
})

console.log(argv.fruit || 'no yummy fruits :(')
```

```sh
$ node issue275.js
no yummy fruits :(
$ node issue275.js -a -o
[ 'apple', 'orange' ]
$ node issue275.js --app --org
[ 'apple', 'orange' ]
$ node issue275.js --fruit apple --fruit=orange
[ 'apple', 'orange' ]
$ node issue275.js --fruit apple --fruit=orange -b
[ 'apple', 'orange', 'banana' ]
```

I know this becomes difficult to maintain when you have a lot of options, but better than nothing? :grinning:

**Comment by bcoe** [comment]
we introduced the concept of `middleware` some time back, this gives you the option to add a handler during the parsing process that can provide some of these advanced parsing options:

https://github.com/yargs/yargs/blob/master/docs/advanced.md#middleware

I'd advocate using this approach for implementing the functionality you're describing 👍 

In general, I'm trying to avoid extending on yargs' API surface too much further; instead adding more configuration options at the parser level, and features like middleware.
