### ISSUE TITLE
Nested options from a configuration file are skipped when one option is given as a command line argument.

### ISSUE THREAD

**Issue by crito** [yargs/yargs#292]
I'm running the following code:

```
#!/usr/bin/env node
var argv = require('yargs')
  .option('twitter.consumer_key', {
    nargs: 1,
    type: 'string',
    desc: 'consumer key'})
  .option('twitter.consumer_secret', {
    nargs: 1,
    type: 'string',
    desc: 'consumer secret'})
  .config('c')
  .help('h')
  .argv;

console.log(argv);
```

And my config file looks like that:

```
{
  "twitter": {
    "consumer_key": "key",
    "consumer_secret": "secret"
  }
}
```

Calling the program with the configuration file gives me the expected output:

```
./cmd.js -c config.json                            
{ _: [],
  h: false,
  c: 'config.json',
  twitter: { consumer_key: 'key', consumer_secret: 'secret' },
  '$0': 'cmd.js' }
```

When I provide one of the nested options as a command line argument, the other fields in the configuration file are skipped (in this case `consumer_secret`):

```
./cmd.js -c config.json --twitter.consumer_key haha
{ _: [],
  h: false,
  c: 'config.json',
  twitter: { consumer_key: 'haha' },
  '$0': 'cmd.js' }
```

I would expect that `twitter.consumer_key` is overwritten by the command line argument, but that I still have `twitter.consumer_secret` from the configuration file. The behaviour can be tracked to the [`setConfig` function in `parser.js`](https://github.com/bcoe/yargs/blob/master/lib/parser.js#L342-L344). `setConfig` makes a test if a key (in our case `twitter`) already exists and skips the configuration file option. This works for flat configuration files, but not for nested ones. `setConfig` should recursively traverse into the object for nested options and update accordingly to the path.

**Comment by elas7** [comment]
Hey @crito, this issue should be solved in the current version of yargs! Please take a look when you can and let us know. Thanks!
