### ISSUE TITLE
suggestion: simplify argv object / granular control

### ISSUE THREAD

**Issue by boneskull** [yargs/yargs#294]
Say you've gathered `argv` like so:

``` js
const argv = yargs.option('baloney', {
  alias: 'b'
})
  .demand(1)
  .argv;
```

I _always_ do something like this afterwards:

``` js
const files = argv._;
const options = argv.filter(function(value, key) {
  return key.length > 1;
});

mainFunc(files, options);
```

Use case:
- The executable using **yargs** is simply an wrapper around an API; the CLI is only one method of accessing the API.
- The API validates its input.
- The fewer keys to worry about, the easier it is to validate `options`.
- Moreover, data duplication sux.

I'd like to propose similar behavior:
- The options object supports a new property, `store`.
- The value of `store` determines in which `argv` property the value is stored.
- If `store` is an `Array` of `string` values, it will be stored in each supplied property.
- Omitting `store` retains default behavior.

I don't _think_ this use case is entirely off-the-wall.  It provides granular control over what ends up in `argv`--your CLI needn't name its flags as expected by your API.

**Comment by bcoe** [comment]
One idea I've been kicking around, that addresses a similar issue, is creating a new module `alias-object`. This module would handle all the logic around alias keys (this is more annoying than you'd think, supporting transitive aliases, etc.

Perhaps rather than adding an additional options setting, we could expose this new object? It would have a method that returns all keys/values without alias keys/values.

**Comment by boneskull** [comment]
This would solve my use case. Granted there are myriad workarounds, but it's save me some boilerplate.

**Comment by coreyfarrell** [comment]
@boneskull recent versions of yargs-parser have an option that I think accomplishes your goal:
```js
const argv = yargs.option('baloney', {
  alias: 'b'
})
  .demand(1)
  .parserConfiguration({'strip-aliased': true})
  .argv
```

See https://github.com/yargs/yargs-parser#strip-aliased and the following option `strip-dashed`.

**Comment by bcoe** [comment]
@coreyfarrell I had forgotten that this feature was added, good catch @coreyfarrell.
