### ISSUE TITLE
Bash completion for commands not working?

### ISSUE THREAD

**Issue by jakub-g** [yargs/yargs#314]
I don't understand how the completion is supposed to work.

With this command

```
var yargs = require('yargs')
  .command('help',
    'Print available commands')
  .command('manual',
    'Print extended help')
  .completion('completion', function(current, argv, done) {
    setTimeout(function() {
      done([
        'apple',
        'banana'
      ]);
    }, 500);
  });
```

`node test.js --get-yargs-completions` prints nothing. I'd expect to see `apple banana`. When I don't provide the custom function, it doesn't output anything neither while I'd expect `help manual`.

I'm on Win7 git bash 1.9.5 but this should not matter. When I use handcrafted completion it works fine.

As a workaround, is there an API of yargs that would return me `['help', 'manual']` in this case so I can do handcrafted completion suggestions handling myself?

Edit: I've realized the calling `.argv` seems to be required to run some parts of the code, I revised my example but it still doesn't work

```
var yargs = require('yargs')
  .command('help',
    'Print available commands')
  .command('manual',
    'Print extended help')
yargs.completion()
yargs.argv
```

**Comment by jakub-g** [comment]
```
    // while building up the argv object, there
    // are two passes through the parser. If completion
    // is being performed short-circuit on the first pass.
    if (completionCommand &&
      (process.argv.join(' ')).indexOf(completion.completionKey) !== -1 &&
      !argv[completion.completionKey]) {
      return argv
    }
```

I'm seeing `parseArgs` called only once, and it returns early inside this `if`

**Comment by elas7** [comment]
@jakub-g This should be fixed in the current version of yargs. Please take a look a let us know. Thanks!
