### ISSUE TITLE
Load nested options from environment variables

### ISSUE THREAD

**Issue by jbcpollak** [yargs/yargs#332]
Is it possible to load nested options from environment variables? For example:

    var opts = require('yargs')
        .env('APP')
        .option('scanner.host', {
            alias: 's',
        })
        .argv;

I would like to be able to do:

`APP_SCANNER_HOST=localhost npm start`

**Comment by nexdrew** [comment]
@jbcpollak Thanks for the question! Wasn't sure anyone was actually using the env var support yet. :smile:

Unfortunately, it's not possible to set nested values via env vars in the current code. It's always just converting the underscore-separated name into camelCase.

The parser could possibly be a little more intelligent when it comes to matching env vars to options, but we may prefer to support this with a change to the API - either by allowing env vars to be mapped explicitly to options, or maybe by defining some kind of nested env var prefix.

That being said, you should be able to accomplish this manually by doing something like:

```
var argv = require('yargs')
  .env('APP')
  .option('scanner.host', {
    alias: 's',
    describe: 'The host for the scanner'
  })
  .help('help').alias('help', 'h')
  .check(function (argv, aliases) {
    if (!argv.scanner) argv.scanner = {}
    argv.scanner.host = argv.s || argv.scannerHost
    return true
  })
  .argv
console.log(argv)
```

Maybe not optimal, but it will work.

Thoughts?

**Comment by jbcpollak** [comment]
Hum, thats a bit clunky, but I'll check it out. 

I was expecting the `.` in a nested parameter to be translated to `_`. This would conflict with a parameter named `scanner_host`, but I would accept that limitation (and give `scanner_host` priority). This seems like an edge condition a developer would be crazy to run into anyway.

In other words, given an environment variable `APP_SCANNER_HOST` I would assign this to parameters in the following order:

  - scanner_host (if defined)
  - scannerHost (if defined)
  - scanner.host (if defined)
  - scanner_host (as a default if nothing matching is declared)

**Comment by nexdrew** [comment]
That make sense, though we may want to just make the order of precedence configurable.

The parser is actually not doing **any** option matching for env vars right now (meaning it ignores configured options completely, with a slight exception for config options), so this is definitely something we can look at if/when we add option matching logic. As is, the parser just looks at the env vars and then, if any match the prefix, it simply converts the name to camelCase and applies it to `argv`, regardless of what options are configured.

Anyway, thanks for the suggestion! This definitely helps us define the next iteration of env var support.

**Comment by bcoe** [comment]
@jbcpollak how do you feel about this proposal as an alternative implementation:

https://github.com/bcoe/yargs/issues/362

I think @nexdrew's suggestion is elegant, and could start to make command handling significantly better.

**Comment by jbcpollak** [comment]
Hi, I've started using Mozilla's convict to solve this problem, it was just
more of an immediate fit for me, so please take what I say with a grain of
salt.

I think that suggestion is great for command line tools (the example is
pretty obviously git), but it's not so relevant for server processes, which
is what my use case is. I don't know which or both use cases you target
(command clearly targets CLI tools) or if it's practical to support both in
a single library.

The positional parameters with optional sub-parameters makes a lot of sense
for a CLI tool. It's less useful for a server process, where you might want
to expose many settings from different sections to the CLI or environment.

Also for cloud deployments, its often much easier to set environment
variables than to set command line params. There is usually a way to adapt
environment variables to command line params, but who wants to maintain a
custom bootscript if you can avoid it?

Anyway, I think the suggestion is great, but I'm not sure it solves what I
was looking for. That being said, it might be a better fit for yargs
intended use case than what I asked for.

**Comment by bcoe** [comment]
@jbcpollak if you again decide to take yargs for a spin, we've now implemented an approach for nested environment variables:

https://github.com/yargs/yargs-parser/pull/26

**Comment by jbcpollak** [comment]
@bcoe - I like the change - if I have a chance I'll try it out, nice work!
