### ISSUE TITLE
Isolate completion functionality from shell integration

### ISSUE THREAD

**Issue by abelnation** [yargs/yargs#335]
Just like you can use yargs to parse any string (not just `process.argv`), it would be great to be able to get completions for any string.  Currently, it looks like `completions.js` relies on `process.argv` explicitly.

**Comment by bcoe** [comment]
@abelnation don't suppose you would be willing to take a stab at this?

**Comment by rwjblue** [comment]
Looks like this was addressed by https://github.com/yargs/yargs/pull/470.

**Comment by bcoe** [comment]
@rwjblue thanks for helping us perform bookkeeping on old issues.
