### ISSUE TITLE
transfer yargs to https://github.com/yargs

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#389]
There are quite a few places where yargs is linked, so we should be mindful when we make this transfer:

- [x] the yargs docs site on the website.
- [x] any links on the website that link to yargs?
- [x] coveralls
- [x] travis
- [x] appveyor
- [x] links in package.json

Am I missing anything?

**Comment by lrlna** [comment]
woot woot! the transfer process has begun :tada:
