### ISSUE TITLE
nested commands

### ISSUE THREAD

**Issue by dennisjac** [yargs/yargs#394]
Hi,
I'm trying to get yargs to support nested commands but I can't get it to work properly.
Here is what I'm currently doing:

```javascript
var agent_list_yargs = function () {
    return yargs
        .option('verbose2', {
            alias: 'v2',
            describe: 'verbose2 output'
        })
        .usage('List agents')
        .help()
}

var agent_yargs = function() {
    return yargs.
        usage('Agent commands')
        .command('list', 'List agents', agent_list_yargs, function (argv){
            console.log(argv)
        })
        .updateStrings({
            'Commands:': 'Commands:'
        })
        .demand(2, 'No command provided')
        .help()
};

var argv = yargs
    .usage('Command line tool')
    .command('agent', 'Agent commands', agent_yargs, function (argv){
        console.log(argv);
    })
    .updateStrings({
        'Commands:': 'Category:'
    })
    .demand(1, 'No category provided')
    .help()
    .alias('h', 'help')
    .argv;
```
This basically works but there are a couple of issues here:
1. I can call this with "app.js agent list" but also with "app.js list agent" i.e. the order of the commands is ignored.
2. In agent_yargs I need to use demand(2) instead of the expected demand(1) (the first argument was already checked for one layer above).
3. Apparently the sub-commands inherit the updateStrings() settings from the layers above. This should probably be reset for each level as the workaround of specifying  updateStrings({'Commands:': 'Commands:'}) looks a bit awkward.

While 2 and 3 are really just style issues in a way number 1 is really a problem.
Am I doing something wrong here?

**Comment by bcoe** [comment]
@dennisjac I think there's a chance that positional arguments might work a bit better for this use-case, then you could do something like this (and not worry about order):

```js
.command('agent <cmd>')
```

Where command would be populated with, as an example, `list`.

**Comment by nexdrew** [comment]
We have at least fixed the 2nd item:

> 2. In agent_yargs I need to use demand(2) instead of the expected demand(1) (the first argument was already checked for one layer above).

with #582. This will be in the upcoming 5.0.0 release. 🎉 

Items 1 and 3 are still issues. 😞 I'm not sure we will "fix" number 3, but I think we will probably do something about number 1.

> 1. I can call this with "app.js agent list" but also with "app.js list agent" i.e. the order of the commands is ignored.

Note, however, that the problem doesn't prevent you from defining a top-level command with the same name as a nested subcommand. For instance, you could define a top-level `list` command and you'd get the correct (different) behavior for `app.js agent list` (calls the nested `list` command of the `agent` category) and `app.js list agent` (calls the `list` category with `agent` in `argv._`).

**Comment by bcoe** [comment]
@dennisjac #582 is out with `yargs@5.x`; give it a shot:

`npm cache clear; npm i yargs@next`

If @nexdrew's workarounds don't do the trick for you, please feel free to open a new issue for points `1` and `2`.
