### ISSUE TITLE
Print text before the help appears [Opposite of .epilogue()]

### ISSUE THREAD

**Issue by sn0w** [yargs/yargs#401]
Hi! :smiley: 

While reading the yarg docs I stumbled upon the .epilogue() function.

It's really useful, but how would I print text (like some fancy ascii-arts) **before** the help appears?

I thought of something like `.prologue()`/`.prolog()` or `.intro()` but found nothing.

Thanks in advance!

**Comment by nexdrew** [comment]
@sn0w Try the [`.usage()` method](http://yargs.js.org/docs/#methods-usagemessage-opts) if you want the text to be part of the help content (but displayed first).

If you _don't_ want the text to be part of the help content, then you can just `console.log('any text here')` before you access `yargs.argv` (which parses the command line args and prints help/error content if necessary).

Let us know if this doesn't suit your needs. Thanks!

**Comment by nexdrew** [comment]
@sn0w Gonna go ahead and close this. If there's something else you'd like to see yargs do, feel free to open another issue. Thanks!
