### ISSUE TITLE
Reset + Parse + Command Fails to Reset argv Passed to Handler

### ISSUE THREAD

**Issue by michaelcaplan** [yargs/yargs#421]
Hi,

New to yargs, so I might be doing something wrong.  Scenario is as follows:

 - Electron app running as a singleton (other attempts to open the app get forwarded to the first instance)
 - I have a bunch of yargs.command()s setup with handlers
 - Initial setup of yargs and parsing of argv runs a-okay.  command hander gets passed the parsed argv
 - Before handing a followup call to yargs.parse(), I yargs.reset() then parse.
 - The command handler always receives the argv from the first parse process
 - I do capture the results of yargs.parse() and the result on first, second, or third call is always right.  Just the argv param passed to the command handler never updates itself.

Am I missing something?

Thanks,

Mike

**Comment by bcoe** [comment]
@michaelcaplan could you share some sample code that's failing?

**Comment by bcoe** [comment]
@michaelcaplan just want to bump this, could you perhaps provide a minimum failing example of this behavior -- you might have already moved on in frustration, but I'd love to solve this issue for future generations 😛

**Comment by nexdrew** [comment]
Closing this for now. If it's still an issue, please open another issue with some sample code. Thanks!
