### ISSUE TITLE
Suggestion: allow passing an object instead of a configuration file path to yargs

### ISSUE THREAD

**Issue by elas7** [yargs/yargs#423]
Let's say you want to have some internal logic in your application to parse configuration files, and then send the result object to yargs.

Right now, you could do it by defining a custom parser in config(). But I really don't need to take a filename as an input, nor having it as an user option available in the CLI. Here is an example using config():

```javascript
yargs
.config('settings', function() {
  return {'a':1, 'b':2}
})
.default('settings', 'fakepath')
```

If a way to directly pass an object is implemented, it is important for the object to have the same order of precedence as a config file passed to config(), so that it is bellow command line args, but above defaults.

Thanks!

**Comment by bcoe** [comment]
@elas7 give `npm i yargs@next` a spin, I've pulled in your yargs-parser changes.

**Comment by bcoe** [comment]
@elas7 could you give:

`npm i yargs@next`

a try; if things are working well we can promote it to latest tomorrow.
