### ISSUE TITLE
Using strict() within the command's options

### ISSUE THREAD

**Issue by alinex** [yargs/yargs#426]
I tried to use a command with it's own additional options (coffee script):

    builder: (yargs) ->
      job = 'test'
      yargs
      .demand 1
      .usage "\nUsage: $0 <job> [options]"
      .option 'xtest',
        alias: 'x'
        type: 'string'
      .group 'x', "#{string.ucFirst job} specific:"
      # help
      .help 'h'
      .alias 'h', 'help'
      .epilogue "For more information, look into the man page."
      #.strict()
    handler: (args) ->
      console.log 'test'
      console.log args

It works fine, the help page looks good but if I use the `strict()` here I get:

    Unknown argument: test

Why is it having a problem with the command name `test` here as an argument?

**Comment by alinex** [comment]
As JavaScript the command module would look like:

    module.exports = {
      builder: function(yargs) {
        var job;
        job = 'test';
        return yargs.demand(1).usage("\nUsage: $0 <job> [options]")
        .option('xtest', {
          alias: 'x',
          type: 'string'
        })
        .group('x', (string.ucFirst(job)) + " specific:")
        .help('h').alias('h', 'help')
        .epilogue("For more information, look into the man page.");
      },
      handler: function(args) {
        console.log('test');
        return console.log(args);
      }
    }

**Comment by nexdrew** [comment]
@alinex I can confirm this bug. The "unknown arguments" validation check induced by `.strict()` is not context- or command-aware, so it's attempting to validate the full `argv._` array against reset command keys.

I think we need to introduce some concept of command context (e.g. levels of nesting, what command is currently being executed, etc) to fix this and to better support nested commands/subcommands. The logic to "reset" things is already there, so we can probably use that to drive this; we just need to add some mechanism to keep track of the resets, I think.

I'll see if I can put together a quick PR to get this ball rolling. Thanks for reporting this!

**Comment by nexdrew** [comment]
This was fixed in [4.4.0](https://github.com/yargs/yargs/blob/master/CHANGELOG.md#v440-20160403-2110-0700). 👍
