### ISSUE TITLE
Update tests that use .command() improperly

### ISSUE THREAD

**Issue by nexdrew** [yargs/yargs#429]
There are still a handful of tests that use the 3.x `.command()` API like so:

```js
.command('wombat', 'wombat burrows', function (yargs, argv) {
  return argv
})
```

But this is misleading b/c 4.x no longer supports passing `argv` as the 2nd argument to the "function which used to be the handler but is now the builder".

Let's update these tests so they are compatible with the 4.x `.command()` API, either using:
- a builder function and handler function
- a module with `builder` (object or function) and `handler` (function) properties
- or an options object and handler function

**Comment by lrlna** [comment]
@nexdrew I shall clean this up :koala:
