### ISSUE TITLE
`.normalize` doesn't work with `.array`

### ISSUE THREAD

**Issue by ljharb** [yargs/yargs#430]
I have an arg that I define with `.array('paths')` - i want this to be N paths, and i want each path normalized. However, when I `.normalize('paths')`, it works when there's 1 - but fails when there's > 1.

Could `.normalize` be extended to support arrays of paths?

**Comment by bcoe** [comment]
@ljharb this should now be available with `npm i yargs@next`, give it a spin and let me know what you think.

**Comment by ljharb** [comment]
@bcoe awesome, this looks great!

This script:
```sh
#!/usr/bin/env node

var args = require('yargs')
  .normalize('path')
  .array('paths')
  .normalize('paths')
  .array('notpaths')
  .argv;

console.log(args, args.path, args.paths);
```
ran with `./test.js quux --path ./foo --paths ./foo ./bar ./baz --notpaths ./foo ./bar ./baz`
prints out:
```sh
{ _: [ 'quux' ],
  path: [Getter/Setter],
  paths: [ 'foo', 'bar', 'baz' ],
  notpaths: [ './foo', './bar', './baz' ],
  '$0': 'test.js' } 'foo' [ 'foo', 'bar', 'baz' ]
```

While it's pretty weird that "path" is a getter/setter instead of a normal value, and that all the items in "paths" are normal values (thus not consistent with "path"), all of them are normalized properly. Thanks!
