### ISSUE TITLE
default `.demand` message has counts, provided one can't?

### ISSUE THREAD

**Issue by ljharb** [yargs/yargs#431]
How can I do `.demand(n, msg)` such that `msg` can contain a count of the number of non-option arguments provided?

**Comment by bcoe** [comment]
@ljharb I like the idea of being able to have a simple placeholder in your message, such as:

`%i`, but this feature doesn't yet exist.

**Comment by ljharb** [comment]
That's exactly what i was thinking - just like `usage` has `$0`.

**Comment by ljharb** [comment]
I went ahead and made a PR - please let me know your thoughts!

**Comment by bcoe** [comment]
demand has now been split into `demandCommand` and `demandOption`, the first for positional arguments, and the latter for options.

https://github.com/yargs/yargs/blob/master/docs/api.md#demandoptionkey-msg
