### ISSUE TITLE
Weird bug where numbers are wrong

### ISSUE THREAD

**Issue by nichoth** [yargs/yargs#440]
The numbers don't match!

```js
// test.js
var argv = require('yargs').argv;
console.log(argv);
```

    $ node test --foo=1202285736968061337
    { _: [], foo: 1202285736968061400, '$0': 'test' }

**Comment by elas7** [comment]
The underlying cause is that the number is bigger that `Number.MAX_SAFE_INTEGER`.

If your use case allows it, you could tell yargs to interpret the value as a string:

```javascript
// test.js
var argv = require('yargs')
  .string('foo')
  .argv;
console.log(argv);
```

```
$ node test --foo=1202285736968061337
{ _: [], foo: '1202285736968061337', '$0': 'test' }
```

**Comment by bcoe** [comment]
@nichoth turns out JavaScript had pretty bad numeric precision, give this a shot:

```js
var i = 1202285736968061337
console.log(i)
```

I think you'll get the same output? Your best bet is probably using a big number module and accepting the input as a string.

**Comment by bcoe** [comment]
What @elas7 said :)

Give this module a shot, and accept the argument as a string.

https://www.npmjs.com/package/bigint

**Comment by nichoth** [comment]
Thanks all for the amazingly quick responses.
