### ISSUE TITLE
question: fake cli input for testing

### ISSUE THREAD

**Issue by philkunz** [yargs/yargs#442]
Is there a good way to fake cli input with yargs for testing without having to call a script via bash etc. ?

**Comment by nexdrew** [comment]
@philkunz Not quite sure what you're after, but you can use the same approach that the tests use:

```js
var yargs = require('yargs')

// pass fake CLI args when calling yargs as a function
var argv = yargs('--foo wut')
  .option('foo', {
    type: 'string',
    default: 'bar'
  })
  .argv

console.log(argv)
```

Executing this will ignore `process.argv` and instead parse `'--foo wut'`.

```
$ node issue442.js --foo no
{ _: [], foo: 'wut', '$0': 'issue442.js' }
```

Is that what you're looking for?

**Comment by philkunz** [comment]
yes, that is exactly what I am looking for! Thank you!

**Comment by nexdrew** [comment]
@philkunz No problem. Thanks for using yargs, and good luck!
