### ISSUE TITLE
Unable to use required positional arguments in strict mode

### ISSUE THREAD

**Issue by th0r** [yargs/yargs#444]
For parsing my args I want to use strict mode (not allow passing of any extra args).
I have 1 required position argument and some required and optional options.

Test configuration (`test.js`):
```js
#! /usr/bin/env node
'use strict';

const argv = require('yargs')
  .required(1, 'Provide required positional argument')
  .options({
    optional: {
      describe: 'optional option'
    },
    required: {
      describe: 'required option',
      required: true
    }
  })
  .strict()
  .argv;

console.log(argv);
```

Running this script with different options:
```bash
$ ./test.js
Provide required positional argument

$ ./test.js positional
Missing required argument: required

./test.js positional --required
Unknown argument: positional

./test.js positional --required --optional
Unknown argument: positional
```

Removing `strict()` statement fixes the situation:
```bash
./test.js positional --required
{ _: [ 'positional' ],
  required: true,
  '$0': 'test.js',
  optional: undefined } 
```

**Comment by nexdrew** [comment]
I can confirm this bug. It appears to be a regression in 4.x. The problem is that strict mode now validates positional arguments against registered commands, but it doesn't ignore commands when none are registered!

I'll try to put a quick PR together.

@th0r Thanks for reporting this!

**Comment by nexdrew** [comment]
@th0r The fix has been released as version 4.3.2. Please give it a shot when you have a chance and let us know. Thanks!

**Comment by th0r** [comment]
@nexdrew Works like a charm now! Thanks a lot!

**Comment by bleathem** [comment]
I'm seeing this in yargs@12.0.2
