### ISSUE TITLE
The pkg-conf is pretty big

### ISSUE THREAD

**Issue by Siilwyn** [yargs/yargs#449]
So `pkg-conf` depends on 26 dependencies of which a lot are not required for `yargs` to work. This includes a promise library, checking if a package is on GitHub, validating the project license and a few more. I think this is quite some bloat for an optstrings parser.

Would it be an idea to replace the `pkg-conf` with something smaller?

**Comment by bcoe** [comment]
@Siilwyn I really like @sindresorhus' modules. They do have a lot of dependencies true, but they're all very well tested, and if they ever break the are fixed within hours.

**Comment by sindresorhus** [comment]
All the dependencies that are mine are super tiny. Many of those packages are polyfills for Node.js 0.12. Soon we'll probably be able to drop Node.js 0.12 support and then it will be a lot less. The rest are there for a reason making the module more durable, like stripping UTF-8 BOM, improved JSON errors, handling awful Windows filesystem stuff, etc. That being said, I found an easy win https://github.com/sindresorhus/pkg-conf/commit/4c8816a34a40360b6fe350d9c0b635dfc8df16b2 to lose some dependencies (26 → 14) (the biggest ones). When Node.js 0.12 support is dropped, it will only be 9 tiny dependencies.

**Comment by Siilwyn** [comment]
That is really great to hear @sindresorhus, thanks for the time and effort!
