### ISSUE TITLE
Make .demand() depend on context?

### ISSUE THREAD

**Issue by maxrimue** [yargs/yargs#451]
This question was raised in #428.

As of right now, `.demand()`, when called, does not care about the context it was called in, meaning that if you `.demand(1)` inside a command, it won't throw, because the the command itself satisfies `.demand()` already:
```javascript
var yargs = require('yargs')(['lol'])
        .command('lol', '', (yargs) => yargs.demand(1)) // Won't throw
        .argv;
```

However, you could argue that if used inside a command, `.demand()` should ignore the command itself so that the upper example won't work anymore.

How does everybody think about this? Should `.demand()` be contextual, stay as it is, or even become more configurable to allow both?

**Comment by nexdrew** [comment]
I think we should consider this for 5.x. I don't think the current `.demand()` behavior for commands makes sense. It's possible that #504 obviates this, but we still might want to change this.
