### ISSUE TITLE
Add ability to process specified options prior to .demand()

### ISSUE THREAD

**Issue by plroebuck** [yargs/yargs#453]
Recently migrated from `optimist` and was very happy with your drop-in replacement. Glancing the documentation, saw there were new capabilities and desired to delegate all option processing to this module. Our app, **abao**, has a single required parameter, so I modified the code as such:
```js
var argv = yargs
    .usage("Usage: \n  abao </path/to/raml/file> [OPTIONS]" +
    "\n\nExample: \n  " + "abao api.raml --server http://api.example.com")
    .options(Abao.options)
    .wrap(80)
    .demand(1, "abao: Must specify path to RAML file")
    .argv;
```

But I discovered that once I added `.demand()`, other *one and done* options no longer process correctly. For example, if I invoke application as such:
```bash
$ abao --version
```

It now displays usage and error for missing argument. Same for `--help` and a couple other
"output'n'quit" style options that don't *actually* require the argument needed for the app's primary functionality.
.
In order to make use of the `.demand()` functionality, I need to be able to specify certain options
that should be handled **before** `.demand()` processing begins, for those not *actually* requiring the argument needed for the app's primary functionality.

**Comment by maxrimue** [comment]
In order to use `--help` and `--version`, have a look at the [help](https://github.com/yargs/yargs#helpoption-description) and [version](https://github.com/yargs/yargs#versionoption-description-version) methods, as both options don't exist out of the box

**Comment by nexdrew** [comment]
@plroebuck Max is correct. Try changing your code to this:

```js
var argv = require('../qi/yargs')
    .usage("Usage: \n  abao </path/to/raml/file> [OPTIONS]" +
    "\n\nExample: \n  " + "abao api.raml --server http://api.example.com")
    .options(Abao.options)
    .wrap(80)
    .demand(1, "abao: Must specify path to RAML file")
    .help().alias('h', 'help')       // new line
    .version().alias('v', 'version') // new line
    .argv;
```

This will allow `--help` (or `-h`) and `--version` (or `-v`) to short-circuit typical processing.

**Comment by nexdrew** [comment]
We should also mention that using `.version()` in yargs 4.x will automatically lookup the version number from your package.json file - hopefully a convenient little bonus.

**Comment by plroebuck** [comment]
Sorry, I had these options already defined, accessed via `Abao.options` above.

```coffeescript
options =
  ## Lots of unlisted options

  reporters:
    description: 'Display available reporters and exit'

  help:
    description: 'Show usage information and exit'

  version:
    description: 'Show version number and exit'

module.exports = options
```

**Comment by nexdrew** [comment]
In that case, you should probably remove those from `Abao.options` and use this code instead:

```js
var argv = yargs
    .usage("Usage: \n  abao </path/to/raml/file> [OPTIONS]" +
    "\n\nExample: \n  " + "abao api.raml --server http://api.example.com")
    .options(Abao.options)
    .wrap(80)
    .demand(1, "abao: Must specify path to RAML file")
    .help('help', 'Show usage information and exit')
    .version().describe('version', 'Show version number and exit')
    .argv;
```

Does that work for you?

**Comment by plroebuck** [comment]
@nexdrew, it does fix the problem for these two specific options, but not genericly.
As shown above, my `reporters` argument works just like `help` does.
Why wouldn't the `options` as previously given work?

**Comment by nexdrew** [comment]
Help and version options are treated as a special case; currently yargs doesn't support generic short-circuiting options.

For this level of customization, you would probably be better off replacing `.demand(1)` with a custom `.check()` function, like so:

```js
var argv = yargs
    .usage("Usage: \n  abao </path/to/raml/file> [OPTIONS]" +
    "\n\nExample: \n  " + "abao api.raml --server http://api.example.com")
    .options(Abao.options)
    .wrap(80)
    .check(function (argv) {
      if (!argv.reporters && argv._.length < 1) throw new Error('abao: Must specify path to RAML file')
      return true
    })
    .help('help', 'Show usage information and exit')
    .version().describe('version', 'Show version number and exit')
    .argv;
```

I'm afraid that's about the best yargs can do at the moment.

**Comment by plroebuck** [comment]
Need something just like [help](https://github.com/yargs/yargs#helpoption-description), except that it outputs a string I specify (or via function call). The `help` function would be a special case of it.

**Comment by nexdrew** [comment]
@plroebuck That's a good suggestion we should consider.

I'm curious, how did you achieve this functionality using optimist before?

**Comment by plroebuck** [comment]
Would it be hard to implement? Seems "small-ish" upgrade to the code [here](https://github.com/yargs/yargs/blob/master/yargs.js#L650). Rename `helpOrVersion` to `shortcircuit` and add capability to allow specifying *shortcircuitedness* to individual `options`.

**Comment by plroebuck** [comment]
@nexdrew, we have **groan** [hardcoded checks](https://github.com/cybertk/abao/blob/master/bin/abao) now, but I believe `yargs` is capable of handling all our cmdline processing with the improvements made since `optimist`, assuming `shortcircuit` capability available.

**Comment by plroebuck** [comment]
@nexdrew, any issues with PR?

**Comment by bcoe** [comment]
@plroebuck nope, sorry that I've been a bit slow to land pull requests this week (some big new features launching at npm).
