### ISSUE TITLE
Sync error of handler should throw a global error

### ISSUE THREAD

**Issue by satazor** [yargs/yargs#455]
```
// foo.js
'use strict';

const yargs = require('yargs');

yargs
.help('help').alias('help', 'h')
.command('foo', 'Foo command is awesome', () => {
    console.log('foo handler');
    throw new Error('This error will show below the help');
})
.argv;
```

If you now run `node foo` it will show the usage and the error below.

<img width="716" alt="screen shot 2016-03-26 at 21 39 45" src="https://cloud.githubusercontent.com/assets/1017236/14062557/8585162c-f39b-11e5-8f4c-603e4e8a8f64.png">

I was expecting the error to be thrown globally and not being handled by yargs.

yargs version: 4.3.2

**Comment by nexdrew** [comment]
@satazor In yargs 4.x, the first function (3rd argument) is a builder (configuration) and you should specify a second function (4th argument) as the handler.

What happens if the error is thrown from the handler function instead? Does it then do what you expect?

```js
yargs.command('foo', 'Foo awesome', (yargs) => {
  return yargs
}, (argv) => {
  throw new Error('error message')
})

```

**Comment by satazor** [comment]
Sorry, I made a mistake in the example. Though the output of the sample code above with the handler still has the same output:

```js
'use strict';

const yargs = require('yargs');

yargs
.help('help').alias('help', 'h')
.command('foo', 'Foo awesome', (yargs) => yargs, (argv) => {
    console.log('foo handler');
    throw new Error('error message');
})
.argv;
```

<img width="679" alt="screen shot 2016-03-26 at 21 58 14" src="https://cloud.githubusercontent.com/assets/1017236/14062640/e11c0192-f39d-11e5-9ddd-06eed319470c.png">

**Comment by nexdrew** [comment]
Ok, I see. If you want to customize this behavior, I think you need to define your own `.fail()` function.

```js
yargs.fail((msg, err) => {
  // do something here, maybe throw err
})
```

Let us know how that works for you.

**Comment by satazor** [comment]
I see, but is this the correct default behaviour? I was not expecting `yargs` to be handling handler errors. For instance, the handler contains a programming error, the consumer of the CLI would be looking at help usage + `Cannot access X of undefined`.

AFAIK, this kind of stuff was ok in v3 but changed in v4.

**Comment by nexdrew** [comment]
I could be wrong, but I think yargs has always behaved this way. It's a convenience for gracefully handling runtime handler errors. I don't think yargs expects coding errors :) and doesn't attempt to distinguish between the two.

**Comment by satazor** [comment]
I don't think handling of runtime errors is a good idea. Showing a help usage + a programming error is very misleading to CLI users. If a runtime error occurs it is much better to simple show the stack trace and exit which is what nodejs does by default. If the CLI dev really wants to do some "validation" they really should do it with `.check()`.

That's my opinion and respect that you disagree with it. Lets see what others think about it.

**Comment by nexdrew** [comment]
Fair enough, but before others weigh in, would you mind confirming if you can achieve the desired behavior using `.fail()`?

**Comment by satazor** [comment]
No, not easily. The problem is that `fail()` is called with an error message and not an Error instance. Even if it was called with an Error instance I had to distinguish between TypeError among others to either show the stack trace and exit or print the help usage.

**Comment by nexdrew** [comment]
The `Error` instance is passed as the 2nd argument. Note my example above and see #382. You should be able to rethrow that. Please confirm.

**Comment by satazor** [comment]
Alright so that makes things possible, but still not very developer friendly:

```js
yargs
...
.fail((msg, err) => {
    if (err instanceof TypeError || err instanceof ParseError || .. and a lot of more native errors) {
       return setImmediate(() => { throw err; });
    }

    yargs.showHelp();
    process.stderr.write(msg + '\n');
    process.exit();
});

// or....

yargs
...
.fail((msg, err) => {
    // For yargs errors
    if (err was throw by yargs validation of args or check()) {
        yargs.showHelp();
        process.stderr.write(msg + '\n');
        process.exit();
    }
    
    // For runtime errors
    return setImmediate(() => { throw err; });
});
```

**Comment by nexdrew** [comment]
Ok, thanks. At least we know there's a workaround.

So you'd like yargs to distinguish between runtime errors and language errors - throw if language, handle if runtime (with delegation to `.fail()`).

We should also document the 2nd argument given to the fail handler.

Does this accurately summarize your request?

**Comment by satazor** [comment]
> So you'd like yargs to distinguish between runtime errors and language errors - throw if language, handle if runtime (with delegation to .fail()).

Well kind of. I expect yargs to not handle errors that come from command handlers.

**Comment by jagin** [comment]
I got the same problem as @satazor and I fully support his proposal.

**Comment by bcoe** [comment]
@satazor I had this exact same discussion over lunch with @iarna last week; I agree that we shouldn't be handling runtime errors, and would like to figure out a better approach in the command handlers.

@satazor basically, are you thinking that we track all the errors that yargs itself generates, perhaps with a special key on the Error object, and throw anything we don't know about?

**Comment by satazor** [comment]
@bcoe yes, either with a key or a subclassed error similar to what [got](https://github.com/sindresorhus/got/blob/master/index.js#L16) is using.

**Comment by bcoe** [comment]
@satazor hope all is well :)

I've finished releasing yargs@7 which introduces its own error class, and should bubble application-level errors to the top. Would love your help testing the 7.x release (which is a pretty big refactor):

`npm cache clear; npm i yargs@next`

CC: @iarna

**Comment by iarna** [comment]
W...why would you clear the cache? 😭 Your poor cache.

Seriously though, there's almost never a reason to ever clear your cache. Please stop! =D
