### ISSUE TITLE
config() does not apply to sub commands

### ISSUE THREAD

**Issue by kumar303** [yargs/yargs#464]
I was surprised that this doesn't work. A config file:

```
{
  "verbose": true,
  "thing": {
    "source": "/path/to/source"
  }
}
```

And with yargs looking something like:

``` javascript
yargs
  .config('config')
  .options({
    verbose: {
      type: 'boolean',
    }
  })
  .command('thing', 'does a thing', function(yargs) {
    yargs.options({
      source: {
        type: 'string'
      }
    });
  });
```

The config file value of `thing.source` is not applied as the default value for the `thing --source` option.
Is that by design? If so, maybe it could be documented. 

Could you suggest another way to accomplish this? I know I could make two config files, one for the main program and one for the sub command but that won't be very nice for users of the tool.

**Comment by nexdrew** [comment]
@kumar303 I'm a little confused about what you're trying to accomplish. Do you want to access the value of `source` within the `thing` handler as `argv.thing.source` or as `argv.source`?

**Comment by nexdrew** [comment]
Is this the behavior you're looking for?

```js
yargs
  .config('config')
  .global('config') // apply --config to commands
  .options({
    verbose: {
      type: 'boolean'
    }
  })
  .command('thing', 'does a thing', function (yargs) {
    return yargs // don't forget return statement here
      .options({
        source: {
          type: 'string'
        }
      })
      .check(function (argv) { // use check to apply --source to argv.thing.source
        if (argv.source) {
          if (argv.thing) argv.thing.source = argv.source
          else argv.thing = { source: argv.source }
        }
        return true
      })
  }, function (argv) {
    console.log('argv.thing.source:', (argv.thing || {}).source)
  })
  .argv
```

```
$ node issue464.js thing                       
argv.thing.source: undefined
```

```
$ node issue464.js thing --config issue464.json 
argv.thing.source: /path/to/source
```

```
$ node issue464.js thing --source /another/path
argv.thing.source: /another/path
```

```
$ node issue464.js thing --config issue464.json --source /override/with/this
argv.thing.source: /override/with/this
```

**Comment by kumar303** [comment]
What I want is to use one config file to specify any main option *as well as* any sub command option. I want to access the value set from a config file just the same way as I would access any real command line option value.

ok, it looks like `global('config')` was definitely one thing I was missing. Thanks.

However, I'm still not clear on how to do this. Do I use the `check()` function? How would I know if a user passed in a real sub-command option value versus a config file value?

To illustrate it another way, what I want is:

````
{
  "thing": {
    "source": "/configured/path/",
  }
}

$ program thing --config ./config.json
-> /configured/path/

$ program thing --config ./config.json --source /overridden/path/
-> /overridden/path/
````

**Comment by nexdrew** [comment]
I think the sample code I posted gives you the results you describe, albeit in a roundabout way :smiley:.

In my code, you know if the user provided `--source` on the command line if `argv.source` is populated, in which case it is preferred; otherwise if `argv.thing.source` is populated, then it comes from the config file.

It's not super straightforward, but does that make sense?

**Comment by kumar303** [comment]
ok, I see how to do it now. Thanks for all your help. It would be nice if yargs automatically munged config values together for sub commands since it already does so for main options but I can make it work as is.

Feel free to close the issue. The crux of it was that I was missing `global('config')` which seems a bit obscure (because it's not obvious that `config` is a "key") so an extra note about this in the [config docs](http://yargs.js.org/docs/#methods-configkey-description-parsefn) would be nice.

**Comment by nexdrew** [comment]
@kumar303 Very good points!

When it comes to issues like this, my first goal is to help folks figure out a workaround to get the desired behavior as quick as possible. Now that we've done that, I think we can turn this into a couple requests (as you mention):

1. Augment nested opts parsing logic to account for "command key > option within command" instead of just shoving things into an object graph

2. Either (a) make config options global by default or (b) document the fact that they are not

Does this sound about right?

**Comment by kumar303** [comment]
Yes to both! I can't think of why config options shouldn't be global by default.

**Comment by nexdrew** [comment]
@kumar303 Cool. Would you mind creating a separate issue for "Make non-command config options global by default"? We can use this one for the first request. That way we can discuss the merit of both requests independently.

**Comment by kumar303** [comment]
> Augment nested opts parsing logic to account for "command key > option within command" instead of just shoving things into an object graph

Actually, I just thought about this more ^ and once that's implemented, I don't think config options need to be global by default.

**Comment by nexdrew** [comment]
But if the config option is not global (and not redeclared in the command builder), then it will be ignored (reset) for command execution.

**Comment by kumar303** [comment]
so you need it to implement the nested config parsing logic so it can apply to sub commands?

**Comment by kumar303** [comment]
I ran into another problem trying to use the workaround for applying a config to sub command options. I cannot detect if an option was passed on the command line when that option declares a default value.

**Comment by HencoBurger** [comment]
Jvhg

**Comment by bcoe** [comment]
@kumar303 we now default the majority of options to being applied globally, this seems much less surprising for folks!
