### ISSUE TITLE
add support for default commands to yargs

### ISSUE THREAD

**Issue by m-mujica** [yargs/yargs#467]
Hey guys, is there any way to do something like:

`yargs.command("*", [module])` 

similar to [commander](http://tj.github.io/commander.js/#Command.prototype.command)

I found https://www.npmjs.com/package/yargs-default-command but does not seem to work with 4.x

Thanks,

**Comment by maxrimue** [comment]
Hey @m-mujica,

unfortunately, there currently is no official way how to do this in yargs. What do folks think about adding this kind of default command that applies if an unknown command or none is called?

**Comment by nexdrew** [comment]
I like this idea. Seems like it would help simplify some "control flow" logic with commands, so you don't have to use some sort of custom state to keep track of if a command was executed or not.

**Comment by vjpr** [comment]
**Workaround**

```
  import yargsParser from 'yargs-parser'
  const args =  args = process.argv
  const parsed = yargsParser(args)
  const useDefaultCommand = parsed._.length === 2
  const defaultCommand = 'publish' // <-- set name of your command here
  if (useDefaultCommand) {
    args.splice(2, 0, defaultCommand)
  }
  const argv = yargs.parse(args)
```

**Comment by bcoe** [comment]
@nexdrew @m-mujica I like the idea of following prior art, and using `*` 👍

**Comment by nexdrew** [comment]
@vjpr brings up a good point.

1. Do we treat the default command just like a hidden command, so it can still apply config for options, validation, etc?
2. Should it affect usage/help content at all?
3. Can I mark a regular named command as the default?

**Comment by bcoe** [comment]
@timoxley closed https://github.com/yargs/yargs/issues/719 in favor of this; I continue to wish we had a simple method like `defaultCommand()` that would allow a default command that fires if no positional arguments are provided; @nexdrew has some really neat ideas around this feature too, surrounding how default commands relate to command aliases.

**Comment by bcoe** [comment]
Another related ticket: https://github.com/yargs/yargs/issues/728

**Comment by bcoe** [comment]
@ahmadnassri I closed your issue in favor of this one, I would love to figure out what the ideal API would be for handling a default or "top level" command.

**Comment by ahmadnassri** [comment]
@bcoe thx, I did come across this one, I figured it to be non-related. but if you see them as such, I'll keep watching here.

**Comment by maxrimue** [comment]
Okay, I'd like to work on this feature to get it landed possibly in v7. My current proposal would be to make default commands happen like this:
- Any existing command with name and handler can get a `default: true` in its builder
- Command gets called either by name or if no command is supplied
- Help output adds a bold **[default]** to said command

This way, you have minimal work to set things up and can even still explicitly call the command. We can also avoid making folks duplicate commands like that, in case they want an actual name _and_ default behaviour. What does everyone think?

**Comment by bcoe** [comment]
@m-mujica @maxrimue @nexdrew, I'm 100% in agreement that having a way to handle default commands in `7.x` of yargs should be a goal -- it will make program flow-control much more consistent.

Where I'm not 100% in agreement, is whether we should use the `*` syntax, or simply introduce a new API method like `.defaultCommand('batman')`; I could be swayed in either direction.

@nexdrew or @m-mujica perhaps you could create a straw-man pull request for this feature, just to continue the discussion?

**Comment by bcoe** [comment]
@m-mujica @vjpr @ahmadnassri, hey! update ... we're planning on releasing @nexdrew's implementation of default commands in the next release.

They work essentially like @m-mujica describes:

https://github.com/yargs/yargs#default-commands

I would love your help testing the new feature, before we push it out to more people:

`npm cache clear; npm i yargs@next`.

**Comment by atian25** [comment]
@bcoe seem this feature is undocument at http://yargs.js.org/docs

**Comment by nexdrew** [comment]
@atian25 Concerning this:

> try yargs@next and found an issue, when set a command name to `['start', '*']`, then exec `my-bin --help` will not print other commands help

We're [aware of this issue](https://github.com/yargs/yargs/issues/803) and [will have the fix in soon](https://github.com/yargs/yargs/pull/810).

Let us know if you find any other oddities or problems. Thanks!
