### ISSUE TITLE
Yargs is no longer lighweight.

### ISSUE THREAD

**Issue by osher** [yargs/yargs#468]
It started as lightweight, and was very cool (and still is).
But it's not lightweight.

Once installed, the size of a package including all its dependencies:

Yargs@4.4.0:  
 -  990Kb 
 - (418 files, 123 folders)

nomnom@1.8.1:
- 115K
- (35 files, 9 folders)

Commander@2.9.0:
 -   40Kb
 - (11 files, 2 folders)

ahm... :(

I was advocating for it, and was corrected by my listeners
It's not lightweight. It's ritch with features.

Since I don't think we should drop functionality, I suggest to correct the misleading description...

**Comment by bcoe** [comment]
@osher I'm for this, I also think we should look at if we're checking in anything we can avoid -- we have quite a few dependencies so it does add up unfortunately.

**Comment by nexdrew** [comment]
@bcoe It looks like the following dependencies could stand some cleanup:

```
# cliui@3.1.2
./cliui/test

# read-pkg-up@1.0.1 > read-pkg@1.1.0 > normalize-package-data@2.3.5 > hosted-git-info@2.1.4
./hosted-git-info/test
./hosted-git-info/test/lib

# read-pkg-up@1.0.1 > read-pkg@1.1.0 > normalize-package-data@2.3.5
./normalize-package-data/test
./normalize-package-data/test/fixtures

# read-pkg-up@1.0.1 > read-pkg@1.1.0 > normalize-package-data@2.3.5 > semver@5.1.0
./semver/test

# yargs-parser@2.2.0
./yargs-parser/test
./yargs-parser/test/fixtures
```
