### ISSUE TITLE
parse-numbers

### ISSUE THREAD

**Issue by alesl** [yargs/yargs#477]
I added yargs stanza in my package.json and set parse-numbers to false, but my options still get parse as string. Since number are rather large (40 chars hex encoded numbers) values get corrupted as floats. Anybody else has problem with this or is there any options to set default type for unspecified options?

**Comment by bcoe** [comment]
@alesl hey, I just tested this on `yargs@4.4.0` with the setting:

```json
  "yargs": {
    "parse-numbers": false
  }
```

And I'm getting strings rather than #s, as I would expect. Could you provide a failing example for us to work from? I wonder if there's a slight difference your development environment from mine.

**Comment by alesl** [comment]
Yes, you are correct - I should have properly test this before reporting. I'm sorry I wasted your time. 
Somehow I managed to install some older version. I installed latest version and now it works flawlessly.
