### ISSUE TITLE
Mock/Stub yargs

### ISSUE THREAD

**Issue by raphaklaus** [yargs/yargs#484]
Hello! 

I'm using yargs in one of my projects, and in my CLI test, I want to mock/stub yargs. Is there a method to help achieve this?

**Comment by maxrimue** [comment]
Yes, there is. If you want to mock user input for yargs you can do it like so:

```javascript
const argv = yargs(["--say", "hello"])
    // your code goes here
    .argv
```

or so:

```javascript
const argv = yargs("--say hello")
    // your code goes here
    .argv
```

**Comment by raphaklaus** [comment]
Thank you!
