### ISSUE TITLE
Unparse arguments

### ISSUE THREAD

**Issue by MeanwhileMedia** [yargs/yargs#503]
This is more of a feature request (as I don't currently see this feature in docs). Might we have a way to convert parsed args back into string format?
One use case could be when a process uses yargs to parse it's args, then manipulates those args during it's lifespan, but later needs to instantiate a child process that receives the args.

**Comment by bcoe** [comment]
@MeanwhileMedia you should be able to access `process.argv` directly, even after yargs has parsed the string; none of the values are changed in place.

Let me know if this does the trick for you.

**Comment by MeanwhileMedia** [comment]
Thanks for the quick response @bcoe. 
My problem is that I call yargs...argv when the process first starts. The object that yargs returns (argsObj) is passed around and manipulated by that process. argsObj becomes a representation of the process's state. At this point, process.argv becomes "outdated".

Eventually, in my app, the process will need to pass it's state into a new child process.  This is why I want to convert argsObj back into a string that I can throw into a cli command.

I"ve build a simple solution to unparse, but I'm currently only traveling a single level deep (see below). It might be nice for yargs to support this in a more extensive manner.

```
      var unparsedString = ''
      _.each(argsObj, function(value, key){
        //We currently only support one layer deep of nested args (dot notation).
        if(_.isArray(value)){
          unparsedString = unparsedString+' --'+key+' '+value.join(' ')
        } else if(_.isObject(value)){
          _.each(value, function(subValue, subKey){
            unparsedString = unparsedString+' --'+key+'.'+subKey+'='+subValue
          })
        } else {
          unparsedString = unparsedString+' --'+key+' '+value
        }
      })
```

**Comment by jdalton** [comment]
This might be helpful: [moxystudio/yargs-unparser](https://github.com/moxystudio/yargs-unparser).

**Comment by bcoe** [comment]
@MeanwhileMedia as @jdalton mentions, we're unlikely to ever add this to yargs itself, but we now have the program `yargs-unparser` 😄
