### ISSUE TITLE
v4.7.1 tag not published to github

### ISSUE THREAD

**Issue by TheAlphaNerd** [yargs/yargs#506]
This is making citgm sad :cry:

**Comment by lrlna** [comment]
don't cry citgm -- we fix it 👯

**Comment by lrlna** [comment]
in fact, @bcoe already fixed it !

**Comment by bcoe** [comment]
@TheAlphaNerd sorry about that, pushed the branch but not the tag.

**Comment by TheAlphaNerd** [comment]
Y'all rock!
