### ISSUE TITLE
Call the wrong command handler in some situation

### ISSUE THREAD

**Issue by KohPoll** [yargs/yargs#514]
I'm not sure if this is a bug...

I just add two commands:

```javascript
// cli.js
#!/usr/bin/env node
var yargs = require('yargs');
yargs.command('foo', 'the foo command', {}, function(argv) {
  console.log('command foo--', argv);
});
yargs.command('bar', 'the bar command', {}, function(argv){
  console.log('command bar--', argv);
});
console.log(yargs.parse(process.argv.slice(2)));
```

```bash
$ ./cli.js foo
```

It call command foo's handler, and print: `command foo-- { _: [ 'foo' ], '$0': 'cli.js' }`.

```bash
$ ./cli.js bar foo
```

***It also call command foo's handler! But I think it should call command bar's handler.***

And I dig into the source code, <https://github.com/yargs/yargs/blob/master/yargs.js#L645>:

```javascript
if (~argv._.indexOf(cmd) && cmd !== completionCommand) {
  setPlaceholderKeys(argv)
  return command.runCommand(cmd, self, parsed)
}
```

Why `argv._.indexOf(cmd)` not is `argv._[0] === cmd`?

**Comment by bcoe** [comment]
@KohPoll this feels like a bug with commands that should be addressed.

**Comment by bcoe** [comment]
@nexdrew wanted to get this patched too, before we release your command fixes in `4.8.0`. Any quick fix we might also be able to land for https://github.com/yargs/yargs/issues/529, while we're at it? Could we just be creative with how we pass the `require` context to https://github.com/yargs/require-main-filename?

@KohPoll mind giving this fix a spin?

`npm cache clear; npm i yargs@next` 👍

**Comment by KohPoll** [comment]
I just tested the next version(3.8.0), it works well.Thanks for your good job!!

**Comment by bcoe** [comment]
@KohPoll sorry to bug you again, mind giving this one more shot:

`npm cache clear; npm i yargs@next`

I'm going to release it to `latest` later today once tests pass.

**Comment by KohPoll** [comment]
It works well, nice~

```bash
$ npm cache clear; npm i yargs@next
yargs@4.8.0-candidate3 node_modules/yargs
```

```bash
/cli.js foo bar
command foo-- { _: [ 'foo', 'bar' ], '$0': 'cli.js' }
{ _: [ 'foo', 'bar' ], '$0': 'cli.js' }

./cli.js bar foo
command bar-- { _: [ 'bar', 'foo' ], '$0': 'cli.js' }
{ _: [ 'bar', 'foo' ], '$0': 'cli.js' }
```
