### ISSUE TITLE
.strict() does not work as expected

### ISSUE THREAD

**Issue by centigrade-thomas-becker** [yargs/yargs#518]
The documentation about strict() reads:

> Any command-line argument given that is not demanded, or does not have a corresponding description, will be reported as an error.

If I tell yargs to be strict about parsing commands and options I would expect it not to accept *any* unspecified commands or options. But it seems to be only working for **commands** and not options.

This will show the help screen and print an error at the bottom:
`mycommand foo --bar`
> Unknown arguments: bar, foo

This is correct, since there is no command named "foo" and no option named "bar" declared for "mycommand".

However, this will not trigger an error:
`mycommand export --bar` ("export" is a valid command)

It will correctly parse the command "export" and then proceed as normal. It won't show any indication that an invalid option has been passed. It will even create create a key for "bar" in the argv object.

Here is my complete command:

```
var yargs = require('yargs')
            .usage('\nUsage: ' + scriptFilename + ' <command> [options]')
            .command('export', 'Request projects form Mantis and save them to file')
            .strict()
            .option('start-date', {
                demand: false,
                default: moment().subtract(1, 'month').startOf('month').format('YYYY-MM-DD'),
                describe: 'Format YYYY-MM-DD',
                type: 'string'
            })
            .option('end-date', {
                demand: false,
                default: moment().subtract(1, 'month').endOf('month').format('YYYY-MM-DD'),
                describe: 'Format YYYY-MM-DD',
                type: 'string'
            })
            .option('f', {
                alias: 'file',
                demand: false,
                default: 'all.trackings-report',
                describe: 'Target file for the "export" command',
                type: 'string'
            })
            .option('d', {
                alias: 'debug',
                demand: false,
                default: false,
                describe: 'Debug mode',
                type: 'boolean'
            })
            .help('h')
            .alias('h', 'help');

var argv = yargs.argv;

if (argv._ == 'export')
{
    exportCommand();
}
else
{
    yargs.showHelp();
}
```

My beef is that it won't throw an error if a user misspells an option, e.g "--date-start" instead of "--start-date". I thought the strict() option was the way to handle this, but maybe I am mistaken.

**Comment by maxrimue** [comment]
What you need to do is enable strict mode within the command as well. I agree that this is not well described, or mentioned at all in the documentation.

You can achieve this by adding a `builder` function to your command, which then returns a new yargs configuration that only applies to that command. In this configuration, you simply enable strict mode like before:
```javascript
.command('export', 'Request projects form Mantis and save them to file', yargs => {
  return yargs
    .strict()
})
```

**Comment by centigrade-thomas-becker** [comment]
Thanks, that helped me get the result I wanted.

**Comment by maxrimue** [comment]
@centigrade-thomas-becker I've opened a new issue (#526) to address this in the documentation. Thanks for submitting your issue!
