### ISSUE TITLE
make command builder work without returning

### ISSUE THREAD

**Issue by moranje** [yargs/yargs#522]
I like the new commandDir feature but I have been having a bit of trouble getting a few of the other functions to work. The one I bumped into were `default` and `demand`. I am new to yargs, so I may just be 'holding it wrong'.

It starts with a cli.js
```js
#!/usr/bin/env node

const yargs = require( 'yargs' );

yargs // eslint-disable-line no-unused-expressions
  .commandDir( 'commands' )
  .help( 'h' )
  .alias( 'h', 'help' )
  .wrap( yargs.terminalWidth() )
  .version()
  .alias( 'version', 'v' )
  .argv
```

I have a folder called `commands` which holds two files: new.js and generate.js

```js
// new.js
exports.command = 'new <project>';
exports.description = 'description';
exports.builder = ( yargs ) => {
  yargs.example( 'example' )
    .option( 'B', {
      alias: 'b',
      description: 'description'
    } )
    .demand( 'B' ) //  or demand( 1, 'B' ) or demand( 1, [ 'B' ] )
    .strict();
};
exports.handler = ( argv ) => {
  // Handle
};
```
I expect it to skip the handle and present the user with the help menu when I type `cli new app`, but it goes right into the handler function (which breaks because I never expect argv.B to be empty)

In the second file, I have set the default values for two of the options but their respective keys on the argv object returned in the handler function contain no values if they aren't explicitly set. So: `cli generate file name` => `argv.p` and `argv.b` will be empty. 

```js
// generate.js
exports.command = 'generate <file> <name>';
exports.description = 'description';
exports.builder = ( yargs ) => {
  yargs.example( 'examplee' )
    .option( 'p', {
      alias: 'P',
      description: 'description',
      choices: [ 'firstChoice', 'secondChoice' ],
      default: 'firstChoice'
    } )
    .option( 'b', {
      alias: 'B',
      description: 'description',
      choices: [ 'firstChoice', 'secondChoice' ],
      default: 'firstChoice'
    } )
};

exports.handler = ( argv ) => {
  // Handle
};
```

Could I be doing something wrong here or should this work?

Thanks, Martien

**Comment by bcoe** [comment]
@moranje looks like you're most of the way there, I think the problem is that you need to return inside the builder, like so:

```js
exports.builder = ( yargs ) => {
  return yargs.example( 'example' )
    .option( 'B', {
      alias: 'b',
      description: 'description'
    } )
    .demand( 'B' ) //  or demand( 1, 'B' ) or demand( 1, [ 'B' ] )
    .strict();
};
```

Let me know if this does the trick for you.

_having said this:_

It seems like commands would be  more straight forward if this wasn't a requirement; does it seem like a reasonable API change to make the `return` not a requirement? CC: @nexdrew 

__an aside: `wrap()` defaults to terminal-width_

**Comment by moranje** [comment]
Indeed! That did the trick. I must have missed that. Both methods work as advertised now.

`.wrap( yargs.terminalWidth() )` also right aligns the type, required and default values, which wrap() shows as one long left aligned string.

Thanks for your help

**Comment by bcoe** [comment]
@moranje in yargs `5.x`, we've removed the requirement for returning the yargs object; give this a spin:

`npm cache clear; npm i yargs@next`
