### ISSUE TITLE
passing parameters into command handler

### ISSUE THREAD

**Issue by brumer** [yargs/yargs#523]
I'm trying to build a server which accepts a command line and handles it using commands in a structure described in commandDir.
My problem is that i want to pass the ClientRequest object or some other information to the different commands without using a singleton that each command need to require. 
Meaning each command should be able to return information somehow..

Is there a way i can assign things to the argv object that is accepted in the command handler?
perhaps passing additional parameter to the handler?

thanks.

**Comment by pedalhead** [comment]
This issue was closed by the creator, but I would still be interested in hearing if there is a good way to pass data into the handler, by somehow setting on the argv object, as brumer suggested.

**Comment by bcoe** [comment]
@pedalhead there is now a way to do just this:

https://github.com/yargs/yargs#parseargs-context-parsecallback

**Comment by pedalhead** [comment]
Awesome, somehow I missed it... Thanks!
