### ISSUE TITLE
--help <argument> should show extended help for an specific argument

### ISSUE THREAD

**Issue by hhaamm** [yargs/yargs#528]
--help command seems to me a bit limited. There's no much space on the screen for describe the arguments in more detail. So I'd like commands to have another option (that could be `extendedDescription()` method) that can be shown when doing:

`--help <command>`

`--help` would continue working as it is now.

`--help <unexistentcommand>` might throw an error.

I'd like to work on this feature so if you agree with this feature and you have any idea of where I can start implementing it please point me to the right files. Thanks.

**Comment by bcoe** [comment]
@hhaamm if you use the [command functionality](https://github.com/yargs/yargs#commandmodule), and run:

`<command> --help`

You will receive extended help. This order of operations is what I've tended to see with other applications, e.g.,

`git commit --help`

Would still love to have your future contributions to yargs! also let us know how your experimentation with the command functionality goes, would love any thoughts you have about how to clarify the documentation.

**Comment by hhaamm** [comment]
@bcoe Sorry, maybe my post was confusing. When I wrote command I wanted to say param (or config option). What I'm really using is string(), boolean() and number() methods for parsing params. So I'd like extended help for `params`.

What I'm doing now is:

```
yargs
.describe("somekey", "short desc")
.string("somekey")
```

Maybe it would be good to add an extended description to the `describe` method. This is because the help for commands doesn't allow me to add a lot of description. Anyway I think I'll workaround the problem.

**Comment by bcoe** [comment]
@hhaamm could you write a little pseudo program for me with the inputs and outputs you'd like? would help me understand the difference between this and command specific help better 💯 

Always open to supporting new features that folks need.
