### ISSUE TITLE
Using yargs as a library

### ISSUE THREAD

**Issue by AljoschaMeyer** [yargs/yargs#532]
I'd like to use yargs for command definition and parsing as part of another program. However, yargs directly uses the global `console` and `process` objects, which makes this difficult. The parser has been extracted as a library, but I'd like access to other yargs features like option validation and help message generation as well. Is there a way to use these without yargs doing global logging or randomly exiting the process?

There are some workarounds I could do, but these come with some disadvantages (and are rather ugly):
- Wrap yargs-access into functions which hijack the necessary globals and reset them to their original value after the yargs-access
- Fork a child-process for each yargs-access

But in a perfect world, yargs would simply expose an API in which e.g. help information is returned as a string rather than logged. Yargs would then use this API itself, resulting in no changes for any existing programs which use it. Thoughts on this, by those who know the codebase?

*Edit:* My use-case is to delegate the command definition and parsing functionality of [vorpal](https://github.com/dthree/vorpal) to a dedicated library (such as yargs). Vorpal currently needs to implement its own parsing, consequently reinventing the wheel and introducing bugs. I'm just exploring some possibilities though, this might not actually make it into vorpal.

**Comment by bcoe** [comment]
@AljoschaMeyer I think if you use `var yargs = require('yargs/yargs`)`, rather than `require('yargs')`. And run it like so:

```js
const yargs = require('./yargs')
const argv = yargs(['--arg', '--arg2'])
  .option('arg', {

   })
   .exitProcess(enable)
   .argv
```

It should do the trick for you. Let me know any hiccups you run into and we can patch them.

**Comment by bcoe** [comment]
@AljoschaMeyer let me know if it's okay to close this ticket gets you on the right path, and we can close it and open specific issues for anything that does not behave as expected.

**Comment by AljoschaMeyer** [comment]
Ok, thanks for the help, this looks like a good starting point. I might still have some trouble with [self.fail in usage.js](https://github.com/yargs/yargs/blob/master/lib/usage.js#L35). Just by skimming through the code, I don't see an intended way to access these messages without having them logged to the console.

**Comment by bcoe** [comment]
@AljoschaMeyer it definitely looks like we fall into a bit of a trap here:

```js
      if (!failureOutput) {
        failureOutput = true
        if (showHelpOnFail) yargs.showHelp('error')
        if (msg) console.error(msg)
        if (failMessage) {
          if (msg) console.error('')
          console.error(failMessage)
        }
      }
```

once you play a bit, just let me know some changes you'd like to see to the API and I'll land them quickly -- let's make it so it's easier to consume as an API.

**Comment by AljoschaMeyer** [comment]
Looks like I missed the [fail function](http://yargs.js.org/docs/#methods-failfn) exposed by the API - it actually does exactly what I need. So yargs actually provides everything necessary for usage as a library:

- [exitProcess](http://yargs.js.org/docs/#methods-exitprocessenable) needs to be invoked with `false` so that it doesn't exit the program
- [fail](http://yargs.js.org/docs/#methods-failfn) can be used to receive failure messages rather than having them logged tot he console
- [showHelp](http://yargs.js.org/docs/#methods-showhelpconsolelevelerror) can be used to get yargs' help message. When given a function as an argument, rather than logging the help message, yargs invokes the function with the message as the single argument (the documentation for this behaviour could be a lot clearer though)

For now this looks to me like its everything necessary. I might reopen this if I stumble upon something else while trying things out (which might take some time due to busy real life).

**Comment by bcoe** [comment]
@AljoschaMeyer I think it's worth noting this thread, and some ongoing refactoring work that will be happening around errors:

https://github.com/yargs/yargs/issues/539

Also pleas feel free to provide any feedback about how things could be made more elegant with this API.

**Comment by pedalhead** [comment]
require('yargs/yargs') was exactly what i needed to help solve an issue I was having.  It would be awesome to have this documented as an example in the readme.
