### ISSUE TITLE
Request: opposite of "implies"

### ISSUE THREAD

**Issue by ljharb** [yargs/yargs#534]
`implies('x', 'y')` means that if "x" is supplied, "y" _must_ be supplied.

I'd like a way to designate that if "x" is supplied, "y" must _not_ be supplied.

Perhaps it could be called ".conflicting(x, y)"

**Comment by slx2005** [comment]
+1, this sounds like a good idea, a case would be if choices were set, but you have another arg which could be an override to these choices, 

```
args = require('yargs')
.option('f', {
    alias: 'fruit',
    describe: 'choose fruit.',
    choices: ['orange', 'apple', 'banana'],
})
.option('c', {
    alias: 'custom-fruit',
    describe: 'set a custom fruit.'
})
.conflicting('c', 'f');
```

**Comment by bcoe** [comment]
this seems reasonable to me. we have enough slight breaking changes queued up, and API fixes, that I'd like to start marching towards a 5.x release of yargs.

Perhaps we can add this as one of the goals here: https://github.com/yargs/yargs/issues/519

**Comment by hax** [comment]
I also suggest support `-c | -f` notation in command pasing:

```js
yargs.command('test [-c | -f] <args..>')
```

But the basic problem is command parsing only support postional arguments now, I wish it support options too. Should I open a separate issue?

**Comment by ljharb** [comment]
@hax as a new syntactic shorthand for "conflicting"? Is that an argument notation that's used elsewhere? If nothing else uses that convention I don't think yargs should be adding it.

**Comment by madcampos** [comment]
@ljharb answering about this convention:
>Arguments separated by the '|' ( <vertical-line>) bar notation are mutually-exclusive. Conforming applications shall not include the '|' symbol in data submitted to the utility. Alternatively, mutually-exclusive options and operands may be listed with multiple synopsis lines.

From: [POSIX docs](http://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html) (got it from [Wikipedia](https://en.wikipedia.org/wiki/Command-line_interface#cite_ref-6))

Also, if it's still open for taking I want to help.

**Comment by ljharb** [comment]
@madcampos thanks, so it seems to be a notational convention, not something typed by the user. that makes sense.

**Comment by nexdrew** [comment]
TIL the `.implies()` method interprets any keys prefixed with `--no-` as "when this key is _not_ given", such that you can make two arguments mutually exclusive.

Here's an example:

```js
const argv = require('yargs')
  .implies('x', '--no-y') // -x and -y are mutually exclusive but neither is required
  .argv
console.log(argv)
```

```console
$ node issue534.js -x this        
{ _: [], x: 'this', '$0': 'issue534.js' }
```

```console
$ node issue534.js -y that        
{ _: [], y: 'that', '$0': 'issue534.js' }
```

```console
$ node issue534.js -x this -y that

Implications failed:
  x -> --no-y
```

```console
$ node issue534.js -y that -x this

Implications failed:
  x -> --no-y
```

If you wanted at least one of them to be given, you could add `.implies('--no-x', 'y')` to this example.

Granted the error message is a little cryptic and probably not ideal, but the functionality is pretty much already there.

**Comment by ljharb** [comment]
@nexdrew that seems like it might be really easy to add a `.conflicting` then :-p Thanks tho, I'll give that a shot.

**Comment by bcoe** [comment]
@ljharb @slx2005 @madcampos \o/

https://github.com/yargs/yargs#conflictsx-y

This goes out in the `next` release, I would love the extra help testing:

`npm cache clear; npm i yargs@next`
