### ISSUE TITLE
.pkgConf(), .normalize() and .array() not working well together

### ISSUE THREAD

**Issue by Josan-Coba** [yargs/yargs#536]
I've just found that having a package.json containing
```json
"opts": {
  "a": ["bin/../a.txt", "bin/../b.txt"]
}
```

This code crashes badly:
```javascript
const argv = require('yargs')
      .pkgConf('opts')
      .array('a')
      .normalize('a')
      .argv;
```
with `TypeError: Path must be a string. Received [ 'bin/../a.txt', 'bin/../b.txt' ]`.

If the `.array('a')` is removed it doesn't crash, but the array doesn't get normalized either.
```javascript
console.log(argv.a); //=> [ 'bin/../a.txt', 'bin/../b.txt' ]
console.log(argv.a.map(require('path').normalize)); //=> [ 'a.txt', 'b.txt' ]
```

**Comment by bcoe** [comment]
@Josan-Coba I don't think that normalize currently gets applied to an array of arguments, this is true of a few flags, e.g., I don't think if you specify that you want a type for a key `number`, `string`, etc., that this will get applied to each element in the array.

Perhaps we could aim to get this enhancement into the work we're scheduling for a `5.x` release? https://github.com/yargs/yargs/issues/519

**Comment by bcoe** [comment]
@Josan-Coba mind opening this as a ticket on https://github.com/yargs/yargs-parser, and referencing it on the `5.x` discussion (the implementation work will most likely be largely in the parser).

**Comment by bcoe** [comment]
Closing this in favor of the open ticket on `yargs-parser`.
