### ISSUE TITLE
Better error reporting for subcommands

### ISSUE THREAD

**Issue by yofreke** [yargs/yargs#539]
Continuation from: https://github.com/yargs/yargs/pull/533

------

>we've also been fairly careful to not print messages directly to the console in yargs

I totally understand, but with the current implementation you are sending the very minimally helpful (if at all) error message to stderr.  This looks almost like a bug to an end user, certainly not a thought out design decision (in my example the text "boop" is appended to the user defined help text).

>folks can register a method for handling errors

The problem with `.fail()` is that you have to register it on every command / subcommand.  This is super cumbersome for an end user who just wants to see a call stack.  I will have to dig up the example that was failing for us, but we also found that the fail handler would not be called, regardless of where it was registered (will try to find the example, and maybe open a separate issue regarding that).

I really love using yargs, it makes building a CLI 10x simpler.  The problem is that it really falls on its face when a command throws an unexpected error.  Depending on how cryptic the error message is (does it even look like an error when appended to help text?), and how savvy the programmer is (do they crawl the yargs docs to find `.fail`? Do they realise that this is an error in their code and not yargs, since they see the same error output either way?), this is they turn away and start using something else.

The real proposition is this:

- If there is an error parsing cli args
  - throw an error explicitly saying that
  - show help text
  - highlight the argument that threw an error
- If there is a missing cli arg:
  - throw an error explicitly saying that
  - show help text
  - highlight the missing arg
- If there is an error running the command handler logic
  - throw an error explicitly saying that
  - do not show red herring help text
- If there is an error anywhere in user code
  - show a full stack trace
  - do not show red herring help text

**Comment by evanderkoogh** [comment]
I completely agree that the reporting of failures is pretty much broken now.
I was very much confused when just getting the message when things went wrong. Went through all the docs, found the fail handler, implemented it and turns out it doesn't get called.

I use the following config:
```
const yargs = require('yargs')
yargs
	.command(require('./cmds/deploy.js'))
	.command(require('./cmds/build.js'))
	.demand(1, 'Need to specify at least an command')
	.fail(function(msg, err) {
		console.log('blah');
		if(err) {
			throw err
		}
		console.log(msg);
		process.exit(1);
	})
	.strict()
	.help()
	.wrap(100)
	.argv

```
I have tried adding:

```
exports.fail = function(msg, err) {
	console.log('blah');
	if(err) {
		throw err
	}
	console.log(msg);
	process.exit(1);
}
```

to the deploy.js file, but that one also does not get called.

At this point, I am manually executing all my files to find a syntax error.

**Comment by bcoe** [comment]
## with regards to `.fail()`:

@evanderkoogh, @yofreke I like the idea that we'd make the top-level `.fail()` apply to all nested commands by default, similar to how `help()` and `version()` are treated as a global.

Do you think this would be a step in the right direction?

## other scenarios outlined by @yofreke

there are configuration settings that can be wired up for some of the other requirements, e.g., failing If there is a missing cli arg, showing help on failure:

https://github.com/yargs/yargs#demandkey-msg--boolean
https://github.com/yargs/yargs#strict
https://github.com/yargs/yargs#showhelponfailenable-message

I think exiting options, combined with coercion (see https://github.com/yargs/yargs/issues/535) and  global `fail()` might get us to a much better place with regards to error handling?

**Comment by evanderkoogh** [comment]
Without a doubt, a global .fail() would be a major step in the right direction. 

But a default that shows stack traces would be even better IMO.

**Comment by yofreke** [comment]
@evanderkoogh Agreed.  I originally implemented a default `.fail()` that would have to be overridden, but it felt too heavy handed.  A global `.fail()` sounds like a good halfway.

@bcoe True, those are definitely helpful for conveying to an end user the problems in their arguments (some sugar on top would be the highlighting of failed arg).  I detailed those examples more as "this is when the help text should be shown", with the last two being "this is where the help text is not helpful anymore".

I think the global `.fail()` is a good step, but the full measure is for yargs to explicitly define all expected exceptions.  This would give us the fine grain control over things like:

`YargsError`

- `showHelptext`
- `showErrorMessage`
- `showErrorStack`

We could also have some things on it like:

- `buildCustomMessage()` which would return a custom message. This would have highlighted lines or instructions to fix, so that it is more clear to the user how to fix this error.
- `runHandlers()` which would let you run a fail handler for a specific type of error. Alternatively you could just send the custom error type in to the existing `.fail()` pipeline

**Comment by bcoe** [comment]
@yofreke, @evanderkoogh in `yargs@5.x` we now apply `fail()` globally; give this a spin:

`npm cache clear; npm i yargs@next`

I'm going to close this ticket for now but please feel free to open more issues as we continue to work on the error handling of yargs.
