### ISSUE TITLE
.implies() ignores parser preferences

### ISSUE THREAD

**Issue by maxrimue** [yargs/yargs#547]
According to the readme, you can influence the behaviour of yargs-parser by [providing a custom config](https://github.com/yargs/yargs#configuration). One thing you can configure is boolean negation, which is turned on by default, and means that `--no-foo` gets parsed as `foo: false`. By turning this off, `--no-foo` would get parsed as `no-foo: true`. This configuration and the expected outcome however is ignored by yargs' `.implies()`.

`implies()` expects two keys and requires the second to be true if the first is, too. It has extended capabilities because it also supports boolean negation, so it always sees a `--no-` not as part of the key that you want to check itself. This should however only be the case if `boolean-negation` wasn't turned off in the parser configuration. This is not caused by a bug, but rather by a missing feature, because a configuration lookup was never implemented at this point. See the necessary lines [here](https://github.com/yargs/yargs#configuration).

**Comment by bcoe** [comment]
@maxrimue great find, want to take a crack at this?

**Comment by maxrimue** [comment]
@bcoe I'll give it a try!
