### ISSUE TITLE
feature: Yargs parses longer-than-long numbers as a number instead of a string

### ISSUE THREAD

**Issue by TomFrost** [yargs/yargs#550]
Consider the following, from the node repl:

```
$ node
> 12345678901234567890
12345678901234567000
```

According to [Parsing Tricks: Numbers](http://yargs.js.org/docs/#parsing-tricks-numbers) in the docs, because `(!isNaN(Number('12345678901234567890')))` returns `true`, Yargs parses this argument as a number even though the resulting value does not match the input. As a result, the value provided by the (yargs) argv object is incorrect.

In this scenario, the number should be parsed as a string instead. Alternatively, if this were to introduce a breaking change or cause unexpected results, a flag could be added to optionally prevent yargs from parsing numbers.

**Comment by nexdrew** [comment]
@TomFrost Looks like your CLI is using yargs 3.32.0. In that version, I think your best option is this:

```js
const argv = yargs
  .usage('Usage: $0 [options] <command> <text>')
  .command('encrypt', 'Encrypt the given plaintext string')
  .command('decrypt', 'Decrypt the given base64 string')
  .command('getSecret', 'Decrypt the given stored secret')
  .demand(2)
  .option('e', {
    alias: 'environment',
    describe: 'The environment configuration to use'
  })
  .nargs('e', 1)
  .string('_') // <-- force yargs to parse all flagless args as strings
  .version(pkg.version)
  .help('help')
  .argv
```

With yargs 4.8.0 that will still work, but you could also disable implicit number parsing by adding this to your package.json:

```json
"yargs": {
  "parse-numbers": false
}
```

And even couple that with positional command args if you wanted, like so:

```js
const argv = yargs
  .usage('Usage: $0 [options] <command> <text>')
  .command('encrypt <plaintext>', 'Encrypt the given plaintext string')
  .command('decrypt <base64>', 'Decrypt the given base64 string')
  .command('getSecret <secret>', 'Decrypt the given stored secret')
  .demand(2)
  .option('e', {
    alias: 'environment',
    describe: 'The environment configuration to use'
  })
  .nargs('e', 1)
  .version(pkg.version)
  .help('help')
  .argv

// access positional args as named options instead of argv._[1]
const command = argv._[0].toLowerCase()
switch (command) {
case 'encrypt':
  return console.log('encrypting', argv.plaintext)
case 'decrypt':
  return console.log('decrypting', argv.base64)
case 'getsecret':
  return console.log('getting secret', argv.secret)
default:
  return yargs.showHelp()
}
```

The advantage of this approach is slightly better help content and unambiguous option references.

If you have other suggestions or feedback, please feel free to add them. Hope this helps, thanks for using yargs!

**Comment by bcoe** [comment]
@TomFrost as @nexdrew points out, I think upgrading to `4.8.0` would give you a few fairly clean work arounds to parsing gigantic #s \o/

**Comment by TomFrost** [comment]
These are wonderful suggestions, thank you! Yargs blows me away yet again.

With that said, I'd probably still count it as a bug that yargs will corrupt a long number entry by converting it rather than intelligently keeping it a string, without additional configuration. It would be fantastic to support that use case without turning number parsing off globally, as well, if there were another numeric argument that _would_ be convenient to have parsed in advanced. Just for your consideration :).

Thanks again for the help! Yarr.

**Comment by bcoe** [comment]
@TomFrost I hadn't thought of this, but like this suggestion -- it would be neat if we were self-aware of JavaScript's numeric bounds, and took this into account in our number guessing logic.

**Comment by sijad** [comment]
I have similar problem, when i try to run my command:

```
node getNumbers.js 0001 0002
```

I get numbers as actual numbers (e.g. `1`, `2`)

**Comment by diogoribeiro23** [comment]
@bcoe I would like to pick this up! Would you mind telling me some specifications that you want implemented or you just want Yargs to be self-aware of the JavaScript numeric bounds and if it bigger, parse it as a string?
Thanks!

**Comment by bcoe** [comment]
@TomFrost the specific issue you were running into should have been addressed by the fact that we now treat options that look like numbers as strings, if they're larger than JavaScript's `Number.MAX_SAFE_INTEGER`.

@sijad @diogoribeiro23 the issue with leading `000`s should be solved in the next release of yargs; try this:

`npm i yargs@next`

I'm closing this conversation in favor of #1099.
