### ISSUE TITLE
Option patterns

### ISSUE THREAD

**Issue by arcanis** [yargs/yargs#554]
It could be interesting to have option pattern. For example, the following:

```js
yargs.string("slack.*.clientId").argv
```

Would correctly parse the following command line:

```
--slack.firstbot.clientId 010101.010101 --slack.secondbot.clientId 101010.101010
```

(It currently can't, because both of these values are incorrectly currently casted to numbers)

**Comment by nexdrew** [comment]
@arcanis It's probably worth mentioning that you can completely disable auto-number coercion in yargs 4 by adding this to your package.json:

```json
"yargs": {
  "parse-numbers": false
}
```

See [the parser configuration section](http://yargs.js.org/docs/index.html#configuration) of the docs for other options.

**Comment by bcoe** [comment]
@arcanis I'm really excited to add this feature:

https://github.com/yargs/yargs/issues/535

for complex parsing beyond what we currently support. As @nexdrew points out, I think setting `parse-numbers` to `false`, however, would be a great fix for the number parsing issue you're running into.

**Comment by arcanis** [comment]
Thanks, I think that disabling `parse-numbers` will work just fine for me! However, I feel like this issue is still valid, regardless of #535. For example, with this option disabled, then the following won't work anymore:

```
--http.afirsthost.port 8080 --http.asecondhost.port 9090
```

However, with the original proposal, it would only require the following:

```js
yargs.number("http.*.port").argv
```
