### ISSUE TITLE
.count() mis behaves with .default().

### ISSUE THREAD

**Issue by dcbartlett** [yargs/yargs#555]
Version: yargs 4.8.0

When using the following:
```
.options('log-level', {
    alias : 'v',
    group : 'Arguments:',
    default : '3'
}).count('v')
```
the resulting arguments from `gulp build` is:
```
{ _: [ 'build' ],
  'log-level': '31',
  v: '31',
  logLevel: '31',
  '$0': 'gulp' }
```

**Comment by nexdrew** [comment]
@dcbartlett This is definitely a bug, see #500. Note that you should use a number for your default value, e.g. `default: 3` instead of `default: '3'`, but hopefully we can fix this so it accepts both.

Closing in favor of #500, please track our progress there. Thanks for reporting!

**Comment by dcbartlett** [comment]
Thanks @nexdrew
