### ISSUE TITLE
demand does not play well with command

### ISSUE THREAD

**Issue by zyy7259** [yargs/yargs#566]
I typed the code from section [http://yargs.js.org/docs/#examples-yargs-is-here-to-help-you](http://yargs.js.org/docs/#examples-yargs-is-here-to-help-you)

```js
#!/usr/bin/env node
var argv = require('yargs')
    .usage('Usage: $0 <command> [options]')
    .command('count', 'Count the lines in a file')
    .demand(1)
    .example('$0 count -f foo.js', 'count the lines in the given file')
    .demand('f')
    .alias('f', 'file')
    .nargs('f', 1)
    .describe('f', 'Load a file')
    .help('h')
    .alias('h', 'help')
    .epilog('copyright 2015')
    .argv;

var fs = require('fs');
var s = fs.createReadStream(argv.file);

var lines = 0;
s.on('data', function (buf) {
    lines += buf.toString().match(/\n/g).length;
});

s.on('end', function () {
    console.log(lines);
});
```

And execute `node line_count.js count`, but `demand('f')` does not give the hint `Missing required arguments: f`

When I comment out the `.command` line, the `demand('f')` works.

`yargs` version: `4.8.1`

**Comment by lrlna** [comment]
hey @zyy7259 ! I apologize for the faulty example here. When demanding both a command and an argument, you would be [using the syntax](http://yargs.js.org/docs/#methods-demandcount-max-msg) of `demand(1, ['f'])`. 

So the example above would look like:

```
#!/usr/bin/env node
var argv = require('./')
  .usage('Usage: $0 <command> [options]')
  .command('count', 'Count the lines in a file')
  .example('$0 count -f foo.js', 'count the lines in the given file')
  .demand(1, ['f'])
  .alias('f', 'file')
  .nargs('f', 1)
  .describe('f', 'Load a file')
  .help('h')
  .alias('h', 'help')
  .epilog('copyright 2015')
  .strict()
  .argv;

var fs = require('fs');
var s = fs.createReadStream(argv.file);

var lines = 0;
s.on('data', function (buf) {
    lines += buf.toString().match(/\n/g).length;

});

s.on('end', function () {
    console.log(lines);

});
```

I've PRed #567 to fix this particular instance `demand` in our docs. I guess another thing with it is that we are not doing anything with the `count` command there, so it's a bit obsolete. If you are actually looking to do some :cool: stuff with `command` ,  there are a bunch of examples [here](http://yargs.js.org/docs/#methods-commandcmd-desc-builder-handler). 

We are also working on fixing demand. It's a bit of a rabbit hole at the moment with handling both commands and arguments. We are tracking that in #504 and #451 .

**Comment by nexdrew** [comment]
@zyy7259 Some of our docs are obviously out of date. 😞 If @lrlna's suggestion doesn't work for you, try adding a "builder" object or function to the `.command()` and marking the `'f'` option as global, like so:

```js
#!/usr/bin/env node
var argv = require('yargs')
    .usage('Usage: $0 <command> [options]')
    .command('count', 'Count the lines in a file', {}) // <-- added {} as 3rd argument
    .demand(1)
    .example('$0 count -f foo.js', 'count the lines in the given file')
    .demand('f')
    .global('f') // <-- this line added
    .alias('f', 'file')
    .nargs('f', 1)
    .describe('f', 'Load a file')
    .help('h')
    .alias('h', 'help')
    .epilog('copyright 2015')
    .argv;

var fs = require('fs');
var s = fs.createReadStream(argv.file);

var lines = 0;
s.on('data', function (buf) {
    lines += buf.toString().match(/\n/g).length;
});

s.on('end', function () {
    console.log(lines);
});
```

We'll be sure to clean up this example in #567. Thanks for reporting!

**Comment by zyy7259** [comment]
@nexdrew Problem solved. thx~

**Comment by bcoe** [comment]
@zyy7259 the original bug should now be fixed in the `next` release of yargs:

https://github.com/yargs/yargs/pull/582

To try this out, simply run:

`npm cache clear; npm i yargs@next`
