### ISSUE TITLE
How to build help for commands with options

### ISSUE THREAD

**Issue by davibe** [yargs/yargs#569]
i have a 

```
program cmd1 subcommand1 --cmd1-option foo
program cmd2 --cmd2-option bar
```

Oddities:
- `program --help` gives me the list of possible commands AND SUBCOMMANDS but it does not include possible options
- `program cmd1 --help` gives the list of possible options, but not the possible subcommands
- `program help` or `program cmd1 help` does not output help

I don't see how i can "fix" any of those odd things. What's the correct way to support commands, subcommands, options with proper help ?

**Comment by nexdrew** [comment]
@davibe Would you mind posting some example code, or pointing us toward a repo, that demonstrates this?

Here is an example I whipped up using your pseudo CLI above:

```js
const subcommand1 = {
  command: 'subcommand1',
  desc: 'sub command 1',
  builder: {},
  handler: (argv) => {
    console.log('subcommand1 handler:', argv)
    argv._handled = true
  }
}

const cmd1 = {
  command: 'cmd1',
  desc: 'command 1',
  builder: (yargs) => yargs
    .command(subcommand1)
    .option('cmd1-option', {
      desc: 'command 1 option 1',
      type: 'string',
      global: true // <-- so it applies to subcommand1 too
    }),
  handler: (argv) => {
    if (!argv._handled) console.log('cmd1 handler:', argv)
    argv._handled = true
  }
}

const cmd2 = {
  command: 'cmd2',
  desc: 'command 2',
  builder: (yargs) => yargs
    .option('cmd2-option', {
      desc: 'command 2 option 1',
      type: 'string'
    }),
  handler: (argv) => {
    if (!argv._handled) console.log('cmd2 handler:', argv)
    argv._handled = true
  }
}

const argv = require('yargs')
  .command(cmd1)
  .command(cmd2)
  .help()
  .wrap(null)
  .argv

if (!argv._handled) console.log('outer:', argv)
```

```
$ node issue569.js --help
Commands:
  cmd1  command 1
  cmd2  command 2

Options:
  --help  Show help  [boolean]
```

```
$ node issue569.js cmd1 --help
issue569.js cmd1

Commands:
  subcommand1  sub command 1

Options:
  --help         Show help  [boolean]
  --cmd1-option  command 1 option 1  [string]
```

Currently yargs does not support an implicit `help` command, so doing `program help` or `program help cmd1` doesn't work without some coding on your part. 😞 But I think that would be a great feature request!

**Comment by dignifiedquire** [comment]
I think I have a similar issue. This is the api I wan my cli to have:

```
$ myapp config <key> [value]
$ myapp config show
```

This means I have a handler attached for the `config` and one for `show`. But when I now run 

```
$ myapp config --help
```

The handler from config executes instead of showing the help. (All code I use is pretty much identical to the example from the readme)

**Comment by nexdrew** [comment]
@dignifiedquire What do you use for the builder of your `config` command? Any chance it's just not returning the yargs instance it was passed?

**Comment by dignifiedquire** [comment]
I am confused, tried a minimal example again and things work as expected, will post tomorrow with a fresh head

**Comment by nexdrew** [comment]
@dignifiedquire Sure thing, sorry for the trouble! yargs currently requires a builder function to return the yargs instance, but this will change with #549 (which will probably go in 5.x).

**Comment by nexdrew** [comment]
FYI yargs will also support implicit `help` commands when #574 is reviewed, merged, and released.

This will allow all of the following to print help text:

```console
$ program --help
$ program help
$ program cmd --help
$ program cmd help
$ program help cmd
```

**Comment by dignifiedquire** [comment]
My problem went away, I had `builder` named `options` from an earlier version :D Thank you for this great module :)

**Comment by davibe** [comment]
I think you addressed my doubts. I can't find any objections. If i do I will reopen. Thank you

**Comment by tanjilk** [comment]
```js   
yargs.command({
    command: 'add',
    describe: 'Add a new note',
    builder:{
        title: {
            describe: 'Note title',
            demandOption : true,
            type: 'string'
        },
    },
    handler : function(argv){
        console.log('Adding a new note...');
        console.log(chalk.green(argv.title + ' succesful added!'));
    }
})   
console.log(yargs.argv);   
```
