### ISSUE TITLE
How would I describe a positional argument?

### ISSUE THREAD

**Issue by wearhere** [yargs/yargs#570]
Let's say that I'm configuring `yargs` like so:

``` js
var argv = require('yargs')
  .usage('Usage: $0 <sourceDir>')
  .demand(1)
  .argv;
```

How would I `.describe` the `sourceDir` argument?

This [similar issue](https://github.com/yargs/yargs/issues/541) discussed positional arguments to commands, but note that I am not using a command here, but rather would like to describe a top-level positional argument.

**Comment by bcoe** [comment]
@wearhere we've been talking about adding top-level commands, which I think could address this issue well.

**Comment by popomore** [comment]
@bcoe How is the progress of this issue?

**Comment by atian25** [comment]
@bcoe +1 for this

**Comment by bcoe** [comment]
this is now possible with default commands and `.positional()` 🎉 

```js
var argv = require('./')
  .usage('$0 <source-dir>', 'performs operation on source-dir', (yargs) => {
    yargs.positional('source-dir', {
      describe: 'this is the source directory'
    })
  })
  .demand(1)
  .argv;

console.info(argv)
```
