### ISSUE TITLE
Allow end users to turn any option into an array

### ISSUE THREAD

**Issue by bopjesvla** [yargs/yargs#573]
Is there a way to construct a hash where the keys are unknown and the values are arrays? I know this is possible:

```
cli --table.users email --table.users password --table.shoes size --table.shoes colour
```

But this gets verbose quickly when there's a great number of elements in the array. I don't remember which one, but I used to work with a CLI that had a nice solution for this problem:

```
cli --table.users[] email password
```

**Comment by nexdrew** [comment]
@bopjesvla You can specify an option with `type: array` to achieve this:

```js
var argv = require('yargs')
  .option('table.users', {
    type: 'array'
  })
  .option('table.shoes', {
    type: 'array'
  })
  .argv
```

```console
$ cli --table.users email password --table.shoes size colour
```

Is that close to what you're looking for?

**Comment by bopjesvla** [comment]
Unfortunately not, because the names of the tables (users and shoes in the example) could be anything. I'm looking for something like:

```js
var argv = require('yargs')
  .option(/^table\./, {
    type: 'array'
  })
  .argv
```

I think what I proposed earlier is the better solution, but I hope this illustrates my needs.

**Comment by bcoe** [comment]
@bopjesvla beyond the current array support, we're probably not going to add an additional edge-case like this to our argument parsing.

_however_., we're planning on implementing the concept of "coercion" in our upcoming roadmap:

https://github.com/yargs/yargs/issues/535

Which will allow folks to much more easily implement their own advanced custom argument parsing features.
