### ISSUE TITLE
Reload config file

### ISSUE THREAD

**Issue by RyanZim** [yargs/yargs#585]
Is it possible to reload the config file loaded with `config()`? I would like to watch the config file and reload it when it is changed.

Also, is there a good way to get the config file's filename to pass to the watcher? I'm currently using a custom loader, like this:

```
var configPath;
var argv=require('yargs')
.config('c', function (filePath) {
  configPath=filePath;
  return require(filePath);
})
.argv
```

**Comment by bcoe** [comment]
👋 yargs is designed to be a one pass parser, I don't think we're likely to add this functionality (also it's been three years sorry 😆).

How I would probably pull this off would be, in the application layer, to setup a watcher for a config file, and then kick off a new yargs parse if a config file is reloaded -- this is similar to how I'd suggest you wire up yargs in an environment like a chat program.
