### ISSUE TITLE
'coerce' does not execute for defaults

### ISSUE THREAD

**Issue by nyurik** [yargs/yargs#598]
There is no way to make `coerce` execute for the default value, yet there are some usecases where this would be very useful. Without this, coerce cannot be used, and argument has to be processed after parsing.

**Comment by nyurik** [comment]
Hmm, it seems like it does work, my mistake. Will submit a documentation PR.

**Comment by satazor** [comment]
@nyurik I've the same issue.. the coerce function is not called for the default value. How did you make it work?

**Comment by bcoe** [comment]
@satazor mind providing some code that reproduces; make sure you're on the most up-to-date yargs (we bumped a major) because we now apply coercion slightly differently.

**Comment by satazor** [comment]
@bcoe I am on yargs `v6`.

```js
// coerce.js
#!/usr/bin/env node

'use strict';

const yargs = require('yargs');
const moment = require('moment');

const argv = yargs
.strict()

.option('min-commits', {
    type: 'string',
    alias: 'mc',
    default: '10:6M',
    describe: 'Filter results based on a minimum number of commits within a certain time-frame (format is <count>:<duration>, see http://momentjs.com/docs/#/durations/creating/ for the duration format)',
})

.coerce('min-commits', (arg) => {
    const split = arg.split(':');
    const count = Number(split[0]);
    const durationValue = parseInt(split[1], 10);
    const durationUnit = split[1].match(/([a-z]*)$/i)[1];

    if (isNaN(count)) {
        throw new Error('Invalid count specified for min-commits, format is <count>:<duration>');
    }
    if (isNaN(durationValue) || !moment.normalizeUnits(durationUnit)) {
        throw new Error('Invalid date when calculating the date for min-commits, format is <count>:<duration>');
    }

    return { count, date: moment().subtract(durationValue, durationUnit).toDate() };
})

.argv;

console.log('min-commits', argv.minCommits);
```

![screen shot 2016-10-07 at 19 54 00](https://cloud.githubusercontent.com/assets/1017236/19201912/d5c95f9c-8cc7-11e6-8c81-9b128eba0e95.png)

**Comment by satazor** [comment]
I'm currently using `.check()` to do what I want to do.

**Comment by bcoe** [comment]
@satazor 👍 will dig into this.

**Comment by ssonal** [comment]
@bcoe I looked into this; seems the problem is with yargs-parser. Specifically, coercions are applied before defaults are set into ```argv```. Happy to submit a pull-request that helps fix the issue.
