### ISSUE TITLE
Do you have any advise for testing CLI using yargs

### ISSUE THREAD

**Issue by mikeerickson** [yargs/yargs#603]
I am stumped as to what to use for testing CLI results?

I have tried

```
const exec   = require('child_process').execFile
```

and my test

```
    it('should start with offset [--from, -f]', () => {
        exec('node', ['./cli --version'], (error, stdout) => {
            console.log('here');
            if (error) { throw error }
            console.log(stdout);
        })
    })
```

**Comment by felixfbecker** [comment]
Should be
```js
 exec('node', ['./cli', '--version'], ...
```

**Comment by maxrimue** [comment]
@mikeerickson You can of course execute the file directly using `child_process`, which is what I think most people do.

If you have too much trouble with `child_process`, you can also check out [execa](https://github.com/sindresorhus/execa) which is easier to use and offers more functionality.

But if you don't want to execute the file directly for whatever reason, you could also try to build a custom solution, since yargs can also take variables as arguments:
```javascript
yargs(['--hello'])
  .option('hello', {})
  .argv;
```
So you could make it use a variable when testing and otherwise `process.argv`. I don't know if this helps you or makes sense in your project, because this approach probably is way harder than just executing the files, but perhaps it's of use for you.

If you have any more questions, please go ahead and ask!

**Comment by mikeerickson** [comment]
@maxrimue Here is the solution I came up with.  I pipe the CLI output to a text file then read that file for my results where I can perform my assertions.  I wound up using `shelljs` 

```
    it('should limit results to defined size [--size, -s]', (done) => {
        shelljs.exec('npms search gulp --output --size 5 > ./result.txt')
        fs.readFile('./result.txt', 'utf8', (err, content) => {
            if (err) { throw err }
            const resultObj = JSON.parse(content)

            assert(resultObj.length, 5)
            done()
        })
    })
```

**Comment by felixfbecker** [comment]
@mikeerickson this is exactly the same:
```
childProcess.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {

})
```

**Comment by mikeerickson** [comment]
@felixfbecker FWIW, this doesnt seem to work (nothing is sent to console

```
        child_process.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {
            console.log('here');
            console.log(err);
            console.log(stdout);
            console.log(stderr);
        })
        done()
```

**Comment by mikeerickson** [comment]
@felixfbecker Curiously, it DOES when called outside of the test block.

When called inside `it` block, not is sent to console.  

```
    it('should use child process', (done) => {
        child_process.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {
            console.log('here');
            console.log(err);
            console.log(stdout);
            console.log(stderr);
        })
        done()
    })
```

However, if I place it a test script, all works (I get console output)

**Comment by felixfbecker** [comment]
Weird. Maybe fiddle around with the stdio setting? You should open an issue at Mocha

**Comment by maxrimue** [comment]
@mikeerickson I think you need to move the `done()` inside the `child_process.exec` callback function, because otherwise the test terminates before the execution is done, hence nothing will be output

**Comment by mikeerickson** [comment]
@maxrimue No difference :-(  Would be great to get this working as it would be much faster than having to pipe results to `results.txt` file

```
    it.only('should use child process', () => {
        child_process.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {
            let obj = JSON.parse(stdout)
            console.log(obj.length)
        })
    })
```

Inside test `it` still no console.   The same code block outside of test produces the results I would expect.  

```
        child_process.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {
            let obj = JSON.parse(stdout)
            console.log(obj.length)
        })
```

**Comment by mikeerickson** [comment]
@felixfbecker I am going to raise an issue with `mocha` now

**Comment by mikeerickson** [comment]
I have created this ticket https://github.com/mochajs/mocha/issues/2461 I will let you know what they have to say for your edification.

**Comment by maxrimue** [comment]
@mikeerickson Sorry, I'm not sure if I put that right, what I meant is something like this:
```javascript
it.only('should use child process', done => {
        child_process.exec('npms search gulp --output --size 5', 'utf8', (err, stdout, stderr) => {
            let obj = JSON.parse(stdout)
            console.log(obj.length)
            done()
        })
    })
```

**Comment by mikeerickson** [comment]
@maxrimue Forgot to post this, but I have gotten everything working!!

**Comment by keithkml** [comment]
This is really not a good solution... I'd like to test in-process so I can validate the results without parsing stdout.

**Comment by bcoe** [comment]
@keithkml we've done quite of refactoring of the past year to make yargs work well as parser for chat bots ... part of this was making it easier to capture output from yargs.

If you use the `.parse()` option rather than `.argv`, you can capture and assert against any text that would be output by yargs -- would love to add a section to our website outlining how to do this, if you want to kick off the conversation:

https://github.com/yargs/yargs.github.io

**Comment by kopax** [comment]
I am having issues when using with babel. I have a test that does : 

```js
import path from 'path';
import execa from 'execa';

describe('CLI', () => {
  it('CLI should show help', async () => {
    const { stdout: help } = await execa.shell(`node ${path.join(__dirname, '../index').replace('src', 'lib')} help`);
    expect(help).toContain('--version');
  });
});
```

I had to do `.replace('src', 'lib')`  because the src is throwing errors due tu `import` synthax. 

Any idea how to do it in a reliable way?
