### ISSUE TITLE
Command arguments shifted when script is run through node <script> <args>

### ISSUE THREAD

**Issue by felixfbecker** [yargs/yargs#605]
For a `bin` entry in package.json, npm will create this batch script in the `node_modules/.bin` folder:

``` bat
@IF EXIST "%~dp0\node.exe" (
  "%~dp0\node.exe"  "%~dp0\..\my-cli\bin\my-cli" %*
) ELSE (
  @SETLOCAL
  @SET PATHEXT=%PATHEXT:;.JS;=;%
  node  "%~dp0\..\my-cli\bin\my-cli" %*
)
```

Which means when you run it with `node_modules\.bin\my-cli command arg1 arg2`, `process.argv` will be 

``` js
[ 'C:\\Program Files\\NodeJS\\latest\\node.exe',
  'C:\\Users\\felix\\git\\OpenSource\\my-cli-test\\node_modules\\my-cli\\bin\\my-cli',
  'command',
  'arg1',
  'arg2' ]
```

Lets say `command` is defined like:

``` js
yargs.command('command <arg1> <arg2>', {}, argv => console.log(argv))
```

The **expected** output would be:

``` js
{ _: [ 'command' ],
  version: false,
  v: false,
  help: false,
  h: false,
  '$0': 'node_modules\\my-cli\\bin\\my-cli',
  arg1: 'arg1',
  arg2: 'arg2' }
```

The **actual** output is:

``` js
{ _: [ 'command' ],
  version: false,
  v: false,
  help: false,
  h: false,
  '$0': 'node_modules\\my-cli\\bin\\my-cli',
  arg1: 'C:\\Users\\felix\\git\\OpenSource\\my-cli-test\\node_modules\\my-cli\\bin\\my-cli',
  arg2: 'command' }
```

As you can see, `arg1` and `arg2` are set incorrectly to the script passed to `node` and the `command`.

**Comment by felixfbecker** [comment]
A workaround is to use `.parse(process.argv.slice(2))`

**Comment by bcoe** [comment]
@felixfbecker 👋 calling `.argv` rather than `.parse(process.argv)`, or `.parse()`, without any arguments, should take into account `parocess.argv.slice(2)` already.

I don't _think_ this is an issue any longer 👍 If you're continuing to see this issue, perhaps I could get you to provide a failing test?
