### ISSUE TITLE
Support mutual exclusion of options

### ISSUE THREAD

**Issue by nunocastromartins** [yargs/yargs#609]
I have the need for a set of mutually exclusive options. I think it would make sense for this package to support them, seeing as it already supports other kinds of validations such as demands and implications.

I image something such as:
```js
#!/usr/bin/env node
require('yargs')
  .option('a')
  .option('b')
  .option('c')
  .option('d')
  .mutuallyExclusive(['a', 'b'])
  .mutuallyExclusive(['b', 'c', 'd'])
  .argv;
```
or (maybe too repetitive and possibly error prone):
```js
#!/usr/bin/env node
require('yargs')
  .option('a', {exclusiveWith: ['b']})
  .option('b', {exclusiveWith: ['a', 'c', 'd']})
  .option('c', {exclusiveWith: ['b', 'd']})
  .option('d', {exclusiveWith: ['b', 'c']})
  .argv;
```
Test run:
```bash
$ ./program -a -b
Error: At most one of -a, -b may be used.
$ ./program -d -b
Error: At most one of -b, -c, -d may be used.
$ ./program -a -c
# This is fine
```

**Comment by nunocastromartins** [comment]
I browsed through the issues first, but somehow I missed #534 and #186. I apologise!

**Comment by maxrimue** [comment]
@nunocastromartins No worries! Hope to get the feature landed soon though.
