### ISSUE TITLE
sometimes unnecessary pkgUp decreases speed a lot

### ISSUE THREAD

**Issue by maxrimue** [yargs/yargs#612]
#610 made me wanna try out some profiling of yargs, too, and I discovered that `pkgUp` actually takes a very long time to do its stuff.

![bildschirmfoto 2016-08-30 um 18 37 35](https://cloud.githubusercontent.com/assets/7421183/18098135/3010f94c-6ee1-11e6-8c4d-f8adf5129842.png)

The shown part that delays execution happens during parsing of args, [here](https://github.com/yargs/yargs/blob/master/yargs.js#L680).

This made me wonder if we could perhaps only run `pkgUp` if the user really told yargs they want to configure it using a `package.json`, like so:
```javascript
require('yargs')
  .configureWithPackageJSON() // I couldn't think of a better name .-.
```

It's of course a great feature to put configuration into a `package.json`, but I doubt everyone uses that feature. If we'd only run `pkgUp` if really necessary, we could improve yargs' speed by another ~33%. I've created a little test file that requires yargs and triggers a parse once with original source and once without the `pkgUp` check during parsing:

```javascript
require('./index.js')('--hello')
	.argv
```

With `pkgUp`:
```
156ms
```

Without `pkgUp`:
```
110ms
```

(Multiple tests were ran to get the average)

What does everyone think?

**Comment by bcoe** [comment]
@maxrimue we've definitely mulled over dropping this in the past; but I think that allowing people should definitely be able to turn features on and off for yargs without having to specify that they're about to do so -- this gets too weird.

My preference would be that we instead dig into `read-pkg-up`, and see if there are any potential performance gains here.
