### ISSUE TITLE
.array('arg') not parsing properly

### ISSUE THREAD

**Issue by achingbrain** [yargs/yargs#616]
The README says:

> ## .array(key)
>
>Tell the parser to interpret key as an array. If `.array('foo')` is set, `--foo foo bar` will be parsed as `['foo', 'bar']` rather than as `'foo'`.

Yet the following test fails:

```javascript
it('parses argument values as an array', function () {
  var argv = yargs('foo --arg bar baz')
    .command('foo [options]', 'the foo command')
    .describe('arg', 'Should contain some values')
    .array('arg')
    .argv

  // fails with AssertionError: expected 'bar' to deeply equal [ 'bar', 'baz' ]
  argv.should.have.property('arg').and.deep.equal(['bar', 'baz'])
})
```

Am I using it correctly?

**Comment by nexdrew** [comment]
@achingbrain Good question. Because you're using a command, you need to mark any top-level options that apply to that command as `global`; otherwise option config is reset for the command execution.

Either one of these should work:

```js
it('parses argument values as an array', function () {
  var argv = yargs('foo --arg bar baz')
    .command('foo [options]', 'the foo command')
    .describe('arg', 'Should contain some values')
    .array('arg')
    .global('arg') // <-- this line added
    .argv

  argv.should.have.property('arg').and.deep.equal(['bar', 'baz'])
})
```

```js
it('parses argument values as an array', function () {
  var argv = yargs('foo --arg bar baz')
    .command('foo [options]', 'the foo command')
    .option('arg', {
      describe: 'Should contain some values',
      type: 'array',
      global: true
    })
    .argv

  argv.should.have.property('arg').and.deep.equal(['bar', 'baz'])
})
```

Or if you make the option local to the command builder and assert on the argv given to the command handler, it would work as well (without `global`):

```js
it('parses argument values as an array', function () {
  var argv = {}
  yargs('foo --arg bar baz')
    .command('foo [options]', 'the foo command', {
      arg: {
        describe: 'Should contain some values',
        type: 'array'
      }
    }, function (innerArgv) {
      argv = innerArgv
    })
    .argv

  argv.should.have.property('arg').and.deep.equal(['bar', 'baz'])
})
```

Otherwise it would also work if we just leave out the command:

```js
it('parses argument values as an array', function () {
  var argv = yargs('--arg bar baz')
    .describe('arg', 'Should contain some values')
    .array('arg')
    .argv

  argv.should.have.property('arg').and.deep.equal(['bar', 'baz'])
})
```

Does this make sense? If you find some misinformation in the docs, please let us know. Thanks!

**Comment by bcoe** [comment]
@achingbrain feel free to reopen this if @nexdrew's tips don't do the trick; we're hoping to pull together a command tutorial on the yargs website soon, which should help clarify some of these issues.

**Comment by achingbrain** [comment]
Sorry for my delay in replying - @nexdrew's tips did indeed do the trick, thanks so much.
