### ISSUE TITLE
Dot-notation boolean flags aren't parsed correctly

### ISSUE THREAD

**Issue by lasalvavida** [yargs/yargs#617]
Given the following example:

`testScript.js`

``` javascript
var argv = require('yargs')
    .options({
        'nested.value': {
            type: 'boolean'
        }
    }).argv;

console.log(argv);
```

`./bin/testScript`

> { _: [],
>   nested: { value: false },
>   '$0': 'bin\testScript.js' }

`./bin/testScript.js --nested.value`

> { _: [],
>   nested: { value: [ false, true ] },
>   '$0': 'bin\testScript.js' }

The value is placed into an array instead of changing the boolean value.

**Comment by lasalvavida** [comment]
Did some digging. This was an issue in yargs-parser that is no longer present in master. This can be closed after release.

**Comment by babhishek21** [comment]
I would like to work on this. Can anyone help me out a bit?
