### ISSUE TITLE
Cannot create an error to say "too many arguments"

### ISSUE THREAD

**Issue by kumar303** [yargs/yargs#618]
I want a command with extraneous arguments to raise an error. For example:

    node script.js args-not-supported

This should produce some kind of error, I guess like:

````
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]

Too many non-option arguments
````

Is this possible? I thought the following code would do it but it does not produce an error at all.

````javascript
var yargs = require('yargs');
yargs
  .help('help')
  .demand(0)
  .strict()
  .argv;
````

**Comment by nexdrew** [comment]
@kumar303 Try `.demand(0, 0)` instead.

**Comment by nexdrew** [comment]
Also, you can customize the error message with a 3rd argument, like `.demand(0, 0, 'Extraneous arguments are not allowed.')`

**Comment by kumar303** [comment]
d'oh! Thanks, I guess I didn't read the docs well enough. It seems weird that `demand(0)` wouldn't do anything at all though since it's non-sensical without a max also of 0. Anyway, now that I know it's not a bug, feel free to close the issue.

**Comment by bcoe** [comment]
@kumar303 this is definitely a part of the API that is confusing, we have this open issue:

https://github.com/yargs/yargs/issues/504

Would love your feedback and thoughts on these potential API improvements.
