### ISSUE TITLE
yargs.help() return value

### ISSUE THREAD

**Issue by coldlamper** [yargs/yargs#620]
Before 5.0 I used to be able to get the help string by calling yargs.help() inside fail like 
```
.fail(function (msg, err) {
		console.log('You broke it!');
		console.log(msg)
		var help = yargs.help();
                userDefinedFunction(help)
})
```

Now it just returns an object.  Is there a way to return the help string not just console.log it out?

**Comment by nexdrew** [comment]
@coldlamper Try `yargs.getUsageInstance().help()` instead.

**Comment by bcoe** [comment]
@coldlamper you can also pass a callback to `.showHelp()`:

https://github.com/yargs/yargs/blob/master/lib/usage.js#L337

Which will then be passed the usage string as the first argument; would it be worth us adding this to the documentation?

I wonder if it would be worth adding a method like `getHelpString()`.

**Comment by coldlamper** [comment]
@nexdrew That works great.
@bcoe Passing a callback to .showHelp() works fine also.
Thanks!

**Comment by shamansir** [comment]
Related to this comment: https://github.com/yargs/yargs/issues/676#issuecomment-279347586
