### ISSUE TITLE
Feature: Custom output function

### ISSUE THREAD

**Issue by scriptdaemon** [yargs/yargs#625]
I wish `yargs` allowed the user to define a custom output function rather than hardcoding console.* (similar to fail(), but for all output). I'm using `yargs` to allow users in a chat to pass commands to a bot, and it'd be easier to supply an output function that sends the message for `--help` or `--version` to the chat rather than creating my own `help` and `version` commands to do that.

Is this a feasible request?

**Comment by bcoe** [comment]
@scriptdaemon I really like this idea; I'd like to switch npm's ops-bot over to using yargs as well, excited to chat about what this API might look like.

**Comment by scriptdaemon** [comment]
This is a quick write-up of what I want to be able to do (I'm not 100% on the name for it, and I'm up for other suggestions for how to work with it):

```js
import yargs  from 'yargs';

// Local modules
import cmd from '../commands/cmd';

// Trigger that attaches a 'message' listener to the bot
function runCommand(bot) {

  // Listener for "message" event
  function onMessage(message, userId, chatId) {

    function sendChatMessage(message) {
      bot.sendChatMessage(chatId, message);
    }

    yargs
      .command(cmd({ bot, userId, chatId }))

      // Custom output function
      // Use this instead of console.* any time any output is sent
      .output(sendChatMessage)
      .parse(message);
  }

  return {
    attach() {
      bot.addListener('message', onMessage);
    },

    detach() {
      bot.removeListener('message', onMessage);
    }
  };
}

export default runCommand;
```

I didn't even think of it until now, but maybe having another function like `yargs.send()` could allow calling the output callback directly (or its default of `console.*` if a custom function is not specified)?

Something like this:

```js
function dice(context) {
  function roll(diceRoll) {
    // Random die roll :D
    return '4';
  }

  return {
    'command'     : 'dice [roll]',
    'description' : 'Roll some dice',

    builder(yargs) {
      yargs.default('roll', '1d6');
    },

    // Also perhaps pass yargs instance to handler?
    handler(argv, yargs) {

      // Call bot.sendChatMessage()
      yargs.send(roll(argv.roll));
    }
  };
}

export default dice;
```

**Comment by scriptdaemon** [comment]
Closing this since https://github.com/yargs/yargs/pull/646 was merged.

**Comment by bcoe** [comment]
@scriptdaemon if you want to take this for a test drive, I've published it to `next`:

`npm cache clear; npm i yargs@next`.
