### ISSUE TITLE
config() does not fail on missing file from default value

### ISSUE THREAD

**Issue by Xerkus** [yargs/yargs#626]
config() does not fail if default file does not exist.

eg with config

```
yargs.options('c', {
    alias: 'config',
    default:  'config.json',
    config: true,
    type: 'string'
```

});

Without `config` parameter and on missing `config.json` file it will silently do nothing. For example if user forgot to copy and fill `config.json.dist`. But if `config.json` IS present it will be loaded.
Explicitly providing `config` parameter will make it fail on missing file.

Upd: it will also do nothing if file from default value fails to be parsed as json. 
Also errors are not swallowed if config parser option is used.

**Comment by bcoe** [comment]
I think my preference in these scenarios would be to `console.warn()`.

CC: @nexdrew @maxrimue @lrlna

**Comment by bcoe** [comment]
@Xerkus a warning is now displayed if an invalid config file is provided, e.g., a missing file or bad JSON. There does seem to continue to be a bug with using `default` and `config` in conjunction, see:

https://github.com/yargs/yargs-parser/issues/218
