### ISSUE TITLE
accumulate arguments

### ISSUE THREAD

**Issue by dciccale** [yargs/yargs#631]
is there a way to accumulate to previous arguments?

`test.js`

``` js
var argv = require('yargs')
  .coerce('V', (arg) => {
    let [k, v] = arg.split(/=/);
    return {[k]: v};
  })
  .argv;
console.log(argv);
```

``` sh
$ node ./test.js -V asd=qwe -V lkj=poi
{ _: [],
  V: [ { asd: 'qwe' }, { lkj: 'poi' } ],
  var: [ { asd: 'qwe' }, { lkj: 'poi' } ],
  '$0': 'test.js' }
```

Would like to have the following output:

``` sh
$ node ./test.js -V asd=qwe -V lkj=poi
{ _: [],
  V: { asd: 'qwe', lkj: 'poi' },
  var: { asd: 'qwe', lkj: 'poi' },
  '$0': 'test.js' }
```

I can do this by post-processing the arguments like this:

``` js
argv.V = argv.Vr.reduce((prev, curr) => Object.assign(total, curr), prev);
```

If there is no way to achieve this without post-processing the result, would be useful to receive on the `coerce` function, current argument, and the previous argument as second parameter of the function maybe or pass an optional initial value to have more flexibility on what to do instead of just concat.

any help thanks in advance

**Comment by bcoe** [comment]
@dciccale sorry for the slow response, have been doing a poor job of triaging issues recently;

You can get similar behavior with yargs' Object syntax:

```
node ./test.js -V.asd qwe -V.lkj poi
```

However, for the exact format you're looking for, I think coerce might be the best bet.
