### ISSUE TITLE
More yargs translations needed

### ISSUE THREAD

**Issue by nexdrew** [yargs/yargs#649]
Hello gracious OSS authors! The yargs team needs your help once again to translate the following into various languages:
1. `"aliases:"` for command aliases (added in PR #647), should be line 13 of each locale file
2. `"Did you mean %s?"` for recommending commands (added in PRs #562, #580), should be line 38 of each locale file

I apologize for directly pinging you, but I only do so because you have been a valued contributor in the past. If you get a chance, please either leave a comment on this issue with the requested translations or (better yet) submit a PR! 😺 
- [x] de.json: @maxrimue
- [x] en.json
- [x] es.json: @zkat
- [ ] fr.json: @LoicMahieu
- [x] id.json: @rilut
- [x] it.json: @madrisan
- [x] ja.json: @oti @watilde
- [x] ko.json: @disjukr
- [ ] nb.json: @sindresorhus
- [x] pl.json: @kamilogorek
- [ ] pt.json: @codemonkey3045
- [x] pt_BR.json: @zkat
- [x] tr.json: @feyzo
- [ ] zh_CN.json: @qiu8310 @andyhu

As always, please feel free to ask questions ❓, say "hi" 👋, or tell us to buzz off 🐝. Regardless, we thank you for your contributions!

Update: Thanks to all who have contributed new languages as well, you are awesome!
- [x] hi.json
- [x] hu.json
- [x] ru.json
- [x] th.json

**Comment by kamilogorek** [comment]
There you go! :) `alias` is commonly used word in polish (mostly in IT), so I just pluralized it, as it should be easily understandable to everyone.

**Comment by addaleax** [comment]
I think @michaalbert would like to give adding a Russian translation a try later today! =)

**Comment by dgrcode** [comment]
I'll send the Spanish translation! But I have a question first. The translation for aliases depends on the context. Could you give me a couple of examples where "aliases" is going to be written?
Thanks!

**Comment by maxrimue** [comment]
@dgrcode "Aliases" is used to reference something like different names for the same command or option. Say if we have the command `add` and want users to be able to call it also using a different name for the same command, say `addFiles`, we do so by creating the _alias_ `addFiles` of `add`. The translation will appear in a box after a command, like this:
```
add [alias: addFiles]
```

Does that answer your question?

**Comment by babhishek21** [comment]
If anyone needs Hindi or Bengali translations, let me know! :smile:

**Comment by maxrimue** [comment]
@babhishek21 Ohh that would be so awesome! If you would like to do it, simply create the new translation files using the existing ones in the `locale/` folder as a template. If you have just any questions, go ahead 😄

**Comment by babhishek21** [comment]
Just one quick question! Are you looking only for native script translations (Hindi uses the Devnagari script and looks like हिन्दी ; Bangla (Bengali) looks like বাংলা )? Transliterated versions are also available.

**Comment by maxrimue** [comment]
@babhishek21 Hmm I'm not sure if that'll work, I don't know to be honest 😄 Perhaps for compatibility reasons, we should go with the transliterated versions, what do you think?

**Comment by babhishek21** [comment]
Hindi (Devnagari) works with UTF-8. Bangla also works with Unicode. I'll take a look at the other translations to see the range of type support. Should I perhaps make separate issues for these?

**Comment by dgrcode** [comment]
@maxrimue This answers my question! I'll send a pull request with the translations in a few minutes

**Comment by maxrimue** [comment]
@babhishek21 Yeah, separate pull requests would be appreciated. Thanks for dealing with this 😄

**Comment by michaalbert** [comment]
Hi, I have a question about translating "Implications failed". Could someone give a general description of situations when this is used? It can't be transalted literally so I have to somehow describe it.

**Comment by nexdrew** [comment]
@michaalbert This is a validation error where the use of one argument implies (requires) the use of another argument. So "Implications failed" basically means "You provided the first argument mentioned but didn't provide the second argument mentioned, which is required when providing the first argument."

That's obviously verbose, so if you can figure out the most concise way of saying the same thing, that would be great. Thanks! And please let us know if you have any additional questions.

**Comment by michaalbert** [comment]
@nexdrew thanks! So would something like "The given command requires additional arguments" be okay or is that too unspecific?

**Comment by nexdrew** [comment]
@michaalbert That would probably be ok, but the message will be followed by text like `x -> y`, where `x` is the argument you gave and `y` is the argument you didn't give, so it _might_ need to be a bit more specific to avoid confusion over `x` pointing to `y`. Not sure, what do you think?

**Comment by michaalbert** [comment]
@nexdrew  Okay, then "The given argument requires the following additional argument:" makes more sense.

**Comment by nexdrew** [comment]
@michaalbert That sounds perfect, thanks!

**Comment by Hunrik** [comment]
#665

**Comment by wolframtheta** [comment]
Hi @nexdrew do you want a Catalan translation?

**Comment by nexdrew** [comment]
Hi @wolframtheta, that would be great! Just add a new ca.json file to the locales directory. Thanks!

**Comment by madcampos** [comment]
Hello, I have a question, is the pt_BR translation open? If so, I wish to work on it if I may.

**Comment by babhishek21** [comment]
@madcampos Check among the current PRs if any pending changes exist for `locales/pt_BR.json`. Other than that, as you can see from the checklist in the Issue Description, there is work to be done there.

**Comment by zkat** [comment]
@madcampos: for the record, pt_BR isn't one of my main langs so pleeease feel free to take over it and correct any awkwardness I put in there!

**Comment by madcampos** [comment]
@zkat I'm brazilian so I can help with that, no problem. 😉

**Comment by Tocive** [comment]
Hiya
Although it wasn't on the list, I did create a Dutch translation (PR #687 )
Happy Hacktoberfest!

**Comment by bcoe** [comment]
I declare this a successful hacktoberfest (two months later :p), thanks everyone who contributed.
