### ISSUE TITLE
camel-case commands

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#653]
For options, e.g., `--foo-bar`, we populate the camel-case `fooBar` variable on the argv object. For commands we're not that clever:

`.command('foo <api-token>')` will result in only `api-token` being populated on the argv object; it would be nice if we were clever enough to populate both `api-token` and `apiToken`.

**Comment by anu0012** [comment]
Hey @bcoe , I would like to tackle this issue. Can you guide me ?

**Comment by ssonal** [comment]
Would like to take a shot at this!

**Comment by maxrimue** [comment]
Thanks @ssonal for the pull request! 

@anu0012 sorry for this, maybe you want to search for another yargs issue you want to tackle? We would definitely help you at it! But no worries if no 😄
