### ISSUE TITLE
alias is not used when passing command

### ISSUE THREAD

**Issue by freed00m** [yargs/yargs#657]
Hi, maybe I don't understand something here. But if I have a sample nodejs app

```
var argv = require('yargs')
    .usage('Usage: $0 -w [num] -h [num]')
    .command('run', 'execute jasmine sequentialy per tests directory e.g. basic')
    .alias('h', 'height')
    .argv;

console.log(argv)
console.log("The area is:", argv.w * argv.h);
```

and I ran 

```
$ node sample.js -w 4 --height 3
```

then I get the correct answer and the 3 is correctly saved to h and height

but when I run it with command

```
$ node sample.js run -w 4 --height 3
```

the 3 si only saved to height not h variable.

**Comment by maxrimue** [comment]
Hey @freed00m,

this is because options in yargs are no longer automatically global. That means, that an option (or alias for it) declared in the global scope will not exist in a child scope, like here in the "run command scope".

You can change that by using `.global()`:
```javascript
var argv = require('yargs')
    .usage('Usage: $0 -w [num] -h [num]')
    .command('run', 'execute jasmine sequentialy per tests directory e.g. basic')
    .alias('h', 'height')
    .global('height') // <---
    .argv;
```
```
>node index.js run --height 3
argv.h => 3
```
We've been thinking about possibly reverting this to be automatic, what do you think? Does this solve your issue?

**Comment by freed00m** [comment]
Well, thank you for clarifying this :)

I don't know what is the use case for not having global. It's certainly something I have to bare in mind and while coding it seemingly works but everything fails when someone adds few commands and tries to use the aliases that are projected to the help. 

If it's not going to be reverted, maybe adding few more disclaimers to readme.md somthing under aliases and commands and recommending new users to be aware of globals would help.

**Comment by bcoe** [comment]
@freed00m we're having an ongoing discussion around what options are treated as `global` vs. `local` in the context of commands -- expect updates in yargs@7.x
