### ISSUE TITLE
Stop parsing, can't distinguish between `./cmd a -- b c` and `./cmd --- a b c`

### ISSUE THREAD

**Issue by olalonde** [yargs/yargs#682]
Is there any way to distinguish between `./cmd a -- b c` and `./cmd -- a b c`? They both return

``` javascript
{ _: [ 'a', 'b', 'c' ],
  '$0': 'cmd' }
```

**Comment by bcoe** [comment]
@olalonde this feels like a bug.

**Comment by olalonde** [comment]
Meanwhile, I'm using https://github.com/substack/minimist which allows passing a `{ '--': true }` option. Maybe yargs could do something similar to avoid a breaking change?

> opts['--'] - when true, populate argv._ with everything before the -- and argv['--'] with everything after the --.

**Comment by ruimarques** [comment]
This should be done on yargs-parser, right?

**Comment by bcoe** [comment]
@ruimarques yes, I think a change will ultimately be in `yargs-parser`; If I understand this ticket @olalonde, this is more of a feature request than a bug? With the current `--` implementation, it's difficult to distinguish between positional arguments, and arguments that simply haven't been parsed?

I wonder what a better implementation would be.

**Comment by olalonde** [comment]
Yes, it was a feature request. 👍

**Comment by ruimarques** [comment]
Hi guys, personally I think this is more on the bug side, but it is debatable for sure. 

Having that in mind I have submitted a PR for it as a feature. Please take a look https://github.com/yargs/yargs-parser/pull/84

**Comment by bcoe** [comment]
@ruimarques @olalonde it's now possible to collect unparsed arguments in `--` rather than `_`; I would love your help testing, just:

`npm i yargs@next --save` to install the candidate release of yargs.

and add this configuration to your package.json:

```json
{
  "yargs": {
    "populate--": true
  }
}
```

thanks for your help on this feature.

**Comment by xaka** [comment]
@bcoe Could you please share the status of `--populate--` feature? Thanks!

**Comment by NeoLegends** [comment]
This is affecting me as well. Has something else be done about this?
