### ISSUE TITLE
multiple array arguments are all flattened instead of getting a nested array

### ISSUE THREAD

**Issue by laggingreflex** [yargs/yargs#688]
I have a command option like this:

```
  volume: {
    type: 'array'
  },
```

So this works as expected:

```
command --volume some thing
```

I get an array `['some', 'thing']`

But I expect multiple `--volume` and in that case it doesn't work (as expected):

```
command --volume some thing --volume some other thing
```

I get a flattened array ['some', 'thing', 'some', 'other', 'thing']

The expected result is to get an array of arrays, right? Like had the option been a string I'd get either a string (for single argument), or an array of strings for multiple arguments. Similarly I should expect to get either an array, or an array of arrays, no? Why the flattening?

**Comment by bcoe** [comment]
@laggingreflex both new configuration options are out in `yargs@6.5.0`; there is one bug fix we should make to `yargs-parser`, but I didn't feel it was severe enough to block the release.
