### ISSUE TITLE
what is the right way to use dot in key name?

### ISSUE THREAD

**Issue by skygragon** [yargs/yargs#692]
```
var args = require('yargs')
  .reset()
  .option('lang.cpp', {type: 'boolean'})
  .argv;

console.log(args);
```

And I got this:

```
$ node ./1.js --lang.cpp
{ _: [], lang: { cpp: [ false, true ] }, '$0': '1.js' }
```

How can I get only one value instead of an array?

**Comment by skygragon** [comment]
Oh, just realized there has a same bug #617 . I see the fix is merged in yargs-parser, do we have a plan to embrace this in next release?

**Comment by bcoe** [comment]
@skygragon this ticket fell off my radar sorry! I believe this bug was fixed quite some time ago.

Please feel free to re-open if you're still seeing any issues.

**Comment by skygragon** [comment]
Thanks！
