### ISSUE TITLE
if no description is provided, allow first argument to example to take up entire line

### ISSUE THREAD

**Issue by lurch** [yargs/yargs#697]
Hi,

I'm not sure what the problem is, but over on [etcher](https://etcher.io) today I found a problem where yargs seemed to be applying the line-wrapping over-enthusiastically?
https://github.com/resin-io/etcher/issues/810

@jviotti managed to work around it, but I figured it would only be 'polite' to also report the problem upstream ;-)

**Comment by bcoe** [comment]
@lurch I believe the idea with examples was that you'd provide two columns of information:

`example command` `description of what command does`

These columns each taking up 50% of the horizontal space; would switching to this two column approach solve your problem for you?

**Comment by lurch** [comment]
Ahhh I see, that explains why yargs is behaving the way it does. Thanks for the feedback!
Unfortunately in Etcher our [usage](https://github.com/resin-io/etcher/issues/810#issuecomment-257424273) is just:
```
example-command-invocation
example-command-invocation
example-command-invocation
```

Perhaps yargs could detect if each of the [desc](https://github.com/yargs/yargs#examplecmd-desc)s is empty, and if so switch to a single-column-100% layout, rather than a 2-column-50% layout?


Also, I'm afraid I'm fairly new to the NodeJS world (I've only recently started working on Etcher), and it seems a bit weird how we invoke the command as `bin/etcher`, but yargs replaces each `$0` with `/usr/bin/nodejs bin/etcher` :-S  Is there any way that could be fixed, or is there a way we can get yargs to use a custom string for `$0`?  (let me know if you'd prefer me to open a separate issue for this second part of the question)

**Comment by lurch** [comment]
Ahhh I see, that explains why yargs is behaving the way it does. Thanks for the feedback!
Unfortunately in Etcher our [usage](https://github.com/resin-io/etcher/issues/810#issuecomment-257424273) is just:
```
example-command-invocation
example-command-invocation
example-command-invocation
```

Perhaps yargs could detect if each of the [desc](https://github.com/yargs/yargs#examplecmd-desc)s is empty, and if so switch to a single-column-100% layout, rather than a 2-column-50% layout?


Also, I'm afraid I'm fairly new to the NodeJS world (I've only recently started working on Etcher), and it seems a bit weird how we invoke the command as `bin/etcher`, but yargs replaces each `$0` with `/usr/bin/nodejs bin/etcher` :-S  Is there any way that could be fixed, or is there a way we can get yargs to use a custom string for `$0`?  (let me know if you'd prefer me to open a separate issue for this second part of the question)

**Comment by nexdrew** [comment]
> Perhaps yargs could detect if each of the descs is empty, and if so switch to a single-column-100% layout, rather than a 2-column-50% layout?

I think this is a reasonable request - I've noticed the same problem in other yargs-based CLIs too.

> is there a way we can get yargs to use a custom string for $0?

It sounds like perhaps we need to revisit the logic that defines `$0`, but you can also just hardcode the app/bin name in usage/example text instead of using `$0`; I know I've done this a few different times.

**Comment by jviotti** [comment]
@nexdrew 

> I think this is a reasonable request - I've noticed the same problem in other yargs-based CLIs too.

Sounds great! Do you want us to help on this on any way?

> It sounds like perhaps we need to revisit the logic that defines $0, but you can also just hardcode the app/bin name in usage/example text instead of using $0; I know I've done this a few different times.

If this is something that caused problems before, I think its the perfect time to revisit the logic. Let us know if we can help out with this, so we don't do duplicate work!

**Comment by bcoe** [comment]
@xstable closing https://github.com/yargs/yargs/issues/747 in favor of this ticket; definitely something we want to support CC: @maxrimue
