### ISSUE TITLE
build subcommand by commandDir how to custom help msg?

### ISSUE THREAD

**Issue by AntSworD** [yargs/yargs#702]
example from `README.md`
`myapp remote --help`
didn't output the subcommand's desc

**Comment by nexdrew** [comment]
@AntSworD If you don't specify a `.usage()` string for the (sub)command, then yargs defaults to printing an auto-generated "synopsis" of how the command should be called/used. Just define `.usage()` within your command's `builder` function to override the default. Here's an example:

```js
const cmd = 'get <key>'
const desc = 'Get the value for key'

require('yargs')
  .usage('Usage: $0 [command] [opts]') // top-level usage string
  .command(cmd, desc, (yargs) => {
    yargs.usage(`Usage: $0 ${cmd}\n\n${desc}`) // command-specific usage string
  }, (argv) => {
    console.log(`getting value for ${argv.key}`)
  })
  .help()
  .argv
```

```console
$ node issue702.js help
Usage: issue702.js [command] [opts]

Commands:
  get <key>  Get the value for key

Options:
  --help  Show help  [boolean]
```

```console
$ node issue702.js help get
Usage: issue702.js get <key>

Get the value for key

Options:
  --help  Show help  [boolean]
```

Is this what you're looking for?

**Comment by nexdrew** [comment]
Sorry, just noticed the reference to `.commandDir()` in the issue title, but the same applies there. Each subcommand would have to define its own custom `.usage()` string in the exported `builder` function.

**Comment by AntSworD** [comment]
THANK YOU!  I know how to do.
