### ISSUE TITLE
Nested Command with config does not display help

### ISSUE THREAD

**Issue by mgfreshour** [yargs/yargs#708]
Hello!  So perhaps I'm just misusing yargs.  Example code:
```js
#!/usr/bin/env node

var argv = require('yargs')
	.command('create', 'Create an EC2 resource', function(yargs, argv){
		return yargs
		.command('instance', 'Create an Instance', function(yargs, argv){
			return yargs
			.config('json-config', {
				describe: 'List of JSON files with parameters',
				array: true
			})
			.option('a', {
				alias: 'ami',
				description: 'AMI name'
			})
			.demand(['ami']);
		})
		.demand(2);
	})
	.demand(2)
	.argv;
```

Running `test.js` display help screen and exits with 1.
Running `test.js create` displays the create help message and exits with 1.
Running `test.js create instance` exits with 1 but does not display any help message. EXPECTED: Exit with 1 and display help message for instances command.
Running `./test.js create instance --ami=test` exits with 0.

If I remove the config() part, then the message displays.  Am I misusing config() or is this a bug?

**Comment by bcoe** [comment]
@mgfreshour I'm surprised it's not displaying a help message, I think you've probably found an edge-case in the command handling; I will work on getting a test around this.

**Comment by bcoe** [comment]
sorry for never following up on this one, the issue seems to have been using the config API slightly wrong:

https://github.com/yargs/yargs/blob/master/docs/api.md#configkey-description-parsefn

The second argument should be a description of the config variable, rather than an object (like with options).
