### ISSUE TITLE
Similar bug to #426

### ISSUE THREAD

**Issue by stevenxxiu** [yargs/yargs#709]
There's a similar bug to #426 I've encountered I think. The following works and can parse the command correctly:

    yargs.command('command [num]', 'give num', (yargs) => yargs.default('num', 1), (argv) => {})

but if I add strict:

    yargs.command('command [num]', 'give num', (yargs) => yargs.default('num', 1).strict(), (argv) => {})

it gives me "Unknown argument: num".

**Comment by maxrimue** [comment]
I think this is happening intentionally, as `.strict()` works differently than what you might expect. Quoting the [documentation](https://github.com/yargs/yargs#strict):
> Any command-line argument given that is not demanded, or does not have a corresponding description, will be reported as an error.

Since you don't describe or demand the option `num`, it will cause an error if given. And since you set a default, you make it given even when the user doesn't pass it. 

This should do:
```javascript
yargs
  .command('command [num]', 'give num', (yargs) => yargs
    .demand('num') // <-- demand 'num'
    .default('num', 1)
    .strict(), (argv) => {})
  .argv;
```

**Comment by stevenxxiu** [comment]
Thanks for the explanation. Although when I tried your fix now it starts to accept additional arguments despite being strict:

    let argv = yargs
      .command('command [num]', 'give num', (yargs) => yargs
        .demand('num') // <-- demand 'num'
        .default('num', 1)
        .strict(), (argv) => {
          console.log(argv.num)
        })
      .demand(1)
      .strict()
      .argv

and I run it with:

    node . command 5 6 7

**Comment by maxrimue** [comment]
@stevenxxiu Hmm yeah I can confirm that... Could you open a new issue for that problem? Thanks for reporting this in the first place :+1:
