### ISSUE TITLE
Key names of an object setting are parsed as dot-notation

### ISSUE THREAD

**Issue by strugee** [yargs/yargs#716]
Given the following (abbreviated) yargs config:

```js
var argv = require('yargs')
	   .describe({port: 'Port that the HTTP server will bind to',
	              address: 'Address that the HTTP server will bind to',
	              path: 'Path that the server will clone things to',
	              override: 'Key/value pairs to override directory names'})
	   .default({ config: '/etc/gh-pages-server.json', address: '0.0.0.0', port: 8000, path: '/srv/http', override: {} })
	   .config()
	   .argv;
```

And the following `/etc/gh-pages-server.json`:

```json
{
  "override": {
    "strugee/strugee.github.com": "default"
  }
}
```

yargs produces an argv object that contains:

```json
"override": {
  "strugee/strugee": { "github": { "com": "default"} }
}
```

whereas the intended result was something like:

```json
"override": {
  "strugee/strugee.github.com": "default"
}
```

I tried setting `dot-notation` to `false` in my `package.json`, but that generated a config key that looked like:

```json
"override.strugee/strugee.github.com": "default",
"override": {}
```

which obviously also isn't what was intended.

**Comment by bcoe** [comment]
@strugee thanks for reporting this bug, I will work on putting some tests around this behavior.

**Comment by bcoe** [comment]
@strugee does this fix seem reasonable? https://github.com/yargs/yargs-parser/pull/72

**Comment by strugee** [comment]
@bcoe I'm not familiar with yargs-parser so I'm not _quite_ in a position to judge, but it seems pretty good!

**Comment by bcoe** [comment]
@strugee this should now be fixed in `yargs@6.5.0` take it for a spin and let me know if you run into any issues.

**Comment by geekdada** [comment]
I put `package.json` in config, and it still messes up.

```
  expect: { js: '^0.3.1' },
  'json-schema-faker': '^0.4.0',
  mocha: '^2.5.3',
  'npm-check': '^5.4.0',
  once: '^1.3.2',
  pedding: '^1.0.0',
  promise: { prototype: { finally: '^2.0.1' } },
```

**Comment by bcoe** [comment]
@geekdada @maxrimue I believe this issue is that you haven't turned off `dot-notation` in your yargs configuration; I just confirmed that this worked on `6.6.0`:

**yargs config in package.json:**

```json
  "yargs": {
    "dot-notation": false
  }
```

**config.json:**

```json
{
  "expect.js": "3.2.9",
  "promise.prototype.finally": "3.3.3"
}
```

**yargs output:**

```bash
{ _: [],
  foo: 'b.json',
  'expect.js': '3.2.9',
  'promise.prototype.finally': '3.3.3',
  '$0': 'index.js',
  x: undefined }
```
