### ISSUE TITLE
positional argument aliases

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#723]
I wish I could do this:

```js
yargs.command('list <user | org>')
```

resulting in both the `user` and `org` positional argument being populated if I run:

```
list bcoe
```

**Comment by Centine** [comment]
I agree, but I also thought this was how it worked already. The documentation states that 

`yargs.command('get <username|email> [password]', 'fetch a user by username or email.').help().argv`

> In this way, both argv.username and argv.email would be populated with the same value when the  command is executed.

This doesn't work for me with the 6.5.0 package from npm.

**Comment by nexdrew** [comment]
@Centine This was implemented with #727, which has been merged to master but not yet released. Please use the docs at http://yargs.js.org/docs/ to refer to the latest release. Thanks!
