### ISSUE TITLE
subcommand dependency injection.

### ISSUE THREAD

**Issue by jaunkst** [yargs/yargs#725]
I would like to be able to execute dependency injection against the command before it gets run. In particular for subcommands.

Lets say we have subcommands developed as external modules and we want to inject core api services into the subcommand using something like `https://github.com/katat/summonjs`

Is this possible?

**Comment by bcoe** [comment]
@jaunkst we do support this, and I'm actually in the process of migrating our slackbot at npm over to yargs today using this very functionality. If you run the `.parse()` command directly, the second argument is optionally a context to pass throughout the command chain:

```js
        return ready => parser.parse(cmdString, {slackboard: this, ready: ready}, function (err, argv, output) {
          if (output) return ready(null, '```' + output + '```')
          if (err) return ready(null, '```' + err.message + '```')
        })
```

**Comment by nexdrew** [comment]
@jaunkst Just some additional info to what bcoe said:

There's nothing particularly special about subcommand modules except that their export conforms to a certain contract - otherwise they can be required and initialized as necessary before handing them to yargs (or, rather, before parsing argv).

If you'd like to use [`.commandDir()`](http://yargs.js.org/docs/index.html#methods-commanddirdirectory-opts), you can use the optional `visit` property (function) to initialize a subcommand module as it is auto-required.

I'm not familiar with SummonJS, but it sounds like you might need to encapsulate the logic (functions/classes) that requires/uses DI in their own submodules and then just use/wrap those submodules in your yargs command modules.

**Comment by jaunkst** [comment]
I was using the visit property to do this last night. I was able to get the first set of subcommands but not a subcommands subcommand. I would assume I would need to do this in the subcommand .commandDir().visit() but I do not want to have to have the sub modules define the core api injection.

**Comment by nexdrew** [comment]
@jaunkst This is an interesting problem. Do you have a repo or some sample code we can consider?

Otherwise bcoe's idea of passing a shared context at parse-time might work better?

**Comment by jaunkst** [comment]
I can mock and example in a repo tonight.

**Comment by jaunkst** [comment]
I was able to implement DI through a custom babel plugin.

**Comment by jaunkst** [comment]
the idea is to build a services manifest of some type. I am walking through a services path and looking for package.json, ignoring node_modules, and building something like this in a babel plugin.
i am using package.main to build a path to the service, and the package.name to camelcase and convert it to a $serviceName

```
    '$somethingInjectable': './path-to-injectable/index.js',
    '$log': './path-to-log-service/index.js'
```
then we inject a require in its place to do constructor and function param injection.

```
export default () => {
  
  const injectables = {
    '$somethingInjectable': './path-to-injectable/index.js',
    '$log': './path-to-log-service/index.js'
  };

  const di = (param) => {
    const path = injectables[param.name];
    param.name = path
      ? `${param.name} = require('${path}')`
      : param.name;
  };
  
  const findConstructor = function(klass) {
    return klass.body.body.filter((body) => {
      return body.kind === 'constructor';
    })[0];
  };

  const getArguments = function(ctor) {
    return ctor.params;
  };
  return {
    'name': 'mochi-di',
    'visitor': {
      ArrowFunctionExpression(nodePath) {
        nodePath.node.params.forEach((param) => {
          di(param);
        });
      },
       FunctionExpression(nodePath) {
        nodePath.node.params.forEach((param) => {
          di(param);
        });
      },
       ClassMethod(nodePath) {
        nodePath.node.params.forEach((param) => {
          di(param);
        });
      },
       ClassDeclaration(nodePath) {
        const ctor = findConstructor(nodePath.node);
        const args = getArguments(ctor);
        args.forEach((param) => {
          di(param);
        });
       }
    }
  };
};
```

**Comment by bcoe** [comment]
@jaunkst I'm really curious to see what you come up with, with regards to an API. I think to stat, this would probably make sense as a plugin for yargs, that folks could run along with it. I've been wanting to add a section to the yargs website that showcases these related modules.

**Comment by jaunkst** [comment]
My use case is to allow for external command modules to be developed and installed to extend a core CLI framework.

The CLI framework provides core service modules that can be injected into the developers project without requiring any of the core modules to be brought in via a package manager.

#### service module
service modules are are injected via AST transformation
```
// @flow
import emoji from 'node-emoji';

class Logger {
  options: any;

  constructor(): Logger {
    this.options = {'emojis': true, 'colors': true};
    return this;
  }

  config(options: any): Logger {
    this.options = Object.assign(this.options, options);
    return this;
  }

  log(msg: any): void {
    if (this.options.emojis) {
      process.stdout.write(emoji.emojify(msg));
      process.stdout.write('\n');
    } else {
      process.stdout.write(msg);
      process.stdout.write('\n');
    }
  }
}

module.exports = new Logger();
```

#### command module
command modules have their own npm dependencies ect. no imports required for api services.
```
// @flow
exports.command = 'upgrade';
exports.desc = 'upgrade all plugins';
exports.aliases =  ['u'];
exports.handler = (argv: any, $mochiLog: any, $mochiModules: any): void => {
  $mochiModules
    .upgrade('modules/plugins/core').then((): void => {
      $mochiLog
        .config({'emojis': true})
        .log(':sparkle: all plugins upgraded');
    });
};
```

I am setting up a repository next to house command and service modules so a mochi_modules.json can define the required service, and command modules for a project to be managed via the CLI.

**Comment by bcoe** [comment]
@jaunkst I'm closing this issue, because it sounds like you've found a suitable workaround 👍 

Would love to see the project that you ended up using this approach in, can you share?
