### ISSUE TITLE
coerce function runs again for each alias

### ISSUE THREAD

**Issue by deployable** [yargs/yargs#729]
The coerce function for an argument with an alias will run multiple times, the initial run and then once more per alias. 

I only noticed as I was using the file coercion example and reading a largish file. 

```
let argv = require('yargs')
  .alias('file', 'f2')
  .alias('file', 'f3')
  .coerce('file', function (arg) {
    console.log('reading file', arg)
    return require('fs').readFileSync(arg, 'utf8')
  })
  .argv
```
then
```
$ node testyargs.js  --file test
reading file test
reading file test
reading file test

EISDIR: illegal operation on a directory, read
```

**Comment by deployable** [comment]
I believe the code is actually in the yargs-parser domain, I can raise an issue there if needed?

**Comment by maxrimue** [comment]
@deployable Good find! Sorry for the slow answer. Yes it seems like this is indeed a `yargs-parser` problem, could you open the issue there? Thanks!
