### ISSUE TITLE
Support `-f, --flag <VALUENAME>` usage

### ISSUE THREAD

**Issue by cspotcode** [yargs/yargs#730]
I can't find a way to output usage information like the following:

```
-d, --dir <PATH>   Removes all files within <PATH>
```
or
```
-d, --dir=PATH   Removes all files within PATH
```

Is this possible?  Providing a name for the option's value is descriptive and makes the usage clearer.

**Comment by maxrimue** [comment]
As of right now, there is no such feature available within yargs unfortunately, though I think what could work for you is [`.example()`](https://github.com/yargs/yargs#examplecmd-desc), with which you can give usage strings and descriptions, such as
```javascript
.example('$0 -d ~/Downloads', 'Removes all files in Downloads')
```
would result into this when help is shown:
```
Examples:
  myProgram -d ~/Downloads               Removes all files in Downloads
```

Does this work for you?

**Comment by bcoe** [comment]
closing since we haven't had any activity on this issue in a couple weeks.

@cspotcode I think @maxrimue is right that examples are a good option for this, they were designed as a way to provide more detailed usage instructions to your users.
