### ISSUE TITLE
Silent crash when calling `alias` with only one parameter.

### ISSUE THREAD

**Issue by SimonSchick** [yargs/yargs#739]
Not sure what exactly went wrong but there should be an assertion or any type of error happening when only passing 1 parameter to `.alias`

**Comment by bcoe** [comment]
I like the idea of starting to add some assertions at the tops of methods, to help people figure out when they've gone off the rails with the API; my coworker @ceejbot does this, and I like the methodology.

thoughts, @nexdrew, @lrlna, @maxrimue, etc.

**Comment by maxrimue** [comment]
That sounds like a good idea to me. What do you have in mind @bcoe? Just a bunch of conditional statements in each method, a little helper module or something else?

**Comment by lrlna** [comment]
I *really* like this idea! Straight up using [something like assert](https://www.npmjs.com/package/assert) with our API methods will probably be super helpful when people are debugging; even just checking `assert.ok` or `assert.equal` 💯 . Is that what you were thinking about @bcoe ?

**Comment by bcoe** [comment]
@maxrimue @iarna this is how @ceejbot approaches it:

https://github.com/numbat-metrics/numbat-collector/blob/master/lib/sink.js#L19

She just uses Node's built in assert library, and places an assert at the top of most public methods.

**Comment by lrlna** [comment]
Yep! Exactly what I was thinking! Definitely good with this approach

**Comment by iarna** [comment]
I use [aproba](https://github.com/iarna/aproba#readme) for my simple asserts. I prefer it as it's even lower friction than ceej's approach. (It's drawback is errors from it are necessarily more generic.)

Use in the real world looks like:
https://github.com/npm/npm/blob/latest/lib/install/validate-args.js#L12
