### ISSUE TITLE
Inconsistent array handling

### ISSUE THREAD

**Issue by kevincaradant** [yargs/yargs#743]
Hi 

Sorry to ask a basic use, but in my case I have this command line:

`node src\index.js --path 'C:\Users\Downloads\Humans\Hotel Transylvania' 'C:\Users\Downloads\Humans' --dest "C:\Users\Downloads\gooooooooo.txt"`   

OR    

`node src\index.js --path ['C:\Users\Downloads\Humans\Hotel Transylvania', 'C:\Users\Downloads\Humans'] --dest "C:\Users\Downloads\gooooooooo.txt"`    

NB: I don't know what can I use for my needs

I need to get the content of` --path` arg in array in the aim to loop on it in my js code. But I don't successful. I tried `.array('path');` but it cut after every space character as a string, and  I dont want it.
The bad result is:
```
Ex: [ '\'C:\\Users\\Downloads\\Humans\\Hotel',
  'Transylvania\',
  '\'C:\\Users\\Downloads\\Humans\'' ]
```

If you have any idea about to get a result (Array type) like this:
`['C:\Users\Downloads\Humans\Hotel Transylvania', 'C:\Users\Downloads\Humans']`

Thank you in advance :)

**Comment by maxrimue** [comment]
@kevincaradant That's interesting, I can't replicate this result on my machine.

With this config:
```javascript
const yargs = require('yargs');
console.log(yargs.array('path').argv);
```

I get:

```shell
node index.js --path 'C:\Users\Downloads\Humans\Hotel Transylvania' 'C:\Users\Downloads\Humans' --dest "C:\Users\Downloads\gooooooooo.txt"

{ _: [],
  path: 
   [ 'C:\\Users\\Downloads\\Humans\\Hotel Transylvania',
     'C:\\Users\\Downloads\\Humans' ],
  dest: 'C:\\Users\\Downloads\\gooooooooo.txt',
  '$0': 'index.js' }
```

Can you tell us the version of yargs you use and the os you're using? Thanks for creating the issue.

**Comment by kevincaradant** [comment]
Hi

Yes of course, I'm using Windows 10 Pro 64 bits. I didn't try on Linux because I didn't think it was a bug.
The version of yargs is 6.5.0

If you need more info, tell me :).

Thanks !

**Comment by maxrimue** [comment]
I can confirm this is an issue on Windows specifically. This issue occurs every time an item within an array has a white space, such as `'hello there' 'bye'` will result into `[ '\'hello', 'there\'', '\'bye\'' ]`.

**Comment by kevincaradant** [comment]
Did you have an idea how / when to resolve this issue. I can't evolve my npm module which need to have this feature available.
It's just to know even if you need some times to resolve it ;)

**Comment by bcoe** [comment]
@kevincaradant @maxrimue unfortunately, this seems to be related to how windows handles single-quoted strings. the Node process is passed `process.argv`, which is what yargs applies its parsing to.

If single quotes are used in Windows you get:

<img width="435" alt="screen shot 2017-01-05 at 10 13 14 pm" src="https://cloud.githubusercontent.com/assets/194609/21709209/35890c30-d394-11e6-9390-c1ff9345ecc9.png">

however, there's fortunately a workaround, use double quotes 👍 

<img width="498" alt="screen shot 2017-01-05 at 10 13 26 pm" src="https://cloud.githubusercontent.com/assets/194609/21709226/4b0dfc78-d394-11e6-95cb-f5227629b9cb.png">

I wish there was a better solution for you; but unfortunately this is an OS level oddity it would appear.

**Comment by kevincaradant** [comment]
Ah yes, sorry I though that the behavior was the same with doublequote and simplequote under Windows, I didn't test correctly.
This workaround with doublequote is good for me, Thank you to notice me about it ! ;)
