### ISSUE TITLE
No errors when executing CLI without required argument

### ISSUE THREAD

**Issue by jeud** [yargs/yargs#745]
Dear all

I would like to execute my cli as this example `node cli.js html readme.md -t 0`

I have defined yargs configuration as below

```
const argv = yargs
    .command('html <markdown-file>', 'convert a markdown file to HTML file')
    .option('t', {
        alias: 'blog-type',
        describe: 'blog type ID associated with the markdown file',
        type: 'number',
        demand: true,
        demand: 'Blog type ID must be specified'
    })
    .help()
    .argv
```

> I tried `.command('html <markdown-file> -t', ...)`, `.command('html <markdown-file> -t <t>', ...)`, `.command('html <markdown-file> <t>, ...)` these are all incorrect and always complain for optional parameter although already provided

Executing `node cli.js --help` outputs as as below
```
Commands:
  html <markdown-file>  convert a markdown file to HTML file

Options:
  -t, --blog-type  blog type ID associated with the markdown file
                                                             [number] [required]
  --help           Show help                                           [boolean]
```

But I still can execute the `cli` without `-t` option using `node cli.js html readme.md`, with no errors at all

I'm not sure my configuration is correct or not, please help

> yarn@6.6.0

Thanks

**Comment by nexdrew** [comment]
@jeud Try configuring your option to be global (so it applies to all commands) by adding this to your option object:

```js
global: true
```

**Comment by jeud** [comment]
@nexdrew 

That's working for this question, thanks

What about if I also would like to have another command with different options will the `global: true` cause me problem?

**Comment by nexdrew** [comment]
@jeud Great question!

The answer is yes, any globally configured options will affect all commands; so if the `-t` option should only apply to (i.e. only be required for) the `html` command, then you should define the option in the command builder instead, like this:

```js
yargs
  .command('html <markdown-file>', 'convert a markdown file to HTML file', {
    t: {
      alias: 'blog-type',
      desc: 'Description',
      type: 'number',
      demand: 'Error message'
    }
  }, argv => {
    console.log('converting md to html, type:', argv.t)
  })
```

In this example, I'm using an object as the command builder (3rd argument) but it could also be a synchronous function that accepts yargs as an argument (for any configuration beyond just options).

**Comment by jeud** [comment]
@nexdrew 

Thanks again, I have tried this (trying to follow the documentation) but I have no ideas what went wrong (or I just don't know how to do it) nothing shows when using `--help` nothing about **required arguments**

This is my entire file

```
#! /usr/bin/env node

const yargs = require('yargs')

const argv = yargs
    .command('html <markdown-file>', 'convert a markdown file to HTML file', {
        t: {
            alias: 'blog-type',
            desc: 'Description',
            type: 'number',
            demand: true,
            demand: 'Error message'
        }
    }, argv => {
        console.log('converting md to html, type:', argv.t)
    })
    .help()
    .argv

console.log(argv)
```

Do I need to call some other methods to make this to work ?, `--help` shows nothing and I still can execute the command without `-t` argument

**Comment by jeud** [comment]
This is also not working, no errors without `-t` argument and nothing shows using `--help`

```
const yargs = require('yargs')

const argv = yargs
    .command('html <markdown-file>', 'convert a markdown file to HTML file', (yargs) => {
        return yargs.option('t', {
            alias: 'blog-type',
            demand: true,
            global: true
        })
    })
    .help()
    .argv

console.log(argv)
```

**Comment by nexdrew** [comment]
I am currently AFK (been doing this from my phone) but will dig into this further soon and get back to you.

**Comment by nexdrew** [comment]
@jeud Note that options specific to a command will only be displayed in help text that is specific to that command, so I wouldn't expect the option to show up with `cli --help` but it would show up with `cli html --help` or `cli html help` or `cli help html`.

I think something like this is closer to what you want:

```js
#! /usr/bin/env node

const yargs = require('yargs')

const argv = yargs
  .command('html <markdown-file>', 'convert a markdown file to HTML file', yargs => {
    yargs
      .option('t', {
        alias: 'blog-type',
        desc: 'blog type ID associated with the markdown file',
        type: 'number',
        demand: 'Blog type ID must be specified'
      })
      .demand(1, 'Please specify a markdown file')
  }, argv => {
    argv._handled = true
    console.log('converting md to html, type:', argv.t)
  })
  .demand(1, 'Please specify a command')
  .help()
  .argv

if (!argv._handled) console.log(argv)
```

```console
$ node issue745.js               
Commands:
  html <markdown-file>  convert a markdown file to HTML file

Options:
  --help  Show help                                                    [boolean]

Please specify a command
```

```console
$ node issue745.js html
issue745.js html <markdown-file>

Options:
  --help           Show help                                           [boolean]
  -t, --blog-type  blog type ID associated with the markdown file
                                                             [number] [required]

Please specify a markdown file
```

```console
$ node issue745.js html file
issue745.js html <markdown-file>

Options:
  --help           Show help                                           [boolean]
  -t, --blog-type  blog type ID associated with the markdown file
                                                             [number] [required]

Missing required argument: t
Blog type ID must be specified
```

```console
$ node issue745.js html file -t 1
converting md to html, type: 1
```

When using a command-based CLI, you could also organize commands into submodules and then use either `.commandDir('lib/commands')` or `.command(require('lib/commands/html'))`, for example.

Let me know if you have further questions or if you have a suggestion for how to make the API better fit your needs.

**Comment by jeud** [comment]
@nexdrew Thanks for a wonderful set of guides and examples, I will try to give you some feedback as soon as posible
