### ISSUE TITLE
Add option shorthand for conflicts / implies

### ISSUE THREAD

**Issue by vseventer** [yargs/yargs#751]
To my surprise, `implies` (and, coming in the next release, `conflicts`) are not available as option shorthand. Adding this would enable:

```
yargs.option('foo', {
  type: 'boolean',
  implies: 'bar',
  conflicts: 'baz'
});

// Same as:

yargs
  .boolean('foo')
  .implies('foo', 'bar')
  .conflicts('foo', 'baz');
```

Please let me know what you think. I'd be more than happy to submit a PR for this.

**Comment by maxrimue** [comment]
@vseventer Hm, can't really think of a reason why not to add this. I see you created the necessary commit already, would be awesome of you to open a pull request with it! Thanks.
