### ISSUE TITLE
Unnamed args reorder if they match a command

### ISSUE THREAD

**Issue by JakeSidSmith** [yargs/yargs#752]
I'm not sure if this is intended functionality, please correct me if I'm wrong, but I've been having an issue with unnamed args.

Args appear to be reordered / replaced (always the first one) when one of the unnamed args matches a command defined in the config.

Using version `6.6.0`

**Config**
```javascript
var argv = yargs
  .command('build', 'Build the thing')
  .argv;

console.log(argv);
```

**Shell output**
```shell
command build foo
{ _: [ 'build', 'foo' ], '$0': 'command' }
# Correct

command foo build
{ _: [ 'build', 'build' ], '$0': 'command' }
# Not what I was expecting

command foo bar build
{ _: [ 'build', 'bar', 'build' ], '$0': 'command' }
# Definitely not what I was expecting
```

Ideally I'd only want commands to match my config if they are the first unnamed arg, and subsequent unnamed args to have to match sub commands.

**Comment by bcoe** [comment]
Hey @JakeSidSmith, I apologize that this bug was never triaged. Looks like we probably fixed this bug ages ago.

**Comment by JakeSidSmith** [comment]
No worries. :blush:
