### ISSUE TITLE
demand groups of options

### ISSUE THREAD

**Issue by danielo515** [yargs/yargs#754]
Hello,

I was thinking that it would be awesome to be able to demand options by groups. This means, that I want to demand one set of options, but if one set of options is provided, the other one should not be demanded, if no option is provided, the help kicks in demanding at least one of the group options.

For example, I want my command to demand user information. The information can be inputted in form of a long string, or a set of options. So, if the options are provided, the long string is not required, and if the long string is provided then the other options are not required, but at least one or the other are required.

Is this possible already?

**Comment by danielo515** [comment]
Ok, seems that the method [implies](https://www.npmjs.com/package/yargs#impliesx-y) is the way to go. Now I have to figure how specify this on a command module

**Comment by bcoe** [comment]
@danielo515 this should do the trick for you:

```js
yargs
  .command('user-command', 'some user command', (yargs) => {
    yargs
      .implies('name', 'password')
      .implies('name', 'zipcode')
  })
```

If you run into any issues, feel free to hop into our gitter chat.

**Comment by danielo515** [comment]
Thank you very much !

**Comment by bkdotcom** [comment]
only implies the last one..  ie only zipcode will be implied/required
if zipcode is specified without password, yargs won't catch it
