### ISSUE TITLE
Bug: .check ignored when .command is specified and complied with

### ISSUE THREAD

**Issue by giacecco** [yargs/yargs#762]
I'm using version 6.6.0. The code below intentionally triggers an error:

```
var argv = require('yargs')
    .check((argv, opts) => { throw(new Error("Error!")); return false; })
    .argv;
console.log("Hello world!");
```

```
$ node test.js

Error!
$ 
```

... but if I add a ```.command``` directive, it does not:

```
var argv = require('yargs')
    .command("foo")
    .check((argv, opts) => { throw(new Error("Error!")); return false; })
    .argv;
console.log("Hello world!");
```

```
$ node test.js foo
Hello world!
$ 
```

Oddly enough, if I don't provide the specified command, then ```.check``` works again:

```
$ node test.js bar
Commands:
  foo

Error!
$
```

**Comment by bcoe** [comment]
@giacecco I believe this is working as expected, because checks are not applied globally by default; rather they are applied at the level they're executed.

So this would have the behavior you expect:

```js
var argv = require('yargs')
    .command("foo", (yargs) => {
      yargs.check((argv, opts) => { throw(new Error("Error!")); return false; })
    })
    .check((argv, opts) => { throw(new Error("Error!")); return false; })
    .argv;
console.log("Hello world!");
```

This re-registers the check on the instance of yargs that is executed for the command.

_Now!_ I understand the fact that many of these settings are not applied globally (to all commands)_ is confusing. We're in discussion on `yargs@7.x` #742, to change this default behavior. Would love to have you add your thoughts.

**Comment by giacecco** [comment]
@bcoe thanks, but I've tried your code and it does not work. Of course I am not as knowledgeable as you of yargs, but there is something wrong in the ```yargs``` object handed over to the handler function. ```check``` simply does not exist there. Try the code below:

```
var argv = require('yargs')
    .command("foo", "[some description]", { }, (yargs) => {
        yargs.check((argv, opts) => { throw(new Error("Error 1!")); return false; })
    })
    .check((argv, opts) => { throw(new Error("Error 2!")); return false; })
    .argv;
console.log("Hello world!");
```

You will get:

```
$ node test.js foo
test.js foo

yargs.check is not a function
$
```

I don't have the permissions to re-open this issue.

**Comment by bcoe** [comment]
@giacecco the third argument is the `builder`, the fourth argument is the `handler` (you can optionally choose to react to parsed options for a command here rather than at the top-level of the application:

```js
var argv = require('yargs')
    .command("foo", "[some description]", (yargs) => {
        yargs.check((argv, opts) => { throw(new Error("Error 1!")); return false; })
    })
    .check((argv, opts) => { throw(new Error("Error 2!")); return false; })
    .argv;
console.log("Hello world!");
```

So, I think the only problem above is the `{ }` which you have as the third argument.

**Comment by rickardrosen** [comment]
Where would I put the check() when a command is a required module?

```
var argv = require('yargs')
.command(require(mycommand))
```

I would like to be able to do:
`exports.check = function(argv){...}`

How can I set up checks for command modules?

**Comment by nexdrew** [comment]
@rickardrosen You should be able to add the check in the `builder` function exported by the module. Something like this:

```js
module.exports = {
  command: 'blah',
  desc: 'The blah command',
  builder: yargs => {
    yargs.check(argv => {
      // your logic here
    })
  },
  handler: argv => {
    // check logic has passed
  }
}
```

That being said, it _would_ be nice if yargs looked for more properties on the exported module.

**Comment by rickardrosen** [comment]
@nexdrew,, that seems to work. Thanks!

My scenario is that I need to validate the same input for several different commands, and each command in turn have to perform additional validations.

A global .check with additional exported module checks would be great!

**Comment by rickardrosen** [comment]
@nexdrew if I define builder as a function like you suggested, how do I define options as well as the check?

**Comment by nexdrew** [comment]
@rickardrosen Using the same yargs API methods, like `.option()`. Most, if not all, of the API is documented here: http://yargs.js.org/docs/index.html#methods

**Comment by bcoe** [comment]
@giacecco, @rickardrosen we're about to release a fairly major change to yargs, that defaults to applying most operations, e.g., `check`, globally -- my hope is that this will reduce the confusion that we bumped into on this issue.

I would love the help testing out some of these pretty major changes, before we release the feature to the wider user-base:

`npm cache clear; npm i yargs@next`

\o/

**Comment by rickardrosen** [comment]
@bcoe Hey, Thanks for the new version!

I'm testing the global check and it seems to work, at least in regards to functionallity.
I haven't really made any changes just moved the module scoped check to the global/app scope.

With the pervious version I got a nice message from yargs telling me the check had failed, but now I just get the error thrown or my own output and nothing else is fed back.

I have tried both throwing and returning false.

Do I need to do anything differently with regards to the check?

**Comment by rickardrosen** [comment]
Ok, sorry, strike that.

I'm working with promises & async/await functions, but the check is obviously asynchronous.
Lifted the async/await stuff out of check and now it returns output as expected instead of just throwing the promise rejection.
