### ISSUE TITLE
.conflicts for a global options ignored in command, unless explicitly added to command handler

### ISSUE THREAD

**Issue by rasmuslp** [yargs/yargs#764]
I'm trying to define some options, which should be mutually exclusive, but the `.conflicts` option specified on top-level seems to be ignored when a command is provided. Is this the intended behaviour?

#### v1

```JS
// v1: Plain .conflicts
require('yargs')
    .command({
        command: 'a'
    })
    .option('b', {
        global: true
    })
    .option('c', {
        global: true
    })
    .conflicts('b', 'c')
    .argv;
```

If I run v1 with no command, yargs stop me. But if I add the command, it doesn't:
``` bash
$ node v1.js -b 2 -c 3
Arguments b and c are mutually exclusive

$ node v1.js a -b 2 -c 3
# No output
```

#### v2
```JS
// v2: Explicitly added .conflicts to command builder
require('yargs')
    .command({
        command: 'a',
        builder: function (yargs) {
            return yargs
                .conflicts('b', 'c');
        }
    })
    .option('b', {
        global: true
    })
    .option('c', {
        global: true
    })
    .conflicts('b', 'c')
    .argv;
```

In v2 yargs stops me:
``` bash
$ node v2.js -b 2 -c 3
Arguments b and c are mutually exclusive

$ node v2.js a -b 2 -c 3
Arguments b and c are mutually exclusive
```

**Comment by bcoe** [comment]
@rasmuslp this is currently intended behavior; but we're in discussion regarding changing the default behavior of options in yargs@7. Please join the conversation in #742 and provide your two cents ... at this point I'm pretty convinced that options should default to being global.

**Comment by rasmuslp** [comment]
Alright, thank you for the response and the pointer.

**Comment by bcoe** [comment]
@rasmuslp I just released a candidate release of yargs 7.x, which switches most settings to being applied globally -- I think this makes the API less confusing.

I would love your help testing out the new release against some of your libraries, before we push things out to a wider audience:

`npm cache clear; npm i yargs@next`

Let me know what you think.
