### ISSUE TITLE
.array() does not work well with array of length 1 and camel case flags accessing

### ISSUE THREAD

**Issue by weiwei-lin** [yargs/yargs#768]
yargs ^6.6.0

Code in `a.js`
```
'use strict';
const yargs = require('yargs');
const flags = yargs
  .array('a-b')
  .argv;

console.log(flags['aB']);
console.log(flags['a-b']);
```

Issue: does not convert argument to an array when the argument is an array of length 1 and the argument is accessed by camel case.
Run command `node a.js --a-b a`
Results:
```
a  // expected: ['a']
[ 'a' ]
```

It works very well when the argument is an array of length > 1
Run command `node a.js --a-b a b`
Results:
```
[ 'a', 'b' ]
[ 'a', 'b' ]
```

Also works when the array is empty
Run command `node a.js --a-b a b`
Results:
```
[]
[ ]
```

**Comment by bcoe** [comment]
I apologize that this ticket was never addressed for you (_I'm currently cleaning up some old issues_.).

At some point in the past, this bug was fixed:

```bash
$ node foo.cjs --a-b a
[ 'a' ]
[ 'a' ]
```
