### ISSUE TITLE
Support for a "base" command

### ISSUE THREAD

**Issue by scriptdaemon** [yargs/yargs#769]
There doesn't seem to be a nice way to simultaneously have a "base" command and allow subcommands for said "base" command to be added at different points in time. I'm wondering if it would be of interest to have a way to add a global "base" command that all commands would be added to.

Logically something like the following (though I'm not sure what to call the method):

```js
// Subcommand
const dice = {
  'command': 'dice <roll>',
  'description': 'Roll the dice',

  handler (argv) {
    // Roll the dice
  }
}

// Subcommand
const ping = {
  'command': 'ping',
  'description': 'pong',

  handler (argv) {
    // pong
  }
}

// Base command, applied globally do we don't have to add subcommands directly to it via builder().
yargs
  .base('!bot <command>', 'Release the kraken... er, bot') // This would probably accept the same parameters as command()
  .command(dice)
  .parse('!bot dice') // Roll the dice

// Base command still applied to the yargs object, so this will still be called via '!bot ping`
yargs
  .command(ping)
  .parse('!bot ping') // Responds with 'pong'
```

The reasoning behind my issue report is that currently you'd have to either only add the subcommands at one point in time, which sacrifices the ability to extend the bot or add the "base" command to each subcommand, e.g.:

```js
// Subcommand
const ping = {
  'command': '!bot dice <roll>',
  'description': 'Roll the dice',

  handler (argv) {
    // Roll the dice
  }
}
```

This adds a slight amount of boilerplate to each command. Plus, if this is being used to build an API, a developer can set the base command once and not have to worry about forgetting what base command is being used down the road.

**Comment by maxrimue** [comment]
Hey @scriptdaemon,
so if I get this right, you're asking for a good way to add subcommands _during_ runtime of your application?

**Comment by scriptdaemon** [comment]
It's more of a request to allow for a more elegant API. It seems a bot API would be much nicer if there was a way to do what I showed in my original post. I suppose this could be accomplished the same way by allowing someone using the API to specify a directory that would get added in at the same time as built-in commands, so I wouldn't be heartbroken if this would be considered not worth the effort.
