### ISSUE TITLE
Documentation on options() demand inconsistent

### ISSUE THREAD

**Issue by pushplay** [yargs/yargs#771]
The README example for options includes `demand` as a parameter:

```
var argv = require('yargs')
    .options({
      'f': {
        alias: 'file',
        demand: true,
        default: '/etc/passwd',
        describe: 'x marks the spot',
        type: 'string'
      }
    })
    .argv;
```

but the list of valid parameters doesn't include `demand`:

```
defaultDescription: string, use this description for the default value in help content, see default()
demandOption: boolean or string, demand the option be given, with optional error message, see demandOption()
desc/describe/description: string, the option description for help content, see describe()
```

Is it still valid?  Deprecated?  Should it be removed from the example?

**Comment by maxrimue** [comment]
Good catch! Yeah, though still working, this way of demanding options has been deprecated and thus is not documented anymore, I'll get the docs fixed. Thanks!

**Comment by bcoe** [comment]
@pushplay we've landed updated documentation against our `7.x` branch, which will hopefully go out the door relatively soon.
