### ISSUE TITLE
Feature Inquiry: Generate Markdown CLI Documentation

### ISSUE THREAD

**Issue by tatemz** [yargs/yargs#774]
It seems to me that the core feature of yargs is its ability to dictate functionality based on the developer's documentation. I love that yargs leads the charge by emphasizing strongly documented CLI tools.

It'd be great if yargs also could handle generating markdown documentation for my custom CLI tool. That way I can publish it with my repo.

Any thoughts?

**Comment by maxrimue** [comment]
Hey @tatemz,
this sounds like an epic feature, but I'm afraid it's a bit out of yarg's original intentions and would also require a lot of code. This would rather be something for a new module IMO.

If you're okay with your docs not being markdown but regular text, you might be able to automatise this still using existing tools. I'm imagining a pre-publish script that pipes help output into a readme file:
```json
...
scripts {
  ...
  "prepublish": "./mybin.js --help > readme"
  ...
}
...
```
Sorry, but thanks for creating the issue anyway!

**Comment by tatemz** [comment]
@maxrimue - Thanks for the reply. At least this issue can be searchable for anyone who has the same idea. Additionally, it can kick off any conversation until a future solution takes it over. 

Yargs is awesome, btw!

**Comment by bcoe** [comment]
@tatemz @maxrimue I like this idea a lot, I think it would be a great idea for an OSS library separate from  the core yargs module itself -- if you wanted to give it a shot @tatemz, we'd happily contribute and blog about the tool. I'd also be happy to create the repo in our org and give you access to it, if you would rather this than build it in your personal account.

I'd look at this:

https://www.npmjs.com/package/marky-markdown

**Comment by ozum** [comment]
This seems to generate README.md from yargs:

https://github.com/EliseevNP/cli-docs-generator?spm=a2c6h.14275010.0.0.3f872e28CXGJFf

**Comment by stevenalanstark** [comment]
I ended up here from google, so I figure I should add my solution as well

for my purposes, this solution worked better:

```package.json
    "preversion": "npm run readme:build && npm run readme:git:add && npm run readme:git:commit",
    "readme:build": "echo '```pre' > README.md && node ./dist/index.cjs help >> README.md && echo '```' >> README.md",
    "readme:git:add": "git add README.md || true",
    "readme:git:commit": "git commit -m'updating readme.md' || true",
```
