### ISSUE TITLE
Repeating options with type array have inconsistent behaviour (with do-notation)

### ISSUE THREAD

**Issue by JeroenVdb** [yargs/yargs#777]
Since the 6.X.X update I'm seeing inconsistent behaviour when I repeat "normal" flags and dot-notated flags.

When I repeat normal flags of the type array each value is part of the array list.
When I repeat dot-notated flags the first value is converted into an array item of type string but subsequent values are wrapped inside an array object.

```
var args = require('yargs')
  .option('metricList', {
	  type: 'array'
  })
  .option('metric.list', {
	  type: 'array'
  })
  .argv;

console.log(args);
```

```
$ npm install yargs@5.0.0 --save
$ node yargstest.js --metric.list AA --metric.list BB --metricList CC --metricList DD

{ _: [],
  metric: { list: [ 'AA', 'BB' ] },
  metricList: [ 'CC', 'DD' ],
  '$0': 'yargstest.js' }

$ npm install yargs@6.6.0 --save
$ node yargstest.js --metric.list AA --metric.list BB --metricList CC --metricList DD

{ _: [],
  metric: { list: [ 'AA', ['BB'] ] },
  metricList: [ 'CC', 'DD' ],
  '$0': 'yargstest.js' }
```

I guess one of both is wrong? In my opinion I would guess the v5.0.0 way is correct and the most intuitive?

**Comment by JeroenVdb** [comment]
It looks like this is probably a problem with the yargs-parser `flatten-duplicate-arrays` option.

Should this issue be moved or should I duplicate this in the correct repo?

**Comment by bcoe** [comment]
@JeroenVdb hoping to spend a few hours yargs hacking tomorrow, thanks for the bug report and pull request to yargs-parser.

**Comment by JeroenVdb** [comment]
Thanks! I Think the PR indicates the place of the problem but because you know the code base beter there might be beter solutions.

**Comment by bcoe** [comment]
I apologize for allowing this issue to stay open so long, it appears that  at some point this specific problem was addressed in full:

```bash
foo.cjs --metric.list AA --metric.list BB --metricList CC --metricList DD
{ _: [], metric: { list: [ 'AA', 'BB' ] }, metricList: [ 'CC', 'DD' ] }
```
