### ISSUE TITLE
Get non standard options

### ISSUE THREAD

**Issue by pedro93** [yargs/yargs#778]
Hello,

Is there a way to get an array of the non-standard options? By this I mean any parameter set the option function and similars, excluding the usual: help, version and $0.

Also I noticed that when creating an option which has a hyphen, the argv object will have it replaced by the name in camel case, e.g:
```js
const flags = yargs
  .help('help')
  .version(() => require('../package').version)
  .showHelpOnFail(false, 'Specify --help for available options')
  .wrap(yargs.terminalWidth())
  .usage('Usage: $0 <url>')
  .command('url', 'URL to test')
  .option('output-path', {
    'describe': 'The file path to output the results',
    'type': 'string',
    'default': '',
    'group': 'Output:'
  });
console.log(flags);
```
output:
```bash
$ node bin/cli.js something
> { _: [ 'something' ],
   help: false,
   version: false,
   'output-path': '',
   outputPath: '',
   '$0': 'bin/cli.js' }
```
Is this intended, in the context of the original question how would that work?

__Edit__: 
I have found how to remove the camel cased option, only needed to add the following to my package.json:
```js
...
"yargs": {
    "camel-case-expansion": false
  }
```
Thank you for all your work :)

**Comment by bcoe** [comment]
@pedro93 lost track of this issue (_I'm doing a bit of cleanup._). The only special keys are `_`, `$0`, `help`, `version`, and sometimes  `--`. Could you just exclude these keys yourself after parsing? It feels like it might be feature creep to build this into yargs itself.

**Comment by bcoe** [comment]
@pedro93 there's a good chance you've moved on from this specific problem now, so I'm going to go ahead and close this.

I wanted to also point you towards [`parserConfiguration()`](https://github.com/yargs/yargs/blob/master/docs/api.md#parserconfigurationobj), which makes it even easier to turn off settings like `camel-case-expansion`.
