### ISSUE TITLE
double-freeze with completion

### ISSUE THREAD

**Issue by kentcdodds** [yargs/yargs#782]
It's kinda hard to explain, so I created [this 3 minute video](https://www.youtube.com/watch?v=_VDQXWI54_M&feature=youtu.be) to demonstrate what's going on.

Basically, when I call `parse`, `freeze` is called, then `parseArgs` is called which eventually calls `freeze` again, then `unfreeze` is called, then `parseArgs`returns and `unfreeze` is called again. It's that last call to `unfreeze` that blows up because `frozen` is now `undefined.

Any ideas appreciated!

**Comment by kentcdodds** [comment]
I just realized that the problem is I'm mocking `exit` so it doesn't exit my testing process. In normal completion, this will exit and we don't worry about it. Thanks!

**Comment by bcoe** [comment]
@kentcdodds phew, was worried I'd have to dive into the completion code -- it's a little sticky.

**Comment by kentcdodds** [comment]
Thanks again for yargs. It's super!
