### ISSUE TITLE
Inconsistent array parsing when value is passed through `config()` option

### ISSUE THREAD

**Issue by le0nik** [yargs/yargs#789]
Passed through cli:

```js
const argv = require('yargs')
  .options({
    arr: {
      type: 'array',
    },
  })
  .argv;

console.log('argv', argv);
```

`$ node ./test.js --arr foo bar`
Outputs: `argv { _: [], arr: [ 'foo', 'bar' ], '$0': 'test.js' }`

Passed through `.config()`

```js
const argv = require('yargs')
  .config({
    arr: 'foo bar',
  })
  .options({
    arr: {
      type: 'array',
    },
  })
  .argv;

console.log('argv', argv);
```

`$ node ./test.js`
Outputs: `argv { _: [], arr: [ 'foo bar' ], '$0': 'test.js' }`

yargs@6.6.0

**Comment by le0nik** [comment]
Found that it's an issue with https://github.com/yargs/yargs-parser. Maybe something like https://github.com/mccormicka/string-argv could be used to parse strings into arrays.

**Comment by bcoe** [comment]
@le0nik I believe this is expected behavior, when passing config, this should be the already parsed values, so you'd pass something like this:

```
yargs.config({
  arr: ['foo', 'bar', 'snuh']
})
```

Which could be overridden with:

`foo.js --arr foo bar`

Is it wort adding a note to our documentation on this topic?

**Comment by le0nik** [comment]
@bcoe the reason I was sure it was going to work is that it works for other types of values. If I pass `'true'` and the `type` of this option is `boolean` the resulting value's going to be `true`. Same works with numbers. In my case I've added a preprocessing step before passing config to yarn where I parse array option(if it's value is string).

**Comment by bcoe** [comment]
@le0nik valid point, perhaps open an issue on `yargs-parser` I'd definitely consider supporting this.
