### ISSUE TITLE
why yargs is called yargs?

### ISSUE THREAD

**Issue by zzzgit** [yargs/yargs#800]
why yargs is called yargs?

`var argv = require('yargs').argv;`,what does `v` mean in `argv`?

**Comment by bcoe** [comment]
ynot?

**Comment by bcoe** [comment]
http://crasseux.com/books/ctutorial/argc-and-argv.html joking aside, in GNU C, you get two values into your method:

`argc`, the argument count, and `argv` the argument vector.

yargs is an amalgam of pirate speak and argument parsing.
