### ISSUE TITLE
[Tracking] Refactor dem docs

### ISSUE THREAD

**Issue by maxrimue** [yargs/yargs#809]
I would like to use this issue to clearly define eventual goals for our documentation. Below, I've listed some points that I _think_ I remember getting discussed in various places. Let me know what you think about it, and then let's do this 💪 

- Reorganise documentation into several topics/files (=> don't use main readme for docs anymore?)
- Head for more readability by more expanding on topics/functionalities and using less pirate english 
- Write "tutorials" that eventually also can be used on the website

**Comment by bcoe** [comment]
@maxrimue oh my goodness, I'd love to get this in motion ... I'd love to look at some existing projects, e.g., `lodash`, `express`, `async`, and see if we could start to come to a standard structure for the `docs/` folder.

**Comment by bcoe** [comment]
see: https://github.com/yargs/yargs/pull/892
