### ISSUE TITLE
Bash completion with Positional Arguments

### ISSUE THREAD

**Issue by atian25** [yargs/yargs#818]
- command: `exports.command = 'test <dir>';`
- exec: `node bin.js --get-yargs-completions`
- output: `test <dir>`
- then the bash completion will output  `test` and `<dir>`

[completion](https://github.com/yargs/yargs/blob/master/lib/completion.js#L59) should be `command[0].split('  ')[0]`

**Comment by bcoe** [comment]
@atian25 sorry for the slow reply! I agree this seems like it would be better behavior.

I would be grateful for a patch 👍

**Comment by bcoe** [comment]
@atian25 @IvanGoncharov this is queued up to be released in the next major release of yargs. I would love your help testing:

`npm i yargs@next --save`
