### ISSUE TITLE
Validate the options declaration

### ISSUE THREAD

**Issue by gajus** [yargs/yargs#819]
I have just switched a project from yargs v6 to v7 and was chasing a bug.

```js
// eslint-disable-next-line flowtype/no-weak-types
export const builder = (yargs: Object): void => {
  // eslint-disable-next-line
  yargs
    .options({
      'database-database': {
        demand: true,
        type: 'string'
      },
      'database-host': {
        demand: true,
        type: 'string'
      },
      'database-password': {
        type: 'string'
      }
    })
    .argv;
};

```

Just scanning the code like this the issue is not obvious. It is only when I remembered about the deprecation of `demand` that I figured why I am not getting the expected error.

In short, I am proposing a change equivalent to https://github.com/webpack/webpack/pull/2974.

Add a JSON schema to validate [`options`](https://github.com/yargs/yargs#optionskey-opt).

**Comment by bcoe** [comment]
@gajus dug into this a bit, could you please try `npm i yargs@next`?

**Comment by gajus** [comment]
What code am I looking? (I cannot see any commits on the master branch relating to this.) It is easier to try something when knowing what I am testing.

**Comment by bcoe** [comment]
https://github.com/yargs/yargs/pull/820, @gajus this should correct the bug you have been running into.

I will release a patch immediately if this does the trick.

**Comment by gajus** [comment]
I am sure this works, by the looks of the code.

What about the broader issue – lack of validation of the API parameters?

**Comment by bcoe** [comment]
@gajus one of the features added in `yargs@7` was API parameter validation:

https://github.com/yargs/yargs/blob/master/yargs.js#L190

This was definitely a case of the API being used correctly, but an underlying bug.

If you have two seconds, it would be awesome if you might be able to run the `yargs@next` branch against your codebase -- having an extra person testing would be awesome.

**Comment by bcoe** [comment]
@gajus perhaps we could open an add-on ticket for the specific problem of validating the opions shorthands? seems like a natural extension to validating the chaining API; Given how constrained this problem is, my one requirement would be that we try to avoid pulling in any dependencies -- I'm trying to continue slimming down yargs.

**Comment by gajus** [comment]
> my one requirement would be that we try to avoid pulling in any dependencies -- I'm trying to continue slimming down yargs.

![36975944](https://cloud.githubusercontent.com/assets/973543/23775557/30cdbbfa-0521-11e7-89e5-7e2d303b235b.jpg)

As far as I can see, there aren't even open issue associated with the package size:

* https://github.com/yargs/yargs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20dependencies
* https://github.com/yargs/yargs/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20size%20

Duplicating the effort of implementing utilities and complex data validation libraries does not make sense. It increases bug surface, effort required to maintain the project and entry barrier for new developers to start contributing to the code base.

Anyway, this issue has been addressed apparently. Thank you. Yargs is a great library.
