### ISSUE TITLE
strict mode does not take into account camel-case for positional arguments

### ISSUE THREAD

**Issue by gajus** [yargs/yargs#823]
After upgrading to `yargs@7.0.2` and `node@v7.7.1` I started getting:

> Not enough non-option arguments: got 0, need at least 1

Command:

```bash
babel-node src/bin/index.js upload-data ./.data.json
```

Code:

Entry program:

```js
#!/usr/bin/env node

import yargs from 'yargs';

// eslint-disable-next-line no-unused-expressions
yargs
  .env('ASDMP')
  .strict()
  .commandDir('commands')
  .help()
  .wrap(80)
  .argv;

```

Command builder:

```js
export const command = 'upload-data <data-file>';
export const desc = 'Updates or inserts information to the database.';

export const builder = (yargs: Object): void => {
  yargs
    .env('ASDMP')
    .strict()
    .options({
      ...commandLineConnectionOptionsShape
    })
    .demandCommand(1, 1);
};

```

**Comment by gajus** [comment]
It appears this is `babel-node` independent (which was my first thought).

```bash
node dist/bin/index.js upload-data ./.data.json

```

gives the same error.

**Comment by gajus** [comment]
The issue goes deeper. Removing `demandCommand` doesn't fix it. The `argv.dataFile` value is not being captured.

**Comment by gajus** [comment]
It is starting to look like this is a dependency of a dependency thats breaking the behaviour. I have just tried downgrading to `v7.0.1` and it doesn't fix the behaviour.

**Comment by gajus** [comment]
Downgrading to v6 makes it work.

**Comment by bcoe** [comment]
@gajus I see the issue, it is a bit of an edge-case (which we should fix):

your initial problem was `.demandCommand`; this is not necessary because you're using non-optional positional arguments `<>`.

The underlying problem now biting you, is that strict does not seem to be taking into account the came-case form of positional arguments:

`exports.command = 'upload-data <datafile>';`

The above works as expected.

**Comment by gajus** [comment]
Understood. Thank you for clarifying.

**Comment by gajus** [comment]
Unless I am doing something wrong, this doesn't work either:

```
babel-node src/bin/index.js upload-data .movies.json
src/bin/index.js upload-data <datafile>

Options:
  --help               Show help                                       [boolean]
  --database-database                                        [string] [required]
  --database-host                                            [string] [required]
  --database-user                                            [string] [required]

Not enough non-option arguments: got 0, need at least 1
```

```js
export const command = 'upload-data <datafile>';
export const desc = 'Updates or inserts information to the database.';

const debug = createDebug('upload-data');

export const builder = (yargs: Object): void => {
  yargs
    .env('ASDMP')
    .strict()
    .options({
      ...commandLineConnectionOptionsShape
    })
    .demandCommand(1, 1);
};

```

**Comment by bcoe** [comment]
@gajus no need for the `.demandCommand` using the `<` `>` around `datafile` indicates that the positional argument is not optional (whereas `. demandCommand` would be used at the top level to indicate that, at least one command (e.g., `upload-data` is required).

**Comment by gajus** [comment]
Thank you

**Comment by bcoe** [comment]
@gajus I've been popping quite a bit of other work off the stack; so should be able to work on fixing this `camel-case` issue this weekend ... I just want to figure out the most elegant place to do so.

**Comment by gajus** [comment]
To be frank, I am not 100% sure it needs to be fixed. As long as the behaviour is documented, I find it less confusing to simply declare command API as `upload-data <dataFile>` as that maps 1-to-1 with the code base.

**Comment by sharmasourabh** [comment]
@gajus 
Is there any specific reason, bable-node migrated to commander?

**Comment by gajus** [comment]
I am not actively involved in anything to do with Babel project.

They have been using commander for many years though.

**Comment by mleguen** [comment]
Reducing @gajus example to:
```js
yargs
  .strict()
  .command(
    'upload-data <data-file>',
    'Updates or inserts information to the database.',
    yargs => yargs
  )
  .argv
```

it now works:
```bash
$ node index.js upload-data my-file.txt
{ _: [ 'upload-data' ],
  '$0': 'index.js',
  'data-file': 'my-file.txt',
  dataFile: 'my-file.txt' }
```
