### ISSUE TITLE
strange argv behavior

### ISSUE THREAD

**Issue by obibring** [yargs/yargs#830]
My colleague and I both experienced the following bug on our machines:

When executing:
```sh
$ coffee some-file.coffee --script=/some/path
```
`argv.script` was `undefined` (`argv` didn't contain the `script` key at all). I then executed the same command with additional options, ie:
```sh
$ coffee some-file.coffee --script=/some/path --x=4 --y=9
```
and still, `argv.script` was undefined, while `x` and `y` were working properly. Finally, after removing the `--script` option and adding it again as the last option, `argv.script` started working.

**Comment by bcoe** [comment]
@obibring curious why you closed this, did you figure out the underlying bug? anything we can fix on our end?

**Comment by obibring** [comment]
@bcoe, it was user error; the result of copy-pasting a command that appeared to use double dashes `--` with a command line option, but in fact, was using another character, causing `yargs` to ignore the option.

**Comment by bcoe** [comment]
@obibring perhaps open a feature request? I think we should parse these special dash characters.
