### ISSUE TITLE
typo on http://yargs.js.org home page

### ISSUE THREAD

**Issue by pandafeeder** [yargs/yargs#838]
On main page __getting started__ section:

The first sentence 

> **After creating hello.js start with the following code to get you going:**

I think it should be

> **After creating *example.js* start with the following code to get you going:**

**Comment by bcoe** [comment]
@pandafeeder great catch, if you have a few minutes, and feel like contributing, I would happily accept a patch here:

https://github.com/yargs/yargs.github.io

**Comment by pandafeeder** [comment]
Hi @bcoe ,  patch has been committed to https://github.com/yargs/yargs.github.io for this. Let me just close this one here. Thanks.
