### ISSUE TITLE
Demand options for a particular command

### ISSUE THREAD

**Issue by yousefamar** [yargs/yargs#839]
Forgive me if this is documented or discussed in previous issues, though I haven't found anything on this in either place — is it possible to demand options for particular commands? If not, I think it might be useful.

An example use case may be that a tool can run in two modes:

    cli-tool auto

and

    cli-tool interactive

the first version may accept input from `stdin`, and write to `stdout`, while the second version might prompt the user for information, or start ncurses, or similar, in which case it would need to use `stdin` and `stdout` for that.

So the usage for the first would be:

    cat file.txt | cli-tool auto > out.txt

while the usage for the second would be similar to:

    cli-tool interactive -i file.txt -o out.txt

As such, the options for input and output files should only be required for the second command, but not the first. If they're not there for the second, the usage should print. Is this possible?

**Comment by bcoe** [comment]
@yousefamar this functionality can be achieved using the third argument to a command which represents a `builder` and can be used to specify command specific options.

Flagged @nexdrew who built much of the command functionality -- I will also make an effort to update this ticket with more details once I finish triaging open bugs.

**Comment by yousefamar** [comment]
Thank you, I've been able to achieve the desired behaviour by using the builder argument. In order to have the same flags be optional for one command and required for another, I simply repeated them, rather than attempt something more imperative like under `.reset()` documentation.

I think I might have initially misunderstood how global scope and command scope works since I was looking at outdated information. I would appreciate those extra details since I might learn something, and for posterity, but otherwise please feel free to close this issue.

**Comment by bcoe** [comment]
@yousefamar awesome; I'm glad your unblocked.

would love your feedback here, we're looking to undertake a major docs overhaul:

https://github.com/yargs/yargs/issues/809
