### ISSUE TITLE
Positional arguments can’t properly be documented, have default values, &c.

### ISSUE THREAD

**Issue by chris-morgan** [yargs/yargs#842]
```js
yargs.command('subcommand <foo>')
     .describe('foo', 'some useful text')
     .default('foo', 'some default value')
```

Quite apart from the need for the subcommand (c.f. #841), you can’t properly document or give default values and types to positional arguments. This ends up with a mishmash of plain positional argument and `--foo`.

**Comment by bcoe** [comment]
@chris-morgan I agree, we should figure out an extension to the API that allows positional arguments to be documented in much the same way that regular options are.

What do you think this API would look like? It feels a bit weird for the description of positional arguments to be performed after the command is defined ... maybe instead this would be something that you configure in the command's builder function?

CC: @nexdrew, @JaKXz

**Comment by borela** [comment]
Just an idea, the `command` could accept either a string as it does now and or an options object:

```js
.command('some-command', 'some description')
.command('needs-args <foo> <bar> [baz]', {
  description: 'Command description',
  args: [{
    foo: {
      description: 'foo description',
      defaultValue: 42
    },
    bar: {
      description: 'bar description',
      defaultValue: 42
    },
    baz: {
      description: 'baz description',
      defaultValue: 42
    }
  }]
})
```

**Comment by bcoe** [comment]
@borela this is clever :) although I'd drag my feet a bit on introducing a new `args` parameter. I wonder if we could do something like this:

```js
.command('needs-args <foo> <bar> [baz]', {
  description: 'Command description',
  foo: {
      description: 'foo description',
      default: 42
   },
   bar: {
      description: 'bar description',
      default: 42
    },
    baz: {
      description: 'baz description',
      defaultValue: 42
    }
  }
})
```

where the values you can provide for positional options are _literally_ anything that you'd be able to provide for flag options ...

Could get even simpler and require that you define the options in the builder:

```js
.command('needs-args <foo> <bar> [baz]', 'description of command', (yargs) => {
  yargs.option('foo', {}).option('baz', {})
})
```

would this work? I like that it minimizes the extension to the API, and pulls positional options closer to being the same as hyphenated options; CC: @chris-morgan

**Comment by borela** [comment]
I thought about the option without the `args` but the advantage of that is that you could add new options and it would never conflict with the arguments identifier, e.g. `some-command <description>`. 

The idea of adding a third function as parameter is definitely better and more compact :
```js
.command(
  'needs-args <foo> <bar> [baz]', 
  'description of command', 
  args => args
    .option('foo', {
      description: 'some description',
      defaultValue: 42
    })
    .option('baz', {
      description: 'some description',
      defaultValue: 42
    })
)
```

**Comment by bcoe** [comment]
@borela what's a bit weird, is the builder (the third argument) is currently what's used to describe the options of sub-command, not the top level command -- so I guess this doesn't quite work the way we'd expect.

This makes me lean towards your suggestion, but something doesn't _quite_ feel right with the api for either of our suggestions... I definitely agree that the collision of keys probably makes it a bad idea to simply use the arguments as keys on the top level object -- lol, it's a shame that commands already have four arguments, the method is getting a bit overloaded.

**Comment by borela** [comment]
Yeah I forgot about the builder and sub commands. Maybe the other suggestion but with some minor changes, it could still accept strings to maintain compatibility:
```js
.command('some-command', 'some description')
.command(
  'needs-args <foo> <bar> [baz]',
  yargs => yargs
    .description('some description')
    .parameter('foo', {
      description: 'some description',
      defaultValue: 42
    })
    .parameter('baz', {
      description: 'some description',
      defaultValue: 42
    })
})

**Comment by Alxandr** [comment]
I'd also suggest a separate category (by default) for usage. Something like this:

```
my-awesome-thingy my-command <arg>

Arguments:
  arg      Info about arg                                [type]

Options:
  --help  Show help                                     [boolean]
```

**Comment by florianb** [comment]
Even though i am pretty new to the yargs-API i'd prefer having a dedicated namespace for arguments to a) prevent masking of properties (f.e. `git commit <description>`) and b) let arguments become a options-like member.

**Comment by ezze** [comment]
Looks like default values for positional arguments are already [supported](https://github.com/yargs/yargs/blob/master/docs/advanced.md#describing-positional-arguments):

```js
yargs.command('get <source> [proxy]', 'make a get HTTP request', (yargs) => {
  yargs.positional('source', {
    describe: 'URL to fetch content from',
    type: 'string',
    default: 'http://www.google.com'
  }).positional('proxy', {
    describe: 'optional proxy URL'
  })
})
.help()
.argv
```

**Comment by bcoe** [comment]
@ezze 👍 missed closing this issue when we introduced the `.positional()` feature.
