### ISSUE TITLE
imply multiple dependencies

### ISSUE THREAD

**Issue by bkdotcom** [yargs/yargs#845]
```
   var argv = require('yargs')
        .usage('Usage: $0 [options]')
        .option('ssl', {
            default: false,
            description: 'Use SSL?'
            // implies: ['ssl_cert', 'ssl_key'] // this doesn't work... unexpected array
        })
        .implies('ssl', 'ssl_cert')
        .implies('ssl', 'ssl_key') // only this one gets implied
        .option('ssl_key', {default:null, description:'filepath to ssl key'})
        .option('ssl_cert', {default:null, description:'filepath to ssl certificate'})
        .help()
        .alias('h', 'help')
        .argv;
```

`command --ssl`
outputs
> Implications failed:
  ssl -> ssl_key

(no mention of ssl_cert also being implied)

`command --ssl --ssl_key="/foo"`
will not catch that ssl_cert was not passed

**Comment by bkdotcom** [comment]
I just tested swapping the two .implies...
confirmed that it's only the last one in the order they're specified that is implied.

**Comment by bkdotcom** [comment]
I guess one could do 
```
.implies('ssl', 'ssl_cert')
.implies('ssl_cert', 'ssl_key')
.implies('ssl_key', 'ssl_cert')
```
but that's just ugly

**Comment by bcoe** [comment]
@bkdotcom it seems like a logical extension to the API would be to allow the second argument of implies to take an array -- do you think this would do the trick?

**Comment by bkdotcom** [comment]
@bcoe   indeed.

definitely should work:
`implies: ['ssl_cert', 'ssl_key']`   // accept array

not sure:
```
.implies('ssl', 'ssl_key')
.implies('ssl', 'ssl_cert')    // should this append/extend the existing implies 
                               //    for ssl, or overwrite?  I lean towards overwrite
```

**Comment by kumarharsh** [comment]
Seeing as this issue is already discussing changes to the `implies` logic, How do I specify an 'exclusive-implication'? As in, if `A` is specified, either `B` or `C` are needed, but not both?

While developing a small cli app, I ran into an issue where I want these conditions to be satisfied by the input:

If `--name` is supplied, either `month` or `months` are required.

```
const argv = require('yargs')
    .usage('Usage: $0 -m [Feb <or> Mar-2016] -n [Harsh]')
    .options({
      name: {
        alias: 'n',
        describe: 'Name of the user.',
        type: 'string',
        conflicts: 'all',
        implies: 'month' or 'months' <--- ???????
      },
      all: {
        describe: 'Generate slip for all users for a given month. Does not combine with `name`.',
        type: 'boolean',
        conflicts: 'name',
      },
      month: {
        alias: 'm',
        describe: 'The month for which you want the slip to be generated. Does not combine with `months`.',
        type: 'string',
        conflicts: 'months',
      },
      months: {
        describe: 'Last N months for which you want the slip to be generated. For example, --months 3 would give you last 3 months' slips. Does not combine with `month`.',
        type: 'number',
        conflicts: 'month',
      },
    })
    .argv;
```

**Comment by bcoe** [comment]
hey @MattSturgeon closed your ticket in favor of this one 👍 

First off, sorry for the slow reply, have been dealing with some stressful life things the past few months, and OSS has had to be put somewhat to the side.

@MattSturgeon @bkdotcom @kumarharsh I like this feature idea, and if you're interested in contributing to the yargs project, would love help implementing it.

I've created a new community slack channel for coordinating works with folks: 

http://devtoolscommunity.herokuapp.com/

Hope to see you there.
