### ISSUE TITLE
Unexpected behavior of `strict()` with extra args

### ISSUE THREAD

**Issue by princjef** [yargs/yargs#853]
I'm writing commands using `commandDir()` and want to enable strict mode. However, strict mode doesn't seem to catch when extra arguments are inserted in the middle of the command. Here's my scenario:

Yargs version: 7.0.2
Node version: 6.10.0

**Folder Structure**
```
index.js
commands/
    command.js
```

**`index.js`**
```js
const yargs = require('yargs');

yargs
    .commandDir('commands')
    .demandCommand(1)
    .strict()
    .help()
    .argv;
```

**`commands/command.js`**
```js
exports.command = 'command <param>';
exports.desc = 'Some sub-command';

exports.builder = (yargs) => {
    return yargs
        .strict(); // Don't think this is necessary, but just in case
};

exports.handler = (args) => {
    console.log(args.param);
};
```

When i run the following, everything is normal:

```
$ node index.js command foo
foo
```

However, when i add an extra non-hyphenated argument in the middle, things get strange:

```
$ node index.js imposter command foo
command
```

Not only does strict mode not fail the command, it seems to both match the command in `command.js` and treat it as if 'imposter' is the command and 'command' is the parameter.

Am I missing something here? I was hoping that strict mode would fail the command, but it seems like it should at least print `foo` in both cases

**Comment by bcoe** [comment]
@princjef you are not missing anything; commands should be working as you expect. We will dig into this as soon as possible.

**Comment by bcoe** [comment]
@princjef I think I've gotten to the bottom of what was happening to you:

https://github.com/yargs/yargs/pull/857

Could you try out this candidate release, and see if it fixes your problem (and ensure that yargs continues to work as expected):

`npm i yargs@next`

**Comment by princjef** [comment]
@bcoe thanks for looking into this! Everything looks good on my end. I don't use all of the more advanced configurations but all of the features I use also appear to still be working.
