### ISSUE TITLE
Default command is not shown in help message

### ISSUE THREAD

**Issue by egoist** [yargs/yargs#855]
*might be a bug since I don't think this is the expected behavior*

For the example code:

```js
// cli.js
const argv = require('yargs')
  .command('*', 'the default command', () => {}, (argv) => {
    console.log('this command will be run by default')
  })
  .help()
  .argv
```

The description `*         the default command` is not shown in help message when I ran `node cli.js --help`

**Comment by nexdrew** [comment]
It will only be included in help content if it has a named alias. Sounds like we should fix the example/docs. Thanks for bringing this up.

**Comment by bcoe** [comment]
@egoist the default command is now shown in help output:

```js
import y from 'yargs'
const argv = y(process.argv.slice(2))
  .command('*', 'the default command', () => {}, (argv) => {
    console.log('this command will be run by default')
  })
  .help()
  .argv
```

output:

```bash
bloop.js

the default command

Options:
  --version  Show version number                                       [boolean]
  --help     Show help                                                 [boolean]
```

Let me know if you continue to have any  issues.
