### ISSUE TITLE
Fail to update the npme license using special quotes  (“ ”) while extending license using slackboard. 

### ISSUE THREAD

**Issue by ritsingh** [yargs/yargs#869]
slackboard enterprise extend id “yyyy-mm-dd”
failed to update license

slackboard enterprise extend id "yyyy-mm-dd"
license updated successfully

**Comment by mleguen** [comment]
@bcoe Is this really a bug? Shells usually do not expect special quotes to be treated as regular ones:

```bash
$ echo “yyyy-mm-dd”
“yyyy-mm-dd”
$ echo "yyyy-mm-dd"
yyyy-mm-dd
```

IMHO, it should be treated as a feature request in yargs-parser, where it could be handled by adding an option defining a list of quote regex (regex to allow exotic use cases when opening and closing quotes are not the same).

**Comment by shadowspawn** [comment]
I agree with @mleguen. This might be supported by yargs-parser when parsing a string containing multiple arguments, but does not make sense for Yargs when the argument splitting has been done by the shell before being processed by Yargs.
