### ISSUE TITLE
ignore '--' (not stop parsing)

### ISSUE THREAD

**Issue by whitecolor** [yargs/yargs#870]
Is it possible for `yarg` not stop parsing when `--` met?

I thought to remove it from `process.argv` and then do

`yargs.parse(process.argv).usage..` - but it doesn't work

**Comment by bcoe** [comment]
@whitecolor I think your best bet would be to use the approach you suggested:

`yargs.parse(process.argv)`, having removed `--` from `process.argv` this approach should definitely work, perhaps put a `console.log` directly before `yargs.parse(process.argv).usage` and double check what you're parsing.

**Comment by whitecolor** [comment]
`yargs.parse(process.argv.slice(2)).usage` won't work because it just `yargs.parse(process.argv)` just returns `args` already not `yargs` instance, so it its by design may close.

Though for me `yargs.parse(process.argv.slice(2)).usage` API is more appropriate.

**Comment by bcoe** [comment]
@whitecolor sounds like you have a workaround 👍 

If you feel that you still do need a way to disable `--`, could you open an issue on `yargs-parser`. We could potentially add a configuration setting for disabling `--`.
