### ISSUE TITLE
Cannot have completion for multiple functions

### ISSUE THREAD

**Issue by fearphage** [yargs/yargs#874]
If you have two tools built on yargs, they will clobber each other. Based on the current implmenetation, they will both [define a function](https://github.com/yargs/yargs/blob/master/completion.sh.hbs#L8) (`_yargs_completions()`) and one will overwrite the other. The last one will win. I'm addressing this now in related issue (#831). I just wanted to log it so it is known.

**Comment by bcoe** [comment]
@jacobator @gardenappl as folks using yargs' completion functionality, any thoughts on this long standing bug? I wonder what a good approach would be

**Comment by jacobator** [comment]
@bcoe https://github.com/yargs/yargs/blob/master/lib/completion-templates.ts. It looks like for zsh there's an app-specific function defined `_{{app_name}}_yargs_completions()` while it's generic `_yargs_completions()` for bash. Should be an easy fix. I can test and create a PR this evening.
