### ISSUE TITLE
Default value only if flag called

### ISSUE THREAD

**Issue by pedro93** [yargs/yargs#875]
Lets say I have a cmd line tool (prog) with yargs options like so:
```js
.option('config', {
    'describe': 'Path to config file',
    'type': 'string',
    'default': 'package.json'
  })
```
If I call: ```$ prog``` I expect the value of config to be not be set
If I call: ```$ prog --config``` No value set explicitly, but option called explicitly then ```config === package.json```
If I call: ```$ prog --config=some.json``` I expect the value of config to be some.json

Is this possible natively in yargs? I have been unsuccessful so far and have to have a workaround like this (without default value in corresponding config yarg option)
```js
if(argv.config !== undefined)
 let config = argv.config.length ? getConfigFrom(argv.config) : getConfigFrom('package.json');
```

**Comment by bcoe** [comment]
@pedro93 I think your best bet might be using the `coerce` functionality:

https://github.com/yargs/yargs#coercekey-fn

this would allow you to check whether the value of `config` is `false`; and default it to package.json ... it was my hope that `coerce` would help people address some of the edge-cases like this.

**Comment by bcoe** [comment]
@pedro93 please let me know if you can't make coerce work for you?

**Comment by pedro93** [comment]
My deepest apologies @bcoe for not having replied sooner. 
I am no longer working on the relevant downstream project in years, in fact I'm not sure it is relevant anymore. 
That being said coerce does seem to be the answer for these use-cases, I don't remember if I tried it the time and if I did why it did not work.

**Comment by justinmchase** [comment]
It doesn't seem like coerce will work for this situation. In the coercion function there is no way to tell the difference between it being set with no argument and not being set at all. Ideally yargs would not set the option onto the args object unless it appears as an actual parameter.

For example I have

```ts
export const example = {
  command: 'example',
  builder: yargs => yargs.option('pre'),
  handler: (argv: Arguments) => {
    console.log('example:', argv)
  }
}
```

When run this is printing out:
```
example: { _: [ "example" ], pre: undefined, "$0": "deno run" }
```

The fact that `pre: undefined` is a problem. Here is what I would expect the output to be like:
```
> deno run cli.ts example
example: { _: [ "example" ], "$0": "deno run" }
```
```
> deno run cli.ts example --pre
example: { _: [ "example" ], "pre": undefined, "$0": "deno run" }
```
```
> deno run cli.ts example --pre test
example: { _: [ "example" ], "pre": "test", "$0": "deno run" }
```
