### ISSUE TITLE
yargs middleware

### ISSUE THREAD

**Issue by Khaledgarbaya** [yargs/yargs#876]
# Feature Request

Hi, 
First of all, thank you for such an amazing project. I have the following proposition.

## Summary
I am in the process of building a fairly large cli project and what it would be really great if yargs has something like express middleware that can prepare data for the `handler`.

## Usage Example
```js
const yargs = require ('yargs')
const myMiddleWare = require('./myMiddleware')
yargs.usage('\nUsage:foo <cmd> [args]')
.commandDir('cmds')
.demandCommand(4, 'Please specify a command.')
.use(myMiddleWare)
.use(...)
.help('h')
.alias('h', 'help')
.version()
.parse(process.argv)
```
## Middleware Example
```js
// not sure what we need to inject in the middleware
// mainly the arguments, context to give us some more infos maybe we don't need it 
// next to just tell theyargs tha we are done
// or maybe the middleware can return a Promise
export  default myMiddleWare(argv, context, next) {
// do some stuff with the arguments
// call next for the next middleware
next() // like express
}
```

## Why
This is very useful if we want to centralize error handling or doing extra validation for the arguments.
So we can have less code in handlers.

## Questions
* Is something similar achievable already? how?
* Does it make sense to have it part of yargs in a separate module?
## Conclusion
I am willing to implement this with some guidance from the maintainers. the implementation details are up for discussion so any feedback is welcome

Best,
Khaled

**Comment by axe312ger** [comment]
This could be a great alternative/workaround to allow async validation --> related to https://github.com/yargs/yargs/issues/859

**Comment by bcoe** [comment]
@axe312ger @Khaledgarbaya I like this idea -- the only thing on my min for both this feature, and the idea of async validation, is what the heck yargs' behavior should be when running an async method.

Right now every operation in the yargs chain is synchronous, so the third command in the chain won't have context about what's about to happen farther down the chaining API -- also the value of argv:

```js
const argv = yargs.command().command()
```
has the final parsed object.

I like the idea of starting to add more async methods to yargs, I just want to make sure we get the behavior right -- @Khaledgarbaya would love to see you build out this idea, which I think would be a good way to center conversation.

**Comment by Khaledgarbaya** [comment]
@bcoe,
thanks a lot for the feedback, my plan is to start simple and keep everything synchronous. That would be the first implementation and the good thing is I can test extensively in the cli project I'm working on and from there we can refine it more and more.
Best,
Khaled

**Comment by bcoe** [comment]
@Khaledgarbaya this sounds great. I would definitely love to start the conversation about introducing some async functionality to yargs -- but we can do this in a future issue.

**Comment by Khaledgarbaya** [comment]
@bcoe Yes definitely, for let's stick with synchronous handler and middlewares

**Comment by bcoe** [comment]
@Khaledgarbaya how progress going, if you open a WIP progress pull request I'd be happy to talk about the API.

**Comment by Khaledgarbaya** [comment]
@bcoe sorry was a bit busy, I will try to get a WIP PR this week

**Comment by onbjerg** [comment]
This is done, right?

**Comment by Khaledgarbaya** [comment]
@onbjerg yep `npm i yargs@next`
