### ISSUE TITLE
Show help for no command and handle unknown command

### ISSUE THREAD

**Issue by wclr** [yargs/yargs#883]
I trouble to implement folliwng case:

1) Show message `unknown command` if some unknnown command supplied
2) Show help if no command supplied.

To handle unknown command I use default command `*`, it works ok

```ts
  .command({
    command: '*',
    handler: (argv) => {      
      if (argv._[0]) {
        console.log('Unknown commmand', argv._[0])        
      }
    }
  })
 .demand(1)
```

But `demand(1)` here doesn't work in this case so If I supply no command nothing happens at all (it goes to `*` handler)

I tried to use `yargs.showHelp()`  somewhere in '*' handler or just checking main argv

```ts
const argv = yargs...

if (!argv._[0]) {
  yargs.showHelp()
}
```

but it doesn't show help. All it shows:

```
Options:
  --help  Show help                                                    [boolean]
```

**Comment by the-spyke** [comment]
Same issue here. I don't what to use strict mode as I need to parse unspecified options. My temporary solution is to use a flag in handlers.

**Comment by fgarcia** [comment]
for those waiting for this feature, here is how I do it

```
var yargs = require('yargs')

var argv = yargs
  .command('all', 'All projects', ya => {
    console.log('all')
  })
  .command('watch', 'watch')
  .command('short', 'short, just print spec file and console', () => {})
  .command('full', 'long, naming each test', () => {})

  .strict().argv

if (!argv._[0]) {
  yargs.showHelp()
}
```

**Comment by gempain** [comment]
Another, shorter way:
```javascript
yargs
  .demandCommand(1)
  .strict()
```
This will throw an error if you don't pass a command, and will print the help at the same time.

**Comment by Zelgadis87** [comment]
@gempain @fgarcia That unfortunately also throws on valid commands with unrecognized arguments, which is not exactly the same the OP is asking for.
Unfortunately I have the same issue as the OP, since I have dynamic arguments. I would only need to check if the command is correct with arbitrary arguments.

**Comment by gempain** [comment]
@Zelgadis87 then I guess you have to use `*`

**Comment by OsmanAltun** [comment]
Specifying default command still removes all commands from yargs.showHelp(callback).

+1

**Comment by bcoe** [comment]
_Cleaning up some stale issues, apologize this one was open for so long.

@wclr @Zelgadis87 @gempain there is now the method available `.strictCommands()`, which I believe provides exactly the behavior you want -- failing on unknown commands, including the default, but allowing any flags.

@OsmanAltun is working on a fix for `.showHelp()` listing commands in #1826, but I think `.strictCommands()`` is closer to what you're looking for.
