### ISSUE TITLE
Feature/ allow to provide user defined general documentation text block

### ISSUE THREAD

**Issue by fogine** [yargs/yargs#885]
In general, generated documentation has the following format:

```
app [option]... [key] [value] ...

Options:
  --help                    Show help    [boolean]
  --another-option   Description

```

I would like to provide large documentation text block bellow the `Options` section, which would describe all the options in-deep. I imagine it would look like this:  

```
app [option]... [key] [value] ...

Options:
  --help                    Show help    [boolean]
  --config                 File path       [String]

Config format:
This is user defined documentation....

Another section:
and so on...
```

Essentially, I'd like to delegate the responsibility of dumping a text block to stdout to the `yargs` instead of handling it manually, which currently looks like this:

```javascript
yargs.parse(process.argv, function(err, argv, output) {
        if (err) {
            throw err;
        }
        if (output) {
            console.info(output);
            if (argv.help) {
                console.log('additional info');
            }

            process.exit(0);
        }
});
```
The above workaround looks somewhat clumsy, it also returns the `argv` object asynchronously which might not be needed in all cases. The other solution would be to define own "help" processing logic. Is there a way how overload "--help" processing logic?

Thank you for your awesome contributions to OS.

**Comment by bcoe** [comment]
@fogine you should be able to use the [group](https://github.com/yargs/yargs#groupkeys-groupname) to create custom groupings of information (this is the approach `webpack` uses for their fancy UI).

**Comment by fogine** [comment]
I think that will do it. Thank you @bcoe
