### ISSUE TITLE
feature request: enable version and help by default

### ISSUE THREAD

**Issue by bcoe** [yargs/yargs#889]
in almost all my applications I end up calling `.help()` and `.verison()` to enable these settings by default, in the next major version of yargs it would nice if we simply enabled these by default.

**Comment by cg-cnu** [comment]
@bcoe Thanks for the invitation on twitter.
Seems to be something small which I can work on. Let me know otherwise. Might need some help to finish it, but am ready to put in some time. Can I pick it up:)
