### ISSUE TITLE
Show help if no command is used

### ISSUE THREAD

**Issue by borela** [yargs/yargs#895]
I tried the following:

```js
Yargs.command('command1', '...')
  .command('command1', '...')
  .showHelpOnFail(true)
  .help(
    'help',
    'Show usage instructions.'
  )
  .command({
    command: '*',
    handler() {
      Yargs.showHelp()
    }
  })
  .argv
```
It kinda works, but the description of the commands does not appear in the list, calling `--help` shows the commands descriptions as it should.

Thanks

**Comment by dvishniakov** [comment]
@borela try to add ```.demandCommand(1)```:
```
Yargs.command('command1', '...')
  .command('command1', '...')
  .showHelpOnFail(true)
  .help(
    'help',
    'Show usage instructions.'
  )
  .command({
    command: '*',
    handler() {
      Yargs.showHelp()
    }
  })
  .demandCommand(1)
  .argv
```

**Comment by bcoe** [comment]
@borela, as @dvishniakov suggests try adding `.demandCommand()` and removing:

```
  .command({
    command: '*',
    handler() {
      Yargs.showHelp()
    }
  })
```

The above code creates a default command that executes and shows help, so you're seeing help for this command not for the top-level yargs object which has command1 and command2 installed... I also note that you have two `command1`s in your example code, it should probably be `command1` and `command2`.

**Comment by borekb** [comment]
The combination that worked for me was:

```
.showHelpOnFail(true)
.demandCommand(1, '')
```

Maybe this could have a more straightforward way in yargs, something like

```
.showHelpWhenNoArgs()
```

**Comment by impressiver** [comment]
Or just show the list of possible commands if no command is specified (same as `—help` as far as I can tell).

**Comment by s-panferov** [comment]
All of the solutions above does not work if provided command is not known (e.g. when you put a random string instead of a real command). Please re-triage this a as a feature request, because the desired behavior cannot be achieved right now.

**Comment by borela** [comment]
@bcoe That works but is it possible to remove the error message `Not enough non-option arguments: got 0, need at least 1`? it is redundant if the usage is being displayed, I added `.demandCommand(1, "")` but it still include the line breaks as if the error message is there.

**Comment by mathroc** [comment]
I have something I like with `.recommendCommands().strict()`

**Comment by borela** [comment]
Thank you all, I can close this, the latest version of yargs is working as I intended previously.

**Comment by matthiasg** [comment]
@borela may I ask what that means 'it is working as I intended' ? `.demandCommand().recommendCommands().strict()` seems to work fine is that as intended ?

**Comment by borela** [comment]
@matthiasg Yes, that works the way I wanted, I am not seeing the generic error message `Not enough non-option arguments: got 0, need at least 1` anymore, it shows the command had a typo.

**Comment by soulmachine** [comment]
I guess `yargs` has upgraded this behavior, now it's more simple, just  `.demandCommand(1, '')` will print help if no command or args provided. My yargs version is `15.0.2`.

**Comment by stevage** [comment]
IMHO there's still a problem here - the `demandCommand` functionality is really not very discoverable. (I tried quite a few things, then googled and landed here).  Maybe putting it in the getting started example would help.

**Comment by m0un10** [comment]
I couldn't find a solution so just did something pretty gross as a workaround.

```
if (argv._.length == 0){
    console.log("Usage: <my command> --help")
}
```
