### ISSUE TITLE
Using .conflicts and .option

### ISSUE THREAD

**Issue by dogboydog** [yargs/yargs#899]
I'm porting a big project over from using `commander` and I am absolutely loving yargs but encountered this issue.

with yargs 8.0.2: 
```

const yargs = require("yargs");  
yargs('command --foo')
          .command('command', 'a command', {}, function (argv) {})
	  .option('foo', {describe:'A foo foo'})
          .option('bar',{describe: 'A bar bar'})
          .fail(function (msg) {
            console.log(msg);
         
          })
          .conflicts('foo', 'bar')
.argv
```

Results in "Arguments foo and bar are mutually exclusive" despite the fact that "bar" is not specified on the command.   From the doc: "This method can be used to make yargs aware of options that could exist." (i.e. it does not imply that you are setting those options to be true).  If I comment out `.option('bar'...` it works as expected.

I was trying to debug this condition in lib\validation.js but  couldn't find a way to make it work 
```
 if (conflicting[arg] && args.indexOf(conflicting[arg]) !== -1) {
        usage.fail(__('Arguments %s and %s are mutually exclusive', arg, conflicting[arg]))
}
```

 Any insight?

**Comment by dogboydog** [comment]
I forked the project to mess around with this. I don't know if I'll be able to fix it but I made this automated test: 

```
    it('should not fail if no conflicting arguments are provided and the .command() syntax is used', function () {
      yargs(['command', '-b', '-c'])
            .command('command')
            .option('f', 'a foo')
            .option('b', 'a bar')
            .conflicts('f', 'b')
            .fail(function (msg) {
              expect.fail()
            })
            .argv
    })
```

This fails as is, but passes if you comment out the `.command('command')` line. I don't know if that will help more experience people debug it

**Comment by bcoe** [comment]
@dogboydog I believe the underlying problem is that `.conflicts` configures the rule to apply globally (in newer versions of yargs, options default to being applied to both the top-level and sub-commands).

_tldr;_ I believe you could work around the problem using logic like this:

```js
yargs.option('foo', {describe: 'description'})
  .conflicts('foo', 'bar')
  .global('foo', false)
  .argv
```
_however_, this isn't very intuitive is it?

I think what we should do is modify the conflicts API so that it takes into account whether or not an option is global, so more like this:

```js
yargs.option('foo', {
     describe: 'description',
     global: false
   })
  .conflicts('foo', 'bar')
  .argv
```

☝️ that feels more intuitive to me, what do you think? If you like this solution, perhaps you could take a stab at implementing it? I believe most of the work would be [here](https://github.com/yargs/yargs/blob/master/lib/validation.js#L301).

**Comment by dogboydog** [comment]
Ah interesting.  Thanks for looking. Does that mean my PR didn't really fix this?  

I'm confused as to why the option being global affects this? I'm a yargs  beginner for sure, but even if both options were intended to be global, why would the command fail if only one (or neither) option was actually specified by the user?

**Comment by bcoe** [comment]
@dogboydog great catch; I believe there are two things actually in play: we actually populate options that are defined, but not set, with `undefined`:

```sh
{ _: [ 'command' ], foo: true, '$0': 'foo.js', bar: undefined }
```

The logic in the validation:

1. should take into account whether or not the argument `bar` is set, but equal to `undefined`; and should not raise an exception if it's `undefined`.
2. the validation should also take into account whether or not an option is `global`; if the option isn't global we shouldn't apply validation.

**Comment by dogboydog** [comment]
Okay. I think I only fixed number 1 in my PR, except I didn't check specifically for `undefined` but rather whether the value for the option was truthy or not in general so that setting  `--foo` and `--no-bar` wouldn't be a conflict.  I figured something like what you explained was causing it.  My real use case in my project is like this:

```node
const yargs = require("yargs");  
yargs('command --foo ')
          .command('command', 'a command', 
	         function(argv){
		argv.option('foo', {describe:'A foo foo'})
		.option('bar',{describe: 'A bar bar'})
		.conflicts('foo', 'bar')},
		function (argv) { }
            )	    
          .fail(function (msg) {	
            console.log(msg);         
          })       
.argv
```

Where I'm defining the options and conflicts within the builder for the command so that the options aren't added on to the default/empty command. This works with my PR changes but not with 8.0.2

Also, without my changes this doesn't work either: 

```node 
const yargs = require("yargs");  
yargs('--no-foo --no-bar')
         
	 .option('foo', {describe:'A foo foo'})
	 .option('bar',{describe: 'A bar bar'})
	 .conflicts('foo', 'bar')
			    
         .fail(function (msg) {		
		
            console.log(msg);         
          })       
		   
console.log(JSON.stringify(yargs.argv));
```
Prints: 
Arguments foo and bar are mutually exclusive
{"_":[],"foo":false,"bar":false,"$0":"yargs.js"}

Or  if you default one of the options like 'bar' explicitly to false it will fail too. Is that intended? I could change my pull request to specifically check for undefined if you'd like, but I didn't realize that was the purpose of `.conflicts` (is a boolean option being false 'setting' it in yargs terminology?) 

Now number 2, I'm not sure I understand enough about the global logic to implement that.  Would you consider that as a separate issue?
