### ISSUE TITLE
Optional parameters that have choices defined are not optional.

### ISSUE THREAD

**Issue by davidkel** [yargs/yargs#903]
I have a command where I want an optional argument, but if the argument is specified it needs to match a set of defined choices.

So my definition of part of the builder is
```
    logLevel: { alias: 'l', optional: true, describe: 'the new logging level (INFO/WARNING/ERROR/DEBUG)', type: 'string', choices : ['INFO', 'WARNING', 'ERROR', 'DEBUG'] }
```
But it seems it isn't possible. It looks like specifying choices ignores the optional request and I get the response
```
Invalid values:
  Argument: logLevel, Given: undefined, Choices: "INFO", "WARNING", "ERROR", "DEBUG"
```

**Comment by nexdrew** [comment]
Is this the same as #849? Perhaps we could add to the conversation there. Thanks!

**Comment by davidkel** [comment]
Yep looks like it is the same as #849. Will close off and copy text over there.
