### ISSUE TITLE
problems with demandOption

### ISSUE THREAD

**Issue by MichelleShieh** [yargs/yargs#906]
When I tried to add a demandOption, it showed: yargs.option(...).option(...).demandOption is not a function. 

Then I tried to use demandOption:true inside the option, it made no difference.

Is it can still be used?

**Comment by bcoe** [comment]
@MichelleShieh did you figure things out? curious why you closed this issue.

**Comment by MichelleShieh** [comment]
Thanks. I found it's a problem with version. solved already.
