### ISSUE TITLE
Yargs doesn't work with npm linked scripts

### ISSUE THREAD

**Issue by moriczgergo** [yargs/yargs#910]
I'm trying to write a script but I can't get yargs to work.

```
var shell = require('shelljs');
var path = require('path');
var pm = "";
var package = require('./package.json');
var argv = require('yargs')
	.usage('Usage: discord-init [options]')
	.example('discord-init', 'Initialize a Discord bot')
	.alias('pm', 'pkgman')
	.nargs('pm', 1)
	.describe('pm', 'Specify to use npm or yarn.')
	.choices('pm', ['npm', 'yarn'])
	.demandOption(['pm'])
	.help('h')
	.alias('h', 'help')
	.epilog("discord-link is an open source project licensed under GPLv3.")
	.argv;

if (shell.which('yarn')){ //If user is using yarn
	pm = "yarn";
} else if (shell.which('npm')){ //If user is using NPM
	pm = "npm";
} else {
	shell.echo("This script requires yarn or npm.");
	shell.exit(1);
}

/*if (typeof args.pkgmanager != "undefined"){
	if (args.pkgmanager == "npm" || args.pkgmanager == "yarn"){
		pm = args.pkgmanager;
	} else {
		shell.echo("Invalid package manager '" + args.pkgmanager + "'.");
	}
}*/

shell.echo("Using " + pm + "..."); //Tell the user what package manager are we using.
```

When I run it with node, yargs works fine and I can access the arguments.
But when I run `npm link` and try to run it with the module's command, it doesn't work.

**Comment by moriczgergo** [comment]
**Update**:

Without `#!/usr/bin/env node`, running the linked script won't work.

This is present on Windows too.

**Comment by bcoe** [comment]
@moriczgergo this is a requirement of scripts in general, not related to yargs.

You need to have `#!/usr/bin/env node` at the top of a script, and `chmod` it to an executable run-level, top be able to run `my-script` vs. `node my-script`.

**Comment by bcoe** [comment]
@moriczgergo here's a good post on the subject, let me know if you continue running into any issues 👍 

https://developer.atlassian.com/blog/2015/11/scripting-with-node/
