### ISSUE TITLE
Async handlers for CLIs

### ISSUE THREAD

**Issue by richburdon** [yargs/yargs#918]
#I'm using `parse` to build a CLI app using `readline`.

My commands execute asynchronously. Is it possible to configure the `handler` to take a callback (or ideally handle a returned promise)?

I think the simplest way to achieve this would be to pass any value returned by a command handler to the parse method. (So that, for example, the handler can return a promise).

My current workaround is to set a value within `yars` E.g.,

~~~~
  let myYargs = yargs.command({
    command: 'run',
    handler: yargs => {
      yargs._result = new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log('OK');
          resolve();
        }, 1000);
      });
    }
  });
  
  let rl = readline.createInterface({ ... });

  rl.prompt();
  rl.on('line', (input) => {
    myYargs.parse(['run'], (err, argv, output) => {
      Promise.resolve(argv._result).then(() => {
        rl.prompt();  // Get next line.
      });
    });
  });
~~~~

**Comment by zenflow** [comment]
@richburdon Async (promise-returning) command handler support was added with PR #1001 .. I think you can probably close this

**Comment by fabiomcosta** [comment]
@zenflow trying a similar example and then running the `run` command won't show the expected `OK` on stdout. There seems to be an issue on the async handler support, the program is closing before they are finished.

For example, try:
```
  let myYargs = yargs.command({
    command: 'run',
    handler: yargs => {
      return new Promise((resolve, reject) => {
        setTimeout(() => {
          console.log('OK');
          resolve();
        }, 1000);
      });
    }
  });
```

Would you expect to see `OK` when you run the `run` command?
