### ISSUE TITLE
Args that contain dashes (or other "invalid" chars aren't processed correctly).

### ISSUE THREAD

**Issue by richburdon** [yargs/yargs#919]

**Comment by bcoe** [comment]
@richburdon did you get this sorted out? what was the issue if you don't mind me asking.

**Comment by richburdon** [comment]
hi @bcoe sorry this was a stupid error on my part. I was incorrectly (and unnecessarily) splitting the args before passing them into process.

Thanks for an awesome module.

**Comment by bcoe** [comment]
@richburdon you're welcome 😄 I'm glad you got things working.
