### ISSUE TITLE
Coerce callbacks are run for each alias

### ISSUE THREAD

**Issue by MattSturgeon** [yargs/yargs#923]
#### Summary

Coerce callbacks are run multiple times.

This is bad, particularly if the coerce method is modifying (or even using) state.

Even something as innocent as injecting a timestamp could cause one alias to have a different value from the other, if the millisecond happened to tick over.

Instead, yargs should check if the value has already been coerced, if so it should set the alias to the other (pre-calculated) alias's value

#### To reproduce:

```js
var count = 0;

require('yargs')
  .option('a', {
    alias: [ 'b', 'c', 'd', 'e', 'f' ],
    default: undefined,
    type: 'string',
    coerce: function (arg) {
      console.log(++count, arg);
      return arg;
    }
  })
  .argv

console.log('\nTotal: ' + count);
```

```
$ node test.js
1 undefined
2 undefined
3 undefined
4 undefined
5 undefined
6 undefined

Total: 6
```

**Comment by bcoe** [comment]
@MattSturgeon good find 👍 I definitely agree that we should dedupe running the coerce method.

**Comment by brewster1134** [comment]
i am still seeing coerce running multiple times. with no alias, it runs twice... with an alias, it runs 4 times.

i am using the latest version of yargs & yargs-parser
```
yargs-parser@11.1.1
yargs@12.0.5
```

**Comment by bcoe** [comment]
@brewster1134 please feel top open another issue with sample code that reproduces this issue; my guess is you're bumping into another issue.
