### ISSUE TITLE
Non-command, non-hyphenated arguments

### ISSUE THREAD

**Issue by peoro** [yargs/yargs#931]
I'd like my program to require some non-hyphenated arguments, and I'd like these arguments to have a description, be subjected to type checks etc.

The only way I could find to do this is using commands, but they have a quite different semantics from what I want: most non-hyphenated arguments have a semantics closer to options than to commands.

I believe that a nice way to define similar arguments could be:
```
const argv = require('yargs')
	.usage('Usage: $0 [option…] <title> [<message>]')
	.strict() // no unknown arguments
	.alias('h', 'help').help('help')
	.option('title', {
		describe: 'Message title',
		demandOption: true,
		type: 'string',
		hyphenated: false
	})
	// or alternatively, something like:
	.freeArgument('message', {
		describe: 'Message content',
		demand: false,
		type: 'string'
	})
```
The output I would expect is something similar to:
```
Usage: index.js [option…] <title> [<message>]

Arguments: // or they could just be under `Options:`
  <title>     Message title                                  [string] [required]
  <message>   Message content                                           [string]

Options:
  -h, --help  Show help                                                [boolean]
```

Is anything like this possible with the current API, or would it be possible to add a similar feature?

**Comment by laggingreflex** [comment]
Related #935?

**Comment by peoro** [comment]
I guess #935 is an "extension" of this feature request.

I moved from yargs to [sywac](http://sywac.io/) in order to achieve what I was looking for. Sywac supports positional arguments, but I'm not sure whether it can handle the same variable both as a positional argument and as an option.

**Comment by bcoe** [comment]
@peoro glad you found a solution for yourself; I put some comments on #935 which I'm closing this issue in favor of.
