### ISSUE TITLE
Suggestion: Use accurate letter casing in documentation headers

### ISSUE THREAD

**Issue by amcasey** [yargs/yargs#932]
First, the docs are great, so thanks for that!  Having said that, I would find it easier to code against them if the headers reflected the actual casing of the names, rather than being shown in uppercase.  For example, the entry for `showHelp` is entitled `SHOWHELP`.  No particular objections if this is closed as unnecessary (since the names appear to all be camelCase).

**Comment by bcoe** [comment]
@amcasey 👍 I agree this is weird! I think it's `flatdoc` that's applying this style. Could I convince you to open the issue on https://github.com/yargs/yargs.github.io, which is where we render the docs.

If you have any interest in contributing, I would also very happily land a fix if you get a chance to dig into it 😉

**Comment by amcasey** [comment]
Done. 😄
