### ISSUE TITLE
completion command does not work if there is a default command

### ISSUE THREAD

**Issue by ehmicky** [yargs/yargs#939]
Hi,

The completion command is skipped, and the default command is run instead, if there is a default command defined.

E.g.:

```js
#!/usr/bin/env node

const yargs = require('yargs');

yargs
  .command('*')
  .completion()
  .argv;
```

When running `mycliapp completion`, the default command `*` is run instead. 

If I replace `*` by `anything_else`, the completion command is correctly run.

If I add CLI options, e.g. `mycliapp completion --help`, the completion command is correctly run.

**Comment by bcoe** [comment]
@ehmicky this appears to be fixed on the latest version of yargs (_npm i yargs@next_).

**Comment by ehmicky** [comment]
Thanks @bcoe!

**Comment by bcoe** [comment]
@ehmicky 👍 just let me know if you do continue to bump into issues.
