### ISSUE TITLE
Suggestion: config, pkgConf: absolute path setting / alter callback

### ISSUE THREAD

**Issue by AaronBurmeister** [yargs/yargs#942]
Hello,

I would need all paths inside of a config file or the package.json to be converted to an absolute path relative to the config location. (`path.resolve(configFilePath, '..', relativeValue)`)

I think a setting to enable path resolving would be a bit unhandy as you would need to specify which properties to update, so how about a callback provided to the `pkgConf()` and `config()` functions to alter the data read from the configs?

Or is there already something similar?

**Comment by bcoe** [comment]
@AaronBurmeister interesting thought; definitely feels like a bit of an edge-case, so I'd be a bit worried about introducing a new method that ends up simply being buried in the docs.

One option would be doing something slightly more manual, and using the fact that config accepts an object:

```js
const pkgConf = readPkgUp.sync()
const config = transform(pkgConf)
const args = require('yargs').config(config)
```

thoughts? I could also imagine this is something similar to @Khaledgarbaya's middleware proposal, which is definitely an idea I'd like to see kicked farther along.

**Comment by AaronBurmeister** [comment]
@bcoe, thanks for your help.

I implemented the approach you suggested above.

The middleware proposal looks good to me. This case would be an example on why the context may be helpful as you would need to pass the configurations path in this example: (e.g.)
```js
yargs
. ...
.use(myMiddleware)
.config(myConfig, { latestConfigPath: myConfigPath }) // relative paths in this config are resolved to myConfigPath
.config(myPackageJson, { latestConfigPath: packageJsonPath }) // relative paths in this config are resolved to packageJsonPath
. ...

function myMiddleware(argv, { latestConfigPath }, next) {
  next(_.mapValues(argv, (value, key) => {
    if (pathKeywords.includes(key)) return path.resolve(latestConfigPath, ...);
    return value;
  });
}
```
This would presume that the middleware would be executed after each yargs function call.
