### ISSUE TITLE
Stop yargs processing after fail() handler is invoked

### ISSUE THREAD

**Issue by dogboydog** [yargs/yargs#943]
Hi, 

I have a project where: 

* I don't want to exit after a command is completed (I'm doing some more complicate stuff after the command is processed) 
* I don't want yargs to print directly to the console because I'm doing things with output redirection
* I don't want yargs to invoke commands with bad syntax 

I have enabled `strict()`, and provided yargs with a custom `fail()` handler. The problem is, I can't `process.exit` or throw an Error when the command fails. So I process the failure information from yargs, but then yargs goes on to invoke the implementation even though the syntax was not valid. Is there any way to prevent this (e.g. some call like `yargs.stop()` that I could call in my fail() handler)?

**Comment by bcoe** [comment]
@dogboydog :wave: we have the `.parse()` method for just such a use-case, see:

https://github.com/yargs/pirate-joe

if you provide a function as the third argument to `.parse()` yargs will not exit or print to the terminal, leaving this decision to you.

We're also mid-way through implementing a promise API that would offer the same functionality:

https://github.com/yargs/yargs/pull/940

**Comment by dogboydog** [comment]
Thank you! that should work
