### ISSUE TITLE
Is there some way to stop parsing at a given point or just collect all remaining text?

### ISSUE THREAD

**Issue by Qard** [yargs/yargs#946]
So currently I have a command like `run <something..>` which the intention is to take *everything* after the `run` and dump it into the `something` field. The problem is that flags after that point are still pulled out, but I want to keep them to pass into another thing. Any suggestions on how best to achieve this? I had though of just doing an `indexOf(...)` on `process.argv` to locate `run` and slice everything after that, but `run` also accepts some flags which might appear after it, so really I need the first instance of whatever `something` starts with, except that could be anything, including words already present in the previous command string. 🤔

**Comment by bcoe** [comment]
There's the built in feature "--" to indicate that everything after this point should not be parsed, I think this might be almost exactly what you're looking for; if not perhaps we can extend on it.

**Comment by Qard** [comment]
That's what I'm doing now, but it's kind of awkward. What I'm trying to do is basically make a CLI app that can arbitrarily run other things. So `mything run node -p "'Hello, world"'` should be able to send the `node -p '"Hello, World"'` to a child process runner internally. Currently I can do `mything run -- node -p '"Hello, world"'` and it does what it should, but I feel like it'd probably a bit confusing/unclear to end users that the `--` is needed and why.

**Comment by bcoe** [comment]
@Qard hey 👋 sorry for the slow reply. `--` is a unix standard (if not super well known) so I think other options could potentially be more confusing... What were your thoughts?

One idea comes to mind, perhaps we could expose an API that's a bit more intuitive for pre-processing arguments -- this feels somewhat similar to the [work](https://github.com/yargs/yargs/pull/881) @Khaledgarbaya is doing around middleware ... what are the proper extension points for yargs' parsing?

**Comment by Qard** [comment]
No worries, this is a free time project, so it's definitely not super critical to me.

Basically I'm making a node version manager that'd have a run command to run a command in a given environment configuration. It'd work a lot like bundler exec in the Ruby world, so I was going for semantic equivalency just for familiarity. So like `jsenv run npm test` would run npm test with the locally configured Node.js environment.

**Comment by wmertens** [comment]
It would be great if yargs could be configured to stop parsing at the first unparseable, basically treating it as `--`.

That way, you can do `./app --foo bar.js --foo` and you'd get `{_: ['bar.js', '--foo'], foo: true}`

**Comment by bcoe** [comment]
@Qard @wmertens I will try to get this released sometime today, sorry for the slow turn around.
