### ISSUE TITLE
Latest release tag is pointing to old version

### ISSUE THREAD

**Issue by pscanf** [yargs/yargs#956]
Expected:

* `latest` -> 9.0.0

Actual:

* `latest` -> 8.0.2
* `next` -> 9.0.0

**Comment by MattSturgeon** [comment]
I think this may be intended. `next` points to a pre-release, although the `9.0.0` tag should probably indicate this too in-case it doesn't end up being the final 9.0 stable.

**Comment by bcoe** [comment]
@pscanf, @MattSturgeon is correct we haven't promoted `9.0.0` to latest just yet. Should be doing so quite soon.

**Comment by pscanf** [comment]
Ah, my misunderstanding then, sorry. Thought it was a case like #862 . Waiting for `9.0.0` then. :)  Cheers!

**Comment by bcoe** [comment]
@pscanf no worries, excited that people are itching for the next release.
