### ISSUE TITLE
Parse method's output is always empty.

### ISSUE THREAD

**Issue by richburdon** [yargs/yargs#960]
The docs (http://yargs.js.org/docs/#api-parseargs-context-parsecallback) imply that console logging is captured and passed to the `output` function, but in my test below, the console.log inside the command handler does the output and an empty string is always passed to the `parse` handler.

```
    this._yargs = yargs
      .exitProcess(false)
      .command(['status', 'stat'], 'Status', {}, argv => {
        console.log('STATUS');
      })
      .help();

     this._yargs.parse(input, (err, argv, output) => {
       console.log('>>', output);
     }
```

Version 9.0.1

**Comment by bcoe** [comment]
@richburdon the default output if you don't pass `--help` is empty, try the following and I think things will be working as expected:

```js
this._yargs = require('yargs')
      .exitProcess(false)
      .command(['status', 'stat'], 'Status', {}, argv => {
        console.log('STATUS');
      })
      .help();

     this._yargs.parse('--help', (err, argv, output) => {
       console.log('>>', output);
     })
```

Also worth noting, you shouldn't need to set `exitProcess(false)` if you're using `.parse()` -- it will do this automatically.

**Comment by richburdon** [comment]
Thanks!
