### ISSUE TITLE
Add `-h` short option

### ISSUE THREAD

**Issue by alexreg** [yargs/yargs#965]
Could we have an `-h` short option, equivalent to `--help`?

**Comment by Morishiri** [comment]
@bcoe what do you think about that?
What about programs which are using `h` as alias for some command already? Will it break them?

**Comment by alexreg** [comment]
It could be configurable, of course. :-)

**Comment by bcoe** [comment]
@alexreg @Morishiri I thought about this when I made `--help` default to enabled. my main concern is that I think it's too likely that `-h` will collide with people's existing configurations (`--help` and `--version are specific enough that I thought it was safe).

You can totally just add `.alias('h', 'help')` to your configuration though, to get the effect.

**Comment by alexreg** [comment]
Ah right, that should do the job then. Thanks!
