### ISSUE TITLE
How to exit process after command is done

### ISSUE THREAD

**Issue by tkarls** [yargs/yargs#966]
Consider:

````javascript
require('yargs')
    .command(
        'test-exit',
        'will this exit',
        (y) => {
            return y
                .option('test', {
                    describe: "just a test",
                    default: false,
                    boolean: true
                });
        },
        (options) => {
            console.log("test");
        }
    )
    .argv
````

I would expect the program (invoked with test-exit) to finish after printing "test". But it does not. Am I doing something wrong or is this how it is supposed to work?

Node js documentation explicitly says I should not call process.exit() either.
https://nodejs.org/api/process.html#process_process_exit_code
````javascript
// This is an example of what *not* to do:
if (someConditionNotMet()) {
  printUsageToStdout();
  process.exit(1);
}
````

Please advice me on a solution for my cli app :)

**Comment by tkarls** [comment]
Please ignore me.
It was the attached debugger that prevented the app to exit *hides in shame*

**Comment by bcoe** [comment]
@tkarls no worries \o/ glad this is sorted out.
