### ISSUE TITLE
Version 9.1.0 is not published to NPM

### ISSUE THREAD

**Issue by panrafal** [yargs/yargs#978]
The last available version on GitHub is `9.1.0`, while on NPM is `9.0.1`. Is `9.1.0` not ready yet?

**Comment by ehmicky** [comment]
Seems like they just published 10.0.3 on npm

**Comment by Morishiri** [comment]
9.1.0 was created by accident actually, but as we already have v10 this is no longer an issue IMHO. Closing :)
