### ISSUE TITLE
Options defined with dot notation not detected by demandOption

### ISSUE THREAD

**Issue by ecoutu** [yargs/yargs#995]
When defining an option using dot notation as well as `demandOption`, yargs always complain about a missing argument:

```javascript
const yargs = require('yargs');

const argv = yargs
  .option('foo.bar', {
    demandOption: true
  })
  .argv;

console.log(argv);
```

```bash
$ node test-yargs.js --foo.bar baz
Options:
  --help     Show help                                                 [boolean]
  --version  Show version number                                       [boolean]
  --foo.bar                                                           [required]

Missing required argument: foo.bar
```

It is possible to work around this by defining the option without dot notation and then adding an alias using dot notation:

```javascript
const yargs = require('yargs');

const argv = yargs
  .option('foo-bar', {
    alias: 'foo.bar',
    demandOption: true
  })
  .argv;

console.log(argv);
```

```bash
$ node test-yargs.js --foo.bar baz
{ _: [],
  help: false,
  version: false,
  foo: { bar: 'baz' },
  'foo-bar': 'baz',
  fooBar: 'baz',
  '$0': 'test-yargs.js' }
```

**Comment by ecoutu** [comment]
I'm looking at doing a quick fix for this. Couple questions: 

* I was thinking [`validation.requiredArguments`](https://github.com/yargs/yargs/blob/master/lib/validation.js#L90-L119) would need to check nested objects.
* Do you have a utility / convention / preferred method for doing deep inspection / assignment / retrieval? Normally I would use something like lodash's `_.get` but obviously don't want to introduce a dependency for a trivial lookup.
* This library accepts the `dot-notation` boolean, which would need to be respected. I was thinking about passing the option parsed in [`yargs._parseArgs` ](https://github.com/yargs/yargs/blob/3c8ac1ddd79cc7adc2fc0214318c7b23d98f613c/yargs.js#L966) through to `validation.requiredArguments`

**Comment by ecoutu** [comment]
WIP branch to give you an idea of where I'm going: https://github.com/yargs/yargs/compare/master...ecoutu:dot-options

I've implemented `.option('foo.bar', // ...)` now I'm looking at handling the `dot-notation` configuration.

**Comment by bcoe** [comment]
@ecoutu 👋 your implementation is looking reasonable so far. I think your gut is right, let's not pull in an additional dependency just for the `_.get` functionality; feel free to introduce an additional helper function however, for instance we have `obj-filter.js` which is used to filter specific keys from an object.

If you want to ask me any questions directly, please feel free to join the community slack:

http://devtoolscommunity.herokuapp.com/

**Comment by ljharb** [comment]
This exact issue is blocking me right now (glad it already exists!)

Any chance this fix could go out quickly?

**Comment by ljharb** [comment]
fwiw, this seems to already work with `demandOption: true`, but not with `.demandOption`.

**Comment by ecoutu** [comment]
Unfortunately I lost a bit of steam on this - I ended up using another mechanism for my needs. 

I was hung up on the best way to handle the `dot-notation` option being false as it's not actually looked at anywhere in yargs itself, but the underlying [yargs-parser](https://github.com/yargs/yargs-parser) library. I couldn't find any existing examples of yargs accessing the options that yargs-parser accepts. 

I did try out a few different routes but was unable to find something simple and not requiring large changes. It is possible I overlooked something however - I was running out of time on my deadline so ended up working around it at the application level. 

The changes in my branch _do_ implement `.option('foo.bar', ...)`, although I haven't thought exhaustively about edge cases.

**Comment by bcoe** [comment]
@ecoutu @ljharb echoing my thoughts in #1021, I'd rather avoid applying configuration to the nested keys of objects (this adds a ton of complexity to the parser); For most applications I think you could get away with something like this:

```js
const argv = require('yargs')
  .option('foo', {
    demandOption: true
  })
  .argv;

console.log(argv);
```

If it is mission critical that you validate the presence of a specific key on an object argument, perhaps you could get away with something like this?

```js
const argv = require('yargs')
  .option('foo', {
    describe: 'i am a foo option'
  })
  .check((argv) => {
    if (!argv.foo.bar) throw Error('foo.bar not set')
    return true
  })
  .argv;
``` 

I think it would be worthwhile to think of ways to the workflow around dot-notation a bit less awkward, for instance perhaps we could introduce option-specific checks, vs., global checks. _but_, I'd like to avoid adding support for configuring the keys on dot-notation arguments -- as I think this adds a lot of complexity to the parser for an edge-case feature.

**Comment by ljharb** [comment]
@bcoe as commented in https://github.com/yargs/yargs/issues/1021#issuecomment-352325015, doing `.option('foo')` makes "foo" show up in the help output, when i only want "foo.bar" showing up.
