### ISSUE TITLE
Scuffed donation button

### ISSUE THREAD

**Issue by sparcut** [yargs/yargs#996]
Viewing `README.md` in Windows 10 Google Chrome, the font on the "Support via Gratipay" button is real scuffed. (When viewed in Firefox, font is fine.)

![chrome_2017-10-25_17-40-08](https://user-images.githubusercontent.com/16233822/31984133-06ec6d8c-b9ac-11e7-9c6f-d5598b9a4c2c.png)

**Comment by bcoe** [comment]
Good news, Gratipay shutdown anyways; almost immediately after we added the button. I've removed it from the README 😛
