### ISSUE TITLE
Possible to have options for different commands

### ISSUE THREAD

**Issue by dolanmiu** [yargs/yargs#997]
At the moment, I have options for commands. This is good, but is it possible to have **different** options for **different** commands?

For example, I have an option called `provider` which is **required**. I want this _only_ on one of the commands. However, it is required for both commands!

```typescript
const commands = Yargs.command({
    command: "strip",
    describe: "Strip the CSV files depending on provider",
    handler: (argv) => {
         ...
    },
}).command({
    command: "last",
    describe: "Find last entry for a provider",
    handler: (argv) => {
        ...
    },
}).option("provider", {
    alias: "p",
    required: true,
    describe: "The provider to work with",
}).option("encoding", {
    alias: "e",
    describe: "The file encoding to be used",
}).argv;
```

**Comment by Morishiri** [comment]
Hi,

check this out:

    const args = yargs
        .command('first', 'description', (y) => {
            return y.option('a-option', {
                description: 'a',
                required: true
            });
        })
        .command('second', 'description', (y) => {
            return y.option('b-option', {
                description: 'b',
                required: true,
            });
        })
        .argv;

    console.log(args);

Notice that `y` argument in function is yargs instance.

**Comment by dolanmiu** [comment]
@Morishiri this would not work for me because it does not support handler (as far as I'm aware)

It would be nice for something like this:

```typescript
const args = yargs
    .command('first', 'description', (y) => {
       y.option('a-option', {
            description: 'a',
            required: true
       });
       y.handler((argv) => {
          // ...
       });
       return y;
    })
```

**Comment by bcoe** [comment]
@dolanmiu this should work like a charm:

```const args = yargs
    .command('first', 'description', (y) => {
        return y.option('a-option', {
            description: 'a',
            required: true
        });
    }, () => { handler code })
    .command('second', 'description', (y) => {
        return y.option('b-option', {
            description: 'b',
            required: true,
        });
    }, () => { handler code })
    .argv;

console.log(args);```

The first function passed to the command represents a `builder` which can be used to define command specific options. The second function is the actual handler.

**Comment by dolanmiu** [comment]
Thanks

What you suggested works

Although, it would be cooler if yargs worked like the above code I mentioned

**Comment by bcoe** [comment]
@dolanmiu thanks for the feedback 👍 glad you're unblocked for the time being.

**Comment by rogerpence** [comment]
This page provided _very_ good help for me. Thank you very much. Yargs is a great piece of software.

**Comment by bcoe** [comment]
@rogerpence thank you 👏

**Comment by ashutoshvarma** [comment]
This issue really saved my day 😄 , Thanks for putting your time and effort into building such a great node module

**Comment by sriramguptathallada** [comment]
> At the moment, I have options for commands. This is good, but is it possible to have **different** options for **different** commands?
> 
> For example, I have an option called `provider` which is **required**. I want this _only_ on one of the commands. However, it is required for both commands!
> 
> ```ts
> const commands = Yargs.command({
>     command: "strip",
>     describe: "Strip the CSV files depending on provider",
>     handler: (argv) => {
>          ...
>     },
> }).command({
>     command: "last",
>     describe: "Find last entry for a provider",
>     handler: (argv) => {
>         ...
>     },
> }).option("provider", {
>     alias: "p",
>     required: true,
>     describe: "The provider to work with",
> }).option("encoding", {
>     alias: "e",
>     describe: "The file encoding to be used",
> }).argv;
> ```

what is the difference between command and option and also in command and option we have options called like describe ,command,alias and more are those inbuilt options or can we create them ourself and also can u explain most used options in command and why we used while parsing --name="sriram" like this "EXPLAIN IN SIMPLE TERMS IF U SEE THIS BCZ I AM A BEGINNER

![WhatsApp Image 2022-10-19 at 2 53 37 PM](https://user-images.githubusercontent.com/98178977/196652862-407a2b36-c781-40d0-9fad-af1e26e4064e.jpeg)

**Comment by sriramguptathallada** [comment]
AND ALSO WHAT IS THE USE OF TITLE AND BODY IN BUILDER OPTION IS IT NECESSARY TO WRITE OR DEPENDS ON WHAT WE CREATE
